// Exports the @plotbreak/analytics event names to Swift.
//
// `packages/analytics/src/index.ts` is the contract (§37) and Swift cannot
// import it, so this mirrors `EVENT_NAMES` into an enum the app spells events
// through. The point is that a rename in the contract cannot silently drift
// from the client: rename an event there and the Swift case disappears here,
// and every call site stops compiling.
//
// Runs as an Xcode pre-build step when node is available; the generated file is
// committed too, so a machine without node still builds.
import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../..');
const outFile = resolve(here, '../Plotbreak/Analytics/GeneratedEvents.swift');

const script = `
  import { EVENT_NAMES } from '${resolve(root, 'packages/analytics/src/index.ts')}';
  import { CONTRACT_VERSION } from '${resolve(root, 'packages/contracts/src/api/index.ts')}';
  process.stdout.write(JSON.stringify({ names: EVENT_NAMES, contractVersion: CONTRACT_VERSION }));
`;
const result = spawnSync(resolve(root, 'node_modules/.bin/tsx'), ['--eval', script], {
  cwd: root,
  encoding: 'utf8',
  maxBuffer: 8 * 1024 * 1024,
});
if (result.status !== 0) {
  console.error(result.stderr);
  process.exit(result.status ?? 1);
}

const { names, contractVersion } = JSON.parse(result.stdout);

/** `turn_10_reached` -> `turn10Reached`. Digits join the word before them. */
function camel(name) {
  const [head, ...rest] = name.split('_');
  return head + rest.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join('');
}

const cases = names.map((name) => `    case ${camel(name)} = "${name}"`).join('\n');

const swift = `// Generated by apps/ios/scripts/export-events.mjs — do not edit.
//
// The source of truth is packages/analytics/src/index.ts (spec §37). Add an
// event there and regenerate; adding a case here by hand gives the client a
// name the server's contract has never heard of, which is the exact drift this
// file exists to prevent.

/// Every event Plotbreak emits, on either client.
///
/// The app can only send names in this enum, so a typo is a compile error
/// rather than a chart that is quietly missing a week.
enum PlotbreakEvent: String, CaseIterable, Sendable {
${cases}
}

/// The API contract this build was generated against, so an event can say which
/// wire format produced it. Same constant the server stamps on
/// \`x-contract-version\`.
enum PlotbreakAnalyticsContract {
    static let version = "${contractVersion}"
}
`;

mkdirSync(dirname(outFile), { recursive: true });
// Only when it actually changed: an unconditional write on every pre-build
// would re-stamp the file's mtime and make Xcode rebuild the world each time.
let existing = null;
try {
  existing = readFileSync(outFile, 'utf8');
} catch {
  // First run.
}
if (existing !== swift) {
  writeFileSync(outFile, swift);
  console.log(`Wrote ${names.length} events to ${outFile}`);
} else {
  console.log(`${names.length} events already up to date`);
}
