import { StoryVersion } from '@plotbreak/contracts';

/**
 * "Last Five" — a basketball program with one year to live.
 *
 * The structural thing sports anime does better than almost any other genre is
 * make improvement legible. You can see a player get better, and you can see
 * exactly who they became while doing it. So nothing here is chosen at a build
 * screen: the player's identity is counted out of what they actually attempt,
 * and the five people standing between them and Nationals each break a
 * different way, so beating one teaches you nothing about the next.
 *
 * The other structural thing it does is the adaptation cycle — find a weapon,
 * dominate with it, get scouted, evolve, come back. That only works if being
 * figured out is real, so every rival who studies film carries a `scouting`
 * block and the number it produces moves the dice.
 *
 * Familiar fantasy, original execution: high-school basketball, a fallen
 * program, five departed stars. No real school, player, team or signature move
 * is referenced, and the reason the five left is the story's own.
 */

const raw = {
  id: 'sv_last_five_1',
  storyId: 'story_last_five',
  version: 1,
  title: 'Last Five',
  fantasyLabel: 'Rebuild the team. Beat the five who left.',
  hook: 'Kosei’s entire starting five walked out last spring. The school shuts the program down in March unless what is left of it reaches Nationals.',
  premise:
    'Kosei High won three straight prefectural titles. Then, last spring, all five starters transferred out in the same month, to five different schools, and nobody has ever explained why.\n\n' +
    'What was left went 2–17.\n\n' +
    'In August the board voted to end the basketball program at the end of this school year. There is one condition attached, and it was meant as a joke: if Kosei reaches Nationals, the program stays. If it does not, everyone still here loses the only thing they do.\n\n' +
    'The team has six players. One of them is a third-year captain who has never started a game he did not have to. One is a first-year point guard who weighs about as much as a wet towel. One has never played basketball in his life and was, until September, a swimmer.\n\n' +
    'You are the seventh.\n\n' +
    'Nobody has seen you play. The coach has forty minutes of practice to decide whether that is a good thing.\n\n' +
    'And every road to Nationals runs through one of the five who left.',
  creatorId: 'creator_official',
  creatorName: 'Plotbreak Studios',
  official: true,
  coverImage: 'last_five/cover',
  keyArt: 'last_five/key',
  tags: ['Sports', 'School', 'Rivalry', 'Team', 'Coming of age', 'Drama'],
  mechanicsChips: [
    'Your style comes from playing',
    'Rivals scout you',
    'Real match clock',
    'Earn your minutes',
    'Five different problems',
  ],
  contentDescriptors: ['MORAL_AMBIGUITY', 'ROMANCE', 'LANGUAGE'],
  intensity: 'MODERATE',
  creatorNote:
    'You do not pick a position. You become one, out of what you actually try on the floor. And the better you get at one thing, the harder the next opponent works to take it away — the whole game is what you do about that.',
  rules: {
    defeatMode: 'FAIL_FORWARD',
    progressionMode: 'MILESTONE',
    revealExactDc: false,
    revealCheckMath: false,
    allowsCombat: false,
    allowsRomance: true,
    startingLocationId: 'kosei_gym',
    startWorldMinute: 15 * 60 + 30,
    startingItems: [{ itemId: 'kosei_reversible', qty: 1 }],
    hardCanon: [
      'Kosei’s five starters all transferred out in the same month last spring, to five different schools.',
      'The board shuts the program down at the end of this school year unless Kosei reaches Nationals.',
      'The official story is that they quit on the school. The official story is wrong.',
      'Coach Denda, who ran the program before, resigned in the same month and nobody says his name.',
      'There is nothing supernatural in this world. Everyone here is a teenager who is good at basketball.',
    ],
    toneGuide:
      'Sweat, squeaking floors, and people who are sixteen. Basketball is described in plain physical language ' +
      'a reader who has never watched a game can follow — where the ball went, who got there first, who was late. ' +
      'Heightened where it earns it: a great play is a great play. Off the court it is small and specific — ' +
      'vending machines, buses, group chats, exams nobody studied for. Never sentimental about winning. ' +
      'Losing is common and is not the end of anything.',
    forkCostCredits: 120,
    loop: null,
  },
  attributes: { might: 10, agility: 12, mind: 11, presence: 10, resolve: 11, arcana: 3 },
  skills: [
    { id: 'handle', name: 'Handle', attribute: 'agility', description: 'Keeping the ball on a string with somebody in your chest.' },
    { id: 'shooting', name: 'Shooting', attribute: 'agility', description: 'Repeatable mechanics under a hand in your face.' },
    { id: 'finishing', name: 'Finishing', attribute: 'might', description: 'Getting it to go in from inside the paint, through contact.' },
    { id: 'passing', name: 'Passing', attribute: 'mind', description: 'Putting it where somebody is about to be.' },
    { id: 'defense', name: 'Defence', attribute: 'resolve', description: 'Staying in front. Wanting to more than they do.' },
    { id: 'rebounding', name: 'Rebounding', attribute: 'might', description: 'Knowing where it comes off and getting there first.' },
    { id: 'court_iq', name: 'Court IQ', attribute: 'mind', description: 'Reading what the defence has decided before they finish deciding it.' },
    { id: 'conditioning', name: 'Conditioning', attribute: 'resolve', description: 'Being the same player in the fourth as in the first.' },
    { id: 'leadership', name: 'Leadership', attribute: 'presence', description: 'Being listened to in a huddle.' },
  ],
  resources: [
    {
      id: 'legs',
      name: 'Legs',
      max: 100,
      start: 100,
      regenPerHour: 8,
      polarity: 'GOOD_HIGH',
      displayPriority: 1,
      visible: true,
      zeroStateConsequence: 'Gone. Your shot is short and everyone can see it.',
      color: '#E8B44A',
    },
    {
      id: 'minutes',
      name: 'Minutes',
      max: 100,
      start: 10,
      regenPerHour: 0,
      polarity: 'GOOD_HIGH',
      displayPriority: 2,
      visible: true,
      zeroStateConsequence: 'You do not get off the bench.',
      color: '#7C6BFF',
    },
    {
      id: 'chemistry',
      name: 'Chemistry',
      max: 100,
      start: 40,
      regenPerHour: 0,
      polarity: 'GOOD_HIGH',
      displayPriority: 3,
      visible: true,
      zeroStateConsequence: 'Five people on the floor and no team.',
      color: '#7A9E7E',
    },
  ],
  tendencies: [
    {
      id: 'drive',
      label: 'Driving',
      identity: 'Slasher',
      scoutedNote: 'They know you are going to the rim and they know which shoulder you like.',
    },
    {
      id: 'pullup',
      label: 'Pulling up',
      identity: 'Shooter',
      scoutedNote: 'They are running you off the line every time you catch it.',
    },
    {
      id: 'post',
      label: 'Posting up',
      identity: 'Post scorer',
      scoutedNote: 'They are fronting you before you get to the block.',
    },
    {
      id: 'dish',
      label: 'Passing out',
      identity: 'Playmaker',
      scoutedNote: 'They have stopped helping off your teammates. They want you to shoot it.',
    },
    {
      id: 'lockdown',
      label: 'Locking up',
      identity: 'Stopper',
      scoutedNote: 'They are running their offence away from you entirely.',
    },
    {
      id: 'offball',
      label: 'Moving off the ball',
      identity: 'Movement scorer',
      scoutedNote: 'They are switching everything so you never come off a screen clean.',
    },
    {
      id: 'board',
      label: 'Crashing the glass',
      identity: 'Glass cleaner',
      scoutedNote: 'They are putting a body on you the second the ball is in the air.',
    },
  ],
  items: [
    {
      id: 'kosei_reversible',
      name: 'A Kosei Reversible',
      tags: ['kit'],
      description: 'Practice jersey, white one side, navy the other. Number 24, because nobody wanted it.',
      icon: 'jersey',
    },
    {
      id: 'nori_tape',
      name: 'Nori’s Cut',
      tags: ['quest', 'film'],
      questItem: true,
      skillModifiers: { court_iq: 2 },
      description: 'Eleven minutes of somebody else’s tendencies, cut down from four hours by a sixteen-year-old at 2am.',
      loreText: 'Nori does this for everyone on the team and has never once been asked to.',
      icon: 'tape',
    },
    {
      id: 'denda_report',
      name: 'The Incident Report',
      tags: ['quest', 'document'],
      questItem: true,
      droppable: false,
      description: 'Four pages, filed in March, signed by a second-year. The school’s response is one paragraph long.',
      icon: 'papers',
    },
    {
      id: 'good_shoes',
      name: 'Shoes That Fit',
      tags: ['kit'],
      equipSlot: 'feet',
      skillModifiers: { handle: 1, conditioning: 1 },
      description: 'Your first pair that were not somebody else’s first.',
      icon: 'shoe',
    },
    {
      id: 'brace',
      name: 'An Ankle Brace',
      tags: ['kit', 'medical'],
      equipSlot: 'ankle',
      skillModifiers: { conditioning: 2 },
      description: 'Ugly, hot, and the reason you are still playing in February.',
      icon: 'brace',
    },
    {
      id: 'energy_drink',
      name: 'Something From The Machine',
      tags: ['supply'],
      stackable: true,
      maxStack: 4,
      consumable: { resourceId: 'legs', amount: 25, consumesItem: true },
      description: 'Blue. Tastes like a colour. Works.',
      icon: 'can',
    },
  ],
  abilities: [
    {
      id: 'hard_drive',
      name: 'Get Downhill',
      tags: ['offense'],
      description: 'Put your shoulder past theirs and get to the rim before the help arrives.',
      // Both vocabularies. A player who says "cook him" and a player who says
      // "run past him and try to score close to the hoop" want the same thing,
      // and a game about basketball has to know the words people use for
      // basketball. Without these, "I fake right, cross hard left and hammer it
      // with two hands" resolved as no action at all.
      affordances: [
        'drive',
        'drive at him',
        'go to the rim',
        'attack the basket',
        'get past him',
        'blow by him',
        'blow past him',
        'run past him and try to score close to the hoop',
        'take it inside',
        'break his ankles',
        'cross him',
        'crossover',
        'cross hard',
        'fake right',
        'fake left',
        'take him off the dribble',
        'cook him',
        'get downhill',
        'drive baseline',
        'attack the rim',
        'dunk it',
        'hammer it',
        'lay it in',
        'finish at the rim',
        'i score',
        'score on him',
        'take him',
      ],
      costs: [{ resourceId: 'legs', amount: 6 }],
      cooldownMinutes: 0,
      targetRule: 'SINGLE',
      check: { attribute: 'agility', skillId: 'handle', baseDc: 13 },
      unlockedByDefault: true,
      tendencies: ['drive'],
      countersTendency: 'pullup',
    },
    {
      id: 'pull_up',
      name: 'Pull Up',
      tags: ['offense'],
      description: 'Stop hard, rise, and shoot it before the closeout gets there.',
      affordances: [
        'pull up',
        'shoot it',
        'take the jumper',
        'shoot from outside',
        'stop and shoot',
        'let him think I am driving and pull up',
        'take the three',
        'step back',
        'stepback',
        'heat check',
        'shoot over him',
        'rise up',
        'from deep',
        'from three',
      ],
      costs: [{ resourceId: 'legs', amount: 4 }],
      cooldownMinutes: 0,
      targetRule: 'NONE',
      check: { attribute: 'agility', skillId: 'shooting', baseDc: 14 },
      unlockedByDefault: true,
      tendencies: ['pullup'],
      countersTendency: 'drive',
    },
    {
      id: 'read_and_pass',
      name: 'Find the Open Man',
      tags: ['offense'],
      description: 'Draw two and put it where the third defender is not.',
      affordances: [
        'pass',
        'pass it',
        'kick it out',
        'find the open man',
        'drive and kick',
        'give it up',
        'set someone else up',
        'dish it',
        'dime',
        'find the cutter',
        'hit the roller',
        'swing it',
      ],
      costs: [{ resourceId: 'legs', amount: 3 }],
      cooldownMinutes: 0,
      targetRule: 'SINGLE',
      check: { attribute: 'mind', skillId: 'passing', baseDc: 12 },
      unlockedByDefault: true,
      tendencies: ['dish'],
      countersTendency: 'drive',
    },
    {
      id: 'post_up',
      name: 'Go To Work',
      tags: ['offense'],
      description: 'Get to the block, feel where they are, and score over the top of them.',
      affordances: [
        'post up',
        'go to the block',
        'back him down',
        'work him in the post',
        'bully him inside',
        'take him on the block',
        'seal him',
      ],
      costs: [{ resourceId: 'legs', amount: 8 }],
      cooldownMinutes: 0,
      targetRule: 'SINGLE',
      check: { attribute: 'might', skillId: 'finishing', baseDc: 13 },
      unlockedByDefault: true,
      tendencies: ['post'],
      countersTendency: 'offball',
    },
    {
      id: 'face_up',
      name: 'Face Up',
      tags: ['offense'],
      description: 'Turn and look at them. Now the whole floor is available and they have to guess.',
      affordances: ['face up', 'turn and face him', 'square up', 'attack him from the elbow'],
      costs: [{ resourceId: 'legs', amount: 6 }],
      cooldownMinutes: 0,
      targetRule: 'SINGLE',
      check: { attribute: 'agility', skillId: 'handle', baseDc: 14 },
      unlockedByDefault: false,
      tendencies: ['post', 'pullup'],
      countersTendency: 'post',
    },
    {
      id: 'come_off_screen',
      name: 'Come Off It Clean',
      tags: ['offense'],
      description: 'Set them up, brush the screen close enough to hurt, and catch it already turning.',
      affordances: [
        'come off the screen',
        'use the screen',
        'run off a screen',
        'call for a screen',
        'get open off the ball',
        'cut',
      ],
      costs: [{ resourceId: 'legs', amount: 7 }],
      cooldownMinutes: 0,
      targetRule: 'NONE',
      check: { attribute: 'agility', skillId: 'shooting', baseDc: 13 },
      unlockedByDefault: false,
      tendencies: ['offball'],
      countersTendency: 'lockdown',
    },
    {
      id: 'face_guard',
      name: 'Take Him',
      tags: ['defense'],
      description: 'Pick up their best player and do not let him breathe for a whole possession.',
      affordances: [
        'guard him',
        'lock him up',
        'lock him down',
        'face guard',
        'take their best player',
        'stop shooting and face-guard their point guard',
        'defend',
        'stay in front of him',
        'body him up',
        'pick him up full court',
        'stay on him',
      ],
      costs: [{ resourceId: 'legs', amount: 9 }],
      cooldownMinutes: 0,
      targetRule: 'SINGLE',
      check: { attribute: 'resolve', skillId: 'defense', baseDc: 14 },
      unlockedByDefault: true,
      tendencies: ['lockdown'],
      countersTendency: null,
    },
    {
      id: 'crash_glass',
      name: 'Go Get It',
      tags: ['defense'],
      description: 'Read the flight, find the body, and come down with it in traffic.',
      affordances: [
        'rebound',
        'crash the boards',
        'go get the rebound',
        'box out',
        'get the board',
        'clean the glass',
        'go up and get it',
      ],
      costs: [{ resourceId: 'legs', amount: 7 }],
      cooldownMinutes: 0,
      targetRule: 'NONE',
      check: { attribute: 'might', skillId: 'rebounding', baseDc: 13 },
      unlockedByDefault: true,
      tendencies: ['board'],
      countersTendency: null,
    },
    {
      id: 'call_it_out',
      name: 'Run It',
      tags: ['social', 'leadership'],
      description: 'Say the set out loud and put four people where they need to be.',
      affordances: ['call a play', 'run a set', 'organise them', 'take charge', 'tell them what to do'],
      costs: [{ resourceId: 'legs', amount: 2 }],
      cooldownMinutes: 0,
      targetRule: 'MULTI',
      check: { attribute: 'presence', skillId: 'leadership', baseDc: 13 },
      unlockedByDefault: false,
      tendencies: ['dish'],
      countersTendency: null,
    },
    {
      id: 'watch_film',
      name: 'Watch Film',
      tags: ['utility'],
      description: 'Sit in the dark with Nori and find the thing somebody does before they do it.',
      affordances: ['watch film', 'study them', 'go to the film room', 'scout them', 'watch the tape'],
      costs: [{ resourceId: 'legs', amount: 2 }],
      cooldownMinutes: 720,
      targetRule: 'SINGLE',
      check: { attribute: 'mind', skillId: 'court_iq', baseDc: 12 },
      unlockedByDefault: true,
      tendencies: [],
      countersTendency: null,
    },
  ],
  locations: [
    {
      id: 'kosei_gym',
      name: 'The Kosei Gym',
      shortName: 'The Gym',
      description:
        'Two courts, one of them with a dead spot near the left elbow that everybody knows about. Three championship banners and a lot of empty wall.',
      artDirection:
        'Japanese high-school gymnasium interior, late afternoon, low sun through high windows, worn wooden floor with taped lines, championship banners on one wall and conspicuous empty space beside them. Warm dusty light.',
      connections: [
        { to: 'locker_room', travelMinutes: 2, label: 'The locker room' },
        { to: 'kosei_school', travelMinutes: 5, label: 'Back into school' },
        { to: 'film_room', travelMinutes: 4, label: 'The film room' },
      ],
      discoveredByDefault: true,
      mapPosition: { x: 0, y: 0 },
      takeableItems: [{ itemId: 'energy_drink', qty: 2, ownerId: null, aka: ['drink', 'can', 'something from the machine'] }],
    },
    {
      id: 'locker_room',
      name: 'The Locker Room',
      shortName: 'Locker Room',
      description: 'Eleven lockers, six of them in use. Somebody has taped a printout of the board’s decision to the door.',
      artDirection:
        'Cramped school locker room, benches, mismatched lockers, a taped-up notice on the door, gym bags. Fluorescent, unglamorous, lived-in.',
      connections: [
        { to: 'kosei_gym', travelMinutes: 2, label: 'Out to the court' },
        { to: 'the_roof', travelMinutes: 6, label: 'Up to the roof' },
      ],
      discoveredByDefault: true,
      mapPosition: { x: -1, y: 0 },
      takeableItems: [{ itemId: 'brace', qty: 1, ownerId: null, aka: ['brace', 'ankle brace', 'the brace'] }],
    },
    {
      id: 'film_room',
      name: 'The Film Room',
      shortName: 'Film Room',
      description:
        'A storage cupboard with a projector in it. Nori’s laptop, four hundred hours of footage, and a whiteboard covered in one person’s handwriting.',
      artDirection:
        'Small dark storage room repurposed as a film room: projector glow on a whiteboard dense with diagrams, a laptop, stacked chairs. Blue light on one face.',
      connections: [
        { to: 'kosei_gym', travelMinutes: 4, label: 'Down to the gym' },
        { to: 'kosei_school', travelMinutes: 3, label: 'The corridor' },
      ],
      discoveredByDefault: true,
      mapPosition: { x: 1, y: 0 },
      takeableItems: [
        { itemId: 'nori_tape', qty: 1, ownerId: 'nori', aka: ['tape', 'the cut', 'film', 'nori’s cut'] },
        { itemId: 'denda_report', qty: 1, ownerId: 'nori', aka: ['report', 'the report', 'incident report', 'the file'] },
      ],
    },
    {
      id: 'kosei_school',
      name: 'Kosei High',
      shortName: 'School',
      description: 'Corridors, a vending machine that only takes exact change, and the staff office where the board’s letter came from.',
      artDirection:
        'Japanese high-school corridor, afternoon, shoe lockers, noticeboards, students in uniform in the middle distance. Ordinary and specific.',
      connections: [
        { to: 'kosei_gym', travelMinutes: 5, label: 'Out to the gym' },
        { to: 'film_room', travelMinutes: 3, label: 'The film room' },
        { to: 'the_roof', travelMinutes: 4, label: 'The roof' },
        { to: 'away_seiran', travelMinutes: 70, label: 'The bus to Seiran' },
      ],
      discoveredByDefault: true,
      mapPosition: { x: 0, y: -1 },
      takeableItems: [{ itemId: 'good_shoes', qty: 1, ownerId: null, aka: ['shoes', 'new shoes', 'the shoes'] }],
    },
    {
      id: 'the_roof',
      name: 'The Roof',
      shortName: 'The Roof',
      description: 'Officially closed. The door has not locked properly since before anyone here started.',
      artDirection:
        'School rooftop at dusk, chain-link fence, water tank, the town below, two people sitting against the fence. Quiet, wide sky.',
      connections: [
        { to: 'kosei_school', travelMinutes: 4, label: 'Back downstairs' },
        { to: 'locker_room', travelMinutes: 6, label: 'Down to the lockers' },
      ],
      discoveredByDefault: true,
      mapPosition: { x: 0, y: -2 },
    },
    {
      id: 'away_seiran',
      name: 'Seiran Academy',
      shortName: 'Seiran',
      description: 'A gym with seating for two thousand and a scoreboard that works. Rei Amagi plays here now.',
      artDirection:
        'Large modern school sports arena, packed stands, bright even lighting, polished floor, a banner with a school crest. Intimidating scale.',
      connections: [
        { to: 'kosei_school', travelMinutes: 70, label: 'The bus home' },
        { to: 'away_hakuba', travelMinutes: 90, lockedByFlag: 'played:rei', label: 'On to Hakuba' },
      ],
      discoveredByDefault: false,
      mapPosition: { x: 2, y: -1 },
    },
    {
      id: 'away_hakuba',
      name: 'Hakuba West',
      shortName: 'Hakuba',
      description: 'A public school gym with a leaking roof and the best point guard in the prefecture. Tsubame Kirisawa plays here now.',
      artDirection:
        'Older public school gymnasium, buckets under a leaking roof, mismatched seating, rain visible through high windows. Character over polish.',
      connections: [
        { to: 'kosei_school', travelMinutes: 90, label: 'The bus home' },
        { to: 'away_tessen', travelMinutes: 110, lockedByFlag: 'played:tsubame', label: 'On to Tessen' },
      ],
      discoveredByDefault: false,
      mapPosition: { x: 3, y: 0 },
    },
    {
      id: 'away_tessen',
      name: 'Tessen Industrial',
      shortName: 'Tessen',
      description: 'A converted factory floor with a court in it. Everything echoes. Gora Vance plays here now.',
      artDirection:
        'Basketball court inside a converted industrial building, exposed steel roof beams, harsh work lighting, vast echoing volume. Cold and impressive.',
      connections: [
        { to: 'kosei_school', travelMinutes: 110, label: 'The bus home' },
        { to: 'away_onda', travelMinutes: 100, lockedByFlag: 'played:gora', label: 'On to Onda' },
      ],
      discoveredByDefault: false,
      mapPosition: { x: 3, y: 1 },
    },
    {
      id: 'away_onda',
      name: 'Onda Commercial',
      shortName: 'Onda',
      description: 'Loudest gym in the prefecture, and most of it is one person talking. Mikael Sorrel plays here now.',
      artDirection:
        'Packed compact school gym, a student section on their feet, streamers, noise made visible through motion and posture. Chaotic energy.',
      connections: [
        { to: 'kosei_school', travelMinutes: 100, label: 'The bus home' },
        { to: 'away_kurogane', travelMinutes: 120, lockedByFlag: 'played:mikael', label: 'On to Kurogane' },
      ],
      discoveredByDefault: false,
      mapPosition: { x: 2, y: 2 },
    },
    {
      id: 'away_kurogane',
      name: 'Kurogane',
      shortName: 'Kurogane',
      description: 'Small, quiet, immaculate. They have won here eleven times in a row. Yuki Hoshizawa plays here now.',
      artDirection:
        'Small pristine private-school gymnasium, dark wood, restrained lighting, sparse respectful crowd, everything in its place. Still and serious.',
      connections: [
        { to: 'kosei_school', travelMinutes: 120, label: 'The bus home' },
        { to: 'nationals', travelMinutes: 240, lockedByFlag: 'qualified', label: 'Nationals' },
      ],
      discoveredByDefault: false,
      mapPosition: { x: 1, y: 3 },
    },
    {
      id: 'nationals',
      name: 'The National Championship',
      shortName: 'Nationals',
      description: 'Nine thousand seats, a floor laid this morning, and a programme with Kosei printed in it.',
      artDirection:
        'Enormous national championship arena from floor level, banked stands full, bright television lighting, fresh court. Overwhelming and clean.',
      connections: [{ to: 'kosei_school', travelMinutes: 240, label: 'Home' }],
      discoveredByDefault: false,
      mapPosition: { x: 0, y: 4 },
    },
  ],
  factions: [
    {
      id: 'faction_team',
      name: 'The Team',
      description: 'Six people and you. What they think of you decides who is on the floor at the end of games.',
      startingReputation: 0,
      ranks: [
        { atReputation: -100, label: 'They play worse when you are on' },
        { atReputation: -30, label: 'Tolerated' },
        { atReputation: 0, label: 'The new one' },
        { atReputation: 30, label: 'One of them' },
        { atReputation: 60, label: 'They look for you' },
      ],
    },
    {
      id: 'faction_school',
      name: 'Kosei',
      description: 'The school board, the staff room, and everybody who has to be persuaded this is worth keeping.',
      startingReputation: 0,
      ranks: [
        { atReputation: -100, label: 'A discipline problem' },
        { atReputation: 0, label: 'A student' },
        { atReputation: 30, label: 'Worth the trouble' },
        { atReputation: 60, label: 'The reason they are reconsidering' },
      ],
    },
    {
      id: 'faction_scouts',
      name: 'The Circuit',
      description: 'Coaches, recruiters, and the people who decide which sixteen-year-olds get talked about.',
      startingReputation: 0,
      ranks: [
        { atReputation: -100, label: 'A cautionary tale' },
        { atReputation: 0, label: 'Unknown' },
        { atReputation: 25, label: 'On a list' },
        { atReputation: 50, label: 'Someone people drive to watch' },
      ],
    },
  ],
  characters: [
    {
      id: 'dai',
      name: 'Dai Okonkwo',
      role: 'Captain, third year',
      cardBlurb:
        'The only starter who stayed, and the captain who puts a ball in your hands before he asks your name. He is not the best player here, and he has run every practice since March anyway.',
      pronouns: 'he/him',
      publicTraits: ['Dependable', 'Loud in a huddle', 'Bad at hiding hurt'],
      hiddenDrives: ['He wants one of them to call him and none of them have'],
      values: ['Showing up', 'Not talking about people who are not there'],
      fears: ['That he stayed because nobody wanted him'],
      socialStyle: 'Greets everybody. Deflects anything about himself into a question about you.',
      boundaries: ['Will not badmouth the five'],
      goals: ['Finish the season with a team', 'Be worth a starting spot on merit'],
      secrets: [
        {
          id: 'dai_the_call',
          fact: 'Tsubame called him the night she transferred. He did not pick up and has never told anyone.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'On the bus back from Hakuba, if the player asks about her.',
        },
      ],
      speechStyle: 'Warm, fast, uses everybody’s first name twice a sentence.',
      topics: ['the five', 'the captaincy', 'what it was like before', 'your minutes'],
      voiceSamples: [
        'Right — new guy. Kai, get him a ball. Bo, stop that.',
        'They were my friends. That is all I am saying about it.',
        'You are better than me. I would rather find that out in October than March.',
      ],
      appearance: 'Eighteen, six foot four, heavy through the shoulders, tape on three fingers of his shooting hand.',
      visualHook: 'Three taped fingers on the right hand, retaped every session, never healed.',
      silhouette: 'Broad and upright, one arm always raised calling for something.',
      artSeed: 'lastfive-dai-01',
      portrait: 'last_five/dai',
      expressions: ['neutral', 'grinning', 'tired'],
      schedule: [
        { startMinute: 0, endMinute: 420, locationId: 'kosei_school', activity: 'asleep' },
        { startMinute: 420, endMinute: 900, locationId: 'kosei_school', activity: 'class' },
        { startMinute: 900, endMinute: 1260, locationId: 'kosei_gym', activity: 'practice, then more practice' },
        { startMinute: 1260, endMinute: 1440, locationId: 'kosei_gym', activity: 'shooting alone' },
      ],
      homeLocationId: 'kosei_gym',
      knowledgeScope: ['kosei', 'the_five', 'basketball'],
      startingRelationship: { trust: 15, affection: 10, respect: 0, fear: 0, rivalry: 0 },
      gates: [
        {
          id: 'dai_opens_up',
          label: 'He tells you about the call',
          kind: 'TRUST',
          requires: { trust: 30, flagsSet: ['visited:away_hakuba'] },
        },
      ],
      attributes: { might: 15, agility: 10, mind: 12, presence: 14, resolve: 15, arcana: 3 },
      companion: null,
      scouting: null,
      combatant: null,
    },
    {
      id: 'kai',
      name: 'Kai Sumire',
      role: 'Point guard, first year',
      cardBlurb:
        'Fifteen, tiny, and sees the pass to you two seconds before you know you are open. He is terrified of throwing it and throws it anyway.',
      pronouns: 'he/him',
      publicTraits: ['Anxious', 'Funny when he forgets to be anxious', 'Sees everything'],
      hiddenDrives: ['He came to Kosei specifically because Tsubame Kirisawa played here'],
      values: ['Getting it right', 'Not letting people down'],
      fears: ['Being the reason'],
      socialStyle: 'Apologises first, then says the smart thing.',
      boundaries: ['Do not shout at him in front of people'],
      goals: ['Not get cut', 'Throw one pass that ends up on the news'],
      secrets: [
        {
          id: 'kai_why_kosei',
          fact: 'He chose Kosei to play with Tsubame, and she transferred out the month before he arrived.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'He blurts it out on the roof if the player is kind about a mistake.',
        },
      ],
      speechStyle: 'Runs sentences together, then a long pause, then the actual point.',
      topics: ['the pass he missed', 'Tsubame Kirisawa', 'being small', 'your game'],
      voiceSamples: [
        'Sorry — sorry, I had you, I saw you, I just — I will get it next time.',
        'You are going to be open in about two seconds. Do not look at me.',
        'Everyone keeps saying I will grow. I am fifteen. I have done my growing.',
      ],
      appearance: 'Fifteen, five foot four, sleeves pulled over his hands off the court, kneepads he does not need yet.',
      visualHook: 'Sleeves pulled down over both hands whenever he is not holding a ball.',
      silhouette: 'Small and hunched at rest; on the floor, suddenly upright and looking past everybody.',
      artSeed: 'lastfive-kai-01',
      portrait: 'last_five/kai',
      expressions: ['neutral', 'panicked', 'delighted'],
      schedule: [
        { startMinute: 0, endMinute: 400, locationId: 'kosei_school', activity: 'asleep' },
        { startMinute: 400, endMinute: 900, locationId: 'kosei_school', activity: 'class' },
        { startMinute: 900, endMinute: 1260, locationId: 'kosei_gym', activity: 'practice' },
        { startMinute: 1260, endMinute: 1440, locationId: 'the_roof', activity: 'on the roof avoiding the bus' },
      ],
      homeLocationId: 'kosei_gym',
      knowledgeScope: ['kosei', 'basketball', 'the_five'],
      startingRelationship: { trust: 10, affection: 5, respect: 0, fear: 0, rivalry: 0 },
      gates: [
        {
          id: 'kai_trusts_you',
          label: 'He tells you why he came here',
          kind: 'TRUST',
          requires: { trust: 25 },
        },
      ],
      attributes: { might: 7, agility: 15, mind: 16, presence: 9, resolve: 12, arcana: 3 },
      companion: null,
      scouting: null,
      combatant: null,
    },
    {
      id: 'jun',
      name: 'Jun Hasabe',
      role: 'Shooting guard, second year',
      cardBlurb:
        'He has taken four hundred shots a day since March to earn a starting spot, and then you turned up in October.',
      pronouns: 'he/him',
      publicTraits: ['Disciplined', 'Cold to new people', 'Extremely competitive'],
      hiddenDrives: ['He is not sure he is good, only that he has worked harder than anybody'],
      values: ['Earning it', 'Nobody being handed anything'],
      fears: ['That effort is not enough and never was'],
      socialStyle: 'Polite, distant, and keeps score of everything.',
      boundaries: ['Do not tell him he is unlucky'],
      goals: ['Start', 'Beat you in something in front of people'],
      secrets: [
        {
          id: 'jun_the_list',
          fact: 'He keeps a written record of every shooting drill, and he has beaten his own numbers every single week.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'He shows the player the notebook once he stops treating them as a threat.',
        },
      ],
      speechStyle: 'Clipped. Compliments sound like measurements.',
      topics: ['the rotation', 'his shooting', 'you taking his minutes', 'the five'],
      voiceSamples: [
        'You went eleven for nineteen. That is fine. I went nineteen for nineteen on Sunday, alone.',
        'I am not angry. I would just like somebody to explain the criteria.',
        'Take the shot. If you miss it, take the next one. I hate watching you pass out of it.',
      ],
      appearance: 'Seventeen, wiry, shooting sleeve on the right arm, hair cut the same week every month.',
      visualHook: 'A black shooting sleeve worn on the right arm at all times, including in class.',
      silhouette: 'Narrow and very straight, hands already in shooting form at rest.',
      artSeed: 'lastfive-jun-01',
      portrait: 'last_five/jun',
      expressions: ['neutral', 'cold', 'reluctantly impressed'],
      schedule: [
        { startMinute: 0, endMinute: 330, locationId: 'kosei_school', activity: 'asleep' },
        { startMinute: 330, endMinute: 480, locationId: 'kosei_gym', activity: 'shooting before school' },
        { startMinute: 480, endMinute: 900, locationId: 'kosei_school', activity: 'class' },
        { startMinute: 900, endMinute: 1290, locationId: 'kosei_gym', activity: 'practice, then shooting' },
        { startMinute: 1290, endMinute: 1440, locationId: 'kosei_gym', activity: 'still shooting' },
      ],
      homeLocationId: 'kosei_gym',
      knowledgeScope: ['kosei', 'basketball'],
      startingRelationship: { trust: -5, affection: 0, respect: 0, fear: 0, rivalry: 20 },
      gates: [
        {
          id: 'jun_respects_you',
          label: 'He stops treating you as a threat',
          kind: 'TRUST',
          requires: { respect: 30 },
        },
      ],
      attributes: { might: 10, agility: 14, mind: 12, presence: 10, resolve: 16, arcana: 3 },
      companion: null,
      scouting: { learnRate: 1, cap: 4, revealCopy: '"You always go right when you are tired. Always."' },
      combatant: null,
    },
    {
      id: 'coach',
      name: 'Ena Torakawa',
      role: 'Head coach, second year',
      cardBlurb:
        'The coach who took the job nobody wanted. She decides whether you play, she will tell you exactly why, and she is not going to be kind about it.',
      pronouns: 'she/her',
      publicTraits: ['Blunt', 'Precise', 'Never raises her voice'],
      hiddenDrives: ['She was an assistant here when it happened and she said nothing'],
      values: ['Telling players the truth', 'Earning the floor'],
      fears: ['Doing to these six what was done to the last five'],
      socialStyle: 'Answers in one sentence. The sentence is always the actual answer.',
      boundaries: ['Will not play somebody who will not defend'],
      goals: ['Get to Nationals', 'Have all six of them still want to play in March'],
      secrets: [
        {
          id: 'coach_knew',
          fact: 'She was Denda’s assistant. She saw enough to have reported it and she did not.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'She says it herself once the player has found the report.',
        },
      ],
      speechStyle: 'Short. Imperative. Uses your name at the start of hard sentences.',
      topics: ['your minutes', 'the five who left', 'what you are good at', 'Coach Denda', 'Nationals'],
      voiceSamples: [
        'You are not going to like this answer, so I will make it quick.',
        'Do that again and I will play you. That is the whole system.',
        'I am not asking you to be Rei Amagi. Rei Amagi is at Seiran.',
      ],
      appearance: 'Forty-four, cropped hair going grey at one temple, a knee that ends every practice with her sitting down.',
      visualHook: 'A heavy brace on the left knee, worn over the tracksuit, never mentioned.',
      silhouette: 'Arms folded, weight entirely on one leg, standing at the edge of everything.',
      artSeed: 'lastfive-coach-01',
      portrait: 'last_five/coach',
      expressions: ['neutral', 'unimpressed', 'quietly pleased'],
      schedule: [
        { startMinute: 0, endMinute: 420, locationId: 'kosei_school', activity: 'not here yet' },
        { startMinute: 420, endMinute: 930, locationId: 'kosei_school', activity: 'teaching, badly' },
        { startMinute: 930, endMinute: 1200, locationId: 'kosei_gym', activity: 'practice' },
        { startMinute: 1200, endMinute: 1440, locationId: 'film_room', activity: 'watching film alone' },
      ],
      homeLocationId: 'kosei_gym',
      knowledgeScope: ['kosei', 'the_five', 'denda', 'basketball'],
      startingRelationship: { trust: 0, affection: 0, respect: 0, fear: 5, rivalry: 0 },
      gates: [
        {
          id: 'coach_trusts_you',
          label: 'She tells you what she saw',
          kind: 'TRUST',
          requires: { trust: 35, hasItems: ['denda_report'] },
        },
      ],
      attributes: { might: 10, agility: 9, mind: 16, presence: 15, resolve: 16, arcana: 3 },
      companion: null,
      scouting: null,
      combatant: null,
    },
    {
      id: 'bo',
      name: 'Bo Ferrand',
      role: 'Centre, second year, six weeks of experience',
      cardBlurb:
        'Six foot nine, a swimmer until September, and he will ask you what a screen is without embarrassment. He is also the biggest person in the prefecture.',
      pronouns: 'he/him',
      publicTraits: ['Cheerful', 'Enormous', 'Genuinely does not mind being bad at this'],
      hiddenDrives: ['He quit swimming because he was going to be very good and it made him miserable'],
      values: ['Enjoying it', 'Not being shouted at'],
      fears: ['Being wasted'],
      socialStyle: 'Asks obvious questions without embarrassment, which is a superpower.',
      boundaries: ['Will not be told he is a project'],
      goals: ['Learn one thing properly', 'Dunk on somebody in a real game'],
      secrets: [
        {
          id: 'bo_the_times',
          fact: 'His 200 free times were good enough for the national junior team. He has told nobody at Kosei.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'He mentions it as a joke, once, and does not elaborate.',
        },
      ],
      speechStyle: 'Cheerful, literal, asks what things mean mid-sentence.',
      topics: ['what a screen is', 'swimming', 'being tall', 'dunking'],
      voiceSamples: [
        'What is a hedge? No, genuinely. Nobody has told me and I have been doing it wrong for a month.',
        'I can just — stand here? And they cannot get past? That is the whole job?',
        'If you throw it high enough I will get to it. That is a promise.',
      ],
      appearance: 'Seventeen, six foot nine, still built like a swimmer, permanently slightly out of breath.',
      visualHook: 'Shoulders far too wide for the jersey, which rides up on him constantly.',
      silhouette: 'Absurdly tall and slightly stooped, taking up the top of any frame he is in.',
      artSeed: 'lastfive-bo-01',
      portrait: 'last_five/bo',
      expressions: ['neutral', 'delighted', 'confused'],
      schedule: [
        { startMinute: 0, endMinute: 420, locationId: 'kosei_school', activity: 'asleep' },
        { startMinute: 420, endMinute: 900, locationId: 'kosei_school', activity: 'class' },
        { startMinute: 900, endMinute: 1230, locationId: 'kosei_gym', activity: 'practice' },
        { startMinute: 1230, endMinute: 1440, locationId: 'kosei_school', activity: 'eating enormously' },
      ],
      homeLocationId: 'kosei_gym',
      knowledgeScope: ['kosei', 'swimming'],
      startingRelationship: { trust: 10, affection: 10, respect: 0, fear: 0, rivalry: 0 },
      gates: [],
      attributes: { might: 17, agility: 8, mind: 10, presence: 12, resolve: 13, arcana: 3 },
      companion: null,
      scouting: null,
      combatant: null,
    },
    {
      id: 'nori',
      name: 'Nori Abe',
      role: 'Manager and analyst, second year',
      cardBlurb:
        'They cut the film, they know every opponent’s habits, and they will tell you what you keep doing before anyone else notices.',
      pronouns: 'they/them',
      publicTraits: ['Precise', 'Dry', 'Notices everything'],
      hiddenDrives: ['They want to coach and have never said so out loud'],
      values: ['Being right', 'Being useful'],
      fears: ['That the program ends and this all turns out to have been nothing'],
      socialStyle: 'Tells you the useful thing without the preamble.',
      boundaries: ['Do not call it "just the tape"'],
      goals: ['Have one of their reads win a game', 'Keep the program alive'],
      secrets: [
        {
          id: 'nori_has_the_report',
          fact: 'They have a copy of the incident report Yuki filed. They have had it since March.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'They hand it over when the player asks a question that shows they already half know.',
        },
      ],
      speechStyle: 'Flat, exact, occasionally very funny without changing tone.',
      topics: ['film', 'opponent habits', 'what you keep doing', 'the five', 'the report'],
      voiceSamples: [
        'You have gone right eleven times out of thirteen. I am not the only person who owns a camera.',
        'He steps across on the second dribble. Every time. It is the most reliable thing in this prefecture.',
        'I do not need you to be interested in this. I need you to watch it.',
      ],
      appearance: 'Sixteen, small, permanently carrying a laptop with one broken hinge.',
      visualHook: 'A laptop with a hinge held together by gaffer tape, carried everywhere like a clipboard.',
      silhouette: 'Compact, one arm clamped around a laptop, always slightly apart from the group.',
      artSeed: 'lastfive-nori-01',
      portrait: 'last_five/nori',
      expressions: ['neutral', 'dry', 'urgent'],
      schedule: [
        { startMinute: 0, endMinute: 400, locationId: 'film_room', activity: 'asleep at the desk, occasionally' },
        { startMinute: 400, endMinute: 900, locationId: 'kosei_school', activity: 'class' },
        { startMinute: 900, endMinute: 1260, locationId: 'kosei_gym', activity: 'filming practice' },
        { startMinute: 1260, endMinute: 1440, locationId: 'film_room', activity: 'cutting film' },
      ],
      homeLocationId: 'film_room',
      knowledgeScope: ['film', 'the_five', 'denda', 'basketball', 'kosei'],
      startingRelationship: { trust: 5, affection: 0, respect: 5, fear: 0, rivalry: 0 },
      gates: [
        {
          id: 'nori_hands_it_over',
          label: 'They give you the report',
          kind: 'TRUST',
          requires: { trust: 30, flagsSet: ['knows:denda_existed'] },
        },
      ],
      attributes: { might: 8, agility: 10, mind: 17, presence: 11, resolve: 13, arcana: 3 },
      companion: null,
      scouting: null,
      combatant: null,
    },
    {
      id: 'rei',
      name: 'Rei Amagi',
      role: 'Seiran Academy · scoring guard',
      cardBlurb:
        'The best scorer in the prefecture and the first of the five you have to beat. He left because Kosei could not win, and he will say so to your face.',
      pronouns: 'he/him',
      publicTraits: ['Cold', 'Exact', 'Utterly without cruelty'],
      hiddenDrives: ['He left first, and the other four followed, and he has never been asked how that felt'],
      values: ['Winning', 'Not lying to people to be liked'],
      fears: ['That he was the reason it collapsed'],
      socialStyle: 'Answers honestly at cost to himself. Does not do small talk.',
      boundaries: ['Will not discuss Denda'],
      goals: ['Win a national title', 'Not think about Kosei'],
      secrets: [
        {
          id: 'rei_went_first',
          fact: 'He transferred two days after Yuki filed the report. He knew what it said.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Only after the player has read the report and beaten him, or lost well.',
        },
      ],
      speechStyle: 'Level, unhurried, no filler. Says the harsh thing without heat.',
      topics: ['why he left', 'Kosei', 'your game', 'Nationals'],
      voiceSamples: [
        'You are better than anyone they had last year. That is not a compliment about you.',
        'I do not owe that school anything and neither did any of us.',
        'Go left. I am asking you to. I want to see if you can.',
      ],
      appearance: 'Eighteen, tall and narrow, Seiran’s white and red, a face that gives away nothing.',
      visualHook: 'A single white wristband on the left wrist, from a Kosei kit he no longer wears.',
      silhouette: 'Long, still, hands at his sides while everyone else is moving.',
      artSeed: 'lastfive-rei-01',
      portrait: 'last_five/rei',
      expressions: ['neutral', 'focused', 'surprised'],
      schedule: [{ startMinute: 0, endMinute: 1440, locationId: 'away_seiran', activity: 'at Seiran' }],
      homeLocationId: 'away_seiran',
      knowledgeScope: ['the_five', 'denda', 'basketball', 'seiran'],
      startingRelationship: { trust: 0, affection: 0, respect: 0, fear: 0, rivalry: 15 },
      gates: [
        {
          id: 'rei_tells_you',
          label: 'He tells you why he went first',
          kind: 'TRUST',
          requires: { respect: 35, hasItems: ['denda_report'] },
        },
      ],
      attributes: { might: 12, agility: 16, mind: 15, presence: 13, resolve: 15, arcana: 3 },
      companion: null,
      scouting: { learnRate: 2, cap: 8, revealCopy: '"Second dribble. You always decide on the second dribble."' },
      combatant: null,
    },
    {
      id: 'tsubame',
      name: 'Tsubame Kirisawa',
      role: 'Hakuba West · point guard',
      cardBlurb:
        'The second of the five, and the one everybody is wrong about. She will ask you how Dai is before she asks who you are.',
      pronouns: 'she/her',
      publicTraits: ['Warm', 'Watchful', 'Will not defend herself'],
      hiddenDrives: ['Her family moved for her mother’s treatment and she has told nobody why she transferred'],
      values: ['Her family', 'Not making it about her'],
      fears: ['Being remembered as the one who quit'],
      socialStyle: 'Asks about you until you forget you were asking about her.',
      boundaries: ['Will not talk about her mother'],
      goals: ['Get through this year', 'Speak to Dai again'],
      secrets: [
        {
          id: 'tsubame_why',
          fact: 'She transferred because her family moved ninety minutes away for her mother’s treatment. Nothing to do with the team.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'She tells the player if they ask without accusing her.',
        },
      ],
      speechStyle: 'Gentle, quick, turns every question back into one.',
      topics: ['Kosei', 'Dai', 'why she left', 'Kai'],
      voiceSamples: [
        'How is he? Dai. Is he — is he all right?',
        'You can think what you like. Most people already have.',
        'That first year of yours is going to be better than me. Tell him I said that.',
      ],
      appearance: 'Seventeen, short, Hakuba’s faded blue, a plait she redoes between every quarter.',
      visualHook: 'A plait she pulls apart and redoes constantly, always mid-motion.',
      silhouette: 'Low and wide-based, head up, looking somewhere other than where she is about to throw it.',
      artSeed: 'lastfive-tsubame-01',
      portrait: 'last_five/tsubame',
      expressions: ['neutral', 'warm', 'wounded'],
      schedule: [{ startMinute: 0, endMinute: 1440, locationId: 'away_hakuba', activity: 'at Hakuba' }],
      homeLocationId: 'away_hakuba',
      knowledgeScope: ['the_five', 'basketball', 'hakuba', 'kosei'],
      startingRelationship: { trust: 0, affection: 0, respect: 0, fear: 0, rivalry: 5 },
      gates: [
        {
          id: 'tsubame_explains',
          label: 'She tells you the real reason',
          kind: 'TRUST',
          requires: { trust: 25 },
        },
      ],
      attributes: { might: 9, agility: 15, mind: 17, presence: 14, resolve: 13, arcana: 3 },
      companion: null,
      scouting: { learnRate: 2, cap: 6, revealCopy: '"You look at him before you pass to him. Every time. I have told everyone."' },
      combatant: null,
    },
    {
      id: 'gora',
      name: 'Gora Vance',
      role: 'Tessen Industrial · centre',
      cardBlurb:
        'Seven foot one, the kindest person you will meet, and the reason nothing you throw at that rim goes in. He left because staying was making him somebody he did not want to be.',
      pronouns: 'he/him',
      publicTraits: ['Quiet', 'Gentle', 'Immovable'],
      hiddenDrives: ['Denda used him as the example when he wanted to frighten the others'],
      values: ['Not being frightened of a gym', 'Protecting whoever is smallest'],
      fears: ['Being made to be an instrument again'],
      socialStyle: 'Says very little, and it is always the point.',
      boundaries: ['Will not be shouted at by anybody, ever again'],
      goals: ['Play somewhere he is not afraid', 'Never see Denda again'],
      secrets: [
        {
          id: 'gora_was_the_example',
          fact: 'Denda singled him out. The others watched it for two years.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'He says it plainly if the player mentions the report.',
        },
      ],
      speechStyle: 'Slow, short sentences, long gaps that are not hesitation.',
      topics: ['Kosei', 'Denda', 'why he left', 'your centre'],
      voiceSamples: [
        'Your big one. Bo. He is enjoying it. Keep that.',
        'I am not angry with anybody there. I just cannot go back in that building.',
        'You are quick. It will not be enough. Come again anyway.',
      ],
      appearance: 'Eighteen, seven foot one, moves carefully as though the world is slightly too small.',
      visualHook: 'Ducks reflexively under every doorway and half the ceiling lights.',
      silhouette: 'Enormous and slightly folded in on himself, taking up more space than he wants to.',
      artSeed: 'lastfive-gora-01',
      portrait: 'last_five/gora',
      expressions: ['neutral', 'gentle', 'closed'],
      schedule: [{ startMinute: 0, endMinute: 1440, locationId: 'away_tessen', activity: 'at Tessen' }],
      homeLocationId: 'away_tessen',
      knowledgeScope: ['the_five', 'denda', 'basketball', 'tessen'],
      startingRelationship: { trust: 5, affection: 0, respect: 0, fear: 0, rivalry: 5 },
      gates: [
        {
          id: 'gora_says_it',
          label: 'He tells you what it was like',
          kind: 'TRUST',
          requires: { trust: 20, flagsSet: ['knows:denda_existed'] },
        },
      ],
      attributes: { might: 18, agility: 8, mind: 12, presence: 12, resolve: 16, arcana: 3 },
      companion: null,
      scouting: { learnRate: 1, cap: 5, revealCopy: '"You go under. You always go under. I will be there."' },
      combatant: null,
    },
    {
      id: 'mikael',
      name: 'Mikael Sorrel',
      role: 'Onda Commercial · defensive guard',
      cardBlurb:
        'He will guard you for thirty-two minutes and talk for all of them, and he has watched every minute of film on you. He left for a scholarship his family needed and he is not sorry.',
      pronouns: 'he/him',
      publicTraits: ['Relentless', 'Talks constantly', 'Unembarrassable'],
      hiddenDrives: ['He sends most of the scholarship money home and nobody at Onda knows'],
      values: ['His family', 'Effort as a moral position'],
      fears: ['Being ordinary once the talking stops'],
      socialStyle: 'Says whatever will get a reaction, then reads the reaction.',
      boundaries: ['Do not bring up money'],
      goals: ['Be the best defender in the country', 'Get his brother through school'],
      secrets: [
        {
          id: 'mik_the_money',
          fact: 'Onda pays his fees. Most of what is left goes home to his younger brother.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Only if the player earns it, and he will deny it once first.',
        },
      ],
      speechStyle: 'Machine-gun, playful, lands one real sentence in ten.',
      topics: ['guarding you', 'why he left', 'Kosei', 'his brother'],
      voiceSamples: [
        'Left. Left. He is going left — oh, you went left. I said it out loud and you did it anyway.',
        'They offered, I took it, my mother cried. Which part is the betrayal?',
        'Thirty-two minutes. That is what you get. Every one of them.',
      ],
      appearance: 'Eighteen, compact and thick through the legs, Onda’s black and gold, permanently mid-sentence.',
      visualHook: 'A gold tooth he got at fifteen and mentions unprompted.',
      silhouette: 'Low, wide, arms out, always between somebody and somewhere.',
      artSeed: 'lastfive-mikael-01',
      portrait: 'last_five/mikael',
      expressions: ['neutral', 'grinning', 'serious'],
      schedule: [{ startMinute: 0, endMinute: 1440, locationId: 'away_onda', activity: 'at Onda' }],
      homeLocationId: 'away_onda',
      knowledgeScope: ['the_five', 'basketball', 'onda'],
      startingRelationship: { trust: 0, affection: 0, respect: 0, fear: 0, rivalry: 20 },
      gates: [
        {
          id: 'mik_is_honest',
          label: 'He tells you about the money',
          kind: 'TRUST',
          requires: { trust: 35, respect: 25 },
        },
      ],
      attributes: { might: 13, agility: 16, mind: 13, presence: 15, resolve: 17, arcana: 3 },
      companion: null,
      scouting: { learnRate: 3, cap: 9, revealCopy: '"I have watched every minute you have played this season. Every minute."' },
      combatant: null,
    },
    {
      id: 'yuki',
      name: 'Yuki Hoshizawa',
      role: 'Kurogane · shooter',
      cardBlurb:
        'The last one between you and Nationals. She filed the report that ended Coach Denda, the school let everyone believe the five just quit, and she has never corrected it.',
      pronouns: 'she/her',
      publicTraits: ['Unreadable', 'Exact', 'Unhurried'],
      hiddenDrives: ['She would do it again and it cost her everything and both of those are true'],
      values: ['Telling the truth once, properly', 'Not needing to be thanked'],
      fears: ['That it made no difference'],
      socialStyle: 'Long silences. Answers the question you should have asked.',
      boundaries: ['Will not perform being a victim'],
      goals: ['Finish school', 'Hear one person say it out loud'],
      secrets: [
        {
          id: 'yuki_filed_it',
          fact: 'She wrote and filed the incident report in March. The school buried it and let the transfers explain themselves.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'The player can work it out from the report’s signature before she ever says it.',
        },
      ],
      speechStyle: 'Sparse and level. Never raises anything.',
      topics: ['the report', 'Denda', 'Kosei', 'the other four'],
      voiceSamples: [
        'You have read it, then. You would not be standing there otherwise.',
        'They did not follow me. They left for their own reasons. I would rather you knew that.',
        'I am going to make about nine of these. You should probably do something about it.',
      ],
      appearance: 'Eighteen, still, Kurogane’s dark green, hair pinned back exactly the same way every day.',
      visualHook: 'Two plain black pins holding her hair back, always in the same place.',
      silhouette: 'Upright and motionless, hands loose, the only person in the gym not fidgeting.',
      artSeed: 'lastfive-yuki-01',
      portrait: 'last_five/yuki',
      expressions: ['neutral', 'level', 'briefly undone'],
      schedule: [{ startMinute: 0, endMinute: 1440, locationId: 'away_kurogane', activity: 'at Kurogane' }],
      homeLocationId: 'away_kurogane',
      knowledgeScope: ['the_five', 'denda', 'the_report', 'basketball', 'kurogane'],
      startingRelationship: { trust: 0, affection: 0, respect: 5, fear: 0, rivalry: 10 },
      gates: [
        {
          id: 'yuki_speaks',
          label: 'She talks about the report',
          kind: 'TRUST',
          requires: { trust: 20, hasItems: ['denda_report'] },
        },
      ],
      attributes: { might: 10, agility: 14, mind: 15, presence: 12, resolve: 18, arcana: 3 },
      companion: null,
      scouting: { learnRate: 2, cap: 7, revealCopy: '"You close out short on me. You have done it four times."' },
      combatant: null,
    },
  ],
  quests: [
    {
      id: 'q_make_the_team',
      title: 'Forty Minutes',
      summary: 'Coach Torakawa has one practice to decide whether you are worth a jersey.',
      kind: 'MAIN',
      startsActive: true,
      involvedCharacterIds: ['coach', 'dai', 'kai', 'jun'],
      involvedLocationIds: ['kosei_gym'],
      knownRewardCopy: 'A place on the team, and a number nobody else wanted.',
      steps: [
        {
          id: 'show_her_something',
          playerCopy: 'Show Coach Torakawa one thing you can actually do.',
          directorNotes:
            'A live scrimmage inside the first five minutes. She is not looking for a complete player, she is looking for one repeatable strength. Whatever the player attempts here starts their tendency profile — do not steer them toward a position.',
          succeedWhen: null,
          succeedWhenAny: [
            {
              routeId: 'score_it',
              label: 'Score on somebody',
              predicate: { flagsSet: ['used:hard_drive'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['tryout_scoring'],
              closesFlags: [],
            },
            {
              routeId: 'shoot_it',
              label: 'Make shots',
              predicate: { flagsSet: ['used:pull_up'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['tryout_shooting'],
              closesFlags: [],
            },
            {
              routeId: 'run_it',
              label: 'Make everybody else better',
              predicate: { flagsSet: ['used:read_and_pass'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['tryout_passing'],
              closesFlags: [],
            },
            {
              routeId: 'guard_someone',
              label: 'Take the best player on the floor',
              predicate: { flagsSet: ['used:face_guard'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['tryout_defense'],
              closesFlags: [],
            },
            {
              routeId: 'go_get_it',
              label: 'Out-rebound people bigger than you',
              predicate: { flagsSet: ['used:crash_glass'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['tryout_boards'],
              closesFlags: [],
            },
            {
              routeId: 'in_the_post',
              label: 'Score with your back to the basket',
              predicate: { flagsSet: ['used:post_up'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['tryout_post'],
              closesFlags: [],
            },
          ],
          rewards: {
            xp: 60,
            items: [],
            flags: ['on_the_team'],
            abilities: [],
            reputation: [{ factionId: 'faction_team', amount: 10 }],
          },
        },
        {
          id: 'meet_them',
          playerCopy: 'Learn who you are actually playing with.',
          directorNotes:
            'Dai introduces everyone whether they want it or not. Jun does not shake your hand. Bo asks you what a hedge is.',
          enterWhen: { flagsSet: ['on_the_team'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhen: { flagsSet: ['spoke:dai', 'spoke:kai'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhenAny: [],
          rewards: {
            xp: 40,
            items: [],
            flags: ['knows:the_team'],
            abilities: [],
            reputation: [{ factionId: 'faction_team', amount: 10 }],
          },
        },
      ],
    },
    {
      id: 'q_earn_minutes',
      title: 'Earn It',
      summary: 'Minutes are not given out. Jun Hasabe has taken four hundred shots a day since March to prove that.',
      kind: 'MAIN',
      involvedCharacterIds: ['coach', 'jun', 'nori'],
      involvedLocationIds: ['kosei_gym', 'film_room'],
      knownRewardCopy: 'A starting spot, and somebody else’s opinion about it.',
      discoverWhen: { flagsSet: ['on_the_team'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
      steps: [
        {
          id: 'become_something',
          playerCopy: 'Become good enough at one thing that Coach has to play you.',
          directorNotes:
            'This step completes off the tendency system: the player has to have leaned on something hard enough for it to be an identity. Do not tell them which. Coach names it when it happens.',
          succeedWhen: null,
          succeedWhenAny: [
            {
              routeId: 'by_reputation',
              label: 'The team starts looking for you',
              predicate: { flagsSet: [], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [{ factionId: 'faction_team', value: 30 }], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['coach_plays_you'],
              closesFlags: [],
            },
            {
              routeId: 'by_film',
              label: 'Show Coach what the film says about you',
              predicate: { flagsSet: [], flagsUnset: [], hasItems: ['nori_tape'], atLocation: null, completedEvents: [], minRelationship: [{ characterId: 'coach', dimension: 'respect', value: 20 }], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['coach_plays_you'],
              closesFlags: [],
            },
            {
              routeId: 'over_juns_body',
              label: 'Beat Jun in front of everybody',
              predicate: { flagsSet: ['engaged:jun'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [{ characterId: 'jun', dimension: 'rivalry', value: 35 }], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['coach_plays_you', 'jun_humiliated'],
              closesFlags: [],
            },
          ],
          rewards: {
            xp: 120,
            items: [],
            flags: ['starting_five'],
            abilities: ['come_off_screen'],
            reputation: [{ factionId: 'faction_school', amount: 10 }],
          },
        },
        {
          id: 'sort_out_jun',
          playerCopy: 'Do something about Jun Hasabe.',
          directorNotes:
            'There is no route where this is free. Making him a friend costs the player something; leaving him angry costs the team chemistry and eventually a game.',
          enterWhen: { flagsSet: ['starting_five'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhen: null,
          succeedWhenAny: [
            {
              routeId: 'make_him_yours',
              label: 'Make him the reason you are good',
              predicate: { flagsSet: [], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [{ characterId: 'jun', dimension: 'respect', value: 30 }], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['jun_is_with_you'],
              closesFlags: [],
            },
            {
              routeId: 'let_it_burn',
              label: 'Let him hate it',
              predicate: { flagsSet: ['jun_humiliated'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['jun_is_against_you'],
              closesFlags: ['jun_is_with_you'],
            },
          ],
          rewards: { xp: 100, items: [], flags: [], abilities: ['call_it_out'], reputation: [] },
        },
      ],
    },
    {
      id: 'q_the_road',
      title: 'The Road',
      summary: 'Five schools between here and Nationals, and one of the five who left is at each of them.',
      kind: 'MAIN',
      involvedCharacterIds: ['rei', 'tsubame', 'gora', 'mikael', 'yuki'],
      involvedLocationIds: ['away_seiran', 'away_hakuba', 'away_tessen', 'away_onda', 'away_kurogane'],
      knownRewardCopy: 'Nationals, and the program still existing in March.',
      discoverWhen: { flagsSet: ['on_the_team'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
      steps: [
        {
          id: 'seiran',
          playerCopy: 'Seiran Academy. Rei Amagi scores forty on people and does not celebrate.',
          directorNotes:
            'The first of the five. Rei is a pure scoring problem: there is no scheme answer, somebody has to guard him. Losing here is normal and opens the training arc rather than ending anything.',
          succeedWhen: { flagsSet: ['played:rei'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhenAny: [],
          rewards: { xp: 140, items: [], flags: ['knows:the_five_are_real'], abilities: [], reputation: [{ factionId: 'faction_scouts', amount: 10 }] },
        },
        {
          id: 'hakuba',
          playerCopy: 'Hakuba West. Tsubame Kirisawa makes four other people unguardable.',
          directorNotes:
            'A passing problem, not a scoring one. Guarding her does nothing; the answer is taking away everyone she is looking for. Dai will not talk on the bus.',
          enterWhen: { flagsSet: ['played:rei'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhen: { flagsSet: ['played:tsubame'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhenAny: [],
          rewards: { xp: 150, items: [], flags: ['knows:tsubame_side'], abilities: [], reputation: [{ factionId: 'faction_scouts', amount: 10 }] },
        },
        {
          id: 'tessen',
          playerCopy: 'Tessen Industrial. Gora Vance is seven foot one and the rim belongs to him.',
          directorNotes:
            'A physical wall. Nothing goes in near him, so the game has to be played somewhere else. He is kind to Bo throughout, which nobody expects.',
          enterWhen: { flagsSet: ['played:tsubame'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhen: { flagsSet: ['played:gora'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhenAny: [],
          rewards: { xp: 160, items: [], flags: ['knows:denda_existed'], abilities: [], reputation: [{ factionId: 'faction_scouts', amount: 10 }] },
        },
        {
          id: 'onda',
          playerCopy: 'Onda Commercial. Mikael Sorrel has watched every minute you have played.',
          directorNotes:
            'This is the scouting payoff game. Whatever the player has leaned on all season, Mikael has it on film and will take it away in the first quarter. The game is about what they do second.',
          enterWhen: { flagsSet: ['played:gora'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhen: { flagsSet: ['played:mikael'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhenAny: [],
          rewards: { xp: 180, items: [], flags: [], abilities: ['face_up'], reputation: [{ factionId: 'faction_scouts', amount: 15 }] },
        },
        {
          id: 'kurogane',
          playerCopy: 'Kurogane. Yuki Hoshizawa, and whatever it is nobody will tell you about last March.',
          directorNotes:
            'The last one before Nationals. By now the player should either know what the report said or be one question away from it.',
          enterWhen: { flagsSet: ['played:mikael'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhen: null,
          succeedWhenAny: [
            {
              routeId: 'won_it',
              label: 'Beat Kurogane',
              predicate: { flagsSet: ['beat:yuki'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['qualified'],
              closesFlags: [],
            },
            {
              routeId: 'lost_it',
              label: 'Lose, and find out what next season looks like',
              predicate: { flagsSet: ['lost_to:yuki'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['season_over'],
              closesFlags: ['qualified'],
            },
          ],
          rewards: { xp: 220, items: [], flags: [], abilities: [], reputation: [{ factionId: 'faction_school', amount: 20 }] },
        },
      ],
    },
    {
      id: 'q_why_they_left',
      title: 'Why They Left',
      summary: 'Everybody at this school has the same answer and none of them will look at you while giving it.',
      kind: 'MAIN',
      involvedCharacterIds: ['nori', 'coach', 'yuki', 'gora', 'dai'],
      involvedLocationIds: ['film_room', 'kosei_school', 'away_kurogane'],
      knownRewardCopy: 'What actually happened in March.',
      discoverWhen: { flagsSet: ['knows:the_team'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
      steps: [
        {
          id: 'the_name',
          playerCopy: 'Find out who was coaching Kosei before Torakawa.',
          directorNotes:
            'Nobody says Denda’s name. The banners stop in the right year, the trophy case has a gap, and Bo will cheerfully say the thing everyone else avoids.',
          succeedWhen: null,
          succeedWhenAny: [
            {
              routeId: 'ask_around',
              label: 'Ask somebody who has not learned not to',
              predicate: { flagsSet: ['spoke:bo'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['knows:denda_existed'],
              closesFlags: [],
            },
            {
              routeId: 'read_the_wall',
              label: 'Read the banners and notice what is missing',
              predicate: { flagsSet: ['inspected:kosei_gym'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['knows:denda_existed'],
              closesFlags: [],
            },
            {
              routeId: 'gora_says',
              label: 'Hear it from somebody who was there',
              predicate: { flagsSet: ['visited:away_tessen'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [{ characterId: 'gora', dimension: 'trust', value: 20 }], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['knows:denda_existed', 'knows:gora_was_the_example'],
              closesFlags: [],
            },
          ],
          rewards: { xp: 80, items: [], flags: [], abilities: [], reputation: [] },
        },
        {
          id: 'the_report',
          playerCopy: 'Get hold of what was filed in March.',
          directorNotes:
            'Nori has had a copy since March and has been waiting for somebody to ask a question that showed they already half knew.',
          enterWhen: { flagsSet: ['knows:denda_existed'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhen: { flagsSet: [], flagsUnset: [], hasItems: ['denda_report'], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhenAny: [],
          rewards: { xp: 140, items: [], flags: ['knows:what_happened'], abilities: [], reputation: [] },
        },
        {
          id: 'what_you_do_with_it',
          playerCopy: 'Decide what to do with what you now know.',
          directorNotes:
            'There is no correct answer and the story does not indicate one. Telling the team changes the room. Telling the school changes the program’s odds. Saying nothing is a real option with real costs.',
          enterWhen: { flagsSet: ['knows:what_happened'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
          succeedWhen: null,
          succeedWhenAny: [
            {
              routeId: 'tell_the_team',
              label: 'Tell the six people it is actually about',
              predicate: { flagsSet: ['spoke:dai', 'spoke:kai'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [{ characterId: 'dai', dimension: 'trust', value: 30 }], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['team_knows'],
              closesFlags: [],
            },
            {
              routeId: 'tell_the_school',
              label: 'Make the board read it',
              predicate: { flagsSet: [], flagsUnset: [], hasItems: ['denda_report'], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [{ factionId: 'faction_school', value: 25 }], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['school_knows'],
              closesFlags: [],
            },
            {
              routeId: 'tell_yuki',
              label: 'Tell Yuki Hoshizawa that somebody knows',
              predicate: { flagsSet: ['visited:away_kurogane'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [{ characterId: 'yuki', dimension: 'trust', value: 20 }], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['yuki_was_told'],
              closesFlags: [],
            },
            {
              routeId: 'say_nothing',
              label: 'Say nothing and play basketball',
              predicate: { flagsSet: ['played:mikael'], flagsUnset: ['team_knows', 'school_knows'], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['said_nothing'],
              closesFlags: [],
            },
          ],
          rewards: { xp: 200, items: [], flags: [], abilities: [], reputation: [] },
        },
      ],
    },
    {
      id: 'q_kai',
      title: 'The Pass',
      summary: 'Kai Sumire sees things two seconds before anybody else and is too frightened to throw them.',
      kind: 'SIDE',
      involvedCharacterIds: ['kai', 'tsubame'],
      involvedLocationIds: ['kosei_gym', 'the_roof'],
      knownRewardCopy: 'A point guard who throws it.',
      discoverWhen: { flagsSet: ['spoke:kai'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
      steps: [
        {
          id: 'get_him_to_throw_it',
          playerCopy: 'Get Kai to make the pass he keeps not making.',
          directorNotes:
            'He needs either somebody to be reliably where he looks, or to hear that Tsubame rated him. Not a pep talk — a reason.',
          succeedWhen: null,
          succeedWhenAny: [
            {
              routeId: 'be_there',
              label: 'Be where he is looking, every time',
              predicate: { flagsSet: ['used:come_off_screen'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [{ characterId: 'kai', dimension: 'trust', value: 25 }], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['kai_throws_it'],
              closesFlags: [],
            },
            {
              routeId: 'tell_him_what_she_said',
              label: 'Bring him what Tsubame said about him',
              predicate: { flagsSet: ['knows:tsubame_side'], flagsUnset: [], hasItems: [], atLocation: null, completedEvents: [], minRelationship: [], minFactionReputation: [], beforeWorldMinute: null, afterWorldMinute: null },
              setsFlags: ['kai_throws_it'],
              closesFlags: [],
            },
          ],
          rewards: {
            xp: 120,
            items: [],
            flags: [],
            abilities: [],
            reputation: [{ factionId: 'faction_team', amount: 15 }],
          },
        },
      ],
    },
  ],
  worldEvents: [
    {
      id: 'we_the_notice',
      atWorldMinute: 20 * 60,
      locationId: 'locker_room',
      publicCopy:
        'Somebody has taped the board’s letter to the inside of the locker room door, at eye height, where you cannot not read it. Nobody admits to doing it.',
      directorNotes:
        'It was Dai. He will not say so. The letter gives the March date and the Nationals condition in the driest possible language.',
      setsFlags: ['knows:the_deadline'],
      cancelledByFlags: [],
      requiresFlags: [],
      movesCharacters: [],
    },
    {
      id: 'we_the_draw',
      atWorldMinute: 3 * 1440 + 16 * 60,
      locationId: 'kosei_school',
      publicCopy:
        'The regional draw goes up outside the staff room. Kosei is in the same half as Seiran, Hakuba, Tessen, Onda and Kurogane. All five. Somebody laughs, and then stops.',
      directorNotes:
        'The road becomes concrete here. This is the moment the season stops being abstract and becomes five specific people.',
      setsFlags: ['knows:the_draw'],
      cancelledByFlags: [],
      requiresFlags: ['on_the_team'],
      movesCharacters: [],
    },
    {
      id: 'we_jun_snaps',
      atWorldMinute: 6 * 1440 + 17 * 60,
      locationId: 'kosei_gym',
      publicCopy:
        'Jun Hasabe stops mid-drill, puts the ball down carefully, and asks Coach Torakawa to explain the criteria in front of everybody.',
      directorNotes:
        'He is not wrong to ask and she does not pretend he is. How the player behaves in the next thirty seconds is worth more to the room than anything they do in a game.',
      setsFlags: ['jun_asked_out_loud'],
      cancelledByFlags: ['jun_is_with_you'],
      requiresFlags: ['starting_five'],
      movesCharacters: [{ characterId: 'jun', toLocationId: 'kosei_gym' }],
    },
    {
      id: 'we_bo_gets_it',
      atWorldMinute: 9 * 1440 + 17 * 60,
      locationId: 'kosei_gym',
      publicCopy:
        'Bo Ferrand catches it above the square, comes down with it, and stands there holding the ball looking genuinely shocked. The gym makes a noise it has not made in a year.',
      directorNotes:
        'The first time anything good has happened on this floor since March. Small, and everybody feels it.',
      setsFlags: ['bo_arrived'],
      cancelledByFlags: [],
      requiresFlags: ['knows:the_team'],
      movesCharacters: [],
    },
    {
      id: 'we_the_ankle',
      atWorldMinute: 14 * 1440 + 18 * 60,
      locationId: 'kosei_gym',
      publicCopy:
        'Dai Okonkwo lands on somebody’s foot in a drill nobody was competing in, and the sound the gym makes is the sound of everybody doing the same arithmetic at once.',
      directorNotes:
        'A high ankle sprain. He will play through it and be worse; sitting him out costs games now and keeps him for March. There is no free option.',
      setsFlags: ['dai_hurt'],
      cancelledByFlags: [],
      requiresFlags: ['knows:the_draw'],
      movesCharacters: [],
    },
    {
      id: 'we_scouts_arrive',
      atWorldMinute: 21 * 1440 + 17 * 60,
      locationId: 'kosei_gym',
      publicCopy:
        'Two people you do not recognise are standing at the back of the gym with lanyards on, and neither of them has sat down.',
      directorNotes:
        'The circuit has heard about somebody at Kosei. Whether that is the player depends on what they have actually done.',
      setsFlags: ['scouts_watching'],
      cancelledByFlags: [],
      requiresFlags: ['played:rei'],
      movesCharacters: [],
    },
  ],
  promises: [
    {
      id: 'p_the_program',
      kind: 'FINALE',
      label: 'Whether there is a team here in March',
      seedHint: 'The board’s letter on the locker room door, in language too dry for what it says.',
      payoffHint: 'Nationals, or a last game in an empty gym, and either way six people who were here.',
      weight: 1,
    },
    {
      id: 'p_why_they_left',
      kind: 'MYSTERY',
      label: 'What actually happened last March',
      seedHint: 'Everybody gives the same answer about the five and nobody looks at you while giving it.',
      payoffHint: 'Yuki filed a report about Coach Denda, the school buried it, and let five teenagers carry the blame.',
      weight: 0.9,
    },
    {
      id: 'p_who_you_become',
      kind: 'THEME',
      label: 'What kind of player you turn out to be',
      seedHint: 'Coach Torakawa refuses to tell you what she wants from you.',
      payoffHint: 'Somebody names it out loud, and it is a description of what you actually did.',
      weight: 0.85,
    },
    {
      id: 'p_getting_solved',
      kind: 'RIVAL',
      label: 'The night somebody has your whole game on film',
      seedHint: 'Nori mentions, flatly, that they are not the only person in the prefecture who owns a camera.',
      payoffHint: 'Mikael Sorrel takes away the thing you are best at inside one quarter, and you have to be somebody else.',
      weight: 0.9,
    },
    {
      id: 'p_jun',
      kind: 'RELATIONSHIP',
      label: 'The teammate whose spot you took',
      seedHint: 'Jun Hasabe does not shake your hand and is perfectly polite about it.',
      payoffHint: 'Either he becomes the reason you are good, or he is right about you and everybody sees it.',
      weight: 0.75,
    },
  ],
  archetypes: [
    {
      id: 'arch_streetball',
      name: 'Never Coached',
      role: 'Handle and creativity',
      summary:
        'You learned on an outdoor court with no referee. Your handle is real and your habits are terrible, and Coach will tell you which is which.',
      playstyle: ['Creative', 'Ball-dominant', 'Undisciplined'],
      blurb:
        'Nobody ever taught you to do it properly, so you worked out your own way, and it turns out your own way beats most people.',
      attributeBonus: { agility: 3, presence: 1 },
      skillProficiencies: { handle: 3, finishing: 2, court_iq: 1, defense: 0 },
      startingItems: [],
      startingAbilities: [],
      startingReputation: [],
    },
    {
      id: 'arch_gym_rat',
      name: 'Gym Rat',
      role: 'Shooting and conditioning',
      summary:
        'You are not the most talented person in any room and you have never been out-worked. Your shot is repeatable and your legs do not go.',
      playstyle: ['Shooting', 'Relentless', 'Not explosive'],
      blurb:
        'Four hundred a day since you were eleven, in a gym that let you in because the caretaker liked you.',
      attributeBonus: { resolve: 3, agility: 1 },
      skillProficiencies: { shooting: 3, conditioning: 2, handle: 1, rebounding: 0 },
      startingItems: [{ itemId: 'good_shoes', qty: 1 }],
      startingAbilities: [],
      startingReputation: [],
    },
    {
      id: 'arch_late',
      name: 'Grew Late',
      role: 'Size and defence',
      summary:
        'You were the small one until eighteen months ago. You still play like a guard and you are now six foot six, which nobody has worked out how to deal with.',
      playstyle: ['Big', 'Defensive', 'Still learning it'],
      blurb:
        'You spent four years learning how to survive being the smallest person on the floor and then stopped being that.',
      attributeBonus: { might: 3, resolve: 1 },
      skillProficiencies: { rebounding: 3, defense: 2, passing: 1, shooting: 0 },
      startingItems: [],
      startingAbilities: [],
      startingReputation: [],
    },
    {
      id: 'arch_analyst',
      name: 'Watched Everything',
      role: 'Reading the game',
      summary:
        'You have watched more basketball than anyone at this school and played almost none of it. You know where the ball should go before you can get it there.',
      playstyle: ['Cerebral', 'Passing', 'Physically behind'],
      blurb:
        'You can name the set they are running from the first cut. You have also never been in a real huddle.',
      attributeBonus: { mind: 3, presence: 1 },
      skillProficiencies: { court_iq: 3, passing: 2, leadership: 1, finishing: 0 },
      startingItems: [{ itemId: 'nori_tape', qty: 1 }],
      startingAbilities: [],
      startingReputation: [],
    },
  ],
  setupFields: [
    { id: 'displayName', label: 'What is on the back of your jersey?', kind: 'TEXT', required: true, maxLength: 40, placeholder: 'e.g. Sora Kimura' },
    { id: 'pronouns', label: 'Pronouns', kind: 'TEXT', required: false, maxLength: 24, placeholder: 'e.g. they/them' },
    {
      id: 'archetype',
      label: 'How did you learn to play?',
      helpText:
        'Where you came from, which sets your attributes and your training. It does NOT set your position — nobody here has one. What kind of player you become is counted out of what you actually try on the floor, over the season, and it can be anything. This choice is fixed for this run; who you turn into is not.',
      kind: 'ARCHETYPE',
      required: true,
    },
    {
      id: 'worldKnowsAboutYou',
      label: 'Has anyone at Kosei heard of you?',
      helpText: 'Most players arrive as nobody. That is fine, and it is the normal answer.',
      kind: 'TEXT',
      required: false,
      maxLength: 300,
      placeholder: 'e.g. I played one year at a school two prefectures away and left in the middle of the season, and I would rather not explain why.',
    },
    {
      id: 'why_here',
      label: 'Why Kosei, of all places?',
      helpText: 'Establishes what you have to lose if the program closes in March.',
      kind: 'CHOICE',
      advanced: true,
      options: [
        { id: 'nowhere_else', label: 'Nowhere else would take you' },
        { id: 'saw_them', label: 'You watched the old team play once and never forgot it' },
        { id: 'family', label: 'Your family moved here and you had no say' },
        { id: 'the_challenge', label: 'You heard it was dying and that sounded interesting' },
      ],
    },
    {
      id: 'appearance',
      label: 'What do people notice first?',
      kind: 'TEXT',
      advanced: true,
      maxLength: 200,
      placeholder: 'e.g. Left-handed, and about four inches taller than anyone expects from behind.',
    },
  ],
  /**
   * Where this can end up.
   *
   * Destinations, not a route. Every one of these is reachable from what the
   * player actually did and none of them is the intended outcome — the world
   * does not know which of these it is heading for, and neither does the
   * director. Several are losses. "Nobody Left To Coach" is what happens if the
   * player is good enough to be scouted and takes the offer, and it is a real
   * ending rather than a punishment for disloyalty.
   */
  endings: [
    {
      id: 'end_nationals',
      name: 'The Program Stays',
      rarity: 'RARE',
      minTurn: 40,
      requires: { flagsSet: ['qualified'] },
      condition:
        'Kosei reached Nationals, so the board condition is met and the program survives. Play this ' +
        'when the season is genuinely over rather than the moment qualification lands — the point is ' +
        'the room afterwards, not the buzzer.',
      epilogue:
        'The board condition was met and nobody at the school mentions it again. The gym is booked for ' +
        'next season. Whoever is still here got what they came for, and the five who left are somewhere ' +
        'else, hearing about it.',
      hint: 'Every road to Nationals runs through one of the five.',
    },
    {
      id: 'end_season_over',
      name: 'Two Points Short',
      rarity: 'COMMON',
      minTurn: 40,
      requires: { flagsSet: ['season_over'], flagsUnset: ['qualified'] },
      condition:
        'The season ended without qualification. The program closes in March. Do not soften this and ' +
        'do not find a loophole — the story is what these people do on the last night of a thing ' +
        'that is ending, and it is allowed to be the ending they get.',
      epilogue:
        'The board does not need to meet again. Somebody takes the banners down in April, and the ' +
        'sixth-years who never started a game they did not have to are the last people to leave the gym.',
      hint: '',
    },
    {
      id: 'end_captain',
      name: 'The One They Follow',
      rarity: 'UNCOMMON',
      minTurn: 30,
      requires: {
        flagsSet: ['starting_five'],
        minFactionReputation: [{ factionId: 'faction_team', value: 60 }],
        minRelationship: [{ characterId: 'coach', dimension: 'respect', value: 40 }],
      },
      condition:
        'The team is the player\'s now, whether or not anybody has said the word captain. Reachable ' +
        'alongside any result — winning is not required to have become the person the room turns to.',
      epilogue:
        'Nobody votes on it. It is simply true by February that the huddle waits for you to speak, and ' +
        'Torakawa has stopped explaining things twice.',
      hint: 'The huddle has started waiting for you.',
    },
    {
      id: 'end_transfer',
      name: 'Nobody Left To Coach',
      rarity: 'UNCOMMON',
      minTurn: 30,
      requires: { flagsSet: ['scouts_watching', 'left_the_map'] },
      condition:
        'The player was seen, and left. This is what the five did, from the inside. Write it without ' +
        'judgement — it is a real thing a sixteen-year-old does when a better school asks, and the ' +
        'people left behind are allowed to be furious about it.',
      epilogue:
        'The paperwork takes a week. Somebody at Kosei finds out from a group chat. Whatever the ' +
        'official story becomes, it will not be the true one, which is the part you already knew.',
      hint: '',
    },
    {
      id: 'end_collapse',
      name: 'Six Became Four',
      rarity: 'RARE',
      minTurn: 25,
      requires: { flagsSet: ['jun_is_against_you', 'dai_hurt'] },
      condition:
        'The team came apart before the season could end it — people stopped turning up, and the ones ' +
        'who did stopped speaking. Reachable whether or not the player caused it. Do not have anybody ' +
        'apologise at the end unless they would.',
      epilogue:
        'The forfeit is recorded as a forfeit. There is no meeting and no speech, just a practice where ' +
        'four people wait twenty minutes and then go home.',
      hint: '',
    },
    {
      id: 'end_reconciliation',
      name: 'What Actually Happened',
      rarity: 'UNIQUE',
      minTurn: 35,
      requires: {
        flagsSet: ['knows:denda_existed', 'knows:gora_was_the_example'],
        minRelationship: [{ characterId: 'coach', dimension: 'trust', value: 50 }],
      },
      condition:
        'The player found out why the five left, from enough sides that it is no longer one person\'s ' +
        'version. Independent of the season result: this can land in a year that ends in March. The ' +
        'reason is the story\'s own and it is not flattering to anybody.',
      epilogue:
        'The official story stays the official story, because nobody has any reason to correct it. But ' +
        'the people who know now know, and one of the five stops answering their phone.',
      hint: 'Somebody resigned in the same month and nobody says his name.',
    },
    {
      id: 'end_quit',
      name: 'You Stop Going',
      rarity: 'UNCOMMON',
      minTurn: 20,
      requires: { flagsSet: ['left_the_map'], flagsUnset: ['scouts_watching'] },
      condition:
        'The player quit. Not a failure state and not a bad ending — write the specific relief and the ' +
        'specific loss of it, and let the people who wanted them there be hurt without making it a ' +
        'lesson.',
      epilogue:
        'Kosei plays out the season with six. Your name is on a roster in a folder nobody opens. Some ' +
        'afternoons in March you notice you are not anywhere in particular at half past three.',
      hint: '',
    },
  ],
  opening:
    'The gym smells like floor polish and the heating has not been on since March.\n\n' +
    'There are six people in it. A very tall boy is holding a ball as though somebody handed it to him by mistake. A first-year who cannot weigh fifty kilos is at the far basket, throwing perfect passes to nobody. A third-year in a Kosei reversible is jogging over to you already, hand out, saying your name like he has been practising it.\n\n' +
    'Coach Torakawa is standing at the edge of the court with her arms folded, not coming over.\n\n' +
    '"Right," she says, when the tall boy finally drops the ball. "Shirts and skins, three-on-three, and I would like to see the new one actually do something."\n\n' +
    'Nobody here knows what you can do. Including, if you are honest, you.',
  openingSuggestions: [
    'I take the ball and go straight at whoever is guarding me. No pass, no set-up — just at him, right now.',
    'I give it up early and go and stand somewhere useful, and find out which of these six can actually catch.',
    'I pick up the best player out there and get into him. “All practice. Every possession. Let us see it.”',
  ],
  publishedAt: '2026-09-09T18:00:00.000Z',
};

export const LAST_FIVE = StoryVersion.parse(raw);
