import { StoryVersion } from '@plotbreak/contracts';

/**
 * "Nine Weeks" — a romance world where the romance can genuinely fail.
 *
 * The failure mode this is built against is the dating sim: a cast who exist to
 * be chosen, whose feelings are a bar the player fills. Here every NPC has a
 * relationship with at least one other NPC that the player is not part of and
 * cannot delete. Teo is Juno's partner and Nadia's closest friend, so hurting
 * one of them costs the other. Cass and Nadia already ended badly once, and she
 * remembers it whether or not he does.
 *
 * The finale quest has a route for every person and one for nobody, and the
 * "nobody" route is not a failure state. Talk is a resource: what the player
 * does in front of other people is a mechanical cost, which is what stops
 * betrayal from being free.
 *
 * No combat. Parsed at import so a malformed world fails the build.
 */

const raw = {
  id: 'sv_nine_weeks_1',
  storyId: 'story_nine_weeks',
  version: 1,
  title: 'Nine Weeks',
  fantasyLabel: 'You came back. So did they.',
  hook: 'You came back to work the same summer season. So did the person who left without saying goodbye, and they did not come back alone.',
  premise:
    'The town on this lake exists for about ten weeks a year. The Longhouse, which is the hotel that keeps it going, hires around twenty people each summer to run the kitchen, the bar and the boats, and puts all of them in six cabins behind the car park.\n\n' +
    'You worked there last summer. So did Juno, and for most of it the two of you were the thing everyone in the cabins had an opinion about. In the last week Juno went home early without saying goodbye, and you have not spoken since.\n\n' +
    'You are both back. Juno got off the bus this afternoon with Teo, who is kind, funny, easy to like, and does not know that last summer happened at all.\n\n' +
    'The season is nine weeks. You share a kitchen, a bathroom and a shift rota with all of these people, and by the third week everybody knows everything about everybody.\n\n' +
    'So you have nine weeks to work out what you actually want, and whether you are willing to cost somebody else something to get it. Some of these people will still be in your life in October. Which ones is not decided.',
  creatorId: 'creator_official',
  creatorName: 'Plotbreak Studios',
  official: true,
  coverImage: 'nine-weeks/cover',
  keyArt: 'nine-weeks/key',
  tags: ['Romance', 'Slice of life', 'Summer', 'Drama', 'Coming of age'],
  mechanicsChips: ['Real rejection', 'People talk', 'Shift rota', 'Friendships that cost', 'Nine-week clock'],
  contentDescriptors: ['ROMANCE', 'SUGGESTIVE_THEMES', 'PSYCHOLOGICAL_THEMES', 'ALCOHOL_REFERENCES', 'LANGUAGE'],
  intensity: 'MODERATE',
  creatorNote:
    'Nobody here is waiting to be chosen. They have their own people, their own boundaries, and their own memory of how you behaved in week two. You can end this season with someone, with a friend you did not expect, or on your own — and the last one is not the bad ending.',
  rules: {
    defeatMode: 'FAIL_FORWARD',
    progressionMode: 'MILESTONE',
    revealExactDc: false,
    revealCheckMath: false,
    allowsCombat: false,
    allowsRomance: true,
    startingLocationId: 'staff_cabins',
    startWorldMinute: 16 * 60 + 20,
    startingItems: [
      { itemId: 'staff_lanyard', qty: 1 },
      { itemId: 'last_summers_photo', qty: 1 },
    ],
    hardCanon: [
      'The season ends in nine weeks and everybody goes home. Nobody here can change that.',
      'Juno and Teo are together, and Teo does not know about last summer.',
      'Teo and Nadia have been close friends for three summers. Hurting one of them is felt by the other.',
      'Cass and Nadia had something two summers ago that ended badly. She has not forgotten it and he thinks it was nothing.',
      'Anything done in the bar, the kitchen or the cabins is seen by somebody and repeated by somebody else.',
    ],
    toneGuide:
      'Warm, funny, and slightly sunburnt. Long shifts, cheap wine on the back steps, and everyone being twenty-one at each other. Feelings are enormous and nobody says them well. No villains, no melodrama; just people with incompatible wants in a very small place.',
    forkCostCredits: 120,
  },
  attributes: { might: 10, agility: 11, mind: 12, presence: 12, resolve: 11, arcana: 8 },
  skills: [
    { id: 'read_people', name: 'Reading People', attribute: 'mind', description: 'What they meant, as distinct from what they said.' },
    { id: 'warmth', name: 'Warmth', attribute: 'presence', description: 'Being the person a shift is better with.' },
    { id: 'candour', name: 'Candour', attribute: 'resolve', description: 'Saying the hard true thing without making it worse.' },
    { id: 'discretion', name: 'Discretion', attribute: 'mind', description: 'Knowing something and not spending it.' },
    { id: 'service', name: 'Service', attribute: 'agility', description: 'Being genuinely good at the job, which counts for more here than it should.' },
    { id: 'music', name: 'Music', attribute: 'presence', description: 'Three chords and the nerve to start.' },
    { id: 'cooking', name: 'Cooking', attribute: 'mind', description: 'Feeding twenty people something they will remember.' },
    { id: 'swimming', name: 'Swimming', attribute: 'might', description: 'The lake, at any hour, in any state.' },
    { id: 'composure', name: 'Composure', attribute: 'resolve', description: 'Finishing the shift with your face doing the right thing.' },
    { id: 'mischief', name: 'Mischief', attribute: 'agility', description: 'Why the night kept going.' },
  ],
  resources: [
    {
      id: 'energy',
      name: 'Energy',
      max: 20,
      start: 18,
      regenPerHour: 1,
      polarity: 'GOOD_HIGH',
      displayPriority: 1,
      visible: true,
      zeroStateConsequence: 'You are running on nothing. Everything you say comes out worse than you meant it.',
      color: '#5FD3A8',
    },
    {
      id: 'standing',
      name: 'Standing',
      max: 100,
      start: 45,
      regenPerHour: 0,
      polarity: 'GOOD_HIGH',
      displayPriority: 2,
      visible: true,
      zeroStateConsequence: 'The rota stops including you, which here means you are on the next bus.',
      color: '#7C6CFF',
    },
    {
      id: 'talk',
      name: 'Talk',
      max: 100,
      start: 20,
      regenPerHour: -1,
      polarity: 'GOOD_LOW',
      displayPriority: 3,
      visible: true,
      zeroStateConsequence: 'Nobody is discussing you this week. Enjoy it.',
      color: '#F6BE55',
    },
  ],
  items: [
    {
      id: 'staff_lanyard',
      name: 'Staff Lanyard',
      tags: ['quest'],
      questItem: true,
      droppable: false,
      description: 'Your name, your section, and a photograph taken on arrival day last year that they did not bother retaking.',
      loreText: 'The lamination has a crease across it from being in a back pocket for a whole season.',
      icon: 'lanyard',
    },
    {
      id: 'last_summers_photo',
      name: 'A Photo From Last Summer',
      tags: ['quest', 'keepsake'],
      questItem: true,
      droppable: false,
      description: 'Nine people on the dock at the end of a shift. You are on the left. Juno is laughing at something out of frame.',
      loreText: 'You know exactly who took it and exactly what happened four days later.',
      icon: 'photo',
    },
    {
      id: 'good_wine',
      name: 'The Decent Bottle',
      tags: ['consumable', 'social'],
      stackable: true,
      maxStack: 3,
      consumable: { resourceId: 'energy', amount: 4, consumesItem: true },
      description: 'Not the staff wine. Bought in town with your own money, which is the entire message.',
      loreText: 'Bringing one to the back steps means something. Bringing two means something else.',
      icon: 'bottle',
    },
    {
      id: 'shift_swap',
      name: 'Owed Shift',
      tags: ['social'],
      stackable: true,
      maxStack: 5,
      description: 'A shift somebody owes you. The only currency that reliably works in this building.',
      loreText: 'Nadia keeps the real ledger in her head and it is never wrong.',
      icon: 'rota',
    },
    {
      id: 'the_letter',
      name: 'The Letter That Never Arrived',
      tags: ['quest', 'document'],
      questItem: true,
      droppable: false,
      description: 'Four pages in Juno’s handwriting, written last September, addressed to you, and never posted.',
      loreText: 'The address is right. The stamp is on it. It has been in a bag for eleven months.',
      icon: 'letter',
    },
  ],
  abilities: [
    {
      id: 'hear_them_out',
      name: 'Hear Them Out',
      tags: ['social', 'utility'],
      description: 'Stop talking for long enough that the person in front of you gets to the real thing.',
      affordances: ['let them talk', 'hear them out', 'wait and listen', 'say nothing and wait'],
      costs: [{ resourceId: 'energy', amount: 2 }],
      cooldownMinutes: 0,
      targetRule: 'SINGLE',
      check: { attribute: 'mind', skillId: 'read_people', baseDc: 11 },
      unlockedByDefault: true,
    },
    {
      id: 'say_it_plainly',
      name: 'Say It Plainly',
      tags: ['social', 'risky'],
      description: 'Put the difficult true thing into words that do not make it worse than it is.',
      affordances: ['tell them the truth', 'say it plainly', 'be honest with them', 'just say it'],
      costs: [{ resourceId: 'energy', amount: 4 }],
      cooldownMinutes: 30,
      targetRule: 'SINGLE',
      check: { attribute: 'resolve', skillId: 'candour', baseDc: 13 },
      unlockedByDefault: true,
    },
    {
      id: 'make_it_easy',
      name: 'Make It Easy',
      tags: ['social', 'kind'],
      description: 'Give somebody a way out of the conversation with their dignity intact.',
      affordances: ['let them off', 'change the subject for them', 'make it easy', 'give them an out'],
      costs: [{ resourceId: 'energy', amount: 3 }],
      cooldownMinutes: 15,
      targetRule: 'SINGLE',
      check: { attribute: 'presence', skillId: 'warmth', baseDc: 12 },
      unlockedByDefault: true,
    },
    {
      id: 'read_the_table',
      name: 'Read the Table',
      tags: ['social', 'utility'],
      description: 'Work out what is actually going on between everyone at this table before you sit down at it.',
      affordances: ['read the room', 'see what is going on', 'work out the mood', 'read the table'],
      costs: [{ resourceId: 'energy', amount: 2 }],
      cooldownMinutes: 0,
      targetRule: 'NONE',
      check: { attribute: 'mind', skillId: 'read_people', baseDc: 12 },
      unlockedByDefault: true,
    },
    {
      id: 'cover_a_shift',
      name: 'Cover a Shift',
      tags: ['social', 'favour'],
      description: 'Take somebody’s hours. Costs you the evening and buys you something that lasts longer.',
      affordances: ['cover for them', 'take their shift', 'do it for them', 'swap shifts'],
      costs: [{ resourceId: 'energy', amount: 8 }],
      cooldownMinutes: 720,
      targetRule: 'SINGLE',
      check: null,
      unlockedByDefault: true,
    },
    {
      id: 'let_it_go',
      name: 'Let It Go',
      tags: ['social', 'discipline'],
      description: 'Decide, on purpose, not to say the thing you are completely entitled to say.',
      affordances: ['let it go', 'say nothing', 'drop it', 'leave it alone'],
      costs: [{ resourceId: 'energy', amount: 3 }],
      cooldownMinutes: 60,
      targetRule: 'SELF',
      check: { attribute: 'resolve', skillId: 'composure', baseDc: 12 },
      unlockedByDefault: true,
    },
  ],
  locations: [
    {
      id: 'staff_cabins',
      takeableItems: [
        { itemId: 'good_wine', qty: 1, ownerId: null, aka: ['wine', 'the bottle'] },
        // Four pages in Juno's handwriting, in Juno's bag, addressed to the
        // player. Taking it is how a run gets the worst version of the truth.
        {
          itemId: 'the_letter',
          qty: 1,
          ownerId: 'juno',
          aka: ['letter', 'the letter', 'their bag', 'juno’s bag', 'the envelope'],
        },
      ],
      name: 'The Staff Cabins',
      shortName: 'Cabins',
      description:
        'Six timber cabins behind the car park, four bunks each, a shared bathroom with one good shower. Everything anybody owns is in a bag under a bed and everybody knows whose bag is whose.',
      artDirection: 'Late afternoon sun, timber cabins under pines, bags on bunks, washing on a line between two trees.',
      stageImage: 'nine-weeks/stage_staff_cabins',
      discoveredByDefault: true,
      mapPosition: { x: 0.3, y: 0.8 },
      ambientSfx: ['cicadas', 'distant_music'],
      connections: [
        { to: 'back_steps', travelMinutes: 2, label: 'Round to the back steps' },
        { to: 'kitchen', travelMinutes: 4, label: 'In through the kitchen' },
        { to: 'the_dock', travelMinutes: 6, label: 'Down to the water' },
      ],
    },
    {
      id: 'kitchen',
      takeableItems: [
        { itemId: 'shift_swap', qty: 1, ownerId: null, aka: ['swap', 'the shift sheet', 'the rota'] },
      ],
      name: 'The Kitchen',
      shortName: 'Kitchen',
      description:
        'Hot, loud, and the actual centre of this building. Two hundred covers a night go through here and every private conversation on staff happens beside the pass at some point.',
      artDirection: 'Stainless steel kitchen mid-service, steam, tickets on a rail, warm overhead light, motion.',
      stageImage: 'nine-weeks/stage_kitchen',
      discoveredByDefault: true,
      mapPosition: { x: 0.5, y: 0.62 },
      ambientSfx: ['kitchen_service', 'ticket_printer'],
      connections: [
        { to: 'longhouse_bar', travelMinutes: 1, label: 'Out to the floor' },
        { to: 'staff_cabins', travelMinutes: 4, label: 'Out the back' },
        { to: 'back_steps', travelMinutes: 1, label: 'Out the side door' },
      ],
    },
    {
      id: 'longhouse_bar',
      name: 'The Longhouse Bar',
      shortName: 'Bar',
      description:
        'A long room with the lake down one whole side and a small stage at the end that gets used more nights than not. Staff drink here after eleven and are supposed to pretend they are not.',
      artDirection: 'Warm evening interior, long windows on dark water, small lit stage, bottles backlit, full room.',
      stageImage: 'nine-weeks/stage_longhouse_bar',
      discoveredByDefault: true,
      mapPosition: { x: 0.62, y: 0.45 },
      ambientSfx: ['bar_crowd', 'acoustic_guitar'],
      connections: [
        { to: 'kitchen', travelMinutes: 1, label: 'Behind the pass' },
        { to: 'the_dock', travelMinutes: 3, label: 'Out to the water' },
        { to: 'town_road', travelMinutes: 12, label: 'Up the road into town' },
      ],
    },
    {
      id: 'back_steps',
      name: 'The Back Steps',
      shortName: 'Steps',
      description:
        'Four concrete steps between the kitchen door and the bins, facing the pines. This is where everything actually gets said, usually after one in the morning and usually badly.',
      artDirection: 'Night, single bulb over a kitchen door, concrete steps, pine dark beyond, two mugs on the step.',
      stageImage: 'nine-weeks/stage_back_steps',
      discoveredByDefault: true,
      mapPosition: { x: 0.4, y: 0.7 },
      ambientSfx: ['cicadas', 'extractor_fan'],
      connections: [
        { to: 'kitchen', travelMinutes: 1, label: 'Back inside' },
        { to: 'staff_cabins', travelMinutes: 2, label: 'Over to the cabins' },
      ],
    },
    {
      id: 'the_dock',
      name: 'The Dock',
      shortName: 'Dock',
      description:
        'Boards out over the water, four boats tied up, and the only place on the property where you can be seen by everyone and overheard by nobody.',
      artDirection: 'Wooden dock at dusk, still lake, small boats, long orange light, hills on the far shore.',
      stageImage: 'nine-weeks/stage_the_dock',
      discoveredByDefault: true,
      mapPosition: { x: 0.72, y: 0.72 },
      ambientSfx: ['water_lap', 'rope_creak'],
      connections: [
        { to: 'longhouse_bar', travelMinutes: 3, label: 'Back up to the bar' },
        { to: 'staff_cabins', travelMinutes: 6, label: 'Up to the cabins' },
        { to: 'the_point', travelMinutes: 22, label: 'Take a boat across' },
      ],
    },
    {
      id: 'town_road',
      name: 'The Road Into Town',
      shortName: 'Road',
      description:
        'Twenty minutes of tarmac with no lights on it, walked at two in the morning by people who wanted twenty minutes of not being at work. Conversations that start on this road tend to finish.',
      artDirection: 'Unlit country road at night, headlights far off, moths, hedges, one distant streetlamp.',
      stageImage: 'nine-weeks/stage_town_road',
      discoveredByDefault: true,
      mapPosition: { x: 0.85, y: 0.28 },
      ambientSfx: ['crickets', 'footsteps_road'],
      connections: [{ to: 'longhouse_bar', travelMinutes: 12, label: 'Back down to the Longhouse' }],
    },
    {
      id: 'the_point',
      name: 'The Point',
      shortName: 'Point',
      description:
        'A shingle spit on the far shore with one dead tree on it, twenty minutes across the water and out of sight of the whole property. Everyone who works a season here ends up here once with somebody.',
      artDirection: 'Shingle spit across still water at night, one bare tree, the hotel lights small and far off.',
      stageImage: 'nine-weeks/stage_the_point',
      discoveredByDefault: false,
      mapPosition: { x: 0.5, y: 0.12 },
      ambientSfx: ['water_lap', 'wind_soft'],
      connections: [{ to: 'the_dock', travelMinutes: 22, label: 'Row back' }],
    },
  ],
  characters: [
    {
      id: 'juno',
      name: 'Juno Vale',
      role: 'Bar staff, second season',
      cardBlurb:
        'The person you were with last summer, who went home a week early without saying goodbye. They are back, and they are with Teo.',
      pronouns: 'they/them',
      publicTraits: ['Funny', 'Restless', 'Terrible at endings'],
      hiddenDrives: [
        'Their mother was ill last September, they left the same night, and they wrote four pages they never sent.',
        'They came back partly for the job and mostly to find out what happens.',
      ],
      values: ['Not lying to Teo', 'The people from last summer', 'Being somewhere they are not required'],
      fears: ['Being the person who does this to people', 'Having to choose in front of everybody'],
      socialStyle: 'Deflects with a joke, twice, and then answers properly if you are still there.',
      boundaries: ['Will not be someone’s secret', 'Will not humiliate Teo, whatever else happens'],
      goals: ['Get through the season without blowing up someone else’s summer', 'Say what happened last September'],
      secrets: [
        {
          id: 'juno_wrote_the_letter',
          fact: 'Juno wrote the player four pages last September, stamped it, and never sent it. It is in their bag.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Trust 45+, and somewhere private. Never in the bar.',
        },
        {
          id: 'juno_told_cass',
          fact: 'Juno asked Cass to explain to the player why they had gone. Cass never did.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Comes out whenever the letter does, or if the player confronts Cass first.',
        },
      ],
      speechStyle:
        'Quick, warm, deflecting. Says your name at the start of a sentence when they are about to be serious, which is the tell.',
      topics: ['last September', 'Teo', 'why they came back', 'the letter'],
      voiceSamples: [
        'Hey. You look well. That is a genuinely annoying thing to have to say first.',
        'I am not going to do this in the bar. Ask me again on the steps.',
        'I did not just go. I know it looked like I just went.',
      ],
      appearance: 'Twenty-two, sun-bleached hair growing out of a bad cut, the same denim jacket as last year.',
      visualHook:
        'A sun-faded denim jacket with one cuff frayed through, and hair grown out of a self-cut bleach job into two clear tones.',
      silhouette:
        'Loose and always half-turned toward the exit, hands in jacket pockets, weight on the back foot.',
      artSeed: 'juno-vale-v1',
      portrait: 'nine-weeks/juno',
      expressions: ['neutral', 'joking', 'guarded', 'stricken', 'soft', 'resigned'],
      voiceId: 'voice_juno',
      homeLocationId: 'longhouse_bar',
      knowledgeScope: ['faction_bar'],
      schedule: [
        { startMinute: 600, endMinute: 900, locationId: 'the_dock', activity: 'Boats and swimming' },
        { startMinute: 900, endMinute: 1020, locationId: 'staff_cabins', activity: 'Sleeping before service' },
        { startMinute: 1020, endMinute: 1380, locationId: 'longhouse_bar', activity: 'Bar service' },
        { startMinute: 1380, endMinute: 1440, locationId: 'back_steps', activity: 'After service' },
        { startMinute: 0, endMinute: 120, locationId: 'back_steps', activity: 'Still on the steps' },
      ],
      startingRelationship: { trust: 25, affection: 45, respect: 20, fear: 0, rivalry: 0 },
      attributes: { might: 10, agility: 13, mind: 12, presence: 15, resolve: 9, arcana: 8 },
      gates: [
        {
          id: 'juno_tells_you',
          kind: 'TRUST',
          label: 'Juno will tell you what happened in September',
          requires: { trust: 45, flagsSet: ['juno_steps_conversation'], flagsUnset: ['juno_cornered_publicly'] },
        },
        {
          id: 'juno_chooses',
          kind: 'ROMANCE',
          label: 'Juno is willing to end things with Teo',
          requires: {
            trust: 65,
            affection: 70,
            flagsSet: ['juno_told_teo_herself'],
            flagsUnset: ['player_told_teo', 'juno_cornered_publicly'],
          },
        },
      ],
      combatant: null,
    },
    {
      id: 'teo',
      name: 'Teo Sandoval',
      role: 'Kitchen, first season',
      cardBlurb:
        'Juno’s partner. New here, funny, works harder than anyone, and has no idea that you and Juno happened. Impossible to dislike, which is your problem.',
      pronouns: 'he/him',
      publicTraits: ['Kind', 'Direct', 'Cheerfully bad at pretending'],
      hiddenDrives: [
        'He can tell something is wrong between Juno and this place and has decided to wait it out.',
        'He has never been the person someone left somebody for, and he has thought about that a lot.',
      ],
      values: ['Being told things', 'Pulling his weight', 'His friends over his pride'],
      fears: ['Being the last to know', 'Being kept for convenience'],
      socialStyle: 'Says the obvious thing warmly and immediately. Asks direct questions and waits for the answer.',
      boundaries: ['Will not be lied to twice', 'Will not compete for someone'],
      goals: ['Get through his first season without being a liability', 'Find out what is going on, from Juno'],
      secrets: [
        {
          id: 'teo_already_suspects',
          fact: 'Teo worked out in week one that Juno and the player have history. He has not raised it.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Trust 40+, usually on a shift, and he will be very calm about it.',
        },
        {
          id: 'teo_and_nadia',
          fact: 'Nadia is the only person Teo has told, and she has been carrying it for him.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'From Nadia at trust 50+, or from Teo once he knows the player knows.',
        },
      ],
      speechStyle:
        'Plain, friendly, and unguarded. Uses your name a lot. When he is hurt he gets more polite, not less.',
      topics: ['Juno', 'the kitchen', 'what I am missing', 'Nadia'],
      voiceSamples: [
        'You are the one from the photo on Juno’s phone. I have been trying to work out how to say that all day.',
        'I would rather you told me something awkward than nothing at all. That is not a trap, it is just true.',
        'Okay. Thank you for saying it. I am going to go and be somewhere else for a bit.',
      ],
      appearance: 'Twenty-three, forearms already burned from the pass, an apron he ties wrong every single time.',
      visualHook:
        'An apron tied in a wrong, elaborate knot he clearly invented himself, and both forearms burned pink from the pass.',
      silhouette:
        'Broad and square-on, facing whoever he is talking to directly, a towel permanently over one shoulder.',
      artSeed: 'teo-sandoval-v1',
      portrait: 'nine-weeks/teo',
      expressions: ['neutral', 'warm', 'thinking', 'hurt', 'polite', 'delighted'],
      voiceId: 'voice_teo',
      homeLocationId: 'kitchen',
      knowledgeScope: ['faction_kitchen'],
      schedule: [
        { startMinute: 540, endMinute: 660, locationId: 'the_dock', activity: 'Swimming before prep' },
        { startMinute: 660, endMinute: 960, locationId: 'kitchen', activity: 'Prep' },
        { startMinute: 960, endMinute: 1020, locationId: 'staff_cabins', activity: 'Getting the bags in' },
        { startMinute: 1020, endMinute: 1380, locationId: 'kitchen', activity: 'Service' },
        { startMinute: 1380, endMinute: 1440, locationId: 'back_steps', activity: 'Sitting down for the first time' },
        { startMinute: 0, endMinute: 90, locationId: 'staff_cabins', activity: 'Asleep before anyone else' },
      ],
      startingRelationship: { trust: 15, affection: 10, respect: 10, fear: 0, rivalry: 15 },
      attributes: { might: 13, agility: 12, mind: 12, presence: 13, resolve: 14, arcana: 8 },
      gates: [
        {
          id: 'teo_trusts_you',
          kind: 'TRUST',
          label: 'Teo will talk to you about Juno',
          requires: { trust: 40, flagsUnset: ['teo_found_out_from_someone_else'] },
        },
        {
          id: 'teo_open',
          kind: 'ROMANCE',
          label: 'Teo is somewhere he could feel something for you',
          requires: {
            trust: 60,
            affection: 55,
            flagsSet: ['juno_and_teo_ended'],
            flagsUnset: ['player_told_teo', 'teo_found_out_from_someone_else'],
          },
        },
      ],
      combatant: null,
    },
    {
      id: 'nadia',
      name: 'Nadia Okonkwo',
      role: 'Head of house, fourth season',
      cardBlurb:
        'She writes the rota and keeps the ledger of who owes whom. Teo’s closest friend here, and not remotely interested in your drama.',
      pronouns: 'she/her',
      publicTraits: ['Dry', 'Unbribable', 'Runs the whole building without appearing to'],
      hiddenDrives: [
        'She is carrying what Teo told her and hates being the only one holding it.',
        'She has decided not to want anything from a season again, and it is not going well.',
      ],
      values: ['People being treated well on her rota', 'Her word', 'Teo'],
      fears: ['Being made complicit', 'Doing the Cass thing again and being the one who is hurt by it'],
      socialStyle: 'Deadpan, generous, and immovable. Will tell you exactly what she thinks of what you did.',
      boundaries: ['Will not keep a secret from Teo that damages him', 'Will not be anyone’s second choice again'],
      goals: ['Get the season through without losing anyone', 'Stop being everybody’s confessional'],
      secrets: [
        {
          id: 'nadia_holds_teos_secret',
          fact: 'Teo told Nadia in week one that he knows there is history, and asked her to say nothing.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Trust 50+, and only if the player has been straight with her first.',
        },
        {
          id: 'nadia_and_cass',
          fact: 'Nadia and Cass had a season together two years ago. He ended it by simply stopping.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Trust 40+, or the player sees how she is with him on a bad night.',
        },
      ],
      speechStyle:
        'Short, dry, and exact. Delivers the kindest thing anybody says to you like it is a rota change.',
      topics: ['the rota', 'Teo', 'Cass', 'what I have seen people do here'],
      voiceSamples: [
        'You are on the dock at six. I gave you the good shift because I like you. Do not make that a mistake.',
        'I have watched four seasons of this. It ends the same way about eighty per cent of the time.',
        'I am not going to lie to him for you. I will not tell him for you either. Those are both real answers.',
      ],
      appearance: 'Twenty-five, braids up, clipboard she does not need, cardigan over the uniform in all weathers.',
      visualHook:
        'A soft oversized cardigan worn over the uniform in every weather, and a clipboard she never actually writes on.',
      silhouette:
        'Upright and unhurried with the clipboard held against her chest like a shield she has forgotten she is holding.',
      artSeed: 'nadia-okonkwo-v1',
      portrait: 'nine-weeks/nadia',
      expressions: ['neutral', 'dry', 'unimpressed', 'kind', 'tired', 'caught out'],
      voiceId: 'voice_nadia',
      homeLocationId: 'longhouse_bar',
      knowledgeScope: ['faction_kitchen', 'faction_bar', 'faction_house'],
      schedule: [
        { startMinute: 480, endMinute: 660, locationId: 'longhouse_bar', activity: 'Rota and deliveries' },
        { startMinute: 660, endMinute: 960, locationId: 'kitchen', activity: 'Everywhere at once' },
        { startMinute: 960, endMinute: 1020, locationId: 'staff_cabins', activity: 'Meeting the arrivals with the rota' },
        { startMinute: 1020, endMinute: 1320, locationId: 'longhouse_bar', activity: 'Floor' },
        { startMinute: 1320, endMinute: 1440, locationId: 'back_steps', activity: 'Ten minutes to herself' },
        { startMinute: 0, endMinute: 60, locationId: 'staff_cabins', activity: 'Last one to bed' },
      ],
      startingRelationship: { trust: 20, affection: 10, respect: 20, fear: 0, rivalry: 0 },
      attributes: { might: 11, agility: 12, mind: 15, presence: 14, resolve: 15, arcana: 8 },
      gates: [
        {
          id: 'nadia_confides',
          kind: 'TRUST',
          label: 'Nadia will stop managing you and talk to you',
          requires: { trust: 50, flagsUnset: ['nadia_saw_you_lie'] },
        },
        {
          id: 'nadia_open',
          kind: 'ROMANCE',
          label: 'Nadia would consider it, which she is furious about',
          requires: {
            trust: 70,
            affection: 60,
            respect: 55,
            flagsSet: ['spoke:nadia', 'visited:the_point'],
            flagsUnset: ['nadia_saw_you_lie', 'player_chased_juno_openly'],
          },
        },
      ],
      combatant: null,
    },
    {
      id: 'cass',
      name: 'Cass Reyner',
      role: 'Bar staff, third season',
      cardBlurb:
        'Interested in you from the first evening, which is easy and therefore worth thinking about. Nadia will not be in a room alone with him.',
      pronouns: 'he/him',
      publicTraits: ['Charming', 'Generous', 'Genuinely does not notice damage'],
      hiddenDrives: [
        'Juno asked him to explain to the player last September and he decided it was not his business.',
        'He wants to be the person everyone is glad arrived, and he does not examine the cost of that.',
      ],
      values: ['A good night', 'Being wanted', 'Not making things heavy'],
      fears: ['Being told plainly what he did', 'Being alone at the end of a season'],
      socialStyle: 'Immediate, flattering, easy. Will change the subject away from anything with weight in it.',
      boundaries: ['Will not be lectured', 'Will not admit fault in front of other people'],
      goals: ['Have the best summer here', 'Not think about two years ago'],
      secrets: [
        {
          id: 'cass_never_passed_it_on',
          fact: 'Cass was asked by Juno to tell the player why they had left, and never did.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'He will admit it if asked directly and privately, and be surprised it mattered.',
        },
        {
          id: 'cass_and_nadia_version',
          fact: 'Cass genuinely believes what happened with Nadia was mutual and unremarkable.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Comes out on its own if the player mentions Nadia to him at all.',
        },
      ],
      speechStyle:
        'Warm, fast, full of easy compliments. Gets vaguer the closer a question gets to something he did.',
      topics: ['last summer', 'Nadia', 'what happened in September', 'the point'],
      voiceSamples: [
        'You are back. Good. This place was extremely boring without something to look at.',
        'I did not think it was mine to pass on. It was between you two, honestly.',
        'Nadia and I are fine. Ask her. Actually, do not ask her.',
      ],
      appearance: 'Twenty-four, permanently half-sunburnt, shirt open one button past where it needs to be.',
      visualHook:
        'A permanent uneven sunburn across the nose and one shoulder, and a bar shirt worn one button further open than anyone else’s.',
      silhouette:
        'Leaning — on a bar, a doorframe, a boat — always at an angle, never quite standing on his own two feet.',
      artSeed: 'cass-reyner-v1',
      portrait: 'nine-weeks/cass',
      expressions: ['neutral', 'flirting', 'amused', 'evasive', 'stung', 'sincere'],
      voiceId: 'voice_cass',
      homeLocationId: 'longhouse_bar',
      knowledgeScope: ['faction_bar'],
      schedule: [
        { startMinute: 660, endMinute: 900, locationId: 'the_dock', activity: 'Not working' },
        { startMinute: 900, endMinute: 1020, locationId: 'longhouse_bar', activity: 'Setting up slowly' },
        { startMinute: 1020, endMinute: 1380, locationId: 'longhouse_bar', activity: 'Bar service' },
        { startMinute: 1380, endMinute: 1440, locationId: 'longhouse_bar', activity: 'Staff drinks' },
        { startMinute: 0, endMinute: 180, locationId: 'town_road', activity: 'Walking somebody home' },
      ],
      startingRelationship: { trust: 10, affection: 25, respect: 5, fear: 0, rivalry: 5 },
      attributes: { might: 12, agility: 13, mind: 11, presence: 16, resolve: 9, arcana: 8 },
      gates: [
        {
          id: 'cass_admits_it',
          kind: 'TRUST',
          label: 'Cass will admit he never passed the message on',
          requires: { trust: 25, flagsUnset: ['cass_confronted_publicly'] },
        },
        {
          id: 'cass_open',
          kind: 'ROMANCE',
          label: 'Cass is serious about it, for once',
          requires: {
            trust: 55,
            affection: 65,
            flagsSet: ['cass_told_the_truth'],
            flagsUnset: ['cass_confronted_publicly'],
          },
        },
      ],
      combatant: null,
    },
  ],
  factions: [
    {
      id: 'faction_kitchen',
      name: 'The Kitchen',
      description: 'The people who do the hard part. Loyal to each other and openly contemptuous of the floor.',
      startingReputation: 0,
      ranks: [
        { atReputation: -40, label: 'Dead weight' },
        { atReputation: 0, label: 'New' },
        { atReputation: 30, label: 'Sound' },
        { atReputation: 60, label: 'One of ours' },
      ],
      enemies: [],
      allies: ['faction_house'],
    },
    {
      id: 'faction_bar',
      name: 'The Bar',
      description: 'Later nights, better tips, and the social centre of the whole season.',
      startingReputation: 10,
      ranks: [
        { atReputation: -40, label: 'Not invited' },
        { atReputation: 0, label: 'Around' },
        { atReputation: 30, label: 'In it' },
        { atReputation: 60, label: 'Why the night happened' },
      ],
      enemies: [],
      allies: [],
    },
    {
      id: 'faction_house',
      name: 'The House',
      description: 'Nadia, the rota, and the management who will not learn anyone’s name until August.',
      startingReputation: 5,
      ranks: [
        { atReputation: -40, label: 'On the next bus' },
        { atReputation: 0, label: 'On the rota' },
        { atReputation: 30, label: 'Given the good shifts' },
        { atReputation: 60, label: 'Asked back next year' },
      ],
      enemies: [],
      allies: ['faction_kitchen'],
    },
  ],
  quests: [
    {
      id: 'q_the_season',
      title: 'Nine Weeks',
      summary: 'Work the season. Do not get sent home.',
      kind: 'MAIN',
      startsActive: true,
      involvedCharacterIds: ['nadia', 'teo'],
      involvedLocationIds: ['kitchen', 'longhouse_bar', 'the_dock'],
      knownRewardCopy: 'A season you are still welcome at in week nine.',
      steps: [
        {
          id: 'step_first_shift',
          playerCopy: 'Get through the first service.',
          directorNotes:
            'Nadia is deciding what kind of summer you are going to be. Being good at the job is the cheapest ' +
            'currency in the building and the player should be allowed to notice that.',
          // Service starts at five. Being in the kitchen at half past four is
          // arriving, not getting through a service.
          succeedWhen: {
            flagsSet: ['spoke:nadia', 'visited:kitchen'],
            afterWorldMinute: 17 * 60,
          },
          rewards: {
            // Being good on the floor is how this place decides what it
            // thinks of you, and it is the only currency here that is not
            // somebody's feelings.
            reputation: [{ factionId: 'faction_house', amount: 12 }],
            xp: 30,
            items: [{ itemId: 'shift_swap', qty: 1 }],
            flags: ['first_service_done', 'on_the_rota'],
          },
        },
        {
          id: 'step_keep_the_job',
          playerCopy: 'Still be on the rota in week five.',
          directorNotes:
            'Talk is the real threat, not competence. A player who causes a scene in the bar can be excellent at the ' +
            'job and still lose their place.',
          enterWhen: { flagsSet: ['on_the_rota'] },
          succeedWhen: {
            flagsUnset: ['sent_home'],
            afterWorldMinute: 28 * 24 * 60,
            minFactionReputation: [{ factionId: 'faction_house', value: 15 }],
          },
          rewards: {
            xp: 60,
            items: [],
            flags: ['week_five_reached'],
            reputation: [{ factionId: 'faction_house', amount: 15 }],
          },
        },
      ],
    },
    {
      id: 'q_last_september',
      title: 'Last September',
      summary: 'Find out why Juno left without saying anything.',
      kind: 'MAIN',
      startsActive: true,
      involvedCharacterIds: ['juno', 'cass'],
      involvedLocationIds: ['back_steps', 'the_dock', 'town_road'],
      knownRewardCopy: 'The actual answer, which is not the one you have been carrying.',
      steps: [
        {
          id: 'step_get_juno_alone',
          playerCopy: 'Get five minutes with Juno where nobody can hear.',
          directorNotes:
            'Juno will not do this in the bar and will say so. The steps after service, the dock, or the road into ' +
            'town all work. Cornering them in public sets a flag that closes the best ending.',
          succeedWhenAny: [
            {
              routeId: 'on_the_steps',
              label: 'The back steps after service',
              predicate: {
                flagsSet: ['spoke:juno'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'back_steps',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['juno_steps_conversation'],
              closesFlags: [],
            },
            {
              routeId: 'on_the_dock',
              label: 'The dock, in daylight, where everyone can see and nobody can hear',
              predicate: {
                flagsSet: ['spoke:juno'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'the_dock',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['juno_steps_conversation'],
              closesFlags: [],
            },
            {
              routeId: 'on_the_road',
              label: 'Twenty minutes of unlit road',
              predicate: {
                flagsSet: ['spoke:juno'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'town_road',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['juno_steps_conversation'],
              closesFlags: [],
            },
          ],
          rewards: { xp: 40, items: [], flags: [] },
        },
        {
          id: 'step_find_out_why',
          playerCopy: 'Find out what actually happened.',
          directorNotes:
            'Three ways to the same fact, and they cost different things. Juno telling you is the warmest. Cass ' +
            'admitting it is the fastest and makes him a problem later. Reading the letter without being given it ' +
            'is a real violation and Juno will treat it as one.',
          enterWhen: { flagsSet: ['juno_steps_conversation'] },
          succeedWhenAny: [
            {
              routeId: 'why_from_juno',
              label: 'Juno told you themselves',
              predicate: {
                flagsSet: ['juno_steps_conversation'],
                flagsUnset: ['juno_cornered_publicly'],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'juno', dimension: 'trust', value: 45 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['knows_about_september', 'juno_chose_to_tell_you', 'juno_told_you_why'],
              closesFlags: [],
            },
            {
              routeId: 'why_from_being_given_it',
              label: 'Juno gave you the letter',
              predicate: {
                flagsSet: ['spoke:juno'],
                flagsUnset: ['juno_cornered_publicly'],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'juno', dimension: 'trust', value: 45 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['knows_about_september', 'juno_chose_to_tell_you', 'was_given_the_letter'],
              closesFlags: ['juno_knows_you_read_it'],
            },
            {
              routeId: 'why_from_cass',
              label: 'Cass admitted he never passed it on',
              predicate: {
                flagsSet: [],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'cass', dimension: 'trust', value: 25 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['knows_about_september', 'cass_told_the_truth', 'cass_owes_you'],
              closesFlags: ['juno_chose_to_tell_you'],
            },
            {
              routeId: 'why_from_the_letter',
              label: 'You read the letter without being given it',
              predicate: {
                flagsSet: [],
                flagsUnset: ['juno_chose_to_tell_you'],
                hasItems: ['the_letter'],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['knows_about_september', 'juno_knows_you_read_it'],
              closesFlags: ['juno_chose_to_tell_you'],
            },
          ],
          rewards: { xp: 80, items: [], flags: [] },
        },
        {
          id: 'step_what_juno_does',
          playerCopy: 'Find out what Juno is going to do about it.',
          directorNotes:
            'This is not the player\u2019s decision to make and the beat should never let them make it. Juno either ' +
            'tells Teo themselves, or does not. Telling Teo on their behalf is a third thing and it costs both of them.',
          enterWhen: { flagsSet: ['knows_about_september'] },
          succeedWhenAny: [
            {
              routeId: 'juno_told_him',
              label: 'Juno told Teo themselves',
              predicate: {
                flagsSet: ['spoke:juno'],
                flagsUnset: ['player_told_teo', 'juno_cornered_publicly'],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [
                  { characterId: 'juno', dimension: 'trust', value: 55 },
                  { characterId: 'juno', dimension: 'affection', value: 55 },
                ],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['juno_and_teo_ended', 'juno_told_teo_herself'],
              closesFlags: ['juno_and_teo_together'],
            },
            {
              routeId: 'player_told_him',
              label: 'You told Teo',
              predicate: {
                flagsSet: ['spoke:teo', 'knows_about_september'],
                flagsUnset: ['juno_told_teo_herself'],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              // He finds out, and he finds out from the wrong person.
              setsFlags: ['juno_and_teo_ended', 'player_told_teo', 'teo_found_out_from_someone_else'],
              closesFlags: ['juno_told_teo_herself'],
            },
            {
              routeId: 'nothing_changes',
              label: 'They stayed together',
              predicate: {
                flagsSet: ['spoke:juno', 'spoke:teo'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: 42 * 24 * 60,
              },
              // Not a failure. It is the most likely thing that happens.
              setsFlags: ['juno_and_teo_together'],
              closesFlags: ['juno_and_teo_ended'],
            },
          ],
          rewards: { xp: 60, items: [], flags: [] },
        },
      ],
    },
    {
      id: 'q_week_nine',
      title: 'Week Nine',
      summary: 'The season ends on a Sunday. Work out what you are taking home from it.',
      kind: 'MAIN',
      startsActive: false,
      discoverWhen: { flagsSet: ['week_five_reached'] },
      involvedCharacterIds: ['juno', 'teo', 'nadia', 'cass'],
      involvedLocationIds: ['the_point', 'back_steps', 'the_dock'],
      knownRewardCopy: 'Whatever you actually did with nine weeks.',
      steps: [
        {
          id: 'step_the_last_week',
          playerCopy: 'Decide what you want, and find out whether it is available.',
          directorNotes:
            'Five endings and none of them is the intended one. Nobody is owed to the player: every romance route ' +
            'requires the other person to have arrived there on their own, and the alone route is written as a good ' +
            'outcome, not a consolation. If the player has hurt people, the endings that remain should reflect that.',
          enterWhen: { flagsSet: ['week_five_reached'] },
          succeedWhenAny: [
            {
              routeId: 'end_juno',
              label: 'Juno, properly this time',
              predicate: {
                flagsSet: ['knows_about_september', 'juno_and_teo_ended'],
                flagsUnset: ['player_told_teo', 'juno_cornered_publicly'],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [
                  { characterId: 'juno', dimension: 'trust', value: 65 },
                  { characterId: 'juno', dimension: 'affection', value: 70 },
                ],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['ending_juno'],
              closesFlags: ['ending_teo', 'ending_nadia', 'ending_cass', 'ending_alone'],
            },
            {
              routeId: 'end_teo',
              label: 'Teo, which nobody saw coming including you',
              predicate: {
                flagsSet: ['juno_and_teo_ended'],
                flagsUnset: ['player_told_teo', 'teo_found_out_from_someone_else'],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [
                  { characterId: 'teo', dimension: 'trust', value: 60 },
                  { characterId: 'teo', dimension: 'affection', value: 55 },
                ],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['ending_teo'],
              closesFlags: ['ending_juno', 'ending_nadia', 'ending_cass', 'ending_alone'],
            },
            {
              routeId: 'end_nadia',
              label: 'Nadia, who is annoyed about it',
              predicate: {
                flagsSet: [],
                flagsUnset: ['nadia_saw_you_lie', 'player_chased_juno_openly'],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [
                  { characterId: 'nadia', dimension: 'trust', value: 70 },
                  { characterId: 'nadia', dimension: 'affection', value: 60 },
                  { characterId: 'nadia', dimension: 'respect', value: 55 },
                ],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['ending_nadia'],
              closesFlags: ['ending_juno', 'ending_teo', 'ending_cass', 'ending_alone'],
            },
            {
              routeId: 'end_cass',
              label: 'Cass, with your eyes open',
              predicate: {
                flagsSet: [],
                flagsUnset: ['cass_confronted_publicly'],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [
                  { characterId: 'cass', dimension: 'trust', value: 55 },
                  { characterId: 'cass', dimension: 'affection', value: 65 },
                ],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['ending_cass'],
              closesFlags: ['ending_juno', 'ending_teo', 'ending_nadia', 'ending_alone'],
            },
            {
              routeId: 'end_alone',
              label: 'Nobody, and you are all right',
              predicate: {
                flagsSet: ['knows_about_september'],
                flagsUnset: ['sent_home'],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [{ factionId: 'faction_house', value: 30 }],
                beforeWorldMinute: null,
              },
              // Not a consolation prize: this one requires you to have done the
              // job well and found out the truth, and it closes nothing you
              // would have wanted more.
              setsFlags: ['ending_alone'],
              closesFlags: [],
            },
          ],
          rewards: { xp: 150, items: [], flags: [] },
        },
      ],
    },
  ],
  promises: [
    {
      id: 'promise_september',
      kind: 'MYSTERY',
      label: 'Why Juno went home a week early without saying anything',
      seedHint: 'They will not talk about it in the bar and say so out loud.',
      payoffHint: 'Their mother was ill, they wrote four pages, and they asked Cass to tell you.',
      weight: 1,
    },
    {
      id: 'promise_teo',
      kind: 'RELATIONSHIP',
      label: 'Teo, who is not in your way on purpose',
      seedHint: 'He recognises you from a photo on Juno’s phone and says so on the first evening.',
      payoffHint: 'He worked it out in week one and has been waiting to be told.',
      weight: 0.9,
    },
    {
      id: 'promise_nadia',
      kind: 'RELATIONSHIP',
      label: 'Nadia, who has decided not to want anything this season',
      seedHint: 'She gives you the good shift and tells you not to make that a mistake.',
      payoffHint: 'She is holding Teo’s secret alone, and the only way in is being straight with her first.',
      weight: 0.85,
    },
    {
      id: 'promise_cass',
      kind: 'RIVAL',
      label: 'Cass, who is easy and is why last summer ended the way it did',
      seedHint: 'He is interested in you before he has asked you anything about yourself.',
      payoffHint: 'He was asked to pass a message on and decided it was not his business.',
      weight: 0.8,
    },
    {
      id: 'promise_the_end',
      kind: 'FINALE',
      label: 'The last Sunday, when everyone gets on a different bus',
      seedHint: 'Nine weeks, said out loud on the first afternoon like it is a long time.',
      payoffHint: 'Some of these people are in your life in October. You find out which.',
      weight: 1,
    },
  ],
  archetypes: [
    {
      id: 'arch_open',
      name: 'Direct',
      role: 'Says it out loud',
      summary:
        'You tell people what you feel, early and without a plan. It lands or it does not, and either way the situation moves.',
      playstyle: ['Honest', 'Moves things fast', 'Costly when it misses'],
      blurb: 'You have never successfully sat on a feeling. It goes well about half the time.',
      attributeBonus: { resolve: 2, presence: 1 },
      skillProficiencies: { candour: 3, warmth: 2, composure: 1 },
      startingItems: [{ itemId: 'good_wine', qty: 1 }],
      startingAbilities: [],
    },
    {
      id: 'arch_careful',
      name: 'Observant',
      role: 'Reads people',
      summary:
        'You work out what is going on between other people before anybody tells you. Sharpest read in the building, and the slowest to actually do anything about it.',
      playstyle: ['Reads people', 'Discreet', 'Slow to commit'],
      blurb: 'You will know what is going on in this building before anyone tells you anything.',
      attributeBonus: { mind: 3 },
      skillProficiencies: { read_people: 3, discretion: 2, composure: 1 },
      startingItems: [],
      startingAbilities: [],
    },
    {
      id: 'arch_warm',
      name: 'Warm',
      role: 'People confide in you',
      summary:
        'You are who everybody ends up talking to on the back steps. You hear everything first, and you carry a lot that is not yours.',
      playstyle: ['Trusted', 'Hears everything', 'Pulled every direction'],
      blurb: 'You are the one everybody ends up talking to on the back steps. It is a lot of other people’s weight.',
      attributeBonus: { presence: 2, mind: 1 },
      skillProficiencies: { warmth: 3, read_people: 2, discretion: 1 },
      startingItems: [{ itemId: 'good_wine', qty: 1 }],
      startingAbilities: [],
    },
    {
      id: 'arch_fun',
      name: 'The Instigator',
      role: 'Starts things',
      summary:
        'You are why the night kept going. You make things happen that would not have happened, and you are the easiest person here to get in trouble.',
      playstyle: ['Makes things happen', 'Quick and physical', 'Gets caught'],
      blurb: 'Boats at 2am, the good playlist, everybody in the lake. Also very easy to get sent home.',
      attributeBonus: { agility: 2, presence: 1 },
      skillProficiencies: { mischief: 3, music: 2, swimming: 1 },
      startingItems: [{ itemId: 'good_wine', qty: 2 }],
      startingAbilities: [],
    },
    {
      id: 'arch_worker',
      name: 'The Grafter',
      role: 'Works instead of talking',
      summary:
        'Work is easier than this. You are the best on the floor, which at this lake buys you more real standing than charm does.',
      playstyle: ['Competent', 'Well respected', 'Avoids hard talks'],
      blurb: 'Work is easier than this. Being the best on the floor turns out to be worth more here than charm.',
      attributeBonus: { agility: 2, resolve: 1 },
      skillProficiencies: { service: 3, cooking: 2, composure: 1 },
      startingItems: [{ itemId: 'shift_swap', qty: 2 }],
      startingAbilities: [],
    },
  ],
  setupFields: [
    { id: 'displayName', label: 'What is on your lanyard?', kind: 'TEXT', required: true, maxLength: 40, placeholder: 'e.g. Robin Ayoade' },
    { id: 'pronouns', label: 'Pronouns', kind: 'TEXT', required: false, maxLength: 24, placeholder: 'e.g. she/her' },
    {
      id: 'archetype',
      label: 'What are you like with people?',
      helpText:
        'There is no combat in this story, so this is your whole toolkit: it decides which social approaches come easily to you — saying it out loud, reading the room, being the person people confide in, starting things, or working instead of talking. Everyone at the lake reacts to it. Fixed for this run.',
      kind: 'ARCHETYPE',
      required: false,
    },
    {
      id: 'worldKnowsAboutYou',
      label: 'What do people here remember about you?',
      kind: 'TEXT',
      required: false,
      maxLength: 300,
      placeholder: 'e.g. I sang once in week six last year and nobody has let it go since.',
    },
    {
      id: 'lastSummer',
      label: 'How did last summer end, from where you were standing?',
      kind: 'TEXT',
      advanced: true,
      maxLength: 300,
      placeholder: 'e.g. We had four days left and then their bunk was empty and nobody would look at me.',
    },
    {
      id: 'appearance',
      label: 'What do people notice first?',
      kind: 'TEXT',
      advanced: true,
      maxLength: 200,
      placeholder: 'e.g. Same boots as last year, and I have gone and cut all my hair off.',
    },
  ],
  opening:
    'The bus drops you at the top of the road at twenty past four, and you carry your bag down past the car park like you did last year.\n\n' +
    'Nadia is on the cabin steps with the rota, and she looks up and says your name in a way that means she already knew you were coming and has already thought about it.\n\n' +
    'Behind her, two people are getting bags out of the boot of a car. One of them is Juno. The other one is laughing at something Juno said, with his hand flat on the small of their back.\n\n' +
    'Juno looks up and sees you. Neither of you does anything for about two seconds.\n\n' +
    '"Right," Nadia says, without looking up. "Cabin four. You are on at six."',
  openingSuggestions: [
    'I take my bag to cabin four and say nothing to anyone, not yet.',
    'I walk over to whoever is standing with Juno and put my hand out first. “I do not think we have met. I am new.”',
    'I sit down near Nadia like it is nothing. “How long have you all been here? I am trying to work out how far behind I am.”',
  ],
  publishedAt: '2026-09-09T09:00:00.000Z',
};

export const NINE_WEEKS = StoryVersion.parse(raw);
