import { StoryVersion } from '@plotbreak/contracts';

/**
 * "The Ninth Archive" — the first official launch world.
 *
 * Built to the §43.1 quality bar: one-sentence premise, a first decision inside
 * one turn, four recurring NPCs with independent motives, one core progression
 * fantasy (forbidden knowledge), one strong deterministic system (the Wards,
 * expressed as a Suspicion resource that gates and escalates), and five seeded
 * promises.
 *
 * Parsed at import so a malformed world fails the build, not a player's session.
 */

const raw = {
  id: 'sv_ninth_archive_1',
  storyId: 'story_ninth_archive',
  version: 1,
  title: 'The Ninth Archive',
  fantasyLabel: 'The school says you were never admitted.',
  hook: 'Your school record has been deleted. You are still standing at the gate, holding your acceptance letter.',
  premise:
    'Verath Academy keeps a magical record for every student it admits. The record lives in the archives, and the spell on the front gate checks it each morning to decide who is allowed inside. ' +
    'On your first day the gate searches for your record and finds nothing. According to Verath, you were never admitted.\n\n' +
    'This is impossible. You have an acceptance letter, a room, and a timetable. So either the Academy made a mistake it has never made before, or somebody deliberately removed you from the record.\n\n' +
    'The gate turns red, which is the signal for a student who should be stopped. A prefect named Kael is ordered to investigate you. An archive assistant named Mira quietly covers for you, and clearly knows more than she says. The Warden who signs off on record changes is extremely kind to you, which is the part that worries you most.\n\n' +
    'You have a term to find out who erased you and why, before the gate stops treating it as an error and starts treating you as an intruder. Students here are never expelled. They are transferred, and the transfers do not arrive anywhere.',
  creatorId: 'creator_official',
  creatorName: 'Plotbreak Studios',
  official: true,
  coverImage: 'ninth-archive/cover',
  keyArt: 'ninth-archive/key',
  tags: ['Magic academy', 'Mystery', 'Dark fantasy', 'Rivalry', 'Investigation'],
  mechanicsChips: ['Investigation', 'Warding', 'Relationships', 'Stealth', 'Factions'],
  contentDescriptors: ['FANTASY_VIOLENCE', 'PSYCHOLOGICAL_THEMES', 'MORAL_AMBIGUITY', 'ROMANCE'],
  intensity: 'MODERATE',
  creatorNote:
    'A mystery you are allowed to lose. Getting caught does not restart the story. It changes it: the gate remembers, and so do the people who watched it happen.',
  rules: {
    defeatMode: 'FAIL_FORWARD',
    progressionMode: 'MILESTONE',
    revealExactDc: false,
    revealCheckMath: false,
    allowsCombat: true,
    allowsRomance: true,
    startingItems: [
      { itemId: 'sigil_pendant', qty: 1 },
      { itemId: 'acceptance_letter', qty: 1 },
    ],
    startingLocationId: 'gate_arch',
    startWorldMinute: 8 * 60 + 10,
    hardCanon: [
      'The ninth archive exists and is not on any Academy map.',
      'Ward-fire is silent. It never makes a sound, which is why it is feared.',
      'Erasure orders require two faculty signatures. Yours has only one.',
      'No student has ever been expelled from Verath. They are transferred, and the transfers do not arrive.',
    ],
    toneGuide:
      'Cold stone, warm lamps, and people being careful with each other. Threat is procedural, not monstrous — the danger is paperwork with teeth. Dry humour is welcome; melodrama is not.',
    forkCostCredits: 120,
  },
  attributes: { might: 9, agility: 11, mind: 13, presence: 11, resolve: 12, arcana: 12 },
  skills: [
    { id: 'arcana_lore', name: 'Arcana Lore', attribute: 'arcana', description: 'What a sigil means, and who wrote it.' },
    { id: 'warding', name: 'Warding', attribute: 'arcana', description: 'Reading, bending, and surviving Academy wards.' },
    { id: 'investigation', name: 'Investigation', attribute: 'mind', description: 'Finding the page someone hoped you would not.' },
    { id: 'stealth', name: 'Stealth', attribute: 'agility', description: 'Moving through a building that is paying attention.' },
    { id: 'sleight', name: 'Sleight', attribute: 'agility', description: 'Taking a key without taking a key.' },
    { id: 'persuasion', name: 'Persuasion', attribute: 'presence', description: 'Being believed, which is harder than being right.' },
    { id: 'deception', name: 'Deception', attribute: 'presence', description: 'Being believed while being wrong on purpose.' },
    { id: 'intimidation', name: 'Intimidation', attribute: 'presence', description: 'Making a problem someone else’s.' },
    { id: 'composure', name: 'Composure', attribute: 'resolve', description: 'Not flinching when the ward turns red.' },
    { id: 'athletics', name: 'Athletics', attribute: 'might', description: 'Stairs, ledges, and the occasional shove.' },
  ],
  resources: [
    {
      id: 'health',
      name: 'Health',
      max: 24,
      start: 24,
      regenPerHour: 1,
      polarity: 'GOOD_HIGH',
      displayPriority: 1,
      visible: true,
      zeroStateConsequence: 'You go down. In this world that means the infirmary and questions, not death.',
      color: '#FF5B69',
    },
    {
      id: 'focus',
      name: 'Focus',
      max: 20,
      start: 20,
      regenPerHour: 3,
      polarity: 'GOOD_HIGH',
      displayPriority: 2,
      visible: true,
      zeroStateConsequence: 'Sigils blur. Every arcane attempt is made at a disadvantage.',
      color: '#7C6CFF',
    },
    {
      id: 'suspicion',
      name: 'Suspicion',
      max: 100,
      start: 15,
      regenPerHour: -1,
      polarity: 'GOOD_LOW',
      displayPriority: 3,
      visible: true,
      zeroStateConsequence: 'The Wards lose interest in you. For now.',
      color: '#F6BE55',
    },
  ],
  items: [
    {
      id: 'acceptance_letter',
      name: 'Acceptance Letter',
      tags: ['quest', 'document'],
      questItem: true,
      droppable: false,
      description:
        'One page, Academy seal, your name in ink. The only object in the world that says you belong here.',
      loreText:
        'Two signatures at the bottom. One is the Warden. The other has been countersigned so heavily you cannot read it.',
      icon: 'letter',
    },
    {
      id: 'sigil_pendant',
      name: 'Unwritten Sigil',
      tags: ['quest', 'arcane'],
      questItem: true,
      droppable: false,
      description: 'The mark that should not resolve. Warm against the sternum when a ward reads it.',
      loreText: 'The engraving is fresh under the tarnish. Someone re-cut this within the year.',
      icon: 'sigil',
    },
    {
      id: 'reading_lens',
      name: "Cartwright's Lens",
      tags: ['tool'],
      equipSlot: 'hand',
      skillModifiers: { investigation: 2, arcana_lore: 1 },
      rarity: 'Uncommon',
      description: 'Ground for reading palimpsests. Shows the layer underneath the layer.',
      loreText: 'Property of C. Cartwright, whose name is also missing from the register.',
      icon: 'lens',
    },
    {
      id: 'ward_chalk',
      name: 'Ward Chalk',
      tags: ['consumable', 'arcane'],
      stackable: true,
      maxStack: 5,
      consumable: { resourceId: 'focus', amount: 8, consumesItem: true },
      description: 'A stub of binding chalk. Steadies a shaking hand and a fraying sigil.',
      loreText: 'Issued three to a student per term. You have been careful with yours.',
      icon: 'chalk',
    },
    {
      id: 'bramble_tonic',
      name: 'Bramble Tonic',
      tags: ['consumable', 'medicine'],
      stackable: true,
      maxStack: 3,
      consumable: { resourceId: 'health', amount: 10, consumesItem: true },
      description: 'Tastes like a hedge. Works like a week of rest compressed into a minute.',
      loreText: 'Bram sells these. Bram does not say where they come from.',
      icon: 'vial',
    },
    {
      id: 'stack_key',
      name: 'Undersecretary’s Key',
      tags: ['quest', 'tool'],
      questItem: true,
      description: 'Opens the stacks after hours. Notably, it does not open the ninth door.',
      loreText: 'The teeth have been filed. This is a copy of a copy.',
      icon: 'key',
    },
    {
      id: 'ledger_page',
      name: 'Torn Ledger Page',
      tags: ['quest', 'evidence'],
      questItem: true,
      description: 'One erasure order. One signature where there should be two.',
      loreText: 'The missing signature line has been scraped, not cut. Someone changed their mind.',
      icon: 'page',
    },
  ],
  abilities: [
    {
      id: 'sigil_read',
      name: 'Sigil Read',
      tags: ['arcane', 'utility'],
      description: 'Hold a mark in your attention until it admits what it is for.',
      affordances: [
        'read the ward',
        'study the sigil',
        'trace the mark',
        'work out what the glyph does',
        'look at the ward properly',
      ],
      costs: [{ resourceId: 'focus', amount: 3 }],
      cooldownMinutes: 0,
      targetRule: 'SINGLE',
      check: { attribute: 'arcana', skillId: 'warding', baseDc: 12 },
      unlockedByDefault: true,
    },
    {
      id: 'veilstep',
      name: 'Veilstep',
      tags: ['arcane', 'stealth'],
      description: 'Step into the seam between two lamps and come out somewhere the light is not.',
      affordances: [
        'veilstep',
        'slip through the shadow',
        'blink behind him',
        'move unseen',
        'cross the hall unseen',
      ],
      costs: [{ resourceId: 'focus', amount: 8 }],
      cooldownMinutes: 30,
      targetRule: 'SELF',
      check: { attribute: 'arcana', skillId: 'stealth', baseDc: 14 },
      unlockedByDefault: false,
    },
    {
      id: 'still_mind',
      name: 'Still Mind',
      tags: ['arcane', 'defensive'],
      description: 'Flatten your own signature until a ward finds you boring.',
      affordances: ['steady myself', 'calm my breathing', 'go quiet', 'still my mind'],
      costs: [{ resourceId: 'focus', amount: 4 }],
      cooldownMinutes: 60,
      targetRule: 'SELF',
      check: null,
      unlockedByDefault: true,
    },
  ],
  locations: [
    {
      id: 'gate_arch',
      takeableItems: [
        { itemId: 'ward_chalk', qty: 1, ownerId: null, aka: ['chalk', 'the box of chalk'] },
      ],
      name: 'The Gate Arch',
      shortName: 'Gate',
      description:
        'Verath’s outer arch, wide enough for four abreast and warded to read every one of them. The stone is worn pale in a strip at shoulder height where a century of students have trailed a hand through on the way in.',
      artDirection: 'Overcast morning, wet flagstones, tall grey arch, ward-light bleeding red across the threshold.',
      stageImage: 'ninth-archive/stage_gate',
      discoveredByDefault: true,
      mapPosition: { x: 0.5, y: 0.9 },
      ambientSfx: ['rain_light', 'crowd_murmur'],
      connections: [{ to: 'commons', travelMinutes: 4, label: 'Into the quad' }],
    },
    {
      id: 'commons',
      takeableItems: [
        { itemId: 'bramble_tonic', qty: 1, ownerId: null, aka: ['tonic', 'a bottle'] },
      ],
      name: 'The Commons',
      shortName: 'Commons',
      description:
        'A long hall of scarred oak tables where the Academy pretends to be a school. Tea urns, wet coats, and eleven separate arguments running at once.',
      artDirection: 'Warm lamplight, steam, crowded long tables, high windows going white with rain.',
      stageImage: 'ninth-archive/stage_commons',
      discoveredByDefault: true,
      mapPosition: { x: 0.5, y: 0.68 },
      ambientSfx: ['crowd_murmur', 'cups'],
      connections: [
        { to: 'gate_arch', travelMinutes: 4, label: 'Back to the gate' },
        { to: 'lecture_hall', travelMinutes: 5, label: 'Up to lectures' },
        { to: 'archive_floor', travelMinutes: 7, label: 'Down to the archives' },
        { to: 'dorm', travelMinutes: 6, label: 'To your room' },
      ],
    },
    {
      id: 'lecture_hall',
      name: 'Arcane Lecture Hall',
      shortName: 'Lectures',
      description:
        'Steep banked benches around a demonstration well. The board still carries yesterday’s proof, half-erased, which is either laziness or a message.',
      artDirection: 'Cool north light, chalk dust in the air, steep wooden benches, a dark slate well at the centre.',
      stageImage: 'ninth-archive/stage_lecture',
      discoveredByDefault: true,
      mapPosition: { x: 0.24, y: 0.5 },
      ambientSfx: ['chalk', 'shuffle'],
      connections: [
        { to: 'commons', travelMinutes: 5, label: 'Down to the commons' },
        { to: 'rooftop', travelMinutes: 8, label: 'The service stair' },
      ],
    },
    {
      id: 'archive_floor',
      name: 'Archive Reading Floor',
      shortName: 'Archives',
      description:
        'Eight doors, eight brass numerals, and a reading floor between them where the lamps are kept deliberately low. The air tastes of cold paper.',
      artDirection: 'Low green lamps, deep shadow between shelves, brass numerals catching light, vaulted dark ceiling.',
      stageImage: 'ninth-archive/stage_archive',
      discoveredByDefault: false,
      mapPosition: { x: 0.72, y: 0.5 },
      ambientSfx: ['paper', 'distant_footsteps'],
      connections: [
        { to: 'commons', travelMinutes: 7, label: 'Up to the commons' },
        { to: 'archive_stacks', travelMinutes: 3, lockedByFlag: 'stacks_access', label: 'Into the stacks' },
        { to: 'warden_office', travelMinutes: 5, label: "The Warden's office" },
      ],
    },
    {
      id: 'archive_stacks',
      takeableItems: [
        { itemId: 'stack_key', qty: 1, ownerId: 'bram', aka: ['key', 'the ring of keys', 'the stack key'] },
      ],
      name: 'The Stacks',
      shortName: 'Stacks',
      description:
        'Rolling shelves on iron rails, packed close enough that you have to crank a gap to walk. The wards down here are older and less polite.',
      artDirection: 'Narrow corridor between towering shelves, single swinging lamp, iron rails underfoot, deep black beyond.',
      stageImage: 'ninth-archive/stage_stacks',
      discoveredByDefault: false,
      mapPosition: { x: 0.9, y: 0.32 },
      ambientSfx: ['iron_rail', 'silence'],
      connections: [{ to: 'archive_floor', travelMinutes: 3, label: 'Back to the reading floor' }],
    },
    {
      id: 'warden_office',
      name: "The Warden's Office",
      shortName: "Warden's",
      description:
        'Warm, tidy, and hung with student portraits going back sixty years. Every one of them is smiling. Several of them you cannot find in the register.',
      artDirection: 'Firelit study, deep red rug, wall of small framed portraits, one empty frame.',
      stageImage: 'ninth-archive/stage_warden',
      discoveredByDefault: false,
      mapPosition: { x: 0.72, y: 0.24 },
      ambientSfx: ['fire', 'clock'],
      connections: [{ to: 'archive_floor', travelMinutes: 5, label: 'Out to the reading floor' }],
    },
    {
      id: 'rooftop',
      name: 'The Leads',
      shortName: 'Rooftop',
      description:
        'Flat lead sheeting between two gables, out of the wind and out of the wards. Someone has been up here often enough to leave a folded coat behind a chimney.',
      artDirection: 'Dusk, wet lead roof, city lights below through rain, two gables framing the sky.',
      stageImage: 'ninth-archive/stage_roof',
      discoveredByDefault: false,
      mapPosition: { x: 0.14, y: 0.24 },
      ambientSfx: ['wind', 'rain_light'],
      connections: [{ to: 'lecture_hall', travelMinutes: 8, label: 'Down the service stair' }],
    },
    {
      id: 'dorm',
      name: 'Your Room',
      shortName: 'Room',
      description:
        'A bed, a desk, a window that does not quite close, and a door the Academy has a key to. You have stopped leaving anything important in it.',
      artDirection: 'Small stone room, one candle, rain on a narrow window, neat desk.',
      stageImage: 'ninth-archive/stage_dorm',
      discoveredByDefault: true,
      mapPosition: { x: 0.34, y: 0.78 },
      ambientSfx: ['rain_window'],
      connections: [{ to: 'commons', travelMinutes: 6, label: 'To the commons' }],
    },
  ],
  characters: [
    {
      id: 'mira',
      name: 'Mira Senn',
      role: 'Archive assistant, third year',
      cardBlurb:
        "The archivist who quietly covers for you at the gate, and clearly knows more than she is saying.",
      pronouns: 'she/her',
      publicTraits: ['Precise', 'Overworked', 'Quietly funny'],
      hiddenDrives: [
        'She filed your erasure order herself and has not slept properly since.',
        'She wants someone to find out, so it stops being only hers.',
      ],
      values: ['Honesty', 'Keeping her word', 'The integrity of the record'],
      fears: ['Being transferred', 'Being the reason someone else is'],
      socialStyle: 'Deflects with procedure. Answers the question under the question if you wait through the silence.',
      boundaries: ['Will not lie to the Warden directly', 'Will not let you into the stacks without cover'],
      goals: ['Survive the term', 'Get the ninth archive on the record where someone senior has to look at it'],
      secrets: [
        {
          id: 'mira_filed_order',
          fact: 'Mira processed the erasure order that removed the player from the register.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Surfaces if the player finds the ledger page or reaches high trust on the roof.',
        },
        {
          id: 'mira_ninth_door',
          fact: 'Mira knows the ninth door opens from the stacks side and only during a ward cycle.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Requires trust 35+ and the rooftop conversation.',
        },
      ],
      speechStyle:
        'Short declaratives. Corrects herself mid-sentence when precision matters. Uses your surname when nervous and your first name when she is not.',
      topics: ['the ward', 'the register', 'who filed your entry', 'the eight doors'],
      voiceSamples: [
        "That's not a reading error. I checked it twice before you got here.",
        "I can give you forty minutes. After that the floor logs who's on it.",
        "Don't thank me yet. I haven't decided what I'm doing.",
      ],
      appearance:
        'Small, dark-haired, ink to the second knuckle, archive coat two sizes too big and worn like armour.',
      visualHook:
        "A single bone-white streak burned through her black hair above the left temple, where a ward caught her, and both hands inked black to the second knuckle.",
      silhouette:
        "Small and swallowed by an archive coat two sizes too big, collar up, sleeves rolled twice and still too long.",
      artSeed: 'mira-senn-v1',
      portrait: 'ninth-archive/mira',
      expressions: ['neutral', 'wary', 'tired', 'amused', 'alarmed', 'resolved'],
      voiceId: 'voice_mira',
      homeLocationId: 'archive_floor',
      knowledgeScope: ['faction_archivists'],
      schedule: [
        { startMinute: 480, endMinute: 690, locationId: 'lecture_hall', activity: 'Arcane lecture' },
        { startMinute: 690, endMinute: 750, locationId: 'commons', activity: 'Tea, and marking' },
        { startMinute: 750, endMinute: 960, locationId: 'archive_floor', activity: 'Archive assistant shift' },
        { startMinute: 960, endMinute: 1080, locationId: 'rooftop', activity: 'Not being found' },
        { startMinute: 1080, endMinute: 1320, locationId: 'commons', activity: 'Evening hall' },
      ],
      startingRelationship: { trust: 5, affection: 0, respect: 5, fear: 0, rivalry: 0 },
      attributes: { might: 8, agility: 11, mind: 15, presence: 11, resolve: 13, arcana: 13 },
      gates: [
        {
          id: 'mira_tells_truth',
          kind: 'TRUST',
          label: 'Mira will tell you what she filed',
          requires: { trust: 35, flagsSet: ['mira_trusts_you'], flagsUnset: ['mira_burned'] },
        },
        {
          id: 'mira_opens_ninth',
          kind: 'ALLIANCE',
          label: 'Mira will walk you to the ninth door',
          requires: { trust: 55, respect: 30, flagsSet: ['mira_trusts_you'] },
        },
      ],
      combatant: null,
    },
    {
      id: 'kael',
      name: 'Kael Ostrand',
      role: 'Gate prefect, fifth year',
      cardBlurb:
        "The prefect who stopped you. He has been told to investigate you, and he intends to do it properly.",
      pronouns: 'he/him',
      publicTraits: ['Rigid', 'Fair', 'Extremely tired of being right'],
      hiddenDrives: [
        'His own brother was transferred two years ago. He signed the form.',
        'He is looking for a case that proves the system works so he can stop suspecting it does not.',
      ],
      values: ['Procedure', 'Consistency', 'Not making exceptions he cannot defend'],
      fears: ['That the rules are a cover', 'Being the last person to notice'],
      socialStyle: 'Confrontational but scrupulously honest. Will state exactly what he is about to do before doing it.',
      boundaries: ['Will not falsify a log', 'Will not let a threat pass unanswered in public'],
      goals: ['Keep the gate clean', 'Find out what happened to the transfers'],
      secrets: [
        {
          id: 'kael_brother',
          fact: "Kael's brother Aldric was transferred and never arrived.",
          visibility: 'NPC_PRIVATE',
          revealHint: 'Only after respect 40+, or if the player shows him the ledger page.',
        },
      ],
      speechStyle:
        'Clipped, formal, no contractions when he is angry. Asks questions he already knows the answer to, to see if you will lie.',
      topics: ['the gate log', 'the transfers', 'what the red actually means'],
      voiceSamples: [
        'You. Do not move.',
        'I am going to log this. I am telling you so you cannot say I did not.',
        'If you are innocent then you will not mind the delay.',
      ],
      appearance: 'Tall, close-cropped fair hair, prefect sash kept immaculate, hands always visible.',
      visualHook:
        "A prefect sash worn immaculately over a black mourning band he has never once explained, and a single black glove on the right hand that never comes off.",
      silhouette:
        "Tall and squared-off, hands always visible and still, the only person in any room standing perfectly straight.",
      artSeed: 'kael-ostrand-v1',
      portrait: 'ninth-archive/kael',
      expressions: ['neutral', 'stern', 'suspicious', 'conflicted', 'furious'],
      voiceId: 'voice_kael',
      homeLocationId: 'gate_arch',
      knowledgeScope: ['faction_prefects'],
      schedule: [
        { startMinute: 420, endMinute: 660, locationId: 'gate_arch', activity: 'Gate watch' },
        { startMinute: 660, endMinute: 780, locationId: 'commons', activity: 'Rounds' },
        { startMinute: 780, endMinute: 990, locationId: 'lecture_hall', activity: 'Fifth-year seminar' },
        { startMinute: 990, endMinute: 1260, locationId: 'archive_floor', activity: 'Evening patrol' },
      ],
      startingRelationship: { trust: 0, affection: 0, respect: 10, fear: 0, rivalry: 15 },
      attributes: { might: 14, agility: 12, mind: 12, presence: 13, resolve: 15, arcana: 10 },
      gates: [
        {
          id: 'kael_alliance',
          kind: 'ALLIANCE',
          label: 'Kael will work the case with you',
          requires: { respect: 45, trust: 25, flagsSet: ['spoke:kael'], hasItems: ['ledger_page'] },
        },
      ],
      combatant: { health: 22, defenseDc: 14, damage: 5, tags: ['trained', 'nonlethal'] },
    },
    {
      id: 'ysolde',
      name: 'Warden Ysolde Farrow',
      role: 'Warden of Records',
      cardBlurb:
        "The teacher who signs off on record changes. She is unfailingly kind to you, which is the worrying part.",
      pronouns: 'she/her',
      publicTraits: ['Warm', 'Unhurried', 'Remembers everything about you'],
      hiddenDrives: [
        'She signs the erasures. She believes, sincerely, that she is protecting the students she removes.',
        'She has been waiting to see whether you would come to her first.',
      ],
      values: ['Order', 'Mercy as she defines it', 'The Academy above any one student'],
      fears: ['A second signature she cannot get', 'Being understood'],
      socialStyle: 'Generous with tea and time. Answers everything except the thing you asked.',
      boundaries: ['Never raises her voice', 'Never denies anything outright'],
      goals: ['Close the matter of the ninth archive quietly', 'Recruit you rather than remove you'],
      secrets: [
        {
          id: 'ysolde_single_signature',
          fact: "Ysolde signed the player's erasure alone. The second signature was never obtained.",
          visibility: 'CREATOR_ONLY',
          revealHint: 'The ledger page is the only in-world evidence.',
        },
      ],
      speechStyle:
        'Long, kind, perfectly grammatical sentences. Uses your name often. Never says no; says "not yet" and "let us see".',
      topics: ['the erasure orders', 'the portraits on her wall', 'what she wants from you'],
      voiceSamples: [
        'Sit down, do. You have had a morning.',
        'I would not call it erasure. I would call it a kindness with poor handwriting.',
        'You may ask me anything. I will answer what I can.',
      ],
      appearance: 'Sixties, silver plait, half-moon spectacles, ink-stained cuffs she does not bother to hide.',
      visualHook:
        "A dozen thin ink-stained silver rings, one per erased student, which she turns on her finger whenever she is about to say something untrue.",
      silhouette:
        "Upright and unhurried, silver plait over one shoulder, half-moon spectacles low on the nose.",
      artSeed: 'ysolde-farrow-v1',
      portrait: 'ninth-archive/ysolde',
      expressions: ['warm', 'neutral', 'attentive', 'disappointed', 'cold'],
      voiceId: 'voice_ysolde',
      homeLocationId: 'warden_office',
      knowledgeScope: ['faction_archivists', 'faction_prefects', 'faction_faculty'],
      schedule: [
        { startMinute: 480, endMinute: 720, locationId: 'warden_office', activity: 'Correspondence' },
        { startMinute: 720, endMinute: 810, locationId: 'commons', activity: 'Lunch, visibly' },
        { startMinute: 810, endMinute: 1140, locationId: 'warden_office', activity: 'Records' },
        { startMinute: 1140, endMinute: 1260, locationId: 'archive_floor', activity: 'Closing walk' },
      ],
      startingRelationship: { trust: 10, affection: 10, respect: 0, fear: 5, rivalry: 0 },
      attributes: { might: 8, agility: 9, mind: 16, presence: 16, resolve: 16, arcana: 16 },
      gates: [
        {
          id: 'ysolde_offer',
          kind: 'OTHER',
          label: 'Ysolde will make you an offer',
          requires: { trust: 40, flagsSet: ['act_one_complete'] },
        },
      ],
      combatant: null,
    },
    {
      id: 'bram',
      name: 'Bram Ketch',
      role: 'Second year, unofficial quartermaster',
      cardBlurb:
        "A second-year who can get you almost anything, for a price he will name later.",
      pronouns: 'he/him',
      publicTraits: ['Cheerful', 'Transactional', 'Genuinely fond of you'],
      hiddenDrives: [
        'He is in debt to someone outside the Academy and is selling small favours to clear it.',
        'He will not sell you out, but he will sell around you.',
      ],
      values: ['Paying what he owes', 'Not being anyone’s employee'],
      fears: ['The debt coming to the gate', 'Being found boring'],
      socialStyle: 'Opens with a joke, closes with a price. Means both.',
      boundaries: ['Will not steal from students', 'Will not carry anything that has a name on it'],
      goals: ['Clear the debt', 'Stay interesting to people who matter'],
      secrets: [
        {
          id: 'bram_debt',
          fact: 'Bram owes forty crowns to a lender in the lower city and has three weeks.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Trust 30+, or catch him counting.',
        },
      ],
      speechStyle: 'Fast, warm, lots of questions, deflects sincerity with a joke exactly once before answering.',
      topics: ['the key to the stacks', 'who he owes', 'what he is really selling'],
      voiceSamples: [
        'Oh, that ward? That ward hates everyone. Statistically you are fine.',
        'I can get you a key. I cannot get you a key today.',
        'Do not look at me like that, I have feelings and a schedule.',
      ],
      appearance: 'Short, broad, permanently slightly damp, four coats’ worth of pockets in one coat.',
      visualHook:
        "The last two fingers missing from his left hand, entirely undiscussed, and a coat carrying four coats' worth of visibly overstuffed pockets.",
      silhouette:
        "Short, broad, permanently slightly damp, leaning in like he is already mid-deal.",
      artSeed: 'bram-ketch-v1',
      portrait: 'ninth-archive/bram',
      expressions: ['grinning', 'neutral', 'shifty', 'serious', 'delighted'],
      voiceId: 'voice_bram',
      homeLocationId: 'commons',
      knowledgeScope: [],
      schedule: [
        { startMinute: 480, endMinute: 690, locationId: 'commons', activity: 'Trading' },
        { startMinute: 690, endMinute: 900, locationId: 'lecture_hall', activity: 'Nominally attending' },
        { startMinute: 900, endMinute: 1140, locationId: 'commons', activity: 'Trading, busier' },
        { startMinute: 1140, endMinute: 1320, locationId: 'dorm', activity: 'Counting' },
      ],
      startingRelationship: { trust: 15, affection: 15, respect: 5, fear: 0, rivalry: 0 },
      attributes: { might: 11, agility: 14, mind: 12, presence: 13, resolve: 10, arcana: 8 },
      gates: [
        {
          id: 'bram_real_answer',
          kind: 'TRUST',
          label: 'Bram will tell you who he owes',
          requires: { trust: 30, affection: 25 },
        },
      ],
      combatant: { health: 14, defenseDc: 12, damage: 3, tags: ['scrappy'] },
    },
  ],
  factions: [
    {
      id: 'faction_archivists',
      name: 'The Archivists',
      description: 'Keepers of the eight archives. Institutionally incapable of admitting there are nine.',
      startingReputation: 0,
      ranks: [
        { atReputation: -40, label: 'Barred' },
        { atReputation: 0, label: 'Reader' },
        { atReputation: 30, label: 'Trusted Reader' },
        { atReputation: 60, label: 'Assistant' },
      ],
      enemies: [],
      allies: ['faction_faculty'],
    },
    {
      id: 'faction_prefects',
      name: 'The Prefecture',
      description: 'Student enforcement. Keeps the logs that the faculty later declines to read.',
      startingReputation: -5,
      ranks: [
        { atReputation: -50, label: 'Flagged' },
        { atReputation: -10, label: 'Watched' },
        { atReputation: 20, label: 'Cleared' },
        { atReputation: 50, label: 'Vouched For' },
      ],
      enemies: [],
      allies: ['faction_faculty'],
    },
    {
      id: 'faction_faculty',
      name: 'The Faculty',
      description: 'Signs everything. Reads very little.',
      startingReputation: 0,
      ranks: [
        { atReputation: -40, label: 'Under Review' },
        { atReputation: 0, label: 'Enrolled' },
        { atReputation: 40, label: 'Commended' },
      ],
      enemies: [],
      allies: ['faction_archivists', 'faction_prefects'],
    },
  ],
  quests: [
    {
      id: 'q_red_ward',
      title: 'The Ward Turned Red',
      summary: 'Get through the gate, and find out what the ward saw.',
      kind: 'MAIN',
      startsActive: true,
      involvedCharacterIds: ['kael', 'mira'],
      involvedLocationIds: ['gate_arch', 'commons', 'archive_floor'],
      knownRewardCopy: 'Access to the archive reading floor.',
      steps: [
        {
          id: 'step_gate',
          playerCopy: 'Get past Kael at the gate.',
          directorNotes:
            'Kael will not be intimidated in public, and he is not the obstacle he looks like — he is a ' +
            'prefect doing a job he did not ask for. Four ways through, and which one the player takes is ' +
            'the first thing this world learns about them. Never hand it over.',
          succeedWhenAny: [
            {
              routeId: 'gate_by_paperwork',
              label: 'You had the letter all along',
              predicate: {
                flagsSet: ['spoke:kael'],
                flagsUnset: [],
                hasItems: ['acceptance_letter'],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['through_the_gate', 'kael_saw_the_letter', 'route_by_paperwork'],
              closesFlags: ['kael_owes_you'],
            },
            {
              routeId: 'gate_by_reading_the_ward',
              label: 'You read the ward before he could log it',
              predicate: {
                flagsSet: ['used:sigil_read', 'spoke:kael'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'gate_arch',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['through_the_gate', 'knows_ward_reads_wrong', 'route_by_reading'],
              closesFlags: [],
            },
            {
              routeId: 'gate_by_someone_else',
              label: 'Somebody vouched for you',
              predicate: {
                flagsSet: ['spoke:ysolde'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'ysolde', dimension: 'trust', value: 20 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['through_the_gate', 'ysolde_vouched', 'route_by_patronage'],
              closesFlags: ['kael_respects_you'],
            },
            {
              routeId: 'gate_by_wearing_him_down',
              label: 'You simply would not go away',
              predicate: {
                flagsSet: ['spoke:kael'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'commons',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['through_the_gate', 'kael_logged_you', 'route_by_persistence'],
              closesFlags: [],
            },
          ],
          rewards: { xp: 30, items: [], flags: [] },
        },
        {
          id: 'step_find_mira',
          playerCopy: 'Find the archive assistant who logged your entry.',
          directorNotes:
            'Mira is on shift from 12:30. Before that she is in lectures and will not talk. A player who ' +
            'cannot wait can get at the same fact another way, and pays for it: the log itself is in the ' +
            'stacks, and Bram keeps the key.',
          succeedWhenAny: [
            {
              routeId: 'mira_in_person',
              label: 'You waited and asked her',
              predicate: {
                flagsSet: ['spoke:mira'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['archive_known', 'mira_told_you_herself'],
              closesFlags: [],
            },
            {
              routeId: 'mira_via_the_log',
              label: 'You read the log instead of asking',
              predicate: {
                flagsSet: ['inspected:archive_stacks'],
                flagsUnset: [],
                hasItems: ['stack_key'],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['archive_known', 'went_round_mira'],
              closesFlags: ['mira_told_you_herself'],
            },
            {
              routeId: 'mira_via_bram',
              label: 'Bram told you what she wrote',
              predicate: {
                flagsSet: ['spoke:bram'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'bram', dimension: 'trust', value: 25 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['archive_known', 'bram_broke_a_rule_for_you'],
              closesFlags: [],
            },
          ],
          rewards: { xp: 40, items: [], flags: [] },
        },
        {
          id: 'step_read_own_record',
          playerCopy: 'Read your own entry in the register.',
          directorNotes: 'The entry exists but the name field is scraped. This is the first hard proof.',
          enterWhen: { flagsSet: ['archive_known'] },
          succeedWhen: { flagsSet: ['inspected:archive_floor'], atLocation: 'archive_floor' },
          rewards: { xp: 60, items: [{ itemId: 'reading_lens', qty: 1 }], flags: ['knows_erasure'] },
        },
      ],
    },
    {
      id: 'q_ninth_shelf',
      title: 'The Ninth Shelf',
      summary: 'Eight doors, eight numerals. Find the ninth.',
      kind: 'MAIN',
      startsActive: false,
      involvedCharacterIds: ['mira', 'ysolde'],
      involvedLocationIds: ['archive_floor', 'archive_stacks'],
      knownRewardCopy: 'The truth about your erasure.',
      discoverWhen: { flagsSet: ['knows_erasure'] },
      steps: [
        {
          id: 'step_stacks_access',
          playerCopy: 'Get into the stacks.',
          directorNotes:
            'Three genuinely different routes, and the one taken changes the rest of the story. ' +
            'Do not steer the player toward any of them.',
          // No single success predicate: any of these three completes the step,
          // and each closes something the others would have kept open.
          succeedWhenAny: [
            {
              routeId: 'mira_covers',
              label: 'Mira covered for you',
              predicate: {
                flagsSet: [],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'archive_stacks',
                completedEvents: [],
                minRelationship: [{ characterId: 'mira', dimension: 'trust', value: 30 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              // She took a risk for you, and that is now a thing you owe her.
              setsFlags: ['stacks_access', 'mira_took_a_risk', 'owe_mira'],
              closesFlags: ['clean_record'],
            },
            {
              routeId: 'bram_key',
              label: 'Bram sold you a key',
              predicate: {
                flagsSet: [],
                flagsUnset: [],
                hasItems: ['stack_key'],
                atLocation: 'archive_stacks',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              // A paper trail exists, and Bram now has something on you.
              setsFlags: ['stacks_access', 'bram_has_leverage', 'key_traceable'],
              closesFlags: ['mira_took_a_risk'],
            },
            {
              routeId: 'broke_in',
              label: 'You got in on your own',
              predicate: {
                flagsSet: [],
                flagsUnset: ['stacks_access'],
                hasItems: [],
                atLocation: 'archive_stacks',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              // Nobody owes you and nobody covers for you. The wards noticed.
              setsFlags: ['stacks_access', 'wards_flagged_you', 'owe_nobody'],
              closesFlags: ['clean_record', 'mira_took_a_risk'],
            },
          ],
          rewards: { xp: 50, items: [], flags: [] },
        },
        {
          id: 'step_ledger',
          playerCopy: 'Find the erasure order with your name on it.',
          directorNotes: 'The page is real and damning: one signature where there should be two.',
          enterWhen: { flagsSet: ['stacks_access'] },
          succeedWhen: { hasItems: ['ledger_page'] },
          rewards: { xp: 80, items: [], flags: ['has_evidence'] },
        },
        {
          id: 'step_ninth_door',
          playerCopy: 'Find the ninth door.',
          directorNotes: 'Opens from the stacks side, during a ward cycle. Mira knows; so does Ysolde.',
          enterWhen: { flagsSet: ['has_evidence'] },
          succeedWhen: { flagsSet: ['inspected:archive_stacks'], atLocation: 'archive_stacks' },
          rewards: { xp: 120, items: [], flags: ['act_one_complete'] },
        },
      ],
    },
    {
      id: 'q_owed_favour',
      title: 'What You Owe Mira',
      summary: 'Mira put herself in front of a disciplinary board for you. She has not asked for anything yet.',
      kind: 'SIDE',
      startsActive: false,
      involvedCharacterIds: ['mira'],
      involvedLocationIds: ['archive_floor', 'rooftop'],
      knownRewardCopy: 'A debt settled, or a friend lost.',
      // Only exists if she was the one who got you in.
      discoverWhen: {
        flagsSet: ['mira_took_a_risk'],
        flagsUnset: [],
        hasItems: [],
        atLocation: null,
        completedEvents: [],
        minRelationship: [],
        minFactionReputation: [],
        beforeWorldMinute: null,
      },
      steps: [
        {
          id: 'step_mira_asks',
          playerCopy: 'Find out what Mira wants in return.',
          directorNotes: 'She does not want a favour back. She wants you to finish what you started.',
          succeedWhen: {
            flagsSet: ['spoke:mira'],
            flagsUnset: [],
            hasItems: [],
            atLocation: null,
            completedEvents: [],
            minRelationship: [],
            minFactionReputation: [],
            beforeWorldMinute: null,
          },
          rewards: { xp: 60, items: [], flags: [] },
        },
      ],
    },
    {
      id: 'q_wards_watching',
      title: 'The Wards Have Your Face',
      summary: 'You forced a door the building was counting. Now it counts you.',
      kind: 'SIDE',
      startsActive: false,
      involvedCharacterIds: ['kael', 'ysolde'],
      involvedLocationIds: ['archive_floor', 'warden_office'],
      knownRewardCopy: 'Get off the list, or learn to live on it.',
      // Only exists if you got in the hard way.
      discoverWhen: {
        flagsSet: ['wards_flagged_you'],
        flagsUnset: [],
        hasItems: [],
        atLocation: null,
        completedEvents: [],
        minRelationship: [],
        minFactionReputation: [],
        beforeWorldMinute: null,
      },
      steps: [
        {
          id: 'step_off_the_list',
          playerCopy: 'Deal with the fact that the building is now watching you.',
          directorNotes:
            'Kael will have seen the log. Ysolde can make it disappear, and will want something for it.',
          succeedWhenAny: [
            {
              routeId: 'kael_vouches',
              label: 'Kael put a note against the log',
              predicate: {
                flagsSet: ['spoke:kael'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'kael', dimension: 'respect', value: 35 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['ward_flag_resolved', 'kael_vouched_for_you'],
              closesFlags: ['owe_ysolde'],
            },
            {
              routeId: 'ysolde_erases',
              label: 'Ysolde made it go away',
              predicate: {
                flagsSet: ['spoke:ysolde'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'warden_office',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              // She fixes it, and now you are a person she has done something for.
              setsFlags: ['ward_flag_resolved', 'owe_ysolde'],
              closesFlags: ['kael_vouched_for_you'],
            },
          ],
          rewards: { xp: 80, items: [], flags: [] },
        },
      ],
    },
    {
      id: 'q_bram_favor',
      title: "Bram's Arithmetic",
      summary: 'Bram wants something moved. He is being unusually vague about what.',
      kind: 'SIDE',
      startsActive: false,
      involvedCharacterIds: ['bram'],
      involvedLocationIds: ['commons', 'dorm'],
      knownRewardCopy: 'A key, a tonic, and a friend who owes you.',
      discoverWhen: { flagsSet: ['met:bram'] },
      steps: [
        {
          id: 'step_bram_ask',
          playerCopy: 'Hear Bram out.',
          directorNotes: 'He undersells the risk. Insight or high trust reveals the debt.',
          succeedWhen: { flagsSet: ['spoke:bram'] },
        },
        {
          id: 'step_bram_deliver',
          playerCopy: 'Decide whether to carry it.',
          directorNotes: 'Carrying it raises Suspicion but earns the stack key. Refusing keeps him warm but costs the key.',
          enterWhen: { flagsSet: ['spoke:bram'] },
          succeedWhenAny: [
            {
              routeId: 'carried_it',
              label: 'You carried it',
              predicate: {
                flagsSet: [],
                flagsUnset: [],
                hasItems: ['stack_key'],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['bram_resolved', 'bram_owes_you'],
              closesFlags: ['clean_record'],
            },
            {
              routeId: 'refused_it',
              label: 'You said no and he took it well',
              predicate: {
                flagsSet: ['spoke:bram'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'bram', dimension: 'trust', value: 25 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['bram_resolved'],
              closesFlags: ['bram_owes_you'],
            },
          ],
          rewards: { xp: 60, items: [{ itemId: 'bramble_tonic', qty: 2 }], flags: [] },
        },
      ],
    },
    {
      id: 'lead_rooftop',
      title: 'Someone Goes Up There',
      summary: 'Someone leaves a folded coat behind a chimney on the flat roof above the lecture hall. They are up there most days.',
      kind: 'LEAD',
      startsActive: false,
      involvedCharacterIds: ['mira'],
      involvedLocationIds: ['rooftop'],
      knownRewardCopy: 'Mira, unguarded.',
      discoverWhen: { flagsSet: ['visited:rooftop'] },
      steps: [
        {
          id: 'step_rooftop_wait',
          playerCopy: 'Be on the leads at four, and wait.',
          directorNotes:
            'Mira is on the roof 16:00-18:00. This is the §16.4 relationship promise payoff and unlocks mira_rooftop_truth.',
          succeedWhen: {
            flagsSet: ['visited:rooftop', 'spoke:mira'],
            atLocation: 'rooftop',
            minRelationship: [{ characterId: 'mira', dimension: 'trust', value: 30 }],
          },
          rewards: { xp: 90, items: [], flags: ['mira_trusts_you'] },
        },
      ],
    },
  ],
  promises: [
    {
      id: 'promise_who_erased',
      kind: 'MYSTERY',
      label: 'Who unwrote you, and why they left the shape behind',
      seedHint: 'The gate ward reads red for a mark that is not in the register.',
      payoffHint: 'Ysolde signed it alone, believing it was mercy.',
      weight: 1,
    },
    {
      id: 'promise_kael_rival',
      kind: 'RIVAL',
      label: 'Kael, who is not wrong about you',
      seedHint: 'He stops you at the gate and logs it, in front of everyone.',
      payoffHint: 'His brother was transferred. He signed that form too.',
      weight: 0.8,
    },
    {
      id: 'promise_mira_trust',
      kind: 'RELATIONSHIP',
      label: 'Mira, who filed the order and has to live with it',
      seedHint: 'She covers for you before you ask her to.',
      payoffHint: 'On the roof, she tells you what she did.',
      weight: 0.9,
    },
    {
      id: 'promise_the_transfers',
      kind: 'THEME',
      label: 'Nobody is expelled from Verath. They are transferred.',
      seedHint: 'A wall of smiling portraits, several not in the register.',
      payoffHint: 'The ninth archive is where the transfers are kept.',
      weight: 0.7,
    },
    {
      id: 'promise_ninth_door',
      kind: 'FINALE',
      label: 'The door with no numeral',
      seedHint: 'Eight doors, and a stretch of wall between five and six that is slightly too wide.',
      payoffHint: 'It opens from the stacks side, during a ward cycle.',
      weight: 1,
    },
  ],
  archetypes: [
    {
      id: 'arch_scholar',
      name: 'Arcane Scholar',
      role: 'Magic and research',
      summary:
        'You work out what a thing is before you touch it. Best at reading wards, spotting traps and knowing what you are looking at.',
      playstyle: ['Investigation', 'Magical knowledge', 'Careful'],
      blurb: 'You read the ward before you touch it. Usually.',
      attributeBonus: { mind: 2, arcana: 1 },
      skillProficiencies: { arcana_lore: 2, investigation: 2, warding: 1 },
      startingItems: [{ itemId: 'ward_chalk', qty: 2 }],
      startingAbilities: [],
    },
    {
      id: 'arch_thief',
      name: 'Quiet Hands',
      role: 'Stealth',
      summary:
        'You go where you are not allowed and are not seen doing it. The only background here that starts with a technique.',
      playstyle: ['Stealth', 'Fast', 'Starts with a technique'],
      blurb: 'You have never been caught, which is not the same as never having done it.',
      attributeBonus: { agility: 3 },
      skillProficiencies: { stealth: 3, sleight: 2, deception: 1 },
      startingItems: [{ itemId: 'bramble_tonic', qty: 1 }],
      startingAbilities: ['veilstep'],
    },
    {
      id: 'arch_orator',
      name: 'Silver Tongue',
      role: 'Social',
      summary:
        'You talk your way past rules everyone else obeys. Best presence in the school and nothing at all to fall back on if talking fails.',
      playstyle: ['Persuasion', 'Talks past trouble', 'Physically weak'],
      blurb: 'Rules are written by people, and people can be talked to.',
      attributeBonus: { presence: 3 },
      skillProficiencies: { persuasion: 3, deception: 1, composure: 2 },
      startingItems: [{ itemId: 'ward_chalk', qty: 1 }],
      startingAbilities: [],
    },
    {
      id: 'arch_duelist',
      name: 'Gate Duelist',
      role: 'Melee',
      summary:
        'You would rather not fight, and you are the best here at it. Strength, nerve, and the ability to still be standing afterwards.',
      playstyle: ['Direct', 'Physical', 'Intimidating'],
      blurb: 'You would rather not. You are very good at it anyway.',
      attributeBonus: { might: 2, resolve: 1 },
      skillProficiencies: { athletics: 3, intimidation: 2, composure: 1 },
      startingItems: [{ itemId: 'bramble_tonic', qty: 2 }],
      startingAbilities: [],
    },
  ],
  setupFields: [
    { id: 'displayName', label: 'What do they call you?', kind: 'TEXT', required: true, maxLength: 40, placeholder: 'e.g. Malik Sarrow' },
    { id: 'pronouns', label: 'Pronouns', kind: 'TEXT', required: false, maxLength: 24, placeholder: 'e.g. he/him' },
    {
      id: 'archetype',
      label: 'How do you get things done?',
      helpText:
        'Your background: how you got into the Archive and what you were already good at when you arrived. It sets your attributes, your training and what you carry, which decides which checks come easily and which you will be sweating. It is fixed for this run.',
      kind: 'ARCHETYPE',
      required: false,
    },
    {
      id: 'worldKnowsAboutYou',
      label: 'What should the world know about you?',
      kind: 'TEXT',
      required: false,
      maxLength: 300,
      placeholder: 'e.g. I transferred in a term late and nobody will say who signed for me.',
    },
    {
      id: 'origin',
      label: 'Where are you from?',
      kind: 'CHOICE',
      advanced: true,
      options: [
        { id: 'lower_city', label: 'The lower city' },
        { id: 'coast', label: 'The salt coast' },
        { id: 'academy_born', label: 'Born inside these walls' },
        { id: 'unknown', label: 'You genuinely do not know' },
      ],
    },
    {
      id: 'appearance',
      label: 'Anything the ward would notice?',
      kind: 'TEXT',
      advanced: true,
      maxLength: 200,
      placeholder: 'e.g. Short, dark hair cut badly by myself, a coat two sizes too big.',
    },
  ],
  opening:
    'The gate spell reads eleven students ahead of you and lets all eleven through. Then it reads you, searches the Academy records for your name, and finds nothing at all.\n\n' +
    'The light above the arch turns red. Red means stop this one.\n\n' +
    'The queue behind you goes quiet. A prefect looks up from his logbook, and you can see him decide that his morning is now about you.\n\n' +
    '"You." Kael Ostrand does not raise his voice. "Do not move."\n\n' +
    'Behind him, a small dark-haired archivist glances at the red light, then at you, and says nothing at all about what she just saw.',
  openingSuggestions: [
    'I stay exactly where I am and let Kael write whatever he is going to write. “Go on. I want to see what it says.”',
    'I pull the acceptance letter out and hold it where the light catches it. “Read the name on this. Then tell me I was never admitted.”',
    'I nod at the red light over the door without taking my eyes off the archivist. “That has been on since I walked in. What does it mean?”',
  ],
  publishedAt: '2026-08-14T09:00:00.000Z',
};

export const NINTH_ARCHIVE = StoryVersion.parse(raw);
