import { StoryVersion } from '@plotbreak/contracts';

/**
 * "Seven Days to Midnight" — the city ends on Sunday and you are the only
 * person who has been here before.
 *
 * This is the world that leans hardest on the engine, and it has to. A looping
 * mystery is only a game if the week is authoritative: thirteen events at
 * thirteen fixed hours, six people on real schedules, and a reset that rebuilds
 * the world from the story rather than from whatever the narrator remembers.
 * A player who learns that the marina office is robbed at ten on Tuesday can be
 * standing in it at five to, and the theft does not happen, because a flag
 * cancelled it — not because the prose was feeling generous.
 *
 * The progression system is knowledge. Nothing else crosses a reset: not items,
 * not injuries, not where anybody is, not what anyone thinks of you. Every
 * `knows:` flag is a door that stays open, and the whole difficulty curve is
 * made of things the player worked out and wrote down in their own head.
 *
 * Echoes are the exception and they are deliberately rare. Nobody remembers.
 * Somebody who trusted you completely just finds, next Monday, that they
 * inexplicably do again.
 *
 * Parsed at import so a malformed world fails the build, not a player's session.
 */

// Monday 00:00 is minute zero. The week runs to Sunday midnight at 10,080.
const DAY = 1440;
const MON = 0;
const TUE = DAY;
const WED = 2 * DAY;
const THU = 3 * DAY;
const FRI = 4 * DAY;
const SAT = 5 * DAY;
const SUN = 6 * DAY;
const at = (day: number, hour: number, minute = 0): number => day + hour * 60 + minute;

const raw = {
  id: 'sv_seven_days_1',
  storyId: 'story_seven_days',
  version: 1,
  title: 'Seven Days to Midnight',
  fantasyLabel: 'The city ends Sunday. Only you remember.',
  hook: 'You arrived on Monday for a fresh start. On Sunday at midnight the city is destroyed and you die. Then it is Monday again.',
  premise:
    'Halcyon Bay is a small coastal city built up the side of a hill, with a marina at the bottom and a clock tower at the top. You arrived on Monday morning with two bags and a room booked for the season.\n\n' +
    'It was a good week. You met a woman called Mina on the platform who decided on the spot to show you around. You found a bar you liked. You started to think you had made the right decision.\n\n' +
    'On Sunday at midnight the city was destroyed. You do not have a better word for it than that, because you did not see what did it — only the light, and the sound, and the water coming up the hill.\n\n' +
    'Then you were on the platform again, on Monday morning, with two bags, and Mina was walking towards you saying the same thing she said the first time.\n\n' +
    'Nobody remembers. You have seven days, and you have had them before.\n\n' +
    'The only thing you keep is what you worked out.',
  creatorId: 'creator_official',
  creatorName: 'Plotbreak Studios',
  official: true,
  coverImage: 'seven_days/cover',
  keyArt: 'seven_days/key',
  tags: ['Mystery', 'Time loop', 'Slice of life', 'Supernatural', 'Drama'],
  mechanicsChips: ['A real weekly timetable', 'Knowledge carries over', 'Change what happens', 'Echoes', 'Multiple endings'],
  contentDescriptors: ['PSYCHOLOGICAL_THEMES', 'MORAL_AMBIGUITY', 'ROMANCE', 'PERMANENT_DEATH', 'LANGUAGE'],
  intensity: 'MODERATE',
  creatorNote:
    'Nothing carries over except what you know. Everything else — where people are, what they think of you, what you are holding — goes back to Monday morning. Learn the week and you can start taking it apart.',
  rules: {
    defeatMode: 'FAIL_FORWARD',
    progressionMode: 'MILESTONE',
    revealExactDc: false,
    revealCheckMath: false,
    allowsCombat: true,
    allowsRomance: true,
    startingLocationId: 'the_platform',
    startWorldMinute: at(MON, 8, 12),
    startingItems: [
      { itemId: 'two_bags', qty: 1 },
      { itemId: 'room_key', qty: 1 },
    ],
    hardCanon: [
      'Nobody in Halcyon Bay remembers a previous week. Not one person, not ever, unless the story has recorded an Echo.',
      'The player never explains the loop to the reader. They already know.',
      'The week is fixed. Events happen at the hours they happen at unless the player changes them.',
      'The city ends at midnight on Sunday. Nothing the player has done has ever stopped that.',
      'The clock tower has been stopped at 11:59 for sixty years and the mechanism is intact.',
    ],
    toneGuide:
      'Warm, specific, coastal. Sunlight on wet pavement, cheap wine, a town that is genuinely nice to be in — ' +
      'which is what makes Sunday unbearable. People are ordinary and well drawn. The horror is structural, not ' +
      'gory: the same conversation happening again with only one person aware of it. Anime pacing — a whole loop ' +
      'can be a quiet one.',
    forkCostCredits: 120,
    loop: {
      startWorldMinute: at(MON, 8, 12),
      endWorldMinute: 7 * DAY,
      persistentFlagPrefixes: ['knows:', 'echo:', 'loop:'],
      echoRetention: 0.4,
      echoThreshold: 45,
      resetCopy:
        'The train is pulling in. Your bags are at your feet, both of them, packed the way you packed them. It is twelve minutes past eight on Monday morning, and Mina Arclight is walking down the platform towards you.',
    },
  },
  attributes: { might: 9, agility: 10, mind: 12, presence: 11, resolve: 11, arcana: 8 },
  skills: [
    { id: 'observation', name: 'Observation', attribute: 'mind', description: 'Noticing the thing that is different this time.' },
    { id: 'persuasion', name: 'Persuasion', attribute: 'presence', description: 'Getting someone to do something on your word alone.' },
    { id: 'deception', name: 'Deception', attribute: 'presence', description: 'Knowing something you should not, convincingly.' },
    { id: 'nerve', name: 'Nerve', attribute: 'resolve', description: 'Doing it anyway on the fourth attempt.' },
    { id: 'research', name: 'Research', attribute: 'mind', description: 'Records, archives, and what a town writes down about itself.' },
    { id: 'legwork', name: 'Legwork', attribute: 'agility', description: 'Following someone, and getting across town in time.' },
    { id: 'rapport', name: 'Rapport', attribute: 'presence', description: 'Being easy to talk to, which is its own kind of key.' },
    { id: 'mechanism', name: 'Mechanism', attribute: 'mind', description: 'Clocks, locks, and things that were built to keep time.' },
  ],
  resources: [
    {
      id: 'energy',
      name: 'Energy',
      max: 100,
      start: 100,
      regenPerHour: 5,
      polarity: 'GOOD_HIGH',
      displayPriority: 1,
      visible: true,
      zeroStateConsequence: 'You are running on nothing. The week is long.',
      color: '#4AB0E8',
    },
    {
      id: 'strain',
      name: 'Strain',
      max: 100,
      start: 0,
      regenPerHour: -2,
      polarity: 'GOOD_LOW',
      displayPriority: 2,
      visible: true,
      zeroStateConsequence: 'Steady. This is the first week, as far as your body is concerned.',
      color: '#B14A6C',
    },
  ],
  items: [
    {
      id: 'two_bags',
      name: 'Two Bags',
      tags: ['quest'],
      questItem: true,
      droppable: false,
      description: 'Everything you brought. You have unpacked them eleven times and it takes forty minutes.',
      loreText: 'The blue one has a broken zip. It has always had a broken zip.',
      icon: 'bag',
    },
    {
      id: 'room_key',
      name: 'Room Key, No. 4',
      tags: ['key'],
      description: 'Brass, worn smooth, on a wooden fob with the number burned into it.',
      icon: 'key',
    },
    {
      id: 'notebook',
      name: 'A Notebook',
      tags: ['tool'],
      skillModifiers: { research: 1, observation: 1 },
      description: 'You buy it from the newsagent on Monday. It is blank again every Monday and you buy it anyway.',
      loreText: 'Writing it down does not help. Doing it makes you feel like a person who is working on something.',
      icon: 'book',
    },
    {
      id: 'marina_ledger',
      name: 'The Marina Ledger',
      tags: ['quest', 'document'],
      questItem: true,
      droppable: false,
      description: 'Berth records for sixty years. The page for the week of the tower stopping has been cut out with a blade.',
      icon: 'ledger',
    },
    {
      id: 'tower_key',
      name: 'The Tower Key',
      tags: ['key', 'quest'],
      questItem: true,
      droppable: false,
      description: 'Iron, eight inches, and far too heavy for the door it opens.',
      loreText: 'Elias keeps it on a string around his neck and has never once used it.',
      icon: 'key',
    },
    {
      id: 'good_bottle',
      name: 'A Good Bottle',
      tags: ['gift'],
      stackable: true,
      maxStack: 2,
      consumable: { resourceId: 'strain', amount: 12, consumesItem: true },
      description: 'The one from the shop on the esplanade that everybody says is overpriced and everybody buys.',
      icon: 'bottle',
    },
    {
      id: 'ivys_coat',
      name: 'A Coat Left on a Bench',
      tags: ['quest'],
      questItem: true,
      droppable: false,
      description: 'Green, good quality, folded. It is on the bench at the Point every Thursday morning and nobody collects it.',
      icon: 'coat',
    },
  ],
  abilities: [
    {
      id: 'take_it_in',
      name: 'Take It In',
      tags: ['utility', 'observation'],
      description: 'Stop, and look properly at what is in front of you. Things you have walked past six times start being visible.',
      affordances: ['take it in', 'look around properly', 'study the room', 'look for what changed'],
      costs: [{ resourceId: 'energy', amount: 3 }],
      cooldownMinutes: 0,
      targetRule: 'NONE',
      check: { attribute: 'mind', skillId: 'observation', baseDc: 12 },
      unlockedByDefault: true,
    },
    {
      id: 'say_the_impossible',
      name: 'Say the Impossible Thing',
      tags: ['social'],
      description: 'Tell someone something you cannot possibly know. It either buys you everything or it costs you them.',
      affordances: ['tell them what happens', 'say the impossible thing', 'prove it to them', 'tell them about the loop'],
      costs: [{ resourceId: 'strain', amount: 10 }],
      cooldownMinutes: 60,
      targetRule: 'SINGLE',
      check: { attribute: 'presence', skillId: 'persuasion', baseDc: 15 },
      unlockedByDefault: true,
    },
    {
      id: 'be_somewhere_first',
      name: 'Be Somewhere First',
      tags: ['utility'],
      description: 'You know when this happens. Get there before it does and stand in the way of it.',
      affordances: ['get there first', 'wait for it to happen', 'be there before them', 'head it off'],
      costs: [{ resourceId: 'energy', amount: 8 }],
      cooldownMinutes: 30,
      targetRule: 'NONE',
      check: { attribute: 'agility', skillId: 'legwork', baseDc: 13 },
      unlockedByDefault: true,
    },
    {
      id: 'read_the_mechanism',
      name: 'Read the Mechanism',
      tags: ['utility', 'mechanism'],
      description: 'Escapement, train, weight. What this was built to do, and what has been done to it since.',
      affordances: ['read the mechanism', 'look at the clockwork', 'examine the movement', 'work out how it runs'],
      costs: [{ resourceId: 'energy', amount: 6 }],
      cooldownMinutes: 0,
      targetRule: 'SINGLE',
      check: { attribute: 'mind', skillId: 'mechanism', baseDc: 14 },
      unlockedByDefault: false,
      requires: {
        flagsSet: ['knows:tower_matters'],
        lockedCopy: 'It is a very large clock and you have no idea what you are looking at.',
      },
    },
    {
      id: 'the_long_way_round',
      name: 'The Long Way Round',
      tags: ['social'],
      description: 'Do not tell them. Arrange for them to find out, from someone they already believe.',
      affordances: ['arrange it', 'get someone else to tell them', 'set it up', 'work it so they find out'],
      costs: [{ resourceId: 'energy', amount: 10 }, { resourceId: 'strain', amount: 5 }],
      cooldownMinutes: 120,
      targetRule: 'SINGLE',
      check: { attribute: 'mind', skillId: 'deception', baseDc: 14 },
      unlockedByDefault: false,
      requires: {
        flagsSet: ['knows:the_week'],
        lockedCopy: 'You do not know enough about this week yet to arrange anything in it.',
      },
    },
  ],
  locations: [
    {
      id: 'the_platform',
      name: 'Halcyon Bay Station',
      shortName: 'The Station',
      description:
        'One platform, a canopy with a hole in it, and a view straight down the hill to the water. The 8:12 comes in and about nine people get off it.',
      artDirection:
        'Small coastal railway station in bright morning light. Iron canopy, peeling paint, hanging baskets, the sea visible below and beyond. Warm, ordinary, slightly faded seaside town.',
      connections: [
        { to: 'the_esplanade', travelMinutes: 12, label: 'Down to the front' },
        { to: 'boarding_house', travelMinutes: 9, label: 'To the boarding house' },
      ],
      discoveredByDefault: true,
      mapPosition: { x: 0, y: -2 },
    },
    {
      id: 'the_esplanade',
      name: 'The Esplanade',
      shortName: 'The Front',
      description:
        'A curve of shopfronts facing the water. A newsagent, a wine shop everyone complains about, three cafes, and benches that are always full by ten.',
      artDirection:
        'Seafront promenade with painted Victorian shopfronts, awnings, bicycles, people at outdoor tables. Bright, busy, salt-bleached colours.',
      connections: [
        { to: 'the_platform', travelMinutes: 12, label: 'Up to the station' },
        { to: 'the_marina', travelMinutes: 8, label: 'Along to the marina' },
        { to: 'boarding_house', travelMinutes: 6, label: 'The boarding house' },
        { to: 'the_library', travelMinutes: 10, label: 'Up to the library' },
      ],
      discoveredByDefault: true,
      mapPosition: { x: 0, y: 0 },
      takeableItems: [
        { itemId: 'good_bottle', qty: 1, ownerId: null, aka: ['bottle', 'wine', 'a bottle of wine'] },
        { itemId: 'notebook', qty: 1, ownerId: null, aka: ['notebook', 'a notebook', 'notepad'] },
      ],
    },
    {
      id: 'boarding_house',
      name: 'The Boarding House',
      shortName: 'The House',
      description:
        'Four rooms, a landlady who does not ask questions, and a kitchen you are allowed to use until nine. Your room is number four and looks over the yard.',
      artDirection:
        'Interior of a small seaside guesthouse. Patterned carpet, brass fittings, a narrow staircase, net curtains. Homely and slightly airless.',
      connections: [
        { to: 'the_esplanade', travelMinutes: 6, label: 'Down to the front' },
        { to: 'the_platform', travelMinutes: 9, label: 'Up to the station' },
        { to: 'the_old_town', travelMinutes: 11, label: 'Into the old town' },
      ],
      discoveredByDefault: true,
      mapPosition: { x: -1, y: -1 },
    },
    {
      id: 'the_marina',
      name: 'The Marina',
      shortName: 'The Marina',
      description:
        'Eighty berths, maybe thirty of them used. The office is a portacabin with sixty years of paperwork in it and a lock a child could open.',
      artDirection:
        'Small working marina. Masts, rope, a portacabin office, gulls, oily water. Overcast, functional, unglamorous.',
      connections: [
        { to: 'the_esplanade', travelMinutes: 8, label: 'Back along the front' },
        { to: 'the_point', travelMinutes: 20, label: 'Out to the Point' },
      ],
      discoveredByDefault: true,
      mapPosition: { x: 1, y: 1 },
      takeableItems: [
        { itemId: 'marina_ledger', qty: 1, ownerId: null, aka: ['ledger', 'the records', 'the book', 'berth records'] },
      ],
    },
    {
      id: 'the_library',
      name: 'The Public Library',
      shortName: 'The Library',
      description:
        'One room upstairs above the old assembly hall. Local history in the back, three tables, and a boy who is always at the middle one.',
      artDirection:
        'Small municipal library room. Dark wood shelves, high windows, dust in the light, a single occupied reading table. Quiet and warm.',
      connections: [
        { to: 'the_esplanade', travelMinutes: 10, label: 'Down to the front' },
        { to: 'the_clock_tower', travelMinutes: 14, label: 'Up the hill' },
        { to: 'council_hall', travelMinutes: 7, label: 'The council hall' },
      ],
      discoveredByDefault: true,
      mapPosition: { x: 0, y: 1 },
    },
    {
      id: 'the_clock_tower',
      name: 'The Clock Tower',
      shortName: 'The Tower',
      description:
        'Top of the hill, ninety feet, and stopped at 11:59 since before anybody alive was born. The mechanism inside is oiled and turning and connected to nothing.',
      artDirection:
        'Stone clock tower on a hilltop above a coastal town, hands stopped near midnight. Interior: an enormous brass clock movement, perfectly maintained, turning silently.',
      connections: [
        { to: 'the_library', travelMinutes: 14, label: 'Down to the library' },
        { to: 'the_old_town', travelMinutes: 9, label: 'Down into the old town' },
      ],
      discoveredByDefault: true,
      mapPosition: { x: 0, y: 3 },
    },
    {
      id: 'the_old_town',
      name: 'The Old Town',
      shortName: 'Old Town',
      description:
        'Six streets of stone cottages above the front, most of them holiday lets. The ones that are not have the same family name on the door as the ones in the churchyard.',
      artDirection:
        'Narrow steep streets of old stone cottages, washing lines, cats, steps everywhere, glimpses of sea between buildings.',
      connections: [
        { to: 'boarding_house', travelMinutes: 11, label: 'Down to the house' },
        { to: 'the_clock_tower', travelMinutes: 9, label: 'Up to the tower' },
      ],
      discoveredByDefault: true,
      mapPosition: { x: -1, y: 2 },
    },
    {
      id: 'council_hall',
      name: 'The Council Hall',
      shortName: 'The Hall',
      description:
        'Municipal, 1890s, and much too big for a town this size. Somebody built it expecting Halcyon Bay to become something.',
      artDirection:
        'Grand disused Victorian municipal hall, marble floor, portraits, too much space for too few people. Cold light.',
      connections: [{ to: 'the_library', travelMinutes: 7, label: 'To the library' }],
      discoveredByDefault: true,
      mapPosition: { x: 1, y: 2 },
    },
    {
      id: 'the_point',
      name: 'The Point',
      shortName: 'The Point',
      description:
        'The headland past the marina. A bench, a path, and a view of the whole city from the water side. People come here to be somewhere else.',
      artDirection:
        'Windswept coastal headland with a single bench, long grass, the town visible across the bay. Beautiful, exposed, lonely.',
      connections: [{ to: 'the_marina', travelMinutes: 20, label: 'Back to the marina' }],
      discoveredByDefault: true,
      mapPosition: { x: 2, y: 0 },
      takeableItems: [
        { itemId: 'ivys_coat', qty: 1, ownerId: 'ivy', aka: ['coat', 'the green coat', 'a coat'] },
      ],
    },
  ],
  factions: [
    {
      id: 'faction_town',
      name: 'Halcyon Bay',
      description: 'The town itself: who knows your name, who nods at you in the shop, and who has started to think you are strange.',
      startingReputation: 0,
      ranks: [
        { atReputation: -100, label: 'That one' },
        { atReputation: 0, label: 'New here' },
        { atReputation: 20, label: 'Known' },
        { atReputation: 45, label: 'One of us' },
      ],
    },
    {
      id: 'faction_believers',
      name: 'People Who Believe You',
      description: 'Everyone who has been convinced, this loop, that the week has happened before. It is almost never more than one.',
      startingReputation: 0,
      ranks: [
        { atReputation: 0, label: 'Nobody' },
        { atReputation: 15, label: 'One person' },
        { atReputation: 40, label: 'Enough to matter' },
      ],
    },
  ],
  characters: [
    {
      id: 'mina',
      name: 'Mina Arclight',
      role: 'The first person you meet, every Monday',
      cardBlurb: 'She walks up to you on the platform and decides to show you around, every single week, and on Sunday night she is the one person you can never find.',
      pronouns: 'she/her',
      publicTraits: ['Warm', 'Direct', 'Genuinely pleased to see you'],
      hiddenDrives: ['She has been trying to leave Halcyon Bay for four years and something always stops her'],
      values: ['Being kind first', 'The people who stayed', 'Not making a fuss'],
      fears: ['Being the reason somebody stays', 'The tower'],
      socialStyle: 'Asks you three questions before you have asked her one.',
      boundaries: ['Will not talk about her father', 'Will not go up to the tower after dark'],
      goals: ['Get through the season', 'Actually get on a train this time'],
      secrets: [
        {
          id: 'mina_goes_to_the_tower',
          fact: 'At half past nine on Sunday Mina goes up to the clock tower on her own. She does it every week and does not know why she does it.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Trust 45+, or the player follows her on a Sunday and asks her about it after a reset.',
        },
        {
          id: 'mina_father_wound_it',
          fact: 'Mina’s father was the last keeper of the tower. He stopped it, on purpose, sixty years is wrong — it was eleven years ago and the town remembers it as sixty.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Late. Only after the player has the ledger or has read the mechanism.',
        },
      ],
      speechStyle: 'Quick, warm, full of small specifics about the town. Deflects with a joke exactly once.',
      topics: ['the town', 'the tower', 'her father', 'Sunday', 'leaving'],
      voiceSamples: [
        'You look like someone who has not eaten since the train. Come on.',
        'Everyone says the wine shop is a rip-off. Everyone buys the wine.',
        'I am not going up there. Not tonight. Ask me anything else.',
      ],
      appearance: 'Late twenties, dark curls pinned badly, a coat too warm for the weather.',
      visualHook: 'A brass pocket-watch on a chain, worn outside her coat, that does not run.',
      silhouette: 'Hands in pockets, walking slightly too fast, always half a step ahead of you.',
      artSeed: 'seven_days_mina_v1',
      expressions: ['neutral', 'delighted', 'evasive', 'frightened'],
      schedule: [
        { startMinute: 480, endMinute: 540, locationId: 'the_platform', activity: 'Meeting the 8:12' },
        { startMinute: 540, endMinute: 780, locationId: 'the_esplanade', activity: 'The cafe she works at' },
        { startMinute: 780, endMinute: 1020, locationId: 'the_esplanade', activity: 'The afternoon shift' },
        { startMinute: 1020, endMinute: 1320, locationId: 'the_old_town', activity: 'Home, with the door open' },
        { startMinute: 1320, endMinute: 1440, locationId: 'the_old_town', activity: 'Asleep, badly' },
      ],
      homeLocationId: 'the_old_town',
      knowledgeScope: ['the town', 'the tower', 'her father'],
      startingRelationship: { trust: 20, affection: 25, respect: 10, fear: 0, rivalry: 0 },
      gates: [
        { id: 'mina_tells_you', label: 'She tells you about Sunday night', kind: 'TRUST', requires: { trust: 45, flagsSet: ['spoke:mina'] } },
        { id: 'mina_romance', label: 'Something that neither of you will remember', kind: 'ROMANCE', requires: { trust: 55, affection: 60 } },
      ],
      attributes: { might: 9, agility: 11, mind: 13, presence: 15, resolve: 12, arcana: 9 },
      combatant: { health: 30, defenseDc: 12, damage: 3, tags: ['civilian'] },
    },
    {
      id: 'theo',
      name: 'Theo Marr',
      role: 'The boy at the middle table',
      cardBlurb: 'He is in the library every day and notices everything, including the fact that you already know where things are.',
      pronouns: 'he/him',
      publicTraits: ['Sarcastic', 'Observant', 'Lonely about it'],
      hiddenDrives: ['He wants to be taken seriously by exactly one adult'],
      values: ['Being right', 'Saying the awkward thing', 'People who do not talk down to him'],
      fears: ['Being humoured', 'Being wrong out loud'],
      socialStyle: 'Opens with something rude to see whether you leave.',
      boundaries: ['Will not be patronised', 'Will not be used'],
      goals: ['Work out what is wrong with this town', 'Get out of it'],
      secrets: [
        {
          id: 'theo_has_a_list',
          fact: 'Theo keeps a list of things in Halcyon Bay that do not add up. There are nineteen items and four of them are correct.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Trust 30+, or if the player tells him something he has already written down.',
        },
      ],
      speechStyle: 'Dry, fast, twelve words where three would do, and occasionally exactly right.',
      topics: ['the town', 'the tower', 'his list', 'the newspaper archive', 'you'],
      voiceSamples: [
        'You have been in here four times and never once looked at a shelf.',
        'I am not saying it is impossible. I am saying you said it like a person reading it off something.',
        'Go on then. Tell me what happens on Thursday.',
      ],
      appearance: 'Seventeen, thin, a school coat he has clearly outgrown.',
      visualHook: 'A red spiral notebook he never lets anybody see the inside of.',
      silhouette: 'Hunched over a table with everything spread out too far.',
      artSeed: 'seven_days_theo_v1',
      expressions: ['neutral', 'sceptical', 'delighted', 'shaken'],
      schedule: [
        { startMinute: 480, endMinute: 900, locationId: 'the_library', activity: 'The middle table' },
        { startMinute: 900, endMinute: 1080, locationId: 'the_esplanade', activity: 'Not going home' },
        { startMinute: 1080, endMinute: 1320, locationId: 'the_library', activity: 'Back at the table' },
        { startMinute: 1320, endMinute: 1440, locationId: 'the_old_town', activity: 'Home eventually' },
      ],
      homeLocationId: 'the_library',
      knowledgeScope: ['the town', 'the archive', 'his list'],
      startingRelationship: { trust: 0, affection: 0, respect: 5, fear: 0, rivalry: 0 },
      gates: [
        { id: 'theo_believes', label: 'He decides you are not making it up', kind: 'TRUST', requires: { trust: 40, flagsSet: ['spoke:theo'] } },
      ],
      attributes: { might: 8, agility: 11, mind: 16, presence: 10, resolve: 11, arcana: 9 },
      combatant: { health: 24, defenseDc: 11, damage: 2, tags: ['civilian'] },
    },
    {
      id: 'wynn',
      name: 'Detective Sera Wynn',
      role: 'Investigating something that has not happened yet',
      cardBlurb: 'She arrives on Wednesday to investigate a disappearance you have already watched happen, and she will want to know how you knew.',
      pronouns: 'she/her',
      publicTraits: ['Methodical', 'Tired', 'Not unkind'],
      hiddenDrives: ['She has been given this case specifically because it will go nowhere'],
      values: ['The file being right', 'Not guessing', 'People who answer the question asked'],
      fears: ['Being made a fool of', 'Another one going cold'],
      socialStyle: 'Writes down what you say while you are saying it.',
      boundaries: ['Will not discuss an open case', 'Will not be lied to twice'],
      goals: ['Find Ivy Sable', 'Get back to the mainland'],
      secrets: [
        {
          id: 'wynn_has_four_files',
          fact: 'Wynn has four files. Four people have gone missing from Halcyon Bay on a Wednesday, in four separate years, and all four coats were found folded on the same bench.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Trust 40+, or the player produces the coat before Thursday.',
        },
      ],
      speechStyle: 'Flat, procedural, and every so often startlingly human.',
      topics: ['the disappearance', 'Ivy Sable', 'the coat', 'her four files', 'the town'],
      voiceSamples: [
        'When did you arrive. Be exact.',
        'You have told me something I have not released. I would like you to explain that.',
        'I have four of these. I would very much like it to be three.',
      ],
      appearance: 'Forties, sensible coat, hair tied back the same way every day.',
      visualHook: 'A cardboard document wallet she carries everywhere, tied with string.',
      silhouette: 'Upright, hands full, always slightly in the way.',
      artSeed: 'seven_days_wynn_v1',
      expressions: ['neutral', 'sharp', 'weary'],
      schedule: [
        { startMinute: 540, endMinute: 780, locationId: 'council_hall', activity: 'The room they gave her' },
        { startMinute: 780, endMinute: 1080, locationId: 'the_marina', activity: 'Asking around the berths' },
        { startMinute: 1080, endMinute: 1260, locationId: 'the_esplanade', activity: 'Interviews, in cafes' },
        { startMinute: 1260, endMinute: 1440, locationId: 'council_hall', activity: 'Writing it all up' },
      ],
      homeLocationId: 'council_hall',
      knowledgeScope: ['the disappearance', 'four files', 'police procedure'],
      startingRelationship: { trust: 0, affection: 0, respect: 5, fear: 0, rivalry: 0 },
      gates: [
        { id: 'wynn_shares', label: 'She shows you the other three files', kind: 'TRUST', requires: { trust: 40, flagsSet: ['spoke:wynn'] } },
      ],
      attributes: { might: 11, agility: 11, mind: 15, presence: 13, resolve: 14, arcana: 8 },
      combatant: { health: 40, defenseDc: 14, damage: 6, tags: ['police'] },
    },
    {
      id: 'elias',
      name: 'Elias Crowe',
      role: 'The man everyone says is unwell',
      cardBlurb: 'Everyone tells you he is unwell. He has measured that clock for nine years and he is the only person here who is right about anything.',
      pronouns: 'he/him',
      publicTraits: ['Intense', 'Exhausted', 'Precise'],
      hiddenDrives: ['He needs one other person to see the numbers'],
      values: ['The measurement', 'Not lying about data', 'Being believed once'],
      fears: ['Being sectioned', 'Being right'],
      socialStyle: 'Talks at speed about the middle of something and does not go back to the start.',
      boundaries: ['Will not let anyone touch the movement', 'Will not go up on a Sunday'],
      goals: ['Finish the measurement', 'Get somebody to look at the ledger'],
      secrets: [
        {
          id: 'elias_the_tower_runs',
          fact: 'The tower’s movement is turning. Elias has measured it for nine years. It is keeping time for something and the hands are not connected to it.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'He will tell literally anyone. Nobody has ever listened long enough.',
        },
        {
          id: 'elias_seven_days',
          fact: 'The movement completes a cycle every seven days, ending at midnight on Sunday. Elias has never worked out what it is counting.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Trust 35+, and only from someone who has asked a second question.',
        },
      ],
      speechStyle: 'Rapid, technical, oddly formal, and completely uninterested in whether you are following.',
      topics: ['the movement', 'the cycle', 'the ledger', 'Mina’s father', 'Sunday'],
      voiceSamples: [
        'It is turning. That is not a theory, it is a measurement, and I have nine years of it.',
        'Everybody stops listening at the third sentence. Please do not.',
        'Seven days. It resets. I do not know what it is counting and neither do you.',
      ],
      appearance: 'Thirties, unshaven, a coat with a notebook in every pocket.',
      visualHook: 'Fingertips permanently stained with clock oil, and a string round his neck with an iron key on it.',
      silhouette: 'Too still, then suddenly all at once.',
      artSeed: 'seven_days_elias_v1',
      expressions: ['neutral', 'urgent', 'vindicated', 'hollow'],
      schedule: [
        { startMinute: 420, endMinute: 720, locationId: 'the_clock_tower', activity: 'Measuring' },
        { startMinute: 720, endMinute: 900, locationId: 'the_library', activity: 'The local history shelf' },
        { startMinute: 900, endMinute: 1320, locationId: 'the_clock_tower', activity: 'Measuring again' },
        { startMinute: 1320, endMinute: 1440, locationId: 'the_old_town', activity: 'A room he does not sleep in' },
      ],
      homeLocationId: 'the_clock_tower',
      knowledgeScope: ['the movement', 'the cycle', 'the tower'],
      startingRelationship: { trust: 5, affection: 0, respect: 0, fear: 0, rivalry: 0 },
      gates: [
        { id: 'elias_shows_you', label: 'He takes you up to the movement', kind: 'TRUST', requires: { trust: 35, flagsSet: ['spoke:elias'] } },
      ],
      attributes: { might: 9, agility: 10, mind: 17, presence: 9, resolve: 13, arcana: 12 },
      combatant: { health: 28, defenseDc: 11, damage: 3, tags: ['civilian'] },
    },
    {
      id: 'ivy',
      name: 'Ivy Sable',
      role: 'The one who disappears on Wednesday',
      cardBlurb: 'You will meet her three times before you realise she is the woman whose coat is folded on the bench every Thursday morning.',
      pronouns: 'she/her',
      publicTraits: ['Quiet', 'Funny once she starts', 'Always slightly leaving'],
      hiddenDrives: ['She has decided to go and has not told anyone'],
      values: ['Not being a burden', 'The people at the marina', 'Doing it on her own terms'],
      fears: ['Being talked out of it', 'Being found'],
      socialStyle: 'Answers the question you asked and not the one you meant.',
      boundaries: ['Will not be followed', 'Will not explain herself twice'],
      goals: ['Get to Wednesday'],
      secrets: [
        {
          id: 'ivy_is_not_taken',
          fact: 'Nobody takes Ivy Sable. On Wednesday at half eleven she walks to the Point, folds her coat, and goes into the water.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'The player has to be there, or work out the pattern from Wynn’s four files.',
        },
      ],
      speechStyle: 'Sparse, dry, warmer than she means to be.',
      topics: ['the marina', 'the boats', 'leaving', 'the Point'],
      voiceSamples: [
        'You are new. That will wear off.',
        'I like it out at the Point. Nobody talks to you out there.',
        'Do not do that. Do not decide you are going to be the one who fixes something.',
      ],
      appearance: 'Fifties, weathered, a green coat that is much better than the rest of what she wears.',
      visualHook: 'The green coat itself — expensive, cared for, and folded on a bench every Thursday.',
      silhouette: 'Small, hands in pockets, standing where the wind is worst.',
      artSeed: 'seven_days_ivy_v1',
      expressions: ['neutral', 'dry', 'distant'],
      schedule: [
        { startMinute: 480, endMinute: 720, locationId: 'the_marina', activity: 'The boats' },
        { startMinute: 720, endMinute: 1080, locationId: 'the_marina', activity: 'The office, doing paperwork nobody asked for' },
        { startMinute: 1080, endMinute: 1260, locationId: 'the_esplanade', activity: 'One drink, alone' },
        { startMinute: 1260, endMinute: 1440, locationId: 'the_point', activity: 'The bench' },
      ],
      homeLocationId: 'the_marina',
      knowledgeScope: ['the marina', 'the boats'],
      startingRelationship: { trust: 5, affection: 0, respect: 5, fear: 0, rivalry: 0 },
      gates: [
        { id: 'ivy_talks', label: 'She tells you what she has decided', kind: 'TRUST', requires: { trust: 45, flagsSet: ['spoke:ivy'] } },
      ],
      attributes: { might: 10, agility: 10, mind: 13, presence: 11, resolve: 15, arcana: 8 },
      combatant: { health: 30, defenseDc: 12, damage: 4, tags: ['civilian'] },
    },
    {
      id: 'harrow',
      name: 'Councillor Ada Harrow',
      role: 'Arrives Thursday, leaves Friday',
      cardBlurb: 'She comes down on Thursday to sign something about the tower and is gone by Friday — the one person you have never found in the city on a Sunday.',
      pronouns: 'she/her',
      publicTraits: ['Polished', 'Impatient', 'Genuinely competent'],
      hiddenDrives: ['She knows exactly what the tower is and her family has been managing it for four generations'],
      values: ['Containment', 'The mainland', 'Nobody finding out'],
      fears: ['A public inquiry', 'Being the generation it fails under'],
      socialStyle: 'Gives you ninety seconds and makes them count.',
      boundaries: ['Will not discuss the tower', 'Will not stay past Friday'],
      goals: ['Sign the maintenance order', 'Be on the Friday train'],
      secrets: [
        {
          id: 'harrow_knows',
          fact: 'The Harrow family has paid for the tower’s upkeep for four generations. Ada knows what it does. She does not know how to stop it and has stopped trying.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Very late. Only to a player who can tell her something about Sunday that she has not told anyone.',
        },
      ],
      speechStyle: 'Clipped, courteous, entirely made of exits.',
      topics: ['the maintenance order', 'the tower', 'the mainland', 'her family'],
      voiceSamples: [
        'I have until four. What is this about.',
        'The tower is a listed structure and a line in a budget. That is all it is.',
        'Whoever told you that was mistaken. Repeatedly, by the sound of it.',
      ],
      appearance: 'Fifties, immaculate, entirely wrong for a seaside town.',
      visualHook: 'A signet ring with a clock face on it, worn on the right hand.',
      silhouette: 'Straight lines and a good coat, always already turning to go.',
      artSeed: 'seven_days_harrow_v1',
      expressions: ['neutral', 'impatient', 'guarded'],
      schedule: [
        { startMinute: 720, endMinute: 960, locationId: 'council_hall', activity: 'The maintenance order' },
        { startMinute: 960, endMinute: 1140, locationId: 'the_clock_tower', activity: 'The annual inspection' },
        { startMinute: 1140, endMinute: 1440, locationId: 'council_hall', activity: 'Not staying for dinner' },
      ],
      homeLocationId: 'council_hall',
      knowledgeScope: ['the tower', 'the maintenance order', 'her family'],
      startingRelationship: { trust: 0, affection: 0, respect: 0, fear: 0, rivalry: 0 },
      gates: [
        { id: 'harrow_admits', label: 'She stops pretending it is a budget line', kind: 'TRUST', requires: { trust: 40, flagsSet: ['knows:tower_matters'] } },
      ],
      attributes: { might: 9, agility: 10, mind: 16, presence: 16, resolve: 15, arcana: 10 },
      combatant: { health: 32, defenseDc: 13, damage: 4, tags: ['civilian'] },
    },
  ],
  quests: [
    {
      id: 'q_the_office',
      title: 'Ten O’Clock, Tuesday',
      summary: 'The marina office is robbed at ten on Tuesday night. You know that now.',
      kind: 'SIDE',
      startsActive: false,
      discoverWhen: { flagsSet: ['knows:theft_happened'] },
      involvedCharacterIds: ['elias', 'ivy'],
      involvedLocationIds: ['the_marina'],
      knownRewardCopy: 'A ledger that still has all of its pages in it.',
      steps: [
        {
          id: 'step_be_in_the_office',
          playerCopy: 'Be in the marina office before ten on Tuesday night.',
          directorNotes:
            'The first thing a player can take away from this week. Standing in the portacabin between eight and ' +
            'ten on Tuesday means Elias does not come in, and the page for the week the tower stopped stays in ' +
            'the book. He is not a thief and should not be written as one — he is a man who has been asking ' +
            'politely for nine years and has run out of polite.',
          succeedWhen: {
            flagsSet: [],
            flagsUnset: [],
            hasItems: [],
            atLocation: 'the_marina',
            completedEvents: [],
            minRelationship: [],
            minFactionReputation: [],
            afterWorldMinute: 2640,
            beforeWorldMinute: 2760,
          },
          rewards: {
            xp: 90,
            items: [],
            flags: ['stopped_the_theft', 'knows:elias_takes_the_page'],
            abilities: [],
            reputation: [],
          },
        },
      ],
    },
    {
      id: 'q_the_bench',
      title: 'Half Eleven, Wednesday',
      summary: 'A green coat is folded on the bench at the Point every Thursday morning. You know why now.',
      kind: 'SIDE',
      startsActive: false,
      discoverWhen: { flagsSet: ['knows:ivy_goes'] },
      involvedCharacterIds: ['ivy', 'wynn'],
      involvedLocationIds: ['the_point'],
      knownRewardCopy: 'Ivy Sable, on Thursday.',
      steps: [
        {
          id: 'step_be_on_the_bench',
          playerCopy: 'Be on the bench at the Point before half past eleven on Wednesday.',
          directorNotes:
            'Nobody takes Ivy Sable. Being there means she has to walk past somebody, and she does not. This is ' +
            'not a puzzle and it is not a rescue — she is a person who has decided something, and the player is ' +
            'a stranger on her bench. She will be furious. She will also still be alive on Thursday.',
          succeedWhen: {
            flagsSet: [],
            flagsUnset: [],
            hasItems: [],
            atLocation: 'the_point',
            completedEvents: [],
            minRelationship: [],
            minFactionReputation: [],
            afterWorldMinute: 4140,
            beforeWorldMinute: 4290,
          },
          rewards: {
            xp: 110,
            items: [],
            flags: ['ivy_stopped', 'knows:why_ivy_goes'],
            abilities: [],
            reputation: [{ factionId: 'faction_town', amount: 10 }],
          },
        },
      ],
    },
    {
      id: 'q_the_week',
      title: 'Learn the Week',
      summary: 'Seven days happen the same way every time. Find out what they are.',
      kind: 'MAIN',
      startsActive: true,
      involvedCharacterIds: ['mina', 'theo', 'elias', 'wynn'],
      involvedLocationIds: ['the_platform', 'the_esplanade', 'the_library', 'the_marina'],
      knownRewardCopy: 'A week you can predict, which is a week you can take apart.',
      steps: [
        {
          id: 'step_see_it_happen',
          playerCopy: 'Find out what this week does when you leave it alone.',
          directorNotes:
            'The first loop is meant to be spent, not won. Anything the player does that puts them in front of ' +
            'one of the fixed events counts. Do not push them toward the tower; let them find whichever thread ' +
            'they find. A player who spends the whole week in a cafe with Mina has still learned something.',
          succeedWhenAny: [
            {
              routeId: 'week_by_theft',
              label: 'You were in the marina office when it was robbed',
              predicate: {
                flagsSet: ['knows:theft_happened'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:the_week', 'saw_a_fixed_event'],
              closesFlags: [],
            },
            {
              routeId: 'week_by_ivy',
              label: 'You found the coat on the bench',
              predicate: {
                flagsSet: ['knows:ivy_goes'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:the_week', 'saw_a_fixed_event'],
              closesFlags: [],
            },
            {
              routeId: 'week_by_clocks',
              label: 'You noticed every clock in town go wrong at once',
              predicate: {
                flagsSet: ['knows:clocks_slip'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:the_week', 'saw_a_fixed_event'],
              closesFlags: [],
            },
            {
              routeId: 'week_by_the_end',
              label: 'You got all the way to midnight',
              predicate: {
                flagsSet: ['knows:the_ending'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:the_week', 'saw_the_ending'],
              closesFlags: [],
            },
          ],
          rewards: {
            xp: 80,
            items: [{ itemId: 'notebook', qty: 1 }],
            flags: [],
            abilities: ['the_long_way_round'],
            reputation: [],
          },
        },
        {
          id: 'step_change_one',
          playerCopy: 'Change something that always happens.',
          directorNotes:
            'The moment this becomes a game rather than a story. The player has to be somewhere before an event ' +
            'and stop it. Two are reachable early — standing in the marina office before ten on Tuesday, and ' +
            'being on the bench at the Point before half eleven on Wednesday. Both should feel like the player ' +
            'beat the world rather than like the world let them.',
          enterWhen: { flagsSet: ['knows:the_week'] },
          succeedWhenAny: [
            {
              routeId: 'changed_theft',
              label: 'The ledger was still whole on Wednesday',
              predicate: {
                flagsSet: ['stopped_the_theft'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:it_can_change', 'changed_something'],
              closesFlags: [],
            },
            {
              routeId: 'changed_ivy',
              label: 'The coat was not on the bench',
              predicate: {
                flagsSet: ['ivy_stopped'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:it_can_change', 'changed_something', 'ivy_alive'],
              closesFlags: [],
            },
          ],
          rewards: {
            xp: 140,
            items: [],
            flags: [],
            abilities: [],
            reputation: [{ factionId: 'faction_town', amount: 10 }],
          },
        },
      ],
    },
    {
      id: 'q_the_tower',
      title: 'The Clock That Is Not Connected',
      summary: 'The tower has been stopped for sixty years and the mechanism inside it has never stopped turning.',
      kind: 'MAIN',
      startsActive: false,
      discoverWhen: { flagsSet: ['spoke:elias'] },
      involvedCharacterIds: ['elias', 'mina', 'harrow'],
      involvedLocationIds: ['the_clock_tower', 'the_library', 'council_hall'],
      knownRewardCopy: 'What the tower is counting.',
      steps: [
        {
          id: 'step_listen_to_elias',
          playerCopy: 'Let the man everyone avoids finish a sentence.',
          directorNotes:
            'Everybody in Halcyon Bay stops listening to Elias at the third sentence. The whole step is: do not. ' +
            'He is right, he has nine years of measurements, and he has never once been asked a second question.',
          succeedWhenAny: [
            {
              routeId: 'elias_by_listening',
              label: 'You asked him a second question',
              predicate: {
                flagsSet: ['spoke:elias'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'elias', dimension: 'trust', value: 35 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:tower_matters', 'elias_has_an_ally'],
              closesFlags: [],
            },
            {
              routeId: 'elias_by_the_clocks',
              label: 'You told him about the clocks on Saturday',
              predicate: {
                flagsSet: ['spoke:elias', 'knows:clocks_slip'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:tower_matters', 'elias_vindicated'],
              closesFlags: [],
            },
            {
              routeId: 'elias_by_the_ledger',
              label: 'You brought him the page he was going to steal',
              predicate: {
                flagsSet: ['spoke:elias'],
                flagsUnset: [],
                hasItems: ['marina_ledger'],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:tower_matters', 'elias_owes_you'],
              closesFlags: ['knows:theft_happened'],
            },
          ],
          rewards: {
            xp: 100,
            items: [{ itemId: 'tower_key', qty: 1 }],
            flags: [],
            abilities: ['read_the_mechanism'],
            reputation: [],
          },
        },
        {
          id: 'step_what_it_counts',
          playerCopy: 'Work out what the movement is counting.',
          directorNotes:
            'Seven days, ending at midnight on Sunday. The reveal is not that the tower causes the loop — it is ' +
            'that the tower is running the loop, and has been holding something off for sixty years by doing it. ' +
            'Do not let anybody say that out loud before the player has earned it.',
          enterWhen: { flagsSet: ['knows:tower_matters'] },
          succeedWhenAny: [
            {
              routeId: 'counted_by_reading',
              label: 'You read the movement yourself',
              predicate: {
                flagsSet: ['used:read_the_mechanism'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'the_clock_tower',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:the_cycle', 'read_it_yourself'],
              closesFlags: [],
            },
            {
              routeId: 'counted_by_harrow',
              label: 'You got the councillor to stop pretending',
              predicate: {
                flagsSet: ['spoke:harrow', 'knows:tower_matters'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'harrow', dimension: 'trust', value: 40 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:the_cycle', 'harrow_admitted_it'],
              closesFlags: [],
            },
            {
              routeId: 'counted_by_mina',
              label: 'Mina told you what her father did',
              predicate: {
                flagsSet: ['spoke:mina'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'mina', dimension: 'trust', value: 50 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:the_cycle', 'knows:minas_father'],
              closesFlags: [],
            },
          ],
          rewards: {
            xp: 200,
            items: [],
            flags: [],
            abilities: [],
            reputation: [{ factionId: 'faction_believers', amount: 20 }],
          },
        },
      ],
    },
    {
      id: 'q_make_someone_believe',
      title: 'Say the Impossible Thing',
      summary: 'You know what happens on Thursday. Telling someone is easy. Being believed is not.',
      kind: 'SIDE',
      startsActive: false,
      discoverWhen: { flagsSet: ['knows:the_week'] },
      involvedCharacterIds: ['theo', 'wynn', 'mina'],
      involvedLocationIds: ['the_library', 'council_hall', 'the_esplanade'],
      knownRewardCopy: 'One other person in Halcyon Bay who knows.',
      steps: [
        {
          id: 'step_convince',
          playerCopy: 'Get one person to believe you.',
          directorNotes:
            'Three people can be convinced and each takes something different. Theo wants a prediction he can ' +
            'check. Wynn wants a fact she has not released. Mina does not want evidence at all — she wants to be ' +
            'told by somebody she trusts, and she will believe it and be destroyed by it. Whoever it is forgets ' +
            'by Monday unless an Echo takes.',
          succeedWhenAny: [
            {
              routeId: 'believed_theo',
              label: 'Theo checked it and it happened',
              predicate: {
                flagsSet: ['spoke:theo', 'used:say_the_impossible'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'theo', dimension: 'trust', value: 40 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['someone_believes', 'echo:theo_believes'],
              closesFlags: [],
            },
            {
              routeId: 'believed_wynn',
              label: 'You told the detective something she had not released',
              predicate: {
                flagsSet: ['spoke:wynn', 'knows:ivy_goes'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'wynn', dimension: 'trust', value: 40 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['someone_believes', 'echo:wynn_believes'],
              closesFlags: [],
            },
            {
              routeId: 'believed_mina',
              label: 'Mina believed you because it was you',
              predicate: {
                flagsSet: ['spoke:mina', 'used:say_the_impossible'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'mina', dimension: 'trust', value: 55 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['someone_believes', 'echo:mina_believes'],
              closesFlags: [],
            },
          ],
          rewards: {
            xp: 160,
            items: [],
            flags: [],
            abilities: [],
            reputation: [{ factionId: 'faction_believers', amount: 20 }],
          },
        },
      ],
    },
    {
      id: 'q_the_last_hour',
      title: 'Half Past Nine on Sunday',
      summary: 'Mina puts her coat on and goes up the hill instead of down it. She has never been able to say why.',
      kind: 'MAIN',
      startsActive: false,
      discoverWhen: { flagsSet: ['knows:the_ending'] },
      involvedCharacterIds: ['mina', 'elias'],
      involvedLocationIds: ['the_old_town', 'the_clock_tower'],
      knownRewardCopy: 'Where Mina goes, and what the choice actually is.',
      steps: [
        {
          id: 'step_follow_her',
          playerCopy: 'Find out where Mina goes on Sunday night.',
          directorNotes:
            'Nothing in the world tells the player to do this. It is the most important thing they can do and ' +
            'they have to notice it themselves. She goes to the tower and she does not know why she goes.',
          succeedWhenAny: [
            {
              routeId: 'followed_her',
              label: 'You followed her up the hill',
              predicate: {
                flagsSet: ['knows:mina_goes_up'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'the_clock_tower',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:where_mina_goes', 'saw_her_at_the_tower'],
              closesFlags: [],
            },
            {
              routeId: 'asked_her_after',
              label: 'You asked her about it the following Monday',
              predicate: {
                flagsSet: ['spoke:mina', 'knows:mina_goes_up'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'mina', dimension: 'trust', value: 45 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:where_mina_goes', 'she_told_you_herself'],
              closesFlags: [],
            },
            {
              routeId: 'waited_at_the_top',
              label: 'You were already up there when she arrived',
              predicate: {
                flagsSet: ['knows:mina_goes_up', 'used:be_somewhere_first'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'the_clock_tower',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['knows:where_mina_goes', 'you_were_waiting'],
              closesFlags: [],
            },
          ],
          rewards: {
            xp: 220,
            items: [],
            flags: [],
            abilities: [],
            reputation: [{ factionId: 'faction_believers', amount: 15 }],
          },
        },
        {
          id: 'step_the_choice',
          playerCopy: 'Decide what to do about a loop that might be holding something back.',
          directorNotes:
            'The last question is not how to escape. It is whether to. Ending the loop ends the city with it; ' +
            'keeping it going means everyone lives this week forever and only the player knows. There is a third ' +
            'answer — hand it to someone who volunteers — and it is the worst thing the player can do to a friend.',
          enterWhen: { flagsSet: ['knows:where_mina_goes', 'knows:the_cycle'] },
          succeedWhenAny: [
            {
              routeId: 'ended_it',
              label: 'You stopped the movement',
              predicate: {
                flagsSet: ['knows:the_cycle', 'used:read_the_mechanism'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'the_clock_tower',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['resolved', 'ending_stopped_it'],
              closesFlags: ['ending_kept_it', 'ending_handed_it_on'],
            },
            {
              routeId: 'kept_it',
              label: 'You wound it and walked away',
              predicate: {
                flagsSet: ['knows:the_cycle'],
                flagsUnset: [],
                hasItems: ['tower_key'],
                atLocation: 'the_clock_tower',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['resolved', 'ending_kept_it'],
              closesFlags: ['ending_stopped_it', 'ending_handed_it_on'],
            },
            {
              routeId: 'handed_it_on',
              label: 'Somebody volunteered',
              predicate: {
                flagsSet: ['knows:the_cycle', 'someone_believes'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'mina', dimension: 'trust', value: 60 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['resolved', 'ending_handed_it_on'],
              closesFlags: ['ending_stopped_it', 'ending_kept_it'],
            },
          ],
          rewards: {
            xp: 400,
            items: [],
            flags: [],
            abilities: [],
            reputation: [],
          },
        },
      ],
    },
  ],
  worldEvents: [
    {
      id: 'arrival',
      atWorldMinute: 492,
      locationId: 'the_platform',
      publicCopy: 'The 8:12 pulls out behind you and Mina Arclight is walking down the platform with her hand already half up.',
      directorNotes:
        'Monday morning. She does this every week and has no idea she does. Whatever the player says, she is pleased to see them.',
      setsFlags: ['week_started'],
      cancelledByFlags: [],
      requiresFlags: [],
      movesCharacters: [],
    },
    {
      id: 'theo_in_the_library',
      atWorldMinute: 1200,
      locationId: 'the_library',
      publicCopy: 'The library is empty except for a boy at the middle table with everything spread out too far.',
      directorNotes:
        'Theo, where Theo always is. He notices anybody who comes in twice.',
      setsFlags: ['theo_at_table'],
      cancelledByFlags: [],
      requiresFlags: [],
      movesCharacters: [],
    },
    {
      id: 'elias_at_the_tower',
      atWorldMinute: 1980,
      locationId: 'the_clock_tower',
      publicCopy: 'Somebody is up at the tower with a notebook, taking a reading and writing it down without looking at the page.',
      directorNotes:
        'Elias, doing the thing he has done every Tuesday for nine years.',
      setsFlags: ['elias_measuring'],
      cancelledByFlags: [],
      requiresFlags: [],
      movesCharacters: [],
    },
    {
      id: 'the_marina_theft',
      atWorldMinute: 2760,
      locationId: 'the_marina',
      publicCopy: 'The portacabin door is open and somebody is going through sixty years of berth records with a torch in their teeth.',
      directorNotes:
        'The theft. It is Elias, and what he takes is the page for the week the tower stopped. If the player is standing in the office at ten he does not do it, and the ledger stays whole — which is the first thing they can change.',
      setsFlags: ['knows:theft_happened', 'ledger_page_gone'],
      cancelledByFlags: ['stopped_the_theft'],
      requiresFlags: [],
      movesCharacters: [],
    },
    {
      id: 'wynn_arrives',
      atWorldMinute: 3540,
      locationId: 'council_hall',
      publicCopy: 'A woman in a sensible coat is being shown into the small room at the back of the council hall, carrying a document wallet tied with string.',
      directorNotes:
        'Detective Wynn, arriving to investigate a disappearance that has not happened yet. She does not find that strange because as far as she knows it has.',
      setsFlags: ['wynn_in_town'],
      cancelledByFlags: [],
      requiresFlags: [],
      movesCharacters: [{ characterId: 'wynn', toLocationId: 'council_hall' }],
    },
    {
      id: 'ivy_at_the_point',
      atWorldMinute: 4290,
      locationId: 'the_point',
      publicCopy: 'There is a green coat folded on the bench at the Point, and nobody near it.',
      directorNotes:
        'Ivy Sable. Nobody takes her — she walks out here, folds her coat, and goes into the water. If the player is on the bench before half eleven she does not, and everything about Thursday changes.',
      setsFlags: ['knows:ivy_goes', 'ivy_gone'],
      cancelledByFlags: ['ivy_stopped'],
      requiresFlags: [],
      movesCharacters: [{ characterId: 'ivy', toLocationId: 'the_point' }],
    },
    {
      id: 'harrow_arrives',
      atWorldMinute: 5040,
      locationId: 'council_hall',
      publicCopy: 'A car nobody in Halcyon Bay owns pulls up outside the council hall and a woman gets out of it who is entirely wrong for the town.',
      directorNotes:
        'Councillor Harrow, down from the mainland to sign the maintenance order for the tower. She is the only person who is never here on Sunday.',
      setsFlags: ['knows:harrow_comes', 'harrow_in_town'],
      cancelledByFlags: [],
      requiresFlags: [],
      movesCharacters: [{ characterId: 'harrow', toLocationId: 'council_hall' }],
    },
    {
      id: 'mina_and_elias',
      atWorldMinute: 5580,
      locationId: 'the_old_town',
      publicCopy: 'Mina is on the steps outside her house talking to the man from the tower, and both of them stop when they see you.',
      directorNotes:
        'They meet on Thursday night, every week. He is asking her about her father. She does not want to talk about it and comes anyway.',
      setsFlags: ['knows:mina_meets_elias'],
      cancelledByFlags: [],
      requiresFlags: [],
      movesCharacters: [],
    },
    {
      id: 'the_harbour_row',
      atWorldMinute: 6840,
      locationId: 'the_marina',
      publicCopy: 'There is shouting down at the berths — the detective and the man from the tower, and the detective is holding a notebook that is not hers.',
      directorNotes:
        'Wynn has worked out the ledger page is missing and has got to Elias. It goes badly and it goes public. If the theft never happened this does not either.',
      setsFlags: ['knows:the_row'],
      cancelledByFlags: ['stopped_the_theft'],
      requiresFlags: ['ledger_page_gone'],
      movesCharacters: [],
    },
    {
      id: 'the_tower_at_three',
      atWorldMinute: 7380,
      locationId: null,
      publicCopy: 'Every clock in Halcyon Bay is one minute slow, and yours is the only one that was right when you checked it at midnight.',
      directorNotes:
        'The movement completes something at three on Saturday morning. The whole town experiences it as a minor irritation. It is the loudest clue in the world and nobody ever notices it.',
      setsFlags: ['knows:clocks_slip'],
      cancelledByFlags: [],
      requiresFlags: [],
      movesCharacters: [],
    },
    {
      id: 'the_festival',
      atWorldMinute: 8340,
      locationId: 'the_esplanade',
      publicCopy: 'The front is strung with lights and half the town is out. Somebody has set up a band that is not very good and nobody minds.',
      directorNotes:
        'The Saturday festival. Warm, ordinary, lovely. This is the scene that makes Sunday land, and it should be played completely straight.',
      setsFlags: ['knows:festival'],
      cancelledByFlags: [],
      requiresFlags: [],
      movesCharacters: [],
    },
    {
      id: 'mina_goes_up',
      atWorldMinute: 9930,
      locationId: 'the_old_town',
      publicCopy: 'Mina says something about needing air, puts her coat on, and goes up the hill instead of down it.',
      directorNotes:
        'Half nine on Sunday. She goes to the tower. She has never been able to say why. Following her is the single most important thing a player can do and nothing in the world tells them to.',
      setsFlags: ['knows:mina_goes_up'],
      cancelledByFlags: [],
      requiresFlags: [],
      movesCharacters: [{ characterId: 'mina', toLocationId: 'the_clock_tower' }],
    },
    {
      id: 'the_end',
      atWorldMinute: 10079,
      locationId: null,
      publicCopy: 'Every clock in the city strikes at once, including the one that has been stopped for sixty years.',
      directorNotes:
        'One minute to midnight. The end of the world, from wherever the player is standing. Do not explain it. Light, sound, water up the hill. The turn after this one is Monday morning.',
      setsFlags: ['knows:the_ending'],
      cancelledByFlags: [],
      requiresFlags: [],
      movesCharacters: [],
    },
  ],
  promises: [
    {
      id: 'promise_what_ends_it',
      kind: 'MYSTERY',
      label: 'What actually destroys Halcyon Bay',
      seedHint: 'Light, sound, and the water coming up the hill. You never see what does it.',
      payoffHint: 'The tower has been holding it off for sixty years, one week at a time.',
      weight: 1,
    },
    {
      id: 'promise_mina',
      kind: 'RELATIONSHIP',
      label: 'Mina Arclight, who meets you every Monday for the first time',
      seedHint: 'She is the first person you meet and the one person you cannot find at the end.',
      payoffHint: 'She goes up to the tower at half nine on Sunday and does not know why.',
      weight: 1,
    },
    {
      id: 'promise_believer',
      kind: 'RELATIONSHIP',
      label: 'Getting one person to believe you',
      seedHint: 'You know what happens on Thursday. Saying it out loud is easy.',
      payoffHint: 'They believe you, and then it is Monday.',
      weight: 0.9,
    },
    {
      id: 'promise_elias',
      kind: 'MYSTERY',
      label: 'Elias Crowe, who is right',
      seedHint: 'Everyone stops listening to him at the third sentence.',
      payoffHint: 'Nine years of measurements, and a movement that completes a cycle every seven days.',
      weight: 0.9,
    },
    {
      id: 'promise_the_choice',
      kind: 'FINALE',
      label: 'Whether the loop is the disaster or the thing preventing it',
      seedHint: 'Every week ends the same way, and every week begins again.',
      payoffHint: 'Ending it ends the city. Keeping it means nobody else ever gets a Monday that is theirs.',
      weight: 1,
    },
  ],
  archetypes: [
    {
      id: 'arch_watcher',
      name: 'The Watcher',
      role: 'Observation',
      summary:
        'You notice what changed. Best at spotting the one detail that is different this time, which in a week you have already lived is most of the game.',
      playstyle: ['Notices everything', 'Finds events early', 'Poor at persuading'],
      blurb: 'You have always been the person who says "was that there before?" and is usually right.',
      attributeBonus: { mind: 3 },
      skillProficiencies: { observation: 3, research: 2, mechanism: 1 },
      startingItems: [{ itemId: 'notebook', qty: 1 }],
      startingAbilities: [],
    },
    {
      id: 'arch_talker',
      name: 'The Talker',
      role: 'Social',
      summary:
        'People tell you things. The fastest route to trust, which is what turns a stranger who forgets you every Monday into someone who believes you by Thursday.',
      playstyle: ['Trusted quickly', 'Convinces people', 'Misses physical detail'],
      blurb: 'Three days in and you are on first-name terms with the whole esplanade. Again.',
      attributeBonus: { presence: 3 },
      skillProficiencies: { persuasion: 3, rapport: 2, deception: 1 },
      startingItems: [{ itemId: 'good_bottle', qty: 1 }],
      startingAbilities: [],
    },
    {
      id: 'arch_runner',
      name: 'The Runner',
      role: 'Speed and reach',
      summary:
        'You get across town in time. Knowing when something happens is only useful if you can be standing in front of it, and you can be in two places in an evening.',
      playstyle: ['Fast', 'Follows people', 'Physically capable'],
      blurb: 'Halcyon Bay is a hill. Most people take the long way round. You have stopped bothering.',
      attributeBonus: { agility: 2, resolve: 1 },
      skillProficiencies: { legwork: 3, nerve: 2, observation: 1 },
      startingItems: [],
      startingAbilities: [],
    },
    {
      id: 'arch_stubborn',
      name: 'The Stubborn One',
      role: 'Nerve',
      summary:
        'You can do the same terrible evening five times without flinching. Highest resolve, and the only one who can stand on the Point at half eleven on a Wednesday more than once.',
      playstyle: ['Hard to shake', 'Handles the bad loops', 'Slow to be liked'],
      blurb: 'Everyone else would have stopped by the fourth week. That is the difference between you and everyone else.',
      attributeBonus: { resolve: 3 },
      skillProficiencies: { nerve: 3, observation: 1, research: 2 },
      startingItems: [],
      startingAbilities: [],
    },
  ],
  setupFields: [
    { id: 'displayName', label: 'What name did you give the landlady?', kind: 'TEXT', required: true, maxLength: 40, placeholder: 'e.g. Noa Fenwick' },
    { id: 'pronouns', label: 'Pronouns', kind: 'TEXT', required: false, maxLength: 24, placeholder: 'e.g. they/them' },
    {
      id: 'archetype',
      label: 'What are you like?',
      helpText:
        'How you get things done. It sets your attributes and training, so it decides which parts of the week come easily — noticing a detail, being trusted quickly, getting across town in time, or being able to do a bad evening five times. Fixed for this run. What you learn is not: knowledge is the one thing that survives a reset.',
      kind: 'ARCHETYPE',
      required: false,
    },
    {
      id: 'worldKnowsAboutYou',
      label: 'Why did you come to Halcyon Bay?',
      kind: 'TEXT',
      required: false,
      maxLength: 300,
      placeholder: 'e.g. I took the job because the photographs looked like somewhere nothing happens.',
    },
    {
      id: 'origin',
      label: 'What were you doing before?',
      helpText: 'What you brought with you, which is what people ask about on the first Monday and every Monday after.',
      kind: 'CHOICE',
      advanced: true,
      options: [
        { id: 'left_a_job', label: 'You walked out of something' },
        { id: 'left_a_person', label: 'You left someone' },
        { id: 'came_back', label: 'You were born here and swore you would not return' },
        { id: 'no_reason', label: 'You picked it off a map' },
      ],
    },
    {
      id: 'appearance',
      label: 'What do people notice first?',
      kind: 'TEXT',
      advanced: true,
      maxLength: 200,
      placeholder: 'e.g. Two bags, one with a broken zip, and the look of someone who has not slept on a train.',
    },
  ],
  opening:
    'The 8:12 pulls out behind you and the noise of it goes down the hill and out over the water.\n\n' +
    'Halcyon Bay in the morning: one platform, a canopy with a hole in it, and the whole town laid out below you down to the marina. It is exactly as nice as the photographs.\n\n' +
    'A woman is coming down the platform towards you with her hand already half raised, the way people do when they have decided to be friendly before finding out whether you want them to be.\n\n' +
    '"You are the one taking room four," she says. "I am Mina. You look like someone who has not eaten since the train."\n\n' +
    'Your bags are at your feet. Both of them. The blue one has a broken zip.\n\n' +
    'It is twelve minutes past eight on Monday morning.',
  openingSuggestions: [
    'I pick up the lighter bag and grin at her. “Go on then. Show me the town — and be honest about the bad parts.”',
    'I look down the hill towards the marina, then back at her. “What is there to do here on a Sunday? Asking for planning purposes.”',
    'I do not move from my bags. “I would rather see the room first, if that is all right. I have been on a train since six.”',
  ],
  publishedAt: '2026-09-09T09:00:00.000Z',
};

export const SEVEN_DAYS = StoryVersion.parse(raw);
