import { StoryVersion } from '@plotbreak/contracts';

/**
 * "The Tidewall" — a class-born fantasy world where the class is the story.
 *
 * The design problem with a class fantasy is that most of them are a
 * character-creation menu followed by the same adventure. Here the five orders
 * are separate institutions with separate ranks, separate training, separate
 * rivalries and separate keys to the same door: every main-quest step that
 * matters carries one route per class, and the route taken sets flags the
 * others close. A Warrior gets onto the posting list by winning the yard. A
 * Stillhand gets on it by being the only person who can keep a wounded rider
 * alive. Neither is the "real" way through.
 *
 * Parsed at import so a malformed world fails the build, not a player's session.
 */

const raw = {
  id: 'sv_tidewall_1',
  storyId: 'story_tidewall',
  version: 1,
  title: 'The Tidewall',
  fantasyLabel: 'Your sister died holding the wall.',
  hook: 'Your sister died holding a gate on the wall. One survivor says he watched her walk away from it afterwards.',
  premise:
    'Once a year, for about thirty days, the animals come down out of the mountains in numbers that behave less like animals and more like weather. A hundred miles of fortification called the Tidewall stands between them and the farm towns, and five orders of fighters hold it.\n\n' +
    'Everyone here is tested at sixteen and placed in one of those five orders. That placement is permanent. It decides who trains you, what weapons you are allowed, what you can be promoted to, and which parts of the wall you may stand on.\n\n' +
    'Last year the tide broke through at the eleventh gate. Your sister Wren commanded it. The record says she died holding the gatehouse so the line behind her could re-form, and you were given her sword and a folded commendation.\n\n' +
    'Then a survivor told you, once and quietly, that after the fighting stopped he saw Wren walk north through the pass on her own feet. Nobody senior will hear it. The pass is closed to everyone except the unit posted at the eleventh gate.\n\n' +
    'That posting goes to whichever recruits rank highest in their order when the next tide comes. So you have four months to earn a place near the top of your order’s list, before the tide arrives and the gate is given to somebody else. Miss it and the pass stays shut for another year, and a recruit caught walking into it alone is struck off the roll for good.',
  creatorId: 'creator_official',
  creatorName: 'Plotbreak Studios',
  official: true,
  coverImage: 'tidewall/cover',
  keyArt: 'tidewall/key',
  tags: ['High fantasy', 'Class RPG', 'Military', 'Monsters', 'Rivalry'],
  mechanicsChips: ['Five classes', 'Mounts & companions', 'Ranking up', 'Order politics', 'Siege combat'],
  contentDescriptors: ['FANTASY_VIOLENCE', 'MORAL_AMBIGUITY', 'PSYCHOLOGICAL_THEMES', 'ROMANCE'],
  intensity: 'MODERATE',
  creatorNote:
    'Your class is not a costume. It decides who will train you, who will not speak to you, and which of the four ways through the next door is yours. Two players who pick differently should not recognise each other’s run.',
  rules: {
    defeatMode: 'FAIL_FORWARD',
    progressionMode: 'MILESTONE',
    revealExactDc: false,
    revealCheckMath: false,
    allowsCombat: true,
    allowsRomance: true,
    startingLocationId: 'muster_yard',
    startWorldMinute: 6 * 60 + 40,
    startingItems: [
      { itemId: 'wrens_sword', qty: 1 },
      { itemId: 'roll_token', qty: 1 },
    ],
    hardCanon: [
      'A placement is permanent. Nobody has ever been re-tested, and the orders do not discuss why.',
      'Blight is what the tide leaves in a person. It does not heal on its own and it does not kill quickly.',
      'The pass above the eleventh gate is closed by standing order to everyone but the posted unit.',
      'Eleven people came back from the eleventh gate. None of them have been assigned to the wall since.',
      'The orders promote from a ranked roll. The roll is public and it is not negotiable.',
    ],
    toneGuide:
      'Cold mornings, wet leather, and professionals doing a dangerous job on a schedule. Grand fantasy is real here but it is also paperwork, rotas and rank. Warmth between soldiers; no melodrama, no speeches.',
    forkCostCredits: 120,
  },
  attributes: { might: 11, agility: 11, mind: 11, presence: 11, resolve: 12, arcana: 10 },
  skills: [
    { id: 'warfare', name: 'Warfare', attribute: 'might', description: 'Formation, footing, and where a line breaks.' },
    { id: 'blades', name: 'Blades', attribute: 'might', description: 'Everything with an edge, held close.' },
    { id: 'riding', name: 'Riding', attribute: 'agility', description: 'Staying on, and making it want to stay under you.' },
    { id: 'archery', name: 'Archery', attribute: 'agility', description: 'Range, wind, and the shot you do not take.' },
    { id: 'stealth', name: 'Stealth', attribute: 'agility', description: 'Being where nobody is looking, on purpose.' },
    { id: 'sorcery', name: 'Sorcery', attribute: 'arcana', description: 'Holding a working open without losing the thread.' },
    { id: 'mending', name: 'Mending', attribute: 'arcana', description: 'Closing what is open, and knowing what to close first.' },
    { id: 'beastlore', name: 'Beastlore', attribute: 'mind', description: 'What a creature wants, before it decides.' },
    { id: 'command', name: 'Command', attribute: 'presence', description: 'Being obeyed by tired people.' },
    { id: 'endurance', name: 'Endurance', attribute: 'resolve', description: 'The last hour of a long day.' },
    { id: 'insight', name: 'Insight', attribute: 'mind', description: 'Reading the room, and the roll behind it.' },
  ],
  resources: [
    {
      id: 'health',
      name: 'Health',
      max: 26,
      start: 26,
      regenPerHour: 1,
      polarity: 'GOOD_HIGH',
      displayPriority: 1,
      visible: true,
      zeroStateConsequence: 'You go down. The Stillhand tent will have you, and the roll will note that you needed it.',
      color: '#FF5B69',
    },
    {
      id: 'vigor',
      name: 'Vigor',
      max: 22,
      start: 22,
      regenPerHour: 3,
      polarity: 'GOOD_HIGH',
      displayPriority: 2,
      visible: true,
      zeroStateConsequence: 'Nothing left in the arms. Every trained ability is attempted at a disadvantage.',
      color: '#7C6CFF',
    },
    {
      id: 'standing',
      name: 'Standing',
      max: 100,
      start: 12,
      regenPerHour: 0,
      polarity: 'GOOD_HIGH',
      displayPriority: 3,
      visible: true,
      zeroStateConsequence: 'Bottom of your order’s roll. You are given the jobs nobody records.',
      color: '#5FD3A8',
    },
    {
      id: 'blight',
      name: 'Blight',
      max: 100,
      start: 0,
      regenPerHour: 0,
      polarity: 'GOOD_LOW',
      displayPriority: 4,
      visible: true,
      zeroStateConsequence: 'Clean. Nothing of the tide is in you today.',
      color: '#9AA3B2',
    },
  ],
  items: [
    {
      id: 'wrens_sword',
      name: "Wren's Sword",
      tags: ['quest', 'blade'],
      questItem: true,
      droppable: false,
      equipSlot: 'hand',
      skillModifiers: { blades: 1, command: 1 },
      description: 'A wall sword, plain, kept sharp by someone who used it. The grip is wound for a smaller hand than yours.',
      loreText: 'Returned with her effects. The blade has been resharpened past its original line at least four times.',
      icon: 'sword',
    },
    {
      id: 'roll_token',
      name: 'Recruit Token',
      tags: ['quest', 'document'],
      questItem: true,
      droppable: false,
      description: 'A stamped brass tab with your order, your intake year, and your current place on the roll punched into the edge.',
      loreText: 'The punches go one way. Everyone checks their own in the dark, and everyone pretends they do not.',
      icon: 'token',
    },
    {
      id: 'field_kit',
      name: 'Field Kit',
      tags: ['consumable', 'medical'],
      stackable: true,
      maxStack: 4,
      consumable: { resourceId: 'health', amount: 8, consumesItem: true },
      description: 'Waxed thread, clean linen, and a bottle of something that stings enough to be doing its job.',
      loreText: 'Issued four to a recruit per season. Using the fourth one is noted.',
      icon: 'kit',
    },
    {
      id: 'ward_salt',
      name: 'Ward Salt',
      tags: ['consumable', 'arcane'],
      stackable: true,
      maxStack: 6,
      consumable: { resourceId: 'blight', amount: -12, consumesItem: true },
      description: 'Coarse grey salt that draws the tide out of a wound. Burns going in and keeps burning for an hour.',
      loreText: 'Mined below the wall itself, which is the part the Bright Hall would rather you did not think about.',
      icon: 'salt',
    },
    {
      id: 'proof_letter',
      name: "Bec's Written Account",
      tags: ['quest', 'document'],
      questItem: true,
      droppable: false,
      description: 'What the survivor saw at the eleventh gate, in his own hand, signed, with the date and the hour.',
      loreText: 'He wrote it three times. The first two are ash.',
      icon: 'letter',
    },
    {
      id: 'gate_key',
      name: 'Gatehouse Key',
      tags: ['quest', 'tool'],
      questItem: true,
      droppable: false,
      description: 'Iron, unlabelled, and cut for the eleventh gatehouse door that has been chained since last autumn.',
      loreText: 'There should be three of these. There are two.',
      icon: 'key',
    },
  ],
  abilities: [
    {
      id: 'read_the_line',
      name: 'Read the Line',
      tags: ['universal', 'utility'],
      description: 'Look at a formation, a crowd, or a fight and see where it is about to come apart.',
      affordances: ['read the line', 'size up the fight', 'look for the weak point', 'watch how they are standing'],
      costs: [{ resourceId: 'vigor', amount: 2 }],
      cooldownMinutes: 0,
      targetRule: 'NONE',
      check: { attribute: 'mind', skillId: 'warfare', baseDc: 12 },
      unlockedByDefault: true,
    },
    {
      id: 'set_yourself',
      name: 'Set Yourself',
      tags: ['universal', 'defensive'],
      description: 'Plant, breathe out, and refuse the next thing that arrives.',
      affordances: ['brace', 'set myself', 'hold my ground', 'plant my feet'],
      costs: [{ resourceId: 'vigor', amount: 3 }],
      cooldownMinutes: 15,
      targetRule: 'SELF',
      check: null,
      unlockedByDefault: true,
    },
    {
      id: 'break_charge',
      name: 'Breaking Charge',
      tags: ['warrior', 'offensive'],
      description: 'Put the whole weight of yourself and whatever you are riding through one point of a line.',
      affordances: ['charge them', 'ride them down', 'run straight through', 'break the line'],
      costs: [{ resourceId: 'vigor', amount: 8 }],
      cooldownMinutes: 30,
      targetRule: 'SINGLE',
      check: { attribute: 'might', skillId: 'warfare', baseDc: 14 },
      unlockedByDefault: false,
    },
    {
      id: 'call_the_mount',
      name: 'Call the Mount',
      tags: ['warrior', 'bond'],
      description: 'Whistle down whatever the Iron March has trusted you with this season.',
      affordances: ['call my horse', 'whistle for my mount', 'get the beast', 'bring the mount up'],
      costs: [{ resourceId: 'vigor', amount: 2 }],
      cooldownMinutes: 60,
      targetRule: 'SELF',
      check: { attribute: 'presence', skillId: 'riding', baseDc: 11 },
      unlockedByDefault: false,
    },
    {
      id: 'open_the_seam',
      name: 'Open the Seam',
      tags: ['rogue', 'offensive'],
      description: 'Two blades, one opening, and a cut placed where the armour was going to be a moment ago.',
      affordances: ['find the gap', 'go for the seam', 'cut low and inside', 'slip past the guard'],
      costs: [{ resourceId: 'vigor', amount: 6 }],
      cooldownMinutes: 20,
      targetRule: 'SINGLE',
      check: { attribute: 'agility', skillId: 'blades', baseDc: 13 },
      unlockedByDefault: false,
    },
    {
      id: 'send_the_bond',
      name: 'Send the Bond',
      tags: ['rogue', 'bond'],
      description: 'Point, and the animal that chose you goes where you pointed.',
      affordances: ['send the wolf', 'set my companion on him', 'send her in', 'let the animal go'],
      costs: [{ resourceId: 'vigor', amount: 4 }],
      cooldownMinutes: 20,
      targetRule: 'SINGLE',
      check: { attribute: 'presence', skillId: 'beastlore', baseDc: 12 },
      unlockedByDefault: false,
    },
    {
      id: 'held_shot',
      name: 'Held Shot',
      tags: ['archer', 'offensive'],
      description: 'Draw, and keep drawing, until the shot is the only thing left in the world.',
      affordances: ['take the shot', 'draw on him', 'line up the shot', 'hold and loose'],
      costs: [{ resourceId: 'vigor', amount: 5 }],
      cooldownMinutes: 10,
      targetRule: 'SINGLE',
      check: { attribute: 'agility', skillId: 'archery', baseDc: 13 },
      unlockedByDefault: false,
    },
    {
      id: 'mark_it',
      name: 'Mark It',
      tags: ['archer', 'utility'],
      description: 'Name a target aloud so the whole line knows which one is yours and which one is theirs.',
      affordances: ['mark it', 'call the target', 'tell them which one', 'put a mark on him'],
      costs: [{ resourceId: 'vigor', amount: 2 }],
      cooldownMinutes: 5,
      targetRule: 'SINGLE',
      check: { attribute: 'presence', skillId: 'command', baseDc: 11 },
      unlockedByDefault: false,
    },
    {
      id: 'first_element',
      name: 'First Element',
      tags: ['sorcerer', 'offensive'],
      description: 'The one working you have bound so far, thrown properly rather than carefully.',
      affordances: ['throw the working', 'use my magic', 'cast at him', 'let the element go'],
      costs: [{ resourceId: 'vigor', amount: 7 }],
      cooldownMinutes: 15,
      targetRule: 'SINGLE',
      check: { attribute: 'arcana', skillId: 'sorcery', baseDc: 13 },
      unlockedByDefault: false,
    },
    {
      id: 'hold_open',
      name: 'Hold It Open',
      tags: ['sorcerer', 'utility'],
      description: 'Keep a working running while you do something else, which is the whole difficulty.',
      affordances: ['hold the working', 'keep it going', 'maintain it', 'hold it open'],
      costs: [{ resourceId: 'vigor', amount: 4 }],
      cooldownMinutes: 30,
      targetRule: 'SELF',
      check: { attribute: 'resolve', skillId: 'sorcery', baseDc: 14 },
      unlockedByDefault: false,
    },
    {
      id: 'thread',
      name: 'Thread',
      tags: ['healer', 'support'],
      description: 'Take hold of what is going wrong in someone and pull it closed.',
      affordances: ['heal them', 'patch him up', 'close the wound', 'work on her', 'thread it'],
      costs: [{ resourceId: 'vigor', amount: 6 }],
      cooldownMinutes: 5,
      targetRule: 'SINGLE',
      check: { attribute: 'arcana', skillId: 'mending', baseDc: 12 },
      unlockedByDefault: false,
    },
    {
      id: 'the_cut',
      name: 'The Cut',
      tags: ['healer', 'offensive'],
      description: 'The same grip, used the other way. Take hold of what is keeping something upright and let go of it.',
      affordances: ['cut him', 'take it out of him', 'unmake it', 'use the cut on him'],
      costs: [{ resourceId: 'vigor', amount: 9 }],
      cooldownMinutes: 45,
      targetRule: 'SINGLE',
      check: { attribute: 'arcana', skillId: 'mending', baseDc: 15 },
      unlockedByDefault: false,
    },
  ],
  locations: [
    {
      id: 'muster_yard',
      takeableItems: [
        { itemId: 'field_kit', qty: 1, ownerId: null, aka: ['kit', 'a field kit'] },
      ],
      name: 'The Muster Yard',
      shortName: 'Yard',
      description:
        'Forty paces of frozen sand between the barracks and the wall stair, raked flat every morning by whoever came last to breakfast. The ranking roll is nailed to the post by the gate and read by everyone who walks past it.',
      artDirection: 'Blue pre-dawn light, frost on sand, high grey wall behind, a lamp on a post and a crowd of breath.',
      stageImage: 'tidewall/stage_muster_yard',
      discoveredByDefault: true,
      mapPosition: { x: 0.5, y: 0.85 },
      ambientSfx: ['wind_low', 'boots_gravel'],
      connections: [
        { to: 'wall_walk', travelMinutes: 6, label: 'Up the wall stair' },
        { to: 'beast_lines', travelMinutes: 5, label: 'Out to the animal lines' },
        { to: 'stillhand_tent', travelMinutes: 4, label: 'Across to the tents' },
        { to: 'bright_hall', travelMinutes: 8, label: 'Down to the hall' },
      ],
    },
    {
      id: 'wall_walk',
      name: 'The Wall Walk',
      shortName: 'Wall',
      description:
        'The top of the Tidewall, wide enough for three abreast and nothing else, running east and west until it stops being a wall and starts being weather. From up here the farm towns are small and orange and clearly worth it.',
      artDirection: 'High stone rampart at dawn, cold mist below, distant lit towns, black mountains north.',
      stageImage: 'tidewall/stage_wall_walk',
      discoveredByDefault: true,
      mapPosition: { x: 0.5, y: 0.55 },
      ambientSfx: ['wind_high', 'rope_creak'],
      connections: [
        { to: 'muster_yard', travelMinutes: 6, label: 'Down the stair' },
        { to: 'longwatch_post', travelMinutes: 7, label: 'East along the walk' },
        { to: 'eleventh_gate', travelMinutes: 20, label: 'East to the eleventh gate' },
      ],
    },
    {
      id: 'beast_lines',
      name: 'The Animal Lines',
      shortName: 'Lines',
      description:
        'Pens, perches and a long roofed run where the orders keep everything they ride, fly, or answer to. It smells of straw and meat and it is the warmest place on the wall.',
      artDirection: 'Long timber stable run, lanterns, steam off animals, huge empty perches at the far end.',
      stageImage: 'tidewall/stage_beast_lines',
      discoveredByDefault: true,
      mapPosition: { x: 0.78, y: 0.8 },
      ambientSfx: ['hooves', 'wings_large'],
      connections: [
        { to: 'muster_yard', travelMinutes: 5, label: 'Back to the yard' },
        { to: 'stillhand_tent', travelMinutes: 6, label: 'Round to the tents' },
      ],
    },
    {
      id: 'stillhand_tent',
      name: 'The Stillhand Tents',
      shortName: 'Tents',
      description:
        'Six canvas halls behind the yard, lit day and night, where the wall’s wounded are sorted by how long they have. The ward salt is kept here and so is every honest opinion on the wall.',
      artDirection: 'Warm canvas interior, hanging lamps, rows of cots, grey salt in open crates.',
      stageImage: 'tidewall/stage_stillhand_tent',
      discoveredByDefault: true,
      mapPosition: { x: 0.26, y: 0.8 },
      ambientSfx: ['canvas_flap', 'low_voices'],
      connections: [
        { to: 'muster_yard', travelMinutes: 4, label: 'Back to the yard' },
        { to: 'beast_lines', travelMinutes: 6, label: 'Round to the lines' },
      ],
    },
    {
      id: 'bright_hall',
      takeableItems: [
        { itemId: 'ward_salt', qty: 2, ownerId: null, aka: ['salt', 'ward salt', 'the jars'] },
      ],
      name: 'The Bright Hall',
      shortName: 'Hall',
      description:
        'A drum-shaped stone room sunk below the yard where the sorcerers of the wall bind their first element and argue about the second. The floor is one continuous ring of worked slate and standing on the wrong part of it is rude.',
      artDirection: 'Sunken circular stone chamber, cold blue light from a ring in the floor, tall narrow windows.',
      stageImage: 'tidewall/stage_bright_hall',
      discoveredByDefault: true,
      mapPosition: { x: 0.28, y: 0.6 },
      ambientSfx: ['low_hum', 'stone_echo'],
      connections: [{ to: 'muster_yard', travelMinutes: 8, label: 'Up to the yard' }],
    },
    {
      id: 'longwatch_post',
      name: 'The Longwatch Post',
      shortName: 'Post',
      description:
        'A stone spur pushed out from the wall so archers can see along the face of it. Three great bows are mounted here on turntables, each one crewed by four people who have all shouted at each other before breakfast.',
      artDirection: 'Projecting stone platform, three huge mounted bows, wind, ranging marks painted on the parapet.',
      stageImage: 'tidewall/stage_longwatch_post',
      discoveredByDefault: true,
      mapPosition: { x: 0.72, y: 0.45 },
      ambientSfx: ['wind_high', 'wood_strain'],
      connections: [{ to: 'wall_walk', travelMinutes: 7, label: 'West along the walk' }],
    },
    {
      id: 'eleventh_gate',
      name: 'The Eleventh Gate',
      shortName: 'Gate Eleven',
      description:
        'A gatehouse and a low crossing where the ground comes up to meet the wall, which is why the tide chose it. The stonework has been rebuilt and the scorching underneath has not been cleaned off.',
      artDirection: 'Rebuilt stone gatehouse, chained door, black scorching under new mortar, the pass beyond in fog.',
      stageImage: 'tidewall/stage_eleventh_gate',
      discoveredByDefault: false,
      mapPosition: { x: 0.9, y: 0.3 },
      ambientSfx: ['wind_low', 'chain'],
      connections: [{ to: 'wall_walk', travelMinutes: 20, label: 'West along the walk' }],
    },
  ],
  characters: [
    {
      id: 'odalys',
      name: 'Drillmaster Odalys Verne',
      role: 'Drillmaster of the intake',
      cardBlurb:
        'She writes the ranking roll that decides who gets the posting. She trained your sister too, and she has not mentioned it once.',
      pronouns: 'she/her',
      publicTraits: ['Blunt', 'Precise', 'Impossible to flatter'],
      hiddenDrives: [
        'She put Wren forward for the eleventh gate herself and has not slept right since.',
        'She wants you ranked high on merit so that nobody can say she gave it to you.',
      ],
      values: ['The roll being honest', 'Recruits surviving their first tide', 'Saying the hard thing early'],
      fears: ['Sending another Calloway to that gate', 'Being right about what is in the pass'],
      socialStyle: 'Answers in one sentence and waits. Will tell you exactly why you are ranked where you are if you ask straight.',
      boundaries: ['Will not move anyone on the roll as a favour', 'Will not discuss Wren in front of other recruits'],
      goals: ['Get this intake through the tide alive', 'Find out who closed the inquiry into the eleventh gate'],
      secrets: [
        {
          id: 'odalys_recommended_wren',
          fact: 'Odalys is the one who recommended Wren for the eleventh gate posting.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Comes out at respect 40+, or immediately if the player shows her the written account.',
        },
        {
          id: 'odalys_inquiry_closed',
          fact: 'The inquiry into the eleventh gate was closed by order of the eastern run command, not by the orders.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Requires trust 35+ and a conversation on the wall walk after dark.',
        },
      ],
      speechStyle:
        'Short, flat, and specific. Uses your order and your roll number instead of your name when she is being official, which is most of the time.',
      topics: ['the roll', 'my ranking', 'the eleventh gate', 'what my sister was like as a recruit'],
      voiceSamples: [
        'You are nineteenth. You want to know why, or you want to be told you should be higher?',
        'I do not move people on the roll. I move the roll when people move.',
        'Your sister asked me that same question standing exactly there.',
      ],
      appearance: 'Fifties, grey cropped hair, one ear missing its top, a drill cane she has never once hit anyone with.',
      visualHook:
        'The top third of her left ear is simply gone, healed clean and old, and she wears a drill cane through her belt like a sword she has retired.',
      silhouette:
        'Square, still, hands behind her back, standing at ease so precisely that it reads as a threat.',
      artSeed: 'odalys-verne-v1',
      portrait: 'tidewall/odalys',
      expressions: ['neutral', 'stern', 'assessing', 'tired', 'approving', 'grim'],
      voiceId: 'voice_odalys',
      homeLocationId: 'muster_yard',
      knowledgeScope: ['faction_iron_march', 'faction_longwatch', 'faction_stillhand'],
      schedule: [
        { startMinute: 360, endMinute: 660, locationId: 'muster_yard', activity: 'Morning drill' },
        { startMinute: 660, endMinute: 780, locationId: 'beast_lines', activity: 'Inspecting the lines' },
        { startMinute: 780, endMinute: 1020, locationId: 'muster_yard', activity: 'Afternoon drill and the roll' },
        { startMinute: 1020, endMinute: 1200, locationId: 'wall_walk', activity: 'Walking the wall alone' },
        { startMinute: 1200, endMinute: 1380, locationId: 'stillhand_tent', activity: 'Sitting with the wounded' },
      ],
      startingRelationship: { trust: 8, affection: 0, respect: 10, fear: 5, rivalry: 0 },
      attributes: { might: 14, agility: 11, mind: 14, presence: 15, resolve: 16, arcana: 8 },
      gates: [
        {
          id: 'odalys_speaks_plainly',
          kind: 'TRUST',
          label: 'Odalys will tell you what she knows about the gate',
          requires: {
            respect: 40,
            flagsSet: ['spoke:odalys', 'visited:wall_walk'],
            flagsUnset: ['odalys_lost_patience'],
          },
        },
        {
          id: 'odalys_puts_you_forward',
          kind: 'ALLIANCE',
          label: 'Odalys will put your name forward for the posting',
          requires: { respect: 55, trust: 35, flagsSet: ['ranked_top_five'] },
        },
      ],
      combatant: { health: 40, defenseDc: 17, damage: 8, tags: ['veteran', 'nonlethal'] },
    },
    {
      id: 'bec',
      name: 'Bec Tarrow',
      role: 'Longwatch archer, survivor of the eleventh gate',
      cardBlurb:
        'The only survivor who will say what he saw. He told you once, and he has been regretting it since.',
      pronouns: 'he/him',
      publicTraits: ['Jumpy', 'Funny when he forgets to be frightened', 'Never sits with his back to a door'],
      hiddenDrives: [
        'He wants someone to believe him so he can stop deciding every morning whether he believes himself.',
        'He did not fire on the thing that came through, and he has not told anyone that part.',
      ],
      values: ['Telling the truth eventually', 'The people from his crew', 'Not being a coward twice'],
      fears: ['Being written up as unfit', 'Going back east', 'Being right'],
      socialStyle: 'Talks fast and sideways. Will answer a direct question if you are the only one in the room.',
      boundaries: ['Will not repeat it in front of an officer', 'Will not go past the wall walk'],
      goals: ['Get put back on a bow crew', 'Say it once in writing and be done with it'],
      secrets: [
        {
          id: 'bec_did_not_shoot',
          fact: 'Bec had a clear shot on the thing coming through the gate and did not take it.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Only at trust 45+, and only somewhere he cannot be overheard.',
        },
        {
          id: 'bec_saw_her_walk',
          fact: 'Bec watched Wren walk north through the pass, unhurried, carrying nothing.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'He has already told the player once. Getting it in writing is the quest.',
        },
      ],
      speechStyle:
        'Runs sentences together, then stops dead. Apologises for things that are not his fault. Uses your first name immediately.',
      topics: ['what he saw', 'the eleventh gate', 'his crew', 'the great bows'],
      voiceSamples: [
        'I said it once. I am not saying it to Ansett, so do not ask me that.',
        'She was walking. Not running. That is the part that gets me.',
        'Do you want to hear the funny version or the true one? The funny one is shorter.',
      ],
      appearance: 'Nineteen, thin, bitten nails, a Longwatch coat he has not been officially allowed to wear since autumn.',
      visualHook:
        'A Longwatch coat with the crew patch unpicked, leaving a clean bright rectangle of unfaded cloth over his heart.',
      silhouette:
        'Narrow and hunched with his hands jammed in his pockets, standing at an angle to whoever he is talking to.',
      artSeed: 'bec-tarrow-v1',
      portrait: 'tidewall/bec',
      expressions: ['neutral', 'nervous', 'amused', 'haunted', 'defiant', 'relieved'],
      voiceId: 'voice_bec',
      homeLocationId: 'stillhand_tent',
      knowledgeScope: ['faction_longwatch'],
      schedule: [
        { startMinute: 360, endMinute: 540, locationId: 'stillhand_tent', activity: 'Not sleeping' },
        { startMinute: 540, endMinute: 780, locationId: 'beast_lines', activity: 'Mucking out, unofficially' },
        { startMinute: 780, endMinute: 1020, locationId: 'longwatch_post', activity: 'Watching his old crew work' },
        { startMinute: 1020, endMinute: 1260, locationId: 'muster_yard', activity: 'Edge of the yard, out of the way' },
        { startMinute: 1260, endMinute: 1440, locationId: 'stillhand_tent', activity: 'Sitting up with a lamp' },
      ],
      startingRelationship: { trust: 20, affection: 10, respect: 5, fear: 0, rivalry: 0 },
      attributes: { might: 9, agility: 15, mind: 12, presence: 10, resolve: 8, arcana: 9 },
      gates: [
        {
          id: 'bec_writes_it',
          kind: 'TRUST',
          label: 'Bec will put it in writing and sign it',
          requires: { trust: 40, flagsSet: ['bec_told_privately'], flagsUnset: ['bec_pushed_too_hard'] },
        },
        {
          id: 'bec_walks_the_wall',
          kind: 'ALLIANCE',
          label: 'Bec will come east with you',
          requires: { trust: 60, affection: 30, flagsSet: ['bec_believed'] },
        },
      ],
      combatant: { health: 16, defenseDc: 13, damage: 6, tags: ['ranged', 'skittish'] },
    },
    {
      id: 'hollis',
      name: 'Hollis Ferrant',
      role: 'Stillhand recruit, first on the roll',
      cardBlurb:
        'The recruit ranked above you. A healer, which is exactly why they can end a fight faster than you can.',
      pronouns: 'they/them',
      publicTraits: ['Generous', 'Relentless', 'Openly competitive about it'],
      hiddenDrives: [
        'Their family has held wall commissions for four generations and none of them were Stillhand.',
        'They want the eleventh gate posting for the same reason you do, and they got there first.',
      ],
      values: ['Earning it', 'Saying so to your face', 'Not letting anyone bleed out to make a point'],
      fears: ['Being thought of as support', 'Coming second in front of their father'],
      socialStyle: 'Warm, direct, and constantly measuring. Will help you and then tell you they helped you.',
      boundaries: ['Will not let a wounded person wait for a rivalry', 'Will not lie to Odalys'],
      goals: ['Hold first place on the roll', 'Be posted to the eleventh gate'],
      secrets: [
        {
          id: 'hollis_wants_the_gate',
          fact: 'Hollis has already asked Odalys for the eleventh gate posting, twice.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Surfaces at respect 30+, or if the player beats them in the yard.',
        },
        {
          id: 'hollis_knew_wren',
          fact: 'Wren taught Hollis the grip that Stillhands use to hold a chest closed. They have never said so.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Requires trust 45+ and a conversation in the tents.',
        },
      ],
      speechStyle:
        'Complete sentences, warm delivery, competitive content. Uses your name a lot, the way people do when they want you paying attention.',
      topics: ['the roll', 'the posting', 'what the Stillhand actually do', 'my family'],
      voiceSamples: [
        'You are nineteenth. I am first. I would like that to stay interesting, so please catch up.',
        'Sit down, you are bleeding on my floor, and yes I am still ahead of you.',
        'People say healer like it means I will be behind you. I will be behind you. That is where the spine is.',
      ],
      appearance: 'Early twenties, tall, forearms scarred to the elbow, Stillhand grey worn with the sleeves cut off.',
      visualHook:
        'Both forearms scarred to the elbow in fine pale lines from wrist to crook, and Stillhand grey with the sleeves deliberately cut away.',
      silhouette:
        'Tall and loose-shouldered with bare forearms crossed, weight on one hip, always slightly closer than expected.',
      artSeed: 'hollis-ferrant-v1',
      portrait: 'tidewall/hollis',
      expressions: ['neutral', 'competitive', 'warm', 'focused', 'stung', 'delighted'],
      voiceId: 'voice_hollis',
      homeLocationId: 'stillhand_tent',
      knowledgeScope: ['faction_stillhand', 'faction_iron_march'],
      schedule: [
        { startMinute: 360, endMinute: 660, locationId: 'muster_yard', activity: 'Morning drill, front rank' },
        { startMinute: 660, endMinute: 900, locationId: 'stillhand_tent', activity: 'Tent rotation' },
        { startMinute: 900, endMinute: 1080, locationId: 'muster_yard', activity: 'Extra work in the yard' },
        { startMinute: 1080, endMinute: 1260, locationId: 'beast_lines', activity: 'Sitting with the animals' },
        { startMinute: 1260, endMinute: 1380, locationId: 'stillhand_tent', activity: 'Night rotation' },
      ],
      startingRelationship: { trust: 10, affection: 5, respect: 15, fear: 0, rivalry: 25 },
      attributes: { might: 12, agility: 12, mind: 14, presence: 14, resolve: 14, arcana: 15 },
      gates: [
        {
          id: 'hollis_respects_you',
          kind: 'TRUST',
          label: 'Hollis will train with you properly',
          requires: { respect: 35, flagsUnset: ['hollis_humiliated'] },
        },
        {
          id: 'hollis_stands_down',
          kind: 'ALLIANCE',
          label: 'Hollis will back your name for the posting instead of their own',
          requires: { trust: 55, respect: 50, flagsSet: ['spoke:hollis', 'has_written_account'] },
        },
      ],
      combatant: { health: 24, defenseDc: 15, damage: 7, tags: ['healer', 'dangerous'] },
    },
    {
      id: 'ansett',
      name: 'Commander Sabel Ansett',
      role: 'Commander of the eastern run',
      cardBlurb:
        'Your sister’s second, now in her chair. She signed the death notice and she will not reopen it.',
      pronouns: 'she/her',
      publicTraits: ['Gracious', 'Immovable', 'Never seen to hurry'],
      hiddenDrives: [
        'She closed the inquiry herself, and she believes she did it to protect the wall.',
        'She knows exactly what walked north through the pass, and she has told nobody.',
      ],
      values: ['The wall holding', 'Not frightening the intake', 'Her own signature meaning something'],
      fears: ['A second gate going the same way', 'Wren coming back'],
      socialStyle: 'Meets you properly, gives you her whole attention, and concedes nothing at all.',
      boundaries: ['Will not reopen a closed inquiry on hearsay', 'Will not permit anyone into the pass'],
      goals: ['Keep the eastern run intact through the next tide', 'Keep the eleventh gate quiet'],
      secrets: [
        {
          id: 'ansett_closed_inquiry',
          fact: 'Ansett closed the inquiry into the eleventh gate on her own authority.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Only with the written account in hand, or from Odalys at high trust.',
        },
        {
          id: 'ansett_saw_it_too',
          fact: 'Ansett was on the wall walk that night and saw the same thing Bec saw.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Endgame reveal. Requires the written account and respect 50+.',
        },
      ],
      speechStyle:
        'Unhurried, complete, and warm in a way that closes the subject. Calls recruits by their order and their surname.',
      topics: ['the eleventh gate', 'the inquiry', 'my sister', 'the pass'],
      voiceSamples: [
        'I signed it. I read it first, and then I signed it, and I would do both again.',
        'You are asking me to reopen a matter on the word of one frightened boy. Bring me the word in writing.',
        'She was the best officer I have ever served under. That is why the notice says what it says.',
      ],
      appearance: 'Forties, dark braid pinned close, commander’s coat kept immaculate, one glove always on.',
      visualHook:
        'A commander’s coat without a single mark on it, and one grey glove worn on the left hand indoors and out.',
      silhouette:
        'Upright and unhurried with hands clasped at the small of her back, taking up exactly as much room as she needs.',
      artSeed: 'sabel-ansett-v1',
      portrait: 'tidewall/ansett',
      expressions: ['neutral', 'gracious', 'closed', 'sorrowful', 'cold', 'resolved'],
      voiceId: 'voice_ansett',
      homeLocationId: 'wall_walk',
      knowledgeScope: ['faction_iron_march', 'faction_longwatch', 'faction_stillhand', 'faction_bright_hall', 'faction_silent_rank'],
      schedule: [
        { startMinute: 360, endMinute: 600, locationId: 'wall_walk', activity: 'Morning inspection' },
        { startMinute: 600, endMinute: 840, locationId: 'muster_yard', activity: 'Command business' },
        { startMinute: 840, endMinute: 1080, locationId: 'longwatch_post', activity: 'The eastern run' },
        { startMinute: 1080, endMinute: 1260, locationId: 'wall_walk', activity: 'Walking east alone' },
        { startMinute: 1260, endMinute: 1380, locationId: 'bright_hall', activity: 'Meeting the hall' },
      ],
      startingRelationship: { trust: 5, affection: 5, respect: 5, fear: 10, rivalry: 0 },
      attributes: { might: 13, agility: 11, mind: 16, presence: 17, resolve: 17, arcana: 11 },
      gates: [
        {
          id: 'ansett_hears_you',
          kind: 'TRUST',
          label: 'Ansett will hear the account out',
          requires: { respect: 35, flagsSet: ['has_written_account'] },
        },
        {
          id: 'ansett_opens_the_pass',
          kind: 'ALLIANCE',
          label: 'Ansett will authorise the pass',
          requires: { respect: 50, trust: 40, flagsSet: ['ansett_knows_you_know'] },
        },
      ],
      combatant: { health: 44, defenseDc: 18, damage: 9, tags: ['commander', 'nonlethal'] },
    },
  ],
  factions: [
    {
      id: 'faction_iron_march',
      name: 'The Iron March',
      description: 'The heavy order. Holds ground, rides everything the wall can feed, and takes the first hit by design.',
      startingReputation: 0,
      ranks: [
        { atReputation: -40, label: 'Struck off' },
        { atReputation: 0, label: 'Recruit' },
        { atReputation: 30, label: 'Lance' },
        { atReputation: 60, label: 'Rider of the March' },
        { atReputation: 85, label: 'Wing' },
      ],
      enemies: [],
      allies: ['faction_stillhand'],
    },
    {
      id: 'faction_silent_rank',
      name: 'The Silent Rank',
      description: 'The light order. Goes over the wall at night, comes back with what the wall did not know.',
      startingReputation: 0,
      ranks: [
        { atReputation: -40, label: 'Struck off' },
        { atReputation: 0, label: 'Recruit' },
        { atReputation: 30, label: 'Walker' },
        { atReputation: 60, label: 'Bonded' },
        { atReputation: 85, label: 'Shadow of the Rank' },
      ],
      enemies: ['faction_longwatch'],
      allies: [],
    },
    {
      id: 'faction_longwatch',
      name: 'The Longwatch',
      description: 'The bows. Owns the great bows on the spurs and the argument about who gets to fire them.',
      startingReputation: 0,
      ranks: [
        { atReputation: -40, label: 'Struck off' },
        { atReputation: 0, label: 'Recruit' },
        { atReputation: 30, label: 'Crew' },
        { atReputation: 60, label: 'Marksman' },
        { atReputation: 85, label: 'Master of the Great Bow' },
      ],
      enemies: ['faction_silent_rank'],
      allies: ['faction_bright_hall'],
    },
    {
      id: 'faction_bright_hall',
      name: 'The Bright Hall',
      description: 'The sorcerers. One element bound at intake, a second if you live long enough to earn it.',
      startingReputation: 0,
      ranks: [
        { atReputation: -40, label: 'Struck off' },
        { atReputation: 0, label: 'Recruit' },
        { atReputation: 30, label: 'First Bound' },
        { atReputation: 60, label: 'Second Bound' },
        { atReputation: 85, label: 'Standing Working' },
      ],
      enemies: [],
      allies: ['faction_longwatch'],
    },
    {
      id: 'faction_stillhand',
      name: 'The Stillhand',
      description: 'The menders. The only order allowed on any part of the wall, and the only one nobody argues with.',
      startingReputation: 0,
      ranks: [
        { atReputation: -40, label: 'Struck off' },
        { atReputation: 0, label: 'Recruit' },
        { atReputation: 30, label: 'Thread' },
        { atReputation: 60, label: 'Stillhand' },
        { atReputation: 85, label: 'The Cut' },
      ],
      enemies: [],
      allies: ['faction_iron_march'],
    },
  ],
  quests: [
    {
      id: 'q_the_roll',
      title: 'Nineteenth on the Roll',
      summary: 'Climb your order’s ranking far enough to be considered for the eleventh gate.',
      kind: 'MAIN',
      startsActive: true,
      involvedCharacterIds: ['odalys', 'hollis'],
      involvedLocationIds: ['muster_yard', 'wall_walk', 'beast_lines'],
      knownRewardCopy: 'A place in the top five, and a conversation with the drillmaster you cannot have yet.',
      steps: [
        {
          id: 'step_first_drill',
          playerCopy: 'Get through your first drill without being sent off it.',
          directorNotes:
            'Odalys is testing whether the player can take a correction. Arguing is survivable; sulking is not.',
          succeedWhen: { flagsSet: ['spoke:odalys'], atLocation: 'muster_yard' },
          rewards: {
            xp: 30,
            items: [{ itemId: 'field_kit', qty: 2 }],
            flags: ['drill_passed', 'known_to_odalys'],
            // Getting through the first drill is when your own order stops
            // treating you as a name on a roll. Enough, with the standing the
            // class already carries, to reach the doors it is supposed to open.
            reputation: [
              { factionId: 'faction_iron_march', amount: 6 },
              { factionId: 'faction_silent_rank', amount: 6 },
              { factionId: 'faction_longwatch', amount: 6 },
              { factionId: 'faction_bright_hall', amount: 6 },
              { factionId: 'faction_stillhand', amount: 6 },
            ],
          },
        },
        {
          id: 'step_earn_a_place',
          playerCopy: 'Move up the roll. How is your order’s business.',
          directorNotes:
            'Five genuinely different routes, one per order, and the route taken changes who owes whom for the rest of ' +
            'the story. Do not steer the player toward any of them. A player with no order can still climb by being ' +
            'useful in the yard, and the story should treat that as its own thing rather than a failure.',
          enterWhen: { flagsSet: ['known_to_odalys'] },
          succeedWhenAny: [
            {
              routeId: 'route_march',
              label: 'You took the yard',
              predicate: {
                flagsSet: ['used:break_charge', 'spoke:odalys'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'muster_yard',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [{ factionId: 'faction_iron_march', value: 25 }],
                beforeWorldMinute: null,
              },
              setsFlags: ['ranked_top_five', 'route_march', 'march_owes_you'],
              closesFlags: ['silent_rank_trust', 'hall_second_element'],
            },
            {
              routeId: 'route_rank',
              label: 'You came back with something nobody else had',
              predicate: {
                flagsSet: ['used:open_the_seam', 'visited:wall_walk'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [{ factionId: 'faction_silent_rank', value: 25 }],
                beforeWorldMinute: null,
              },
              setsFlags: ['ranked_top_five', 'route_rank', 'silent_rank_trust'],
              closesFlags: ['longwatch_crew_seat', 'march_owes_you'],
            },
            {
              routeId: 'route_longwatch',
              label: 'You earned a seat on a great bow crew',
              predicate: {
                flagsSet: ['used:held_shot'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'longwatch_post',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [{ factionId: 'faction_longwatch', value: 25 }],
                beforeWorldMinute: null,
              },
              setsFlags: ['ranked_top_five', 'route_longwatch', 'longwatch_crew_seat'],
              closesFlags: ['silent_rank_trust'],
            },
            {
              routeId: 'route_hall',
              label: 'You bound your element in front of the hall',
              predicate: {
                flagsSet: ['used:first_element'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'bright_hall',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [{ factionId: 'faction_bright_hall', value: 25 }],
                beforeWorldMinute: null,
              },
              setsFlags: ['ranked_top_five', 'route_hall', 'hall_second_element'],
              closesFlags: ['march_owes_you'],
            },
            {
              routeId: 'route_stillhand',
              label: 'You kept someone alive who should not have lived',
              predicate: {
                flagsSet: ['used:thread'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'stillhand_tent',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [{ factionId: 'faction_stillhand', value: 25 }],
                beforeWorldMinute: null,
              },
              setsFlags: ['ranked_top_five', 'route_stillhand', 'tents_owe_you'],
              closesFlags: ['won_the_yard'],
            },
            {
              routeId: 'route_useful',
              label: 'You made yourself impossible to leave off the list',
              predicate: {
                flagsSet: ['spoke:odalys'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'odalys', dimension: 'respect', value: 40 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['ranked_top_five', 'route_useful'],
              closesFlags: [],
            },
          ],
          rewards: { xp: 80, items: [], flags: [] },
        },
      ],
    },
    {
      id: 'q_written_account',
      title: 'Get It In Writing',
      summary: 'Nobody senior will act on what Bec said out loud. Get him to sign it.',
      kind: 'MAIN',
      startsActive: true,
      involvedCharacterIds: ['bec', 'ansett', 'odalys'],
      involvedLocationIds: ['stillhand_tent', 'longwatch_post', 'wall_walk'],
      knownRewardCopy: 'A signed account, and a commander who has to read it.',
      steps: [
        {
          id: 'step_find_bec',
          playerCopy: 'Find Bec somewhere he can talk.',
          directorNotes:
            'He will not repeat it in the yard or anywhere an officer might pass. The tents late, or the lines while ' +
            'he is working, are both fine.',
          succeedWhen: {
            flagsSet: ['spoke:bec'],
            minRelationship: [{ characterId: 'bec', dimension: 'trust', value: 28 }],
          },
          rewards: {
            xp: 40,
            items: [],
            flags: ['bec_told_privately'],
            // Getting a Longwatch archer to say it to you and not to an officer
            // is how the bows come to think you are worth talking to.
            reputation: [{ factionId: 'faction_longwatch', amount: 8 }],
          },
        },
        {
          id: 'step_get_signature',
          playerCopy: 'Get Bec to write it down and sign it.',
          directorNotes:
            'Pushing him hard works once and costs the relationship. Getting him back on a bow crew, or simply being ' +
            'seen to believe him, both work and cost nothing.',
          enterWhen: { flagsSet: ['bec_told_privately'] },
          succeedWhenAny: [
            {
              routeId: 'account_believed',
              label: 'He wrote it because you believed him',
              predicate: {
                flagsSet: ['spoke:bec'],
                flagsUnset: ['bec_pushed_too_hard'],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'bec', dimension: 'trust', value: 40 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['has_written_account', 'bec_believed', 'bec_owes_nothing'],
              closesFlags: [],
            },
            {
              routeId: 'account_traded',
              label: 'He wrote it because you got him back on a crew',
              predicate: {
                flagsSet: ['spoke:bec'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [{ factionId: 'faction_longwatch', value: 30 }],
                beforeWorldMinute: null,
              },
              setsFlags: ['has_written_account', 'bec_owes_you'],
              closesFlags: ['bec_owes_nothing'],
            },
            {
              routeId: 'account_forced',
              label: 'He wrote it because you would not stop',
              predicate: {
                flagsSet: ['spoke:bec'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['has_written_account', 'bec_will_not_speak_again'],
              closesFlags: ['bec_believed', 'bec_owes_nothing'],
            },
          ],
          rewards: { xp: 70, items: [{ itemId: 'proof_letter', qty: 1 }], flags: [] },
        },
      ],
    },
    {
      id: 'q_the_pass',
      title: 'The Pass Above the Gate',
      summary: 'Get to the eleventh gate legally, and find out what is north of it.',
      kind: 'MAIN',
      startsActive: false,
      discoverWhen: { flagsSet: ['has_written_account'] },
      involvedCharacterIds: ['ansett', 'odalys', 'hollis'],
      involvedLocationIds: ['wall_walk', 'eleventh_gate'],
      knownRewardCopy: 'The gatehouse, opened, and whatever is behind the chain.',
      steps: [
        {
          id: 'step_make_ansett_read',
          playerCopy: 'Put the account in Commander Ansett’s hands.',
          directorNotes:
            'She will read it properly. She will not be surprised by it, and a player paying attention should notice that.',
          enterWhen: { flagsSet: ['has_written_account'] },
          succeedWhen: {
            flagsSet: ['spoke:ansett'],
            hasItems: ['proof_letter'],
            minRelationship: [{ characterId: 'ansett', dimension: 'respect', value: 35 }],
          },
          rewards: { xp: 90, items: [], flags: ['ansett_knows_you_know'] },
        },
        {
          id: 'step_get_the_posting',
          playerCopy: 'Get yourself posted to the eleventh gate.',
          directorNotes:
            'Three ways: ranked into it, given it by Hollis, or authorised by Ansett directly. Each one leaves a ' +
            'different person standing next to the player at the gate, and the finale should use whoever it is.',
          enterWhen: { flagsSet: ['ansett_knows_you_know'] },
          succeedWhenAny: [
            {
              routeId: 'posting_earned',
              label: 'You were ranked into it',
              predicate: {
                flagsSet: ['ranked_top_five'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'odalys', dimension: 'respect', value: 55 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['posted_to_gate', 'went_alone'],
              closesFlags: [],
            },
            {
              routeId: 'posting_given',
              label: 'Hollis gave you theirs',
              predicate: {
                flagsSet: ['spoke:hollis', 'has_written_account'],
                flagsUnset: ['hollis_humiliated'],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [
                  { characterId: 'hollis', dimension: 'trust', value: 55 },
                  { characterId: 'hollis', dimension: 'respect', value: 50 },
                ],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['posted_to_gate', 'hollis_came_with_you', 'owe_hollis'],
              closesFlags: ['went_alone'],
            },
            {
              routeId: 'posting_authorised',
              label: 'Ansett signed for you herself',
              predicate: {
                flagsSet: [],
                flagsUnset: [],
                hasItems: ['proof_letter'],
                atLocation: null,
                completedEvents: ['q_the_pass:step_make_ansett_read'],
                minRelationship: [
                  { characterId: 'ansett', dimension: 'respect', value: 50 },
                  { characterId: 'ansett', dimension: 'trust', value: 40 },
                ],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['posted_to_gate', 'ansett_came_with_you'],
              closesFlags: ['went_alone'],
            },
          ],
          rewards: { xp: 120, items: [{ itemId: 'gate_key', qty: 1 }], flags: [] },
        },
      ],
    },
  ],
  promises: [
    {
      id: 'promise_did_she_walk',
      kind: 'MYSTERY',
      label: 'Whether Wren walked north, and what walked with her',
      seedHint: 'One survivor, one account, and eleven people who have not been put back on the wall.',
      payoffHint: 'She walked. Ansett watched her go and closed the inquiry the same night.',
      weight: 1,
    },
    {
      id: 'promise_hollis_rival',
      kind: 'RIVAL',
      label: 'Hollis Ferrant, first on the roll and not your enemy',
      seedHint: 'They are ranked above you and cheerfully tell you so on the first morning.',
      payoffHint: 'They wanted the gate for their own reasons, and they can choose to hand it to you.',
      weight: 0.85,
    },
    {
      id: 'promise_odalys',
      kind: 'RELATIONSHIP',
      label: 'Odalys, who put your sister forward for that posting',
      seedHint: 'She knows your surname and does not react to it.',
      payoffHint: 'She recommended Wren, and she has been waiting to be asked.',
      weight: 0.8,
    },
    {
      id: 'promise_class_ceiling',
      kind: 'THEME',
      label: 'What your order can eventually make you',
      seedHint: 'Empty perches at the end of the animal lines, sized for something much larger than a horse.',
      payoffHint: 'The top of every order is absurd, and the wall needs it to be.',
      weight: 0.7,
    },
    {
      id: 'promise_the_gate',
      kind: 'FINALE',
      label: 'The chained door of the eleventh gatehouse',
      seedHint: 'Rebuilt stone with the scorching left underneath it, and a chain that is newer than the repair.',
      payoffHint: 'Three keys were cut for that door. Two are accounted for.',
      weight: 1,
    },
  ],
  archetypes: [
    {
      id: 'arch_warrior',
      name: 'Warrior',
      role: 'Heavy melee',
      summary:
        'Armour, a big weapon, and eventually something enormous to ride. You break charges and hold ground nobody else can hold.',
      playstyle: ['Front line', 'Strongest', 'Mounted'],
      blurb: 'Heavy armour, heavy weapons, and eventually something enormous to ride. You are the part of the line that does not move.',
      attributeBonus: { might: 3, resolve: 1 },
      skillProficiencies: { warfare: 3, blades: 2, riding: 2, endurance: 1 },
      startingItems: [{ itemId: 'field_kit', qty: 1 }],
      startingAbilities: ['break_charge', 'call_the_mount'],
      startingReputation: [{ factionId: 'faction_iron_march', amount: 20 }],
    },
    {
      id: 'arch_rogue',
      name: 'Rogue',
      role: 'Stealth and blades',
      summary:
        'Fast, quiet, and never quite alone — an animal attaches itself to you and can be sent into places you cannot go.',
      playstyle: ['Stealth', 'Fast blades', 'Animal companion'],
      blurb: 'Fast blades, dark ground, and an animal that picks you rather than the other way round.',
      attributeBonus: { agility: 3, mind: 1 },
      skillProficiencies: { blades: 2, stealth: 3, beastlore: 2, insight: 1 },
      startingItems: [{ itemId: 'field_kit', qty: 1 }],
      startingAbilities: ['open_the_seam', 'send_the_bond'],
      startingReputation: [{ factionId: 'faction_silent_rank', amount: 20 }],
    },
    {
      id: 'arch_archer',
      name: 'Archer',
      role: 'Ranged attacker',
      summary:
        'You fight from distance and height, hold a shot until it is worth taking, and mark targets so everyone else hits them too.',
      playstyle: ['Ranged', 'Precise', 'Sets others up'],
      blurb: 'Range, height, and the discipline to hold a shot. The great bows on the spurs are crewed, and one day commanded, by people who started here.',
      attributeBonus: { agility: 2, mind: 2 },
      skillProficiencies: { archery: 3, insight: 2, endurance: 1, command: 1 },
      startingItems: [{ itemId: 'field_kit', qty: 1 }],
      startingAbilities: ['held_shot', 'mark_it'],
      startingReputation: [{ factionId: 'faction_longwatch', amount: 20 }],
    },
    {
      id: 'arch_sorcerer',
      name: 'Sorcerer',
      role: 'Elemental magic',
      summary:
        'You bind one element now and a second if you live long enough, and you can leave a working running after you have walked away from it.',
      playstyle: ['Magic damage', 'Controls ground', 'Physically frail'],
      blurb: 'One element bound now, a second if you live long enough, and a working that keeps running after you walk away.',
      attributeBonus: { arcana: 3, mind: 1 },
      skillProficiencies: { sorcery: 3, insight: 2, endurance: 1 },
      startingItems: [{ itemId: 'ward_salt', qty: 2 }],
      startingAbilities: ['first_element', 'hold_open'],
      startingReputation: [{ factionId: 'faction_bright_hall', amount: 20 }],
    },
    {
      id: 'arch_healer',
      name: 'Healer',
      role: 'Healing — and the reverse of it',
      summary:
        'You hold people together, and the same grip run backwards takes a body apart. You keep a squad alive and you are genuinely dangerous at arm’s length.',
      playstyle: ['Keeps people alive', 'Lethal up close', 'Everyone wants you'],
      blurb: 'You hold people together, and the same grip run backwards takes something apart. Nobody on this wall is frightened of the Iron March.',
      attributeBonus: { arcana: 2, presence: 1, resolve: 1 },
      skillProficiencies: { mending: 3, insight: 2, endurance: 1, command: 1 },
      startingItems: [{ itemId: 'ward_salt', qty: 2 }, { itemId: 'field_kit', qty: 1 }],
      startingAbilities: ['thread', 'the_cut'],
      startingReputation: [{ factionId: 'faction_stillhand', amount: 20 }],
    },
  ],
  setupFields: [
    { id: 'displayName', label: 'What name is on the roll?', kind: 'TEXT', required: true, maxLength: 40, placeholder: 'e.g. Rell Calloway' },
    { id: 'pronouns', label: 'Pronouns', kind: 'TEXT', required: false, maxLength: 24, placeholder: 'e.g. they/them' },
    {
      id: 'archetype',
      label: 'Choose your class',
      helpText:
        'This is the biggest decision on this screen. Your class sets your attributes, training, starting techniques and kit — and several problems later in the story can only be solved by the class that has the right tool for them. It is fixed for this run.',
      kind: 'ARCHETYPE',
      required: true,
    },
    {
      id: 'worldKnowsAboutYou',
      label: 'What does the wall already know about you?',
      kind: 'TEXT',
      required: false,
      maxLength: 300,
      placeholder: 'e.g. I am Wren Calloway’s little sibling and everyone here has decided how they feel about that.',
    },
    {
      id: 'origin',
      label: 'Where did you grow up?',
      kind: 'CHOICE',
      advanced: true,
      options: [
        { id: 'farm_towns', label: 'The farm towns the wall protects' },
        { id: 'wall_born', label: 'On the wall — a garrison family' },
        { id: 'inland_city', label: 'The inland city, which has never seen a tide' },
        { id: 'north_of_it', label: 'North of the wall, which you do not advertise' },
      ],
    },
    {
      id: 'appearance',
      label: 'What do people notice first?',
      kind: 'TEXT',
      advanced: true,
      maxLength: 200,
      placeholder: 'e.g. Too small for the armour they issued me, and I have not asked for a smaller set.',
    },
  ],
  opening:
    'The roll goes up on the post at first light, and everyone reads it on the way past whether they mean to or not.\n\n' +
    'You are nineteenth. Hollis Ferrant is first, and is standing close enough to watch you find that out.\n\n' +
    'Down the yard, Drillmaster Odalys Verne reads your surname off the intake sheet, stops for exactly as long as it takes to decide not to say anything, and moves on to the next name.\n\n' +
    'Bec Tarrow is at the edge of the sand with his hands in his pockets, not in formation, watching you. He told you what he saw four days ago and has not met your eye since.\n\n' +
    '"Front rank," Odalys says. "We start whether you are ready or not."',
  openingSuggestions: [
    'I take a place in the front rank without being asked, and set my feet like I intend to stay there.',
    'I catch Odalys before the line settles. “Nineteenth. I want to know what I did to earn that, or what you think I did.”',
    'I get to Bec before drill starts and keep my voice down. “What is the one thing nobody tells the new ones?”',
  ],
  publishedAt: '2026-09-09T09:00:00.000Z',
};

export const TIDEWALL = StoryVersion.parse(raw);
