import { StoryVersion } from '@plotbreak/contracts';

/**
 * "The Unbound" — an original internal-energy world built for build freedom.
 *
 * The design problem with this fantasy is that it usually resolves into a
 * character sheet chosen at minute one. Here the premise itself is the
 * justification for an open build: the player's school was dissolved and they
 * are attached to another on probation, so they belong to nobody and can be
 * taught by anyone. Half the abilities are not in any archetype at all — they
 * are awakened, taught, or found, which means two players end the first arc
 * with different verbs available rather than different numbers.
 *
 * Original throughout: the schools, the Concord, the leans, the openings and
 * the forbidden form are this world's own. Parsed at import so a malformed
 * world fails the build, not a player's session.
 */

const raw = {
  id: 'sv_unbound_1',
  storyId: 'story_unbound',
  version: 1,
  title: 'The Unbound',
  fantasyLabel: 'Your school was dissolved. You were not.',
  hook: 'Your school was dissolved and its students parcelled out. You are the one nobody has decided what to do with yet.',
  premise:
    'Everyone here trains breath — the energy a body carries — into forms, which are the techniques a fighter can actually use. Five schools in the river city of Anvar Reach teach it, and every child is bound to one of them at fourteen, for life.\n\n' +
    'Six months ago your school was dissolved. The Concord that governs the other five ruled that your master had taught a form nobody is allowed to teach. It sealed the doors and parcelled the students out like furniture.\n\n' +
    'You went to the Kiln, which trains nothing like the way you were raised. You are there on probation, which means you are a guest who can be sent away, and you have to earn a full place before the year’s assessment or leave with nothing.\n\n' +
    'Your master says he never taught it. Somebody did, because that form has been used three times outside these walls this year, and each one is a death nobody has explained.\n\n' +
    'So there are two things to do at once. Earn a place in a school that did not ask for you, and find out who actually taught that form, before the Concord finishes deciding what to do with the man who says he did not.',
  creatorId: 'creator_official',
  creatorName: 'Plotbreak Studios',
  official: true,
  coverImage: 'unbound/cover',
  keyArt: 'unbound/key',
  tags: ['Martial arts', 'Anime', 'Mystery', 'Rivalry', 'Coming of age'],
  mechanicsChips: ['Build freedom', 'Awakened powers', 'Rival schools', 'Contract work', 'Forbidden forms'],
  contentDescriptors: ['FANTASY_VIOLENCE', 'MORAL_AMBIGUITY', 'PSYCHOLOGICAL_THEMES', 'ROMANCE'],
  intensity: 'MODERATE',
  creatorNote:
    'Half of what your character will eventually do is not on the setup screen. It gets taught to you, or it wakes up in you at a bad moment, or you find it written down somewhere it should not be. Two players should not end up with the same list of things they can do.',
  rules: {
    defeatMode: 'FAIL_FORWARD',
    progressionMode: 'MILESTONE',
    revealExactDc: false,
    revealCheckMath: false,
    allowsCombat: true,
    allowsRomance: true,
    startingLocationId: 'kiln_yard',
    startWorldMinute: 5 * 60 + 30,
    startingItems: [
      { itemId: 'oyan_band', qty: 1 },
      { itemId: 'probation_slip', qty: 1 },
    ],
    hardCanon: [
      'Breath is trained, not inherited. What is inherited is how easily it leans one way.',
      'A form used on someone leaves a trace in them that another trained fighter can read for about a day.',
      'The Concord governs the five schools. It has no fighters of its own and has never needed any.',
      'An opening — a change in the eyes — cannot be taught, bought, or faked. It happens or it does not.',
      'Oyan House is sealed, not demolished. Everything in it is still in it.',
    ],
    toneGuide:
      'Early mornings, cold river air, and teenagers who are extremely serious about a craft. Training is repetitive and physical; power is quiet until it is not. Rivalries are real and mostly affectionate. No speeches mid-fight.',
    forkCostCredits: 120,
  },
  attributes: { might: 10, agility: 12, mind: 11, presence: 11, resolve: 11, arcana: 12 },
  skills: [
    { id: 'breathwork', name: 'Breathwork', attribute: 'arcana', description: 'Moving your own energy without spilling it.' },
    { id: 'hand_forms', name: 'Hand Forms', attribute: 'might', description: 'Everything done with an empty hand, close in.' },
    { id: 'blade_forms', name: 'Blade Forms', attribute: 'agility', description: 'Short steel, drawn late and put away early.' },
    { id: 'thrown_forms', name: 'Thrown Forms', attribute: 'agility', description: 'What leaves your hand and still belongs to you.' },
    { id: 'stillness', name: 'Stillness', attribute: 'resolve', description: 'Holding a form open while somebody is hitting you.' },
    { id: 'reading', name: 'Reading', attribute: 'mind', description: 'Seeing the trace a form leaves, and who left it.' },
    { id: 'stealth', name: 'Stealth', attribute: 'agility', description: 'The city at night, and the parts of it that are watched.' },
    { id: 'persuasion', name: 'Persuasion', attribute: 'presence', description: 'Getting a straight answer from someone paid not to give one.' },
    { id: 'lore', name: 'School Lore', attribute: 'mind', description: 'Who taught whom, and what they stopped teaching.' },
    { id: 'endurance', name: 'Endurance', attribute: 'resolve', description: 'The fourth hour of the same drill.' },
  ],
  resources: [
    {
      id: 'health',
      name: 'Health',
      max: 24,
      start: 24,
      regenPerHour: 1,
      polarity: 'GOOD_HIGH',
      displayPriority: 1,
      visible: true,
      zeroStateConsequence: 'You go down. The Kiln keeps a room for it and a very short memory about who used it.',
      color: '#FF5B69',
    },
    {
      id: 'breath',
      name: 'Breath',
      max: 22,
      start: 22,
      regenPerHour: 4,
      polarity: 'GOOD_HIGH',
      displayPriority: 2,
      visible: true,
      zeroStateConsequence: 'Empty. Forms will not hold, and everyone trained can see that they will not.',
      color: '#6CC8FF',
    },
    {
      id: 'standing',
      name: 'Standing',
      max: 100,
      start: 10,
      regenPerHour: 0,
      polarity: 'GOOD_HIGH',
      displayPriority: 3,
      visible: true,
      zeroStateConsequence: 'Your probation is reviewed early, and early reviews go one way.',
      color: '#5FD3A8',
    },
    {
      id: 'strain',
      name: 'Strain',
      max: 100,
      start: 0,
      regenPerHour: -3,
      polarity: 'GOOD_LOW',
      displayPriority: 4,
      visible: true,
      zeroStateConsequence: 'Rested. Nothing is fraying.',
      color: '#F6BE55',
    },
  ],
  items: [
    {
      id: 'oyan_band',
      name: "Oyan House Band",
      tags: ['quest', 'clothing'],
      questItem: true,
      droppable: false,
      description: 'A plain grey wrist band from a school that the Concord has ruled no longer exists. Wearing it is not illegal. It is just noticed.',
      loreText: 'The dye is river silt. Everyone in the city knows the colour and nobody says so.',
      icon: 'band',
    },
    {
      id: 'probation_slip',
      name: 'Probation Slip',
      tags: ['quest', 'document'],
      questItem: true,
      droppable: false,
      description: 'One card, stamped by the Kiln, listing what you may do here and what you may not. The second list is longer.',
      loreText: 'There is a line at the bottom for a full-student signature. It is empty.',
      icon: 'card',
    },
    {
      id: 'river_salt',
      name: 'River Salt',
      tags: ['consumable'],
      stackable: true,
      maxStack: 5,
      consumable: { resourceId: 'strain', amount: -18, consumesItem: true },
      description: 'Coarse salt from the tidal reach, taken under the tongue. Settles breath that has been pushed too far.',
      loreText: 'Sold on the stair by people who are not supposed to be selling it.',
      icon: 'salt',
    },
    {
      id: 'wrapped_blade',
      name: 'Wrapped Short Blade',
      tags: ['blade'],
      equipSlot: 'hand',
      skillModifiers: { blade_forms: 2 },
      description: 'A student blade, edge wrapped in linen because probationers are not allowed a live one.',
      loreText: 'The wrapping comes off in about four seconds. Everyone knows that too.',
      icon: 'blade',
    },
    {
      id: 'trace_glass',
      name: 'Reading Glass',
      tags: ['tool'],
      equipSlot: 'hand',
      skillModifiers: { reading: 2 },
      description: 'A palm-sized disc of dark glass. Held over a fresh trace it shows the shape of the form that made it.',
      loreText: 'Standard issue to Concord readers. Not standard issue to you.',
      icon: 'glass',
    },
    {
      id: 'sealed_page',
      name: 'Page From a Sealed Room',
      tags: ['quest', 'document'],
      questItem: true,
      droppable: false,
      description: 'One page of a training record, in your master’s hand, listing a student he taught privately and never registered.',
      loreText: 'The name has been gone over twice with the same pen, which is not how you correct a mistake.',
      icon: 'page',
    },
  ],
  abilities: [
    {
      id: 'settle',
      name: 'Settle',
      tags: ['universal', 'utility'],
      description: 'Put your breath back where it belongs before it costs you something.',
      affordances: ['settle my breath', 'steady myself', 'breathe', 'centre myself', 'calm down'],
      costs: [],
      cooldownMinutes: 30,
      targetRule: 'SELF',
      check: null,
      unlockedByDefault: true,
    },
    {
      id: 'read_trace',
      name: 'Read the Trace',
      tags: ['universal', 'utility'],
      description: 'Look at what a form left behind in a person or a place and tell what shape it was.',
      affordances: ['read the trace', 'check what hit him', 'look for the trace', 'read the room for breath'],
      costs: [{ resourceId: 'breath', amount: 3 }],
      cooldownMinutes: 0,
      targetRule: 'SINGLE',
      check: { attribute: 'mind', skillId: 'reading', baseDc: 12 },
      unlockedByDefault: true,
    },
    {
      id: 'ember_palm',
      name: 'Ember Palm',
      tags: ['ember', 'offensive'],
      description: 'Heat carried in the hand and put into something at the moment of contact.',
      affordances: ['ember palm', 'burn him', 'strike with heat', 'put fire in the hit'],
      costs: [{ resourceId: 'breath', amount: 6 }],
      cooldownMinutes: 10,
      targetRule: 'SINGLE',
      check: { attribute: 'might', skillId: 'hand_forms', baseDc: 13 },
      unlockedByDefault: false,
    },
    {
      id: 'tide_turn',
      name: 'Turning Tide',
      tags: ['tide', 'defensive'],
      description: 'Take the force arriving at you and give it somewhere else to go.',
      affordances: ['turn it', 'redirect the strike', 'use his weight', 'send it past me'],
      costs: [{ resourceId: 'breath', amount: 5 }],
      cooldownMinutes: 5,
      targetRule: 'SINGLE',
      check: { attribute: 'agility', skillId: 'stillness', baseDc: 13 },
      unlockedByDefault: false,
    },
    {
      id: 'stone_root',
      name: 'Rooting',
      tags: ['stone', 'defensive'],
      description: 'Make yourself, briefly, part of the ground you are standing on.',
      affordances: ['root myself', 'hold my ground', 'plant and take it', 'set like stone'],
      costs: [{ resourceId: 'breath', amount: 4 }],
      cooldownMinutes: 15,
      targetRule: 'SELF',
      check: { attribute: 'resolve', skillId: 'stillness', baseDc: 12 },
      unlockedByDefault: false,
    },
    {
      id: 'gale_step',
      name: 'Gale Step',
      tags: ['gale', 'movement'],
      description: 'Two paces of distance that were not available a moment ago.',
      affordances: ['gale step', 'step past him', 'close the distance', 'get behind him'],
      costs: [{ resourceId: 'breath', amount: 5 }],
      cooldownMinutes: 10,
      targetRule: 'SELF',
      check: { attribute: 'agility', skillId: 'breathwork', baseDc: 13 },
      unlockedByDefault: false,
    },
    {
      id: 'thrown_line',
      name: 'Thrown Line',
      tags: ['universal', 'ranged'],
      description: 'Something leaves your hand with your breath still attached to it.',
      affordances: ['throw it', 'send the blade', 'throw and pull', 'line it at him'],
      costs: [{ resourceId: 'breath', amount: 4 }],
      cooldownMinutes: 5,
      targetRule: 'SINGLE',
      check: { attribute: 'agility', skillId: 'thrown_forms', baseDc: 12 },
      unlockedByDefault: false,
    },
    {
      id: 'quiet_opening',
      name: 'The Quiet Opening',
      tags: ['awakened', 'sight'],
      description:
        'Your eyes change. For a few seconds you see what a person is about to do, roughly a breath before they do it.',
      affordances: ['open my eyes', 'use the opening', 'look at him properly', 'see it coming'],
      costs: [{ resourceId: 'breath', amount: 8 }, { resourceId: 'strain', amount: 12 }],
      cooldownMinutes: 120,
      targetRule: 'SINGLE',
      check: { attribute: 'arcana', skillId: 'breathwork', baseDc: 15 },
      unlockedByDefault: false,
    },
    {
      id: 'lantern_opening',
      name: 'The Lantern Opening',
      tags: ['awakened', 'sight'],
      description:
        'Your eyes change the other way. You stop seeing people and start seeing where their breath is pooled.',
      affordances: ['use the lantern', 'see the breath', 'look for where it pools', 'open the lantern'],
      costs: [{ resourceId: 'breath', amount: 7 }, { resourceId: 'strain', amount: 10 }],
      cooldownMinutes: 120,
      targetRule: 'NONE',
      check: { attribute: 'arcana', skillId: 'reading', baseDc: 15 },
      unlockedByDefault: false,
    },
    {
      id: 'the_unnamed_form',
      name: 'The Unnamed Form',
      tags: ['forbidden', 'offensive'],
      description:
        'The form that got your school closed. It does not hit a body. It takes hold of the breath inside one and stops it.',
      affordances: ['use the form', 'the unnamed form', 'stop his breath', 'do the thing they closed us for'],
      costs: [{ resourceId: 'breath', amount: 12 }, { resourceId: 'strain', amount: 30 }],
      cooldownMinutes: 240,
      targetRule: 'SINGLE',
      check: { attribute: 'arcana', skillId: 'breathwork', baseDc: 17 },
      unlockedByDefault: false,
    },
  ],
  locations: [
    {
      id: 'kiln_yard',
      takeableItems: [
        { itemId: 'wrapped_blade', qty: 1, ownerId: null, aka: ['blade', 'the wrapped blade'] },
      ],
      name: 'The Kiln Yard',
      shortName: 'Kiln',
      description:
        'A walled square of packed red earth behind the Kiln’s furnaces, warm even before sunrise. Two hundred students train here in shifts and the earth never gets a chance to cool.',
      artDirection: 'Pre-dawn, red packed earth, brick furnace wall throwing heat shimmer, rows of students, low orange light.',
      stageImage: 'unbound/stage_kiln_yard',
      discoveredByDefault: true,
      mapPosition: { x: 0.5, y: 0.85 },
      ambientSfx: ['fire_low', 'feet_earth'],
      connections: [
        { to: 'river_stair', travelMinutes: 8, label: 'Down to the river stair' },
        { to: 'contract_office', travelMinutes: 12, label: 'Across to the office' },
      ],
    },
    {
      id: 'river_stair',
      name: 'The River Stair',
      shortName: 'Stair',
      description:
        'Ninety wide stone steps from the upper city down to the water, where students from all five schools pass each other twice a day and pretend not to look. Everything unofficial in this city happens on these steps.',
      artDirection: 'Wide stone stair to a broad river at dawn, mist, small stalls on the landings, mixed uniforms.',
      stageImage: 'unbound/stage_river_stair',
      discoveredByDefault: true,
      mapPosition: { x: 0.5, y: 0.6 },
      ambientSfx: ['water', 'crowd_murmur'],
      connections: [
        { to: 'kiln_yard', travelMinutes: 8, label: 'Up to the Kiln' },
        { to: 'night_market', travelMinutes: 10, label: 'Along the water' },
        { to: 'oyan_house', travelMinutes: 14, label: 'North to the sealed house' },
        { to: 'contract_office', travelMinutes: 9, label: 'Up to the office' },
      ],
    },
    {
      id: 'contract_office',
      name: 'The Contract Office',
      shortName: 'Office',
      description:
        'A long counter, five queues, and a board of work the schools have agreed to let students take. The clerk behind the counter belongs to none of the five, which is the entire point of her.',
      artDirection: 'Institutional stone hall, long wooden counter, a wall of pinned paper notices, cold north light.',
      stageImage: 'unbound/stage_contract_office',
      discoveredByDefault: true,
      mapPosition: { x: 0.76, y: 0.55 },
      ambientSfx: ['paper', 'low_voices'],
      connections: [
        { to: 'kiln_yard', travelMinutes: 12, label: 'Back to the Kiln' },
        { to: 'river_stair', travelMinutes: 9, label: 'Down to the stair' },
        { to: 'concord_hall', travelMinutes: 7, label: 'Up to the Concord' },
      ],
    },
    {
      id: 'night_market',
      takeableItems: [
        { itemId: 'trace_glass', qty: 1, ownerId: null, aka: ['glass', 'the trace glass', 'the lens'] },
      ],
      name: 'The Night Market',
      shortName: 'Market',
      description:
        'Four streets of awnings along the water that only open after dark, selling food, salt, and the occasional thing a school would confiscate. Nobody here asks which band you wear.',
      artDirection: 'Night, lantern strings over narrow streets, steam from food stalls, dark water at the end of every alley.',
      stageImage: 'unbound/stage_night_market',
      discoveredByDefault: true,
      mapPosition: { x: 0.26, y: 0.45 },
      ambientSfx: ['crowd_murmur', 'sizzle'],
      connections: [{ to: 'river_stair', travelMinutes: 10, label: 'Back along the water' }],
    },
    {
      id: 'oyan_house',
      takeableItems: [
        { itemId: 'river_salt', qty: 1, ownerId: null, aka: ['salt', 'river salt'] },
      ],
      name: 'Oyan House',
      shortName: 'Oyan',
      description:
        'Your old school, doors sealed with a Concord band and a wax stamp, everything still inside it. The training floor is visible through the window grille and has not been swept since the ruling.',
      artDirection: 'Shuttered martial school at dusk, sealed doors with an official paper band, dust in shafts of light.',
      stageImage: 'unbound/stage_oyan_house',
      discoveredByDefault: true,
      mapPosition: { x: 0.5, y: 0.28 },
      ambientSfx: ['wind_low', 'timber_creak'],
      connections: [{ to: 'river_stair', travelMinutes: 14, label: 'South to the stair' }],
    },
    {
      id: 'concord_hall',
      name: 'The Concord Hall',
      shortName: 'Concord',
      description:
        'Where five schools that would rather not agree do it in writing anyway. Visitors wait on a bench in the entry and are told, politely, exactly how long they will be waiting.',
      artDirection: 'Cold formal stone antechamber, five banners, a single long bench, tall doors that stay shut.',
      stageImage: 'unbound/stage_concord_hall',
      discoveredByDefault: true,
      mapPosition: { x: 0.82, y: 0.32 },
      ambientSfx: ['stone_echo', 'clock'],
      connections: [
        { to: 'contract_office', travelMinutes: 7, label: 'Down to the office' },
        { to: 'confinement_house', travelMinutes: 6, label: 'Through to the back court' },
      ],
    },
    {
      id: 'confinement_house',
      name: 'The Confinement House',
      shortName: 'Confinement',
      description:
        'Three rooms behind the Concord where people awaiting a ruling are kept comfortably and absolutely. There is tea, a window, and a door that opens on someone else’s decision.',
      artDirection: 'Plain warm room, barred window on a courtyard, a table with two cups, one door with no handle inside.',
      stageImage: 'unbound/stage_confinement_house',
      discoveredByDefault: false,
      mapPosition: { x: 0.9, y: 0.16 },
      ambientSfx: ['clock', 'distant_court'],
      connections: [{ to: 'concord_hall', travelMinutes: 6, label: 'Back to the hall' }],
    },
  ],
  characters: [
    {
      id: 'renna',
      name: 'Renna Vosk',
      role: 'Kiln instructor, holds your probation',
      cardBlurb:
        'The instructor who decides whether the Kiln keeps you. She did not want you and says so, which is the most honest thing anyone here has done.',
      pronouns: 'she/her',
      publicTraits: ['Direct', 'Overworked', 'Allergic to sentiment'],
      hiddenDrives: [
        'She argued against taking Oyan students and lost, and she is determined not to be proved right.',
        'She trained under your master for two years and has never told anyone at the Kiln.',
      ],
      values: ['Work that shows', 'Saying what she means once', 'Students not dying on contracts'],
      fears: ['Signing off on someone who is not ready', 'Being asked about Oyan House in public'],
      socialStyle: 'Blunt, fast, and fair. Corrects you in front of everyone and defends you the same way.',
      boundaries: ['Will not teach an Oyan form on Kiln ground', 'Will not sign a probation early to be liked'],
      goals: ['Get this intake through the assessment', 'Find out what her old master actually did'],
      secrets: [
        {
          id: 'renna_trained_under_sedge',
          fact: 'Renna spent two years as Sedge Oyan’s student before transferring to the Kiln.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Comes out at trust 35+, or instantly if the player performs a recognisably Oyan form in front of her.',
        },
        {
          id: 'renna_knows_the_shape',
          fact: 'Renna has read one of the three traces herself and knows it was not made by an Oyan hand.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Requires respect 45+ and the reading glass in the player’s possession.',
        },
      ],
      speechStyle:
        'Imperative sentences and no filler. Calls you "probationer" until she decides otherwise, then uses your name and does not explain the change.',
      topics: ['my probation', 'the assessment', 'Oyan forms', 'what a trace can tell you'],
      voiceSamples: [
        'You are not a student here. You are a guest with a slip. Train like it and I will fix that.',
        'I did not ask for you. That is not the same as wanting you gone, so stop looking for it.',
        'Do it again. Slower. I want to see where you learned it.',
      ],
      appearance: 'Thirties, forearms permanently reddened from the furnace wall, hair cut short with a knife.',
      visualHook:
        'Both forearms burned an even brick red to the elbow from years against the furnace wall, and hair cropped raggedly short as if done in a hurry with a blade.',
      silhouette:
        'Compact and squared, arms folded high on the chest, standing close enough to correct your stance without moving.',
      artSeed: 'renna-vosk-v1',
      portrait: 'unbound/renna',
      expressions: ['neutral', 'stern', 'assessing', 'impatient', 'approving', 'guarded'],
      voiceId: 'voice_renna',
      homeLocationId: 'kiln_yard',
      knowledgeScope: ['faction_kiln', 'faction_concord'],
      schedule: [
        { startMinute: 300, endMinute: 660, locationId: 'kiln_yard', activity: 'Morning shifts' },
        { startMinute: 660, endMinute: 780, locationId: 'contract_office', activity: 'Signing contracts out' },
        { startMinute: 780, endMinute: 1080, locationId: 'kiln_yard', activity: 'Afternoon shifts' },
        { startMinute: 1080, endMinute: 1200, locationId: 'river_stair', activity: 'Walking down to the water' },
        { startMinute: 1200, endMinute: 1380, locationId: 'kiln_yard', activity: 'Last shift and the log' },
      ],
      startingRelationship: { trust: 5, affection: 0, respect: 8, fear: 5, rivalry: 0 },
      attributes: { might: 14, agility: 13, mind: 14, presence: 14, resolve: 15, arcana: 14 },
      gates: [
        {
          id: 'renna_teaches_you',
          kind: 'TRUST',
          label: 'Renna will teach you something off the syllabus',
          requires: { respect: 40, flagsSet: ['renna_saw_you_work'], flagsUnset: ['renna_lost_faith'] },
        },
        {
          id: 'renna_signs_you',
          kind: 'ALLIANCE',
          label: 'Renna will sign your full-student line',
          requires: { respect: 60, trust: 40, flagsSet: ['assessment_passed'] },
        },
      ],
      combatant: { health: 34, defenseDc: 16, damage: 8, tags: ['instructor', 'nonlethal'] },
    },
    {
      id: 'tam',
      name: 'Tam Ashgrove',
      role: 'Kiln full student, third year',
      cardBlurb:
        'The student whose place you are standing in. He is not cruel about it, which is somehow worse.',
      pronouns: 'he/him',
      publicTraits: ['Charming', 'Competitive', 'Genuinely good at this'],
      hiddenDrives: [
        'His family paid for his place and he has never been sure the Kiln would have taken him otherwise.',
        'He wants to be beaten by someone honestly, once, so he knows where he actually stands.',
      ],
      values: ['Being liked', 'Winning cleanly', 'Not being his father'],
      fears: ['That he is only here because of money', 'Losing in front of Renna'],
      socialStyle: 'Warm in public, needling in private, and completely straight the moment you are actually hurt.',
      boundaries: ['Will not report you for something he would also do', 'Will not throw a match'],
      goals: ['Top the assessment', 'Get a first contract with his name on it'],
      secrets: [
        {
          id: 'tam_bought_in',
          fact: 'Tam’s place at the Kiln was arranged by a payment from his family.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Only at trust 40+, and never where another student could hear.',
        },
        {
          id: 'tam_saw_the_third',
          fact: 'Tam was on the stair the night of the third death and saw who left.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Requires trust 50+ or beating him in a real match.',
        },
      ],
      speechStyle:
        'Quick, funny, and always slightly a challenge. Uses your name constantly. Drops the performance when someone is bleeding.',
      topics: ['the assessment', 'the Kiln', 'what happened on the stair', 'my family'],
      voiceSamples: [
        'Oyan, is it? I have heard the forms are pretty. Show me a pretty one.',
        'You are not bad. That is a genuine compliment and I would like it noted.',
        'I was on the stair that night. I have not said that to anyone, so do not make me regret it.',
      ],
      appearance: 'Twenty, tall, expensive haircut growing out, Kiln reds worn slightly too well.',
      visualHook:
        'Kiln reds tailored better than anyone else’s and an expensive haircut three months past its shape, growing out unevenly.',
      silhouette:
        'Tall and easy, hands loose at his sides, standing with his weight back like he has already decided he is not worried.',
      artSeed: 'tam-ashgrove-v1',
      portrait: 'unbound/tam',
      expressions: ['neutral', 'grinning', 'competitive', 'stung', 'serious', 'sheepish'],
      voiceId: 'voice_tam',
      homeLocationId: 'kiln_yard',
      knowledgeScope: ['faction_kiln'],
      schedule: [
        { startMinute: 300, endMinute: 660, locationId: 'kiln_yard', activity: 'Morning shifts' },
        { startMinute: 660, endMinute: 840, locationId: 'river_stair', activity: 'Being seen on the stair' },
        { startMinute: 840, endMinute: 1080, locationId: 'kiln_yard', activity: 'Afternoon shifts' },
        { startMinute: 1080, endMinute: 1320, locationId: 'night_market', activity: 'Eating badly with friends' },
        { startMinute: 1320, endMinute: 1440, locationId: 'kiln_yard', activity: 'Sneaking in late' },
      ],
      startingRelationship: { trust: 8, affection: 8, respect: 5, fear: 0, rivalry: 20 },
      attributes: { might: 13, agility: 14, mind: 12, presence: 15, resolve: 12, arcana: 13 },
      gates: [
        {
          id: 'tam_takes_you_seriously',
          kind: 'TRUST',
          label: 'Tam will train with you for real',
          requires: { respect: 35, flagsUnset: ['tam_humiliated'] },
        },
        {
          id: 'tam_tells_you',
          kind: 'ALLIANCE',
          label: 'Tam will say what he saw on the stair',
          requires: { trust: 50, respect: 35, flagsSet: ['attacked:tam'], flagsUnset: ['tam_humiliated'] },
        },
      ],
      combatant: { health: 26, defenseDc: 15, damage: 7, tags: ['student', 'showy'] },
    },
    {
      id: 'sera',
      name: 'Sera Ilm',
      role: 'Oyan student, sent to the Long Quiet',
      cardBlurb:
        'The only other person who grew up in your school. She landed somewhere that suits her, and she is not sure how she feels about that.',
      pronouns: 'she/her',
      publicTraits: ['Watchful', 'Funny in a low voice', 'Slow to commit to anything'],
      hiddenDrives: [
        'She is doing well at the Long Quiet and feels like a traitor for it.',
        'She was the last student in Oyan House before it was sealed, and she took something out with her.',
      ],
      values: ['The people from before', 'Not lying to you specifically', 'Getting out from under it'],
      fears: ['Being made to choose between the two schools out loud', 'What is on the page she took'],
      socialStyle: 'Says less than she knows, then says all of it at once when she decides you have earned it.',
      boundaries: ['Will not go back inside Oyan House', 'Will not let you take the blame for her'],
      goals: ['Pass her own assessment without being noticed', 'Decide what to do with the page'],
      secrets: [
        {
          id: 'sera_has_the_page',
          fact: 'Sera took a page of private training records out of Oyan House on the night it was sealed.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Trust 45+, or if the player is caught trying to get into Oyan House and she has to explain herself.',
        },
        {
          id: 'sera_reported',
          fact: 'Sera answered a Concord reader’s questions honestly, and part of the ruling rests on what she said.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Late reveal. Requires trust 60+ and the page already in the open.',
        },
      ],
      speechStyle:
        'Quiet, precise, and dry. Uses your first name the way people do when it is the only old thing left in the room.',
      topics: ['Oyan House', 'the Long Quiet', 'what she took', 'the master'],
      voiceSamples: [
        'You still wear the band. I put mine in a drawer and I think about the drawer a lot.',
        'The Quiet suits me. I would rather it did not.',
        'Ask me the real question. You have been circling it since the stair.',
      ],
      appearance: 'Nineteen, small, Long Quiet greys, an Oyan band conspicuously not on her wrist.',
      visualHook:
        'Long Quiet greys worn correctly in every detail, and a pale unweathered band of skin on her left wrist where something used to be.',
      silhouette:
        'Small and very still, hands behind her, standing just outside the edge of a group rather than in it.',
      artSeed: 'sera-ilm-v1',
      portrait: 'unbound/sera',
      expressions: ['neutral', 'watchful', 'dry', 'guilty', 'warm', 'closed'],
      voiceId: 'voice_sera',
      homeLocationId: 'river_stair',
      knowledgeScope: ['faction_long_quiet', 'faction_oyan'],
      schedule: [
        { startMinute: 300, endMinute: 600, locationId: 'river_stair', activity: 'Long Quiet morning run' },
        { startMinute: 600, endMinute: 840, locationId: 'contract_office', activity: 'Clerking, for the access' },
        { startMinute: 840, endMinute: 1080, locationId: 'river_stair', activity: 'Watching the stair' },
        { startMinute: 1080, endMinute: 1320, locationId: 'night_market', activity: 'Eating alone on purpose' },
        { startMinute: 1320, endMinute: 1440, locationId: 'river_stair', activity: 'Last one on the steps' },
      ],
      startingRelationship: { trust: 30, affection: 20, respect: 15, fear: 0, rivalry: 0 },
      attributes: { might: 10, agility: 15, mind: 14, presence: 12, resolve: 13, arcana: 14 },
      gates: [
        {
          id: 'sera_shows_the_page',
          kind: 'TRUST',
          label: 'Sera will show you what she took',
          requires: { trust: 45, flagsUnset: ['sera_burned'] },
        },
        {
          id: 'sera_stands_with_you',
          kind: 'ALLIANCE',
          label: 'Sera will say it in front of the Concord',
          requires: { trust: 60, affection: 35, flagsSet: ['spoke:sera', 'has_sealed_page'] },
        },
      ],
      combatant: { health: 20, defenseDc: 16, damage: 6, tags: ['evasive', 'quiet'] },
    },
    {
      id: 'auber',
      name: 'Reader Auber Kell',
      role: 'Concord reader, took the Oyan ruling',
      cardBlurb:
        'The official who read the traces and closed your school. Unfailingly polite, and the only person who has seen all three.',
      pronouns: 'he/him',
      publicTraits: ['Courteous', 'Exact', 'Never in a hurry'],
      hiddenDrives: [
        'He knows the third trace does not match the first two and filed it anyway.',
        'He is waiting for somebody to notice, because he cannot be the one to say it.',
      ],
      values: ['The record being complete', 'Procedure', 'His own signature meaning something'],
      fears: ['Having signed the wrong ruling', 'The fourth one'],
      socialStyle: 'Gives you his whole attention, answers precisely, and concedes nothing you did not already have.',
      boundaries: ['Will not discuss a live ruling with a student', 'Will not lie outright, ever'],
      goals: ['Close the Oyan matter properly', 'Be asked the right question by somebody'],
      secrets: [
        {
          id: 'auber_third_trace',
          fact: 'The third trace was made by a different hand than the first two, and Auber recorded it as the same.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Only if the player brings him a reading of their own, or Renna’s reading of the trace.',
        },
        {
          id: 'auber_taught_once',
          fact: 'Auber studied at Oyan House for one year, forty years ago, and it is not in his file.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Endgame. Requires the sealed page.',
        },
      ],
      speechStyle:
        'Complete, unhurried sentences. Repeats your question back accurately before answering a narrower version of it.',
      topics: ['the ruling', 'the three traces', 'my master', 'what a reader can prove'],
      voiceSamples: [
        'You are asking whether I am certain. I am asking whether you have brought me anything.',
        'I read what was in front of me and I wrote down what I read. Both of those are true.',
        'Bring me a reading. Not an opinion, not a feeling. A reading.',
      ],
      appearance: 'Sixties, small, spectacles on a cord, Concord grey with no school colour anywhere on him.',
      visualHook:
        'Concord grey with no school colour anywhere on it, and a pair of dark reading spectacles worn pushed up on the forehead rather than on the eyes.',
      silhouette:
        'Small and upright with hands folded in front, standing with the patience of someone who has never been late.',
      artSeed: 'auber-kell-v1',
      portrait: 'unbound/auber',
      expressions: ['neutral', 'courteous', 'precise', 'troubled', 'closed', 'relieved'],
      voiceId: 'voice_auber',
      homeLocationId: 'concord_hall',
      knowledgeScope: ['faction_concord', 'faction_kiln', 'faction_long_quiet', 'faction_oyan'],
      schedule: [
        { startMinute: 420, endMinute: 660, locationId: 'concord_hall', activity: 'Morning rulings' },
        { startMinute: 660, endMinute: 780, locationId: 'confinement_house', activity: 'The daily interview' },
        { startMinute: 780, endMinute: 1020, locationId: 'concord_hall', activity: 'Reading room' },
        { startMinute: 1020, endMinute: 1140, locationId: 'contract_office', activity: 'Countersigning' },
        { startMinute: 1140, endMinute: 1320, locationId: 'concord_hall', activity: 'Alone with the file' },
      ],
      startingRelationship: { trust: 0, affection: 0, respect: 5, fear: 10, rivalry: 0 },
      attributes: { might: 8, agility: 9, mind: 17, presence: 14, resolve: 16, arcana: 16 },
      gates: [
        {
          id: 'auber_hears_a_reading',
          kind: 'TRUST',
          label: 'Auber will look at a reading you bring him',
          requires: { respect: 30, flagsSet: ['has_own_reading'] },
        },
        {
          id: 'auber_reopens',
          kind: 'ALLIANCE',
          label: 'Auber will reopen the Oyan ruling',
          requires: { respect: 55, trust: 40, flagsSet: ['ruling_in_question'] },
        },
      ],
      combatant: null,
    },
  ],
  factions: [
    {
      id: 'faction_kiln',
      name: 'The Kiln',
      description: 'Heat and forward pressure. Trains more students than the other four together and loses more of them.',
      startingReputation: -5,
      ranks: [
        { atReputation: -40, label: 'Turned away' },
        { atReputation: -10, label: 'Probationer' },
        { atReputation: 20, label: 'Student' },
        { atReputation: 50, label: 'Full Student' },
        { atReputation: 80, label: 'Hand of the Kiln' },
      ],
      enemies: [],
      allies: ['faction_concord'],
    },
    {
      id: 'faction_long_quiet',
      name: 'The Long Quiet',
      description: 'Distance, patience and things not seen. Takes few students and never advertises which.',
      startingReputation: 0,
      ranks: [
        { atReputation: -40, label: 'Watched' },
        { atReputation: 0, label: 'Known' },
        { atReputation: 30, label: 'Welcome' },
        { atReputation: 60, label: 'Trusted' },
        { atReputation: 85, label: 'Counted' },
      ],
      enemies: ['faction_kiln'],
      allies: [],
    },
    {
      id: 'faction_concord',
      name: 'The Concord',
      description: 'The five schools in writing. Owns no fighters, decides everything, and has never had to raise its voice.',
      startingReputation: -10,
      ranks: [
        { atReputation: -50, label: 'Named in a ruling' },
        { atReputation: -10, label: 'On file' },
        { atReputation: 25, label: 'In good order' },
        { atReputation: 60, label: 'Cited favourably' },
      ],
      enemies: [],
      allies: ['faction_kiln'],
    },
    {
      id: 'faction_oyan',
      name: 'Oyan House',
      description: 'Your school. Dissolved by ruling, sealed by wax, and still the first thing anyone learns about you.',
      startingReputation: 40,
      ranks: [
        { atReputation: 0, label: 'Former student' },
        { atReputation: 30, label: 'One of ours' },
        { atReputation: 70, label: 'Carrying it' },
      ],
      enemies: ['faction_concord'],
      allies: [],
    },
  ],
  quests: [
    {
      id: 'q_the_opening',
      title: 'Something You Were Not Taught',
      summary: 'Your eyes did something at the wrong moment and you would like to know what.',
      kind: 'SIDE',
      startsActive: true,
      involvedCharacterIds: ['sera', 'auber', 'tam'],
      involvedLocationIds: ['river_stair', 'kiln_yard', 'night_market'],
      knownRewardCopy: 'Whatever that was, on purpose, next time.',
      steps: [
        {
          id: 'step_awaken_the_opening',
          playerCopy: 'Find out what happened behind your eyes — and get it to happen again.',
          directorNotes:
            'This is the only way into the Quiet Opening, and it is deliberately reachable three different ways: ' +
            'through a real fight, through someone who has seen it before, or through reading traces until the ' +
            'pattern is obvious. A player who started with no lean needs this. A player who has a lean can still ' +
            'take it and is unusual for having done so. Never hand it over; make them go and get it.',
          succeedWhenAny: [
            {
              routeId: 'opening_under_pressure',
              label: 'It happened in a fight and you kept it',
              predicate: {
                flagsSet: ['attacked:tam'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['opening_awakened', 'opening_by_force', 'tam_saw_your_eyes'],
              closesFlags: ['opening_quietly'],
            },
            {
              routeId: 'opening_shown',
              label: 'Someone who has seen it before showed you',
              predicate: {
                flagsSet: ['spoke:sera', 'visited:river_stair'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'sera', dimension: 'trust', value: 25 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['opening_awakened', 'opening_quietly', 'sera_taught_you'],
              closesFlags: ['opening_by_force'],
            },
            {
              routeId: 'opening_read',
              label: 'You read your way to it',
              predicate: {
                flagsSet: ['used:read_trace', 'spoke:auber'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['opening_awakened', 'opening_quietly', 'auber_knows_you_can'],
              closesFlags: [],
            },
          ],
          rewards: { xp: 70, items: [], flags: [], abilities: ['quiet_opening'] },
        },
      ],
    },
    {
      id: 'q_probation',
      title: 'A Guest With a Slip',
      summary: 'Turn a probation into a place, before the year’s assessment decides for you.',
      kind: 'MAIN',
      startsActive: true,
      involvedCharacterIds: ['renna', 'tam'],
      involvedLocationIds: ['kiln_yard', 'contract_office', 'river_stair'],
      knownRewardCopy: 'A full-student line with a signature on it.',
      steps: [
        {
          id: 'step_first_shift',
          playerCopy: 'Get through your first Kiln shift.',
          directorNotes:
            'Renna is measuring whether the player can take a correction from a school that is not theirs. ' +
            'Using an Oyan form here is not forbidden, but it will be seen and remembered — and which form ' +
            'it is decides what she writes down. The Kiln trains Ember. A hot shift is unremarkable; a ' +
            'stone one is stubborn; a tide one is the thing they have been told not to teach. Every lean ' +
            'gets through. Not every lean gets through the same way.',
          succeedWhenAny: [
            {
              routeId: 'shift_the_kiln_way',
              label: 'You did it the way the Kiln does it',
              predicate: {
                flagsSet: ['used:ember_palm', 'spoke:renna'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'kiln_yard',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['first_shift_done', 'renna_saw_you_work', 'renna_thinks_you_are_kiln'],
              closesFlags: ['renna_watched_you_closely'],
            },
            {
              routeId: 'shift_by_not_moving',
              label: 'You refused to be moved',
              predicate: {
                flagsSet: ['used:stone_root', 'spoke:renna'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'kiln_yard',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['first_shift_done', 'renna_saw_you_work', 'kiln_floor_respects_you'],
              closesFlags: [],
            },
            {
              routeId: 'shift_by_turning_it',
              label: 'You gave the floor back its own force',
              predicate: {
                flagsSet: ['used:tide_turn', 'spoke:renna'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'kiln_yard',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['first_shift_done', 'renna_saw_you_work', 'renna_watched_you_closely', 'oyan_form_seen'],
              closesFlags: ['renna_thinks_you_are_kiln'],
            },
            {
              routeId: 'shift_by_being_elsewhere',
              label: 'You were never where the blow was',
              predicate: {
                flagsSet: ['used:gale_step', 'spoke:renna'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'kiln_yard',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['first_shift_done', 'renna_saw_you_work', 'tam_could_not_touch_you'],
              closesFlags: [],
            },
            {
              routeId: 'shift_by_getting_through_it',
              label: 'You simply got through it',
              predicate: {
                flagsSet: ['spoke:renna'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'kiln_yard',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['first_shift_done', 'renna_saw_you_work'],
              closesFlags: [],
            },
          ],
          rewards: {
            xp: 30,
            items: [{ itemId: 'wrapped_blade', qty: 1 }],
            flags: [],
            // A guest with a slip who works a shift is a guest who has worked a
            // shift. It is not much, and it is the first thing the Kiln has
            // written down about the player that is not the slip.
            reputation: [{ factionId: 'faction_kiln', amount: 30 }],
          },
        },
        {
          id: 'step_earn_the_line',
          playerCopy: 'Give the Kiln a reason to keep you.',
          directorNotes:
            'Four routes, and the player’s build decides which are even available. None of them is the intended one. ' +
            'A player who takes a contract and comes back with the work done is as valid as one who wins the floor.',
          enterWhen: { flagsSet: ['renna_saw_you_work'] },
          succeedWhenAny: [
            {
              routeId: 'line_by_winning',
              label: 'You beat the room',
              predicate: {
                flagsSet: ['attacked:tam'],
                flagsUnset: ['tam_humiliated'],
                hasItems: [],
                atLocation: 'kiln_yard',
                completedEvents: [],
                minRelationship: [{ characterId: 'tam', dimension: 'respect', value: 35 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['assessment_passed', 'route_won_floor', 'tam_respects_you'],
              closesFlags: ['tam_close_friend'],
            },
            {
              routeId: 'line_by_contract',
              label: 'You came back with the work done',
              predicate: {
                flagsSet: ['visited:contract_office', 'spoke:renna'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [{ factionId: 'faction_kiln', value: 20 }],
                beforeWorldMinute: null,
              },
              setsFlags: ['assessment_passed', 'route_contract', 'office_knows_you'],
              closesFlags: [],
            },
            {
              routeId: 'line_by_reading',
              label: 'You made yourself the only one who could read it',
              predicate: {
                flagsSet: ['used:read_trace'],
                flagsUnset: [],
                hasItems: ['trace_glass'],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'renna', dimension: 'respect', value: 40 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['assessment_passed', 'route_reader', 'renna_teaches_you_more'],
              closesFlags: ['route_won_floor'],
            },
            {
              routeId: 'line_by_awakening',
              label: 'Something opened, in front of everyone',
              predicate: {
                flagsSet: ['used:quiet_opening'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['assessment_passed', 'route_awakened', 'concord_watching_you'],
              closesFlags: [],
            },
          ],
          rewards: { xp: 90, items: [], flags: [] },
        },
      ],
    },
    {
      id: 'q_three_traces',
      title: 'Three Traces',
      summary: 'A form nobody is allowed to teach has been used three times. Find out whose hand made them.',
      kind: 'MAIN',
      startsActive: true,
      involvedCharacterIds: ['auber', 'renna', 'sera', 'tam'],
      involvedLocationIds: ['concord_hall', 'river_stair', 'oyan_house', 'night_market'],
      knownRewardCopy: 'A reading the Concord cannot file as the same as the others.',
      steps: [
        {
          id: 'step_learn_to_read',
          playerCopy: 'Learn what a trace actually shows, from someone who can read one.',
          directorNotes:
            'Renna can teach it. So can the market, badly and for money. Auber will not teach it and will say so politely.',
          succeedWhen: {
            flagsSet: ['spoke:renna'],
            minRelationship: [{ characterId: 'renna', dimension: 'respect', value: 25 }],
          },
          rewards: { xp: 40, items: [{ itemId: 'trace_glass', qty: 1 }], flags: ['can_read_traces'] },
        },
        {
          id: 'step_get_a_reading',
          playerCopy: 'Get your own reading of one of the three.',
          directorNotes:
            'Three sources, three costs. The stair is public and recent. The market sells a copy that may be wrong. ' +
            'Oyan House is sealed and going in is a real crime with real consequences.',
          enterWhen: { flagsSet: ['can_read_traces'] },
          succeedWhenAny: [
            {
              routeId: 'reading_stair',
              label: 'You read the third one yourself, on the stair',
              predicate: {
                flagsSet: ['used:read_trace'],
                flagsUnset: [],
                hasItems: ['trace_glass'],
                atLocation: 'river_stair',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['has_own_reading', 'reading_is_clean'],
              closesFlags: [],
            },
            {
              routeId: 'reading_sera',
              label: 'Sera gave you the page instead',
              predicate: {
                flagsSet: ['spoke:sera'],
                flagsUnset: ['sera_burned'],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'sera', dimension: 'trust', value: 45 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['has_own_reading', 'has_sealed_page', 'owe_sera'],
              closesFlags: [],
            },
            {
              routeId: 'reading_break_in',
              label: 'You went into Oyan House',
              predicate: {
                flagsSet: ['visited:oyan_house'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'oyan_house',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
              },
              setsFlags: ['has_own_reading', 'has_sealed_page', 'broke_the_seal'],
              closesFlags: ['reading_is_clean'],
            },
          ],
          rewards: { xp: 80, items: [{ itemId: 'sealed_page', qty: 1 }], flags: [] },
        },
        {
          id: 'step_show_auber',
          playerCopy: 'Put a reading in front of Reader Auber Kell.',
          directorNotes:
            'He has been waiting for this and will not act pleased about it. How the reading was obtained changes ' +
            'what he can do with it — a clean one reopens the ruling, a stolen one gets the player charged as well.',
          enterWhen: { flagsSet: ['has_own_reading'] },
          succeedWhenAny: [
            {
              routeId: 'auber_clean',
              label: 'A reading he can file',
              predicate: {
                flagsSet: ['spoke:auber', 'has_own_reading', 'reading_is_clean'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'auber', dimension: 'respect', value: 30 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['auber_shown_mismatch', 'ruling_in_question', 'auber_can_act_on_it'],
              closesFlags: ['auber_protects_you'],
            },
            {
              routeId: 'auber_stolen',
              label: 'A reading he cannot admit having seen',
              predicate: {
                flagsSet: ['spoke:auber', 'has_own_reading', 'broke_the_seal'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['auber_shown_mismatch', 'ruling_in_question', 'auber_protects_you', 'concord_wants_you'],
              closesFlags: ['auber_can_act_on_it'],
            },
            {
              routeId: 'auber_by_eyes',
              label: 'You showed him what you can do instead',
              predicate: {
                flagsSet: ['spoke:auber', 'used:quiet_opening'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'auber', dimension: 'trust', value: 25 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['auber_shown_mismatch', 'ruling_in_question', 'auber_knows_what_you_are'],
              closesFlags: [],
            },
          ],
          rewards: { xp: 120, items: [], flags: [] },
        },
      ],
    },
  ],
  promises: [
    {
      id: 'promise_who_taught_it',
      kind: 'MYSTERY',
      label: 'Who actually taught the unnamed form',
      seedHint: 'Three deaths, three traces, and one ruling that treats them as the same hand.',
      payoffHint: 'The third does not match the first two, and the reader who filed it knows.',
      weight: 1,
    },
    {
      id: 'promise_your_build',
      kind: 'THEME',
      label: 'What you turn out to be',
      seedHint: 'Nobody owns your training any more, and everyone has something they could teach you.',
      payoffHint: 'A set of forms nobody else in the city has in that combination.',
      weight: 0.9,
    },
    {
      id: 'promise_tam_rival',
      kind: 'RIVAL',
      label: 'Tam Ashgrove, standing where you are trying to stand',
      seedHint: 'He is first on the Kiln floor and welcomes you to it, loudly.',
      payoffHint: 'He was on the stair the night of the third death, and telling you costs him something.',
      weight: 0.8,
    },
    {
      id: 'promise_sera',
      kind: 'RELATIONSHIP',
      label: 'Sera Ilm, the only person who remembers the same rooms you do',
      seedHint: 'She no longer wears the band and has not explained why.',
      payoffHint: 'She took a page out of the house, and part of the ruling rests on what she told them.',
      weight: 0.85,
    },
    {
      id: 'promise_the_room',
      kind: 'FINALE',
      label: 'The room they are keeping your master in',
      seedHint: 'Behind the Concord hall there is a door with no handle on the inside, and tea for two on the table.',
      payoffHint: 'He will answer every question you ask. That turns out to be the difficulty.',
      weight: 1,
    },
  ],
  archetypes: [
    {
      id: 'lean_ember',
      name: 'Ember',
      role: 'Fire affinity — aggressive',
      summary:
        'Close range and heavy. You drive heat through whatever you hit, and you are strong enough to be standing where that matters.',
      playstyle: ['Aggressive', 'Close range', 'Highest damage'],
      blurb: 'Your breath runs hot and wants to go through things. Closest to how the Kiln already trains, which is its own problem.',
      attributeBonus: { might: 2, arcana: 1 },
      skillProficiencies: { hand_forms: 3, breathwork: 2, endurance: 1 },
      startingItems: [{ itemId: 'river_salt', qty: 1 }],
      startingAbilities: ['ember_palm'],
    },
    {
      id: 'lean_tide',
      name: 'Tide',
      role: 'Water affinity — counter-fighter',
      summary:
        'You take the force arriving at you and send it somewhere else. Strongest when you let the other person commit first.',
      playstyle: ['Counter-attacking', 'Redirects force', 'Quick'],
      blurb: 'Your breath prefers to redirect rather than meet. Very hard to teach, very hard to fight.',
      attributeBonus: { agility: 2, resolve: 1 },
      skillProficiencies: { stillness: 3, breathwork: 2, blade_forms: 1 },
      startingItems: [{ itemId: 'river_salt', qty: 1 }],
      startingAbilities: ['tide_turn'],
    },
    {
      id: 'lean_stone',
      name: 'Stone',
      role: 'Earth affinity — defensive',
      summary:
        'You root yourself and become very hard to move, knock down or get past. Slow, durable, and the last one standing.',
      playstyle: ['Defensive', 'Hard to move', 'Outlasts people'],
      blurb: 'Your breath sinks. You are slower than everyone and considerably harder to remove.',
      attributeBonus: { resolve: 2, might: 1 },
      skillProficiencies: { stillness: 3, endurance: 2, hand_forms: 1 },
      startingItems: [{ itemId: 'river_salt', qty: 2 }],
      startingAbilities: ['stone_root'],
    },
    {
      id: 'lean_gale',
      name: 'Gale',
      role: 'Wind affinity — mobility',
      summary:
        'You move first and from further away. Fastest lean, and the only one that starts able to attack at range.',
      playstyle: ['Fast', 'Evasive', 'Fights at range'],
      blurb: 'Your breath moves you before it moves anything else. Distance is a thing you decide.',
      attributeBonus: { agility: 3 },
      skillProficiencies: { breathwork: 2, thrown_forms: 2, stealth: 2 },
      startingItems: [{ itemId: 'river_salt', qty: 1 }],
      startingAbilities: ['gale_step', 'thrown_line'],
    },
    {
      id: 'lean_none',
      name: 'Unsettled',
      role: 'No affinity yet — hardest start',
      summary:
        'You start with no technique at all and the sharpest mind of the five. Your first one is something you awaken during the story rather than pick here — and it is not one of the other four.',
      playstyle: ['Hard early game', 'Study and observation', 'Build decided in play'],
      blurb: 'Nothing has settled. Rare, awkward, and the reason some people end up with a shape nobody has seen before.',
      attributeBonus: { mind: 2, arcana: 1 },
      skillProficiencies: { reading: 2, lore: 2, breathwork: 1 },
      startingItems: [{ itemId: 'river_salt', qty: 2 }],
      startingAbilities: [],
    },
  ],
  setupFields: [
    { id: 'displayName', label: 'What name is on the slip?', kind: 'TEXT', required: true, maxLength: 40, placeholder: 'e.g. Ilan Oyan-Reth' },
    { id: 'pronouns', label: 'Pronouns', kind: 'TEXT', required: false, maxLength: 24, placeholder: 'e.g. she/her' },
    {
      id: 'archetype',
      label: 'Choose a breath style',
      helpText:
        'Breathwork is how people fight here: you push your breath into a shape, and the shape decides what you can do with it. Your lean is the shape yours settles into — it sets your attributes, your training and your first technique. You keep it for the whole story, but you can learn techniques from any lean later by being taught them.',
      kind: 'ARCHETYPE',
      required: false,
    },
    {
      id: 'worldKnowsAboutYou',
      label: 'What do people already say about you?',
      kind: 'TEXT',
      required: false,
      maxLength: 300,
      placeholder: 'e.g. I still wear the Oyan band, and everyone has decided what that means about me.',
    },
    {
      id: 'origin',
      label: 'How did you end up at Oyan House?',
      kind: 'CHOICE',
      advanced: true,
      options: [
        { id: 'bound_normally', label: 'Bound at fourteen like everyone else' },
        { id: 'taken_in', label: 'Taken in late, off the stair' },
        { id: 'family', label: 'Your family has been Oyan for three generations' },
        { id: 'chose_you', label: 'The master picked you out and never said why' },
      ],
    },
    {
      id: 'appearance',
      label: 'What do people notice first?',
      kind: 'TEXT',
      advanced: true,
      maxLength: 200,
      placeholder: 'e.g. Kiln reds that do not fit, and a grey band I have not taken off.',
    },
  ],
  opening:
    'The Kiln trains before light, and the earth in the yard is already warm through your shoes.\n\n' +
    'Two hundred students in red are working the first drill in ranks. You are at the back in the wrong colours, holding a card that says what you are allowed to do here.\n\n' +
    'Renna Vosk walks the line, stops in front of you, and reads the card without taking it out of your hand.\n\n' +
    '"Probationer," she says. "You have been taught to move a different way for five years, and you are going to do it my way for the next hour. When you get it wrong I will say so out loud."\n\n' +
    'Further down the line Tam Ashgrove turns to watch, entirely without malice, which somehow makes it worse.',
  openingSuggestions: [
    'I fall in and do it her way, exactly her way, and keep my mouth shut about the rest.',
    'I hold the form a beat and look at Renna. “What happens if I get this wrong twice? I would rather know now.”',
    'I move through the Oyan version instead — slower, lower, wrong for this room — and let her see all of it.',
  ],
  publishedAt: '2026-09-09T09:00:00.000Z',
};

export const UNBOUND = StoryVersion.parse(raw);
