import { StoryVersion } from '@plotbreak/contracts';

/**
 * "The Understudy" — a social-systems world.
 *
 * Deliberately built on a different spine to The Ninth Archive: no combat, one
 * hard clock, and a Standing resource that the *cast* controls rather than the
 * player. Proves the engine handles a world where every check is a social one.
 */

const raw = {
  id: 'sv_understudy_1',
  storyId: 'story_understudy',
  version: 1,
  title: 'The Understudy',
  fantasyLabel: 'You know the part. You are second choice.',
  hook: 'You are the understudy for the lead. Opening night is in six weeks, and the director does not recast.',
  premise:
    'You are a drama student at the Verrine Company, and you are the understudy for the lead role in this year\'s production. Understudy means you learn the whole part and you do not perform it. You go on only if the lead cannot.\n\n' +
    'The lead is Talia Renn. She is better than you at one thing and worse at four, and everybody in the building knows it, including her. Opening night is in six weeks and the date never moves.\n\n' +
    'You cannot simply out-rehearse her, because the director does not recast after the third week and he has never broken that rule. So the only way in is to become the person the room turns to when something goes wrong.\n\n' +
    'That means favours. The company keeps a book of who owes what, in the director\'s handwriting, and it is read out loud at the end of term. Getting help puts your name in it. So does helping someone else.\n\n' +
    'So you have six weeks to make yourself necessary. That means being the person who fixes things when they go wrong, and it means collecting favours you will have to pay for later. ' +
    'Nobody in this building will ever raise their voice at you. It is still the most dangerous place you have worked.',
  creatorId: 'creator_official',
  creatorName: 'Plotbreak Studios',
  official: true,
  coverImage: null,
  keyArt: null,
  tags: ['Rivalry', 'Romance', 'Drama', 'Ambition'],
  mechanicsChips: ['Persuasion', 'Reputation', 'Relationships', 'Deadlines'],
  contentDescriptors: ['ROMANCE', 'PSYCHOLOGICAL_THEMES', 'MORAL_AMBIGUITY'],
  intensity: 'MODERATE',
  creatorNote:
    'No fights and no magic. The only thing you are really managing is what people say about you when you are not in the room.',
  rules: {
    defeatMode: 'FAIL_FORWARD',
    progressionMode: 'MILESTONE',
    revealExactDc: false,
    revealCheckMath: false,
    allowsCombat: false,
    allowsRomance: true,
    startingItems: [{ itemId: 'annotated_sides', qty: 1 }],
    startingLocationId: 'rehearsal_room',
    startWorldMinute: 9 * 60,
    hardCanon: [
      'Opening night is in six weeks and the date never moves.',
      'The Company book records every favour. It is read aloud at the end of term.',
      'Nobody has ever been recast after the third week.',
      'Ysra is a role, not a person. Everyone forgets this eventually.',
    ],
    toneGuide:
      'Warm rooms, cold arithmetic. People are generous in public and precise in private. Ambition is not a flaw here; pretending you do not have it is.',
    forkCostCredits: 120,
  },
  attributes: { might: 9, agility: 12, mind: 12, presence: 14, resolve: 12, arcana: 8 },
  skills: [
    { id: 'performance', name: 'Performance', attribute: 'presence', description: 'Being watched on purpose.' },
    { id: 'persuasion', name: 'Persuasion', attribute: 'presence', description: 'Getting a yes you can hold someone to.' },
    { id: 'deception', name: 'Deception', attribute: 'presence', description: 'A version of events that flatters everyone.' },
    { id: 'insight', name: 'Insight', attribute: 'mind', description: 'Reading the room before the room reads you.' },
    { id: 'composure', name: 'Composure', attribute: 'resolve', description: 'Taking a note without flinching.' },
    { id: 'stagecraft', name: 'Stagecraft', attribute: 'mind', description: 'Ropes, cues, and what breaks when.' },
    { id: 'movement', name: 'Movement', attribute: 'agility', description: 'Blocking, falls, and the illusion of ease.' },
  ],
  resources: [
    {
      id: 'stamina',
      name: 'Stamina',
      max: 20,
      start: 20,
      regenPerHour: 1,
      polarity: 'GOOD_HIGH',
      displayPriority: 1,
      visible: true,
      zeroStateConsequence: 'You are visibly exhausted. Everything social gets harder.',
      color: '#43D6A4',
    },
    {
      id: 'standing',
      name: 'Standing',
      max: 100,
      start: 25,
      regenPerHour: 0,
      polarity: 'GOOD_HIGH',
      displayPriority: 2,
      visible: true,
      zeroStateConsequence: 'The room stops turning toward you. You are furniture.',
      color: '#7C6CFF',
    },
    {
      id: 'debt',
      name: 'Debt',
      max: 100,
      start: 0,
      regenPerHour: 0,
      polarity: 'GOOD_LOW',
      displayPriority: 3,
      visible: true,
      zeroStateConsequence: 'You owe nobody anything. Rare, and worth protecting.',
      color: '#F6BE55',
    },
  ],
  items: [
    {
      id: 'annotated_sides',
      name: 'Annotated Sides',
      tags: ['quest'],
      questItem: true,
      droppable: false,
      skillModifiers: { performance: 2 },
      description: 'Your copy of the script. Four months of margin notes nobody asked you to make.',
      loreText: 'Act two is in three colours of ink. You have opinions about act two.',
      icon: 'script',
    },
    {
      id: 'throat_tincture',
      name: 'Throat Tincture',
      tags: ['consumable'],
      stackable: true,
      maxStack: 3,
      consumable: { resourceId: 'stamina', amount: 8, consumesItem: true },
      description: 'Tastes of aniseed and desperation. Buys you an hour you did not have.',
      loreText: 'The wardrobe mistress makes it. She does not sell it to everyone.',
      icon: 'vial',
    },
    {
      id: 'company_book',
      name: 'The Company Book',
      tags: ['quest', 'evidence'],
      questItem: true,
      droppable: false,
      description: 'Who owes what, in the director’s hand. You are on page four, twice.',
      loreText: 'The second entry is not in your handwriting and is not about you.',
      icon: 'ledger',
    },
  ],
  abilities: [
    {
      id: 'run_it_again',
      name: 'Run It Again',
      tags: ['stagecraft', 'technician'],
      description: 'Reset the room and take it from a specific line, so everyone gets the second chance you set up.',
      affordances: ['run it again', 'take it from the top', 'reset the scene', 'go again from my line'],
      costs: [{ resourceId: 'stamina', amount: 4 }],
      cooldownMinutes: 60,
      targetRule: 'NONE',
      check: { attribute: 'mind', skillId: 'stagecraft', baseDc: 13 },
      unlockedByDefault: false,
    },
    {
      id: 'take_the_stage',
      name: 'Take the Stage',
      tags: ['performance', 'natural'],
      description: 'Step into the light and hold it. Whatever else was happening in the room stops happening.',
      affordances: ['take the stage', 'step into the light', 'do it now', 'show them', 'perform it'],
      costs: [{ resourceId: 'stamina', amount: 5 }],
      cooldownMinutes: 90,
      targetRule: 'NONE',
      check: { attribute: 'presence', skillId: 'performance', baseDc: 14 },
      unlockedByDefault: false,
    },
    {
      id: 'have_a_word',
      name: 'Have a Word',
      tags: ['social', 'diplomat'],
      description: 'Get one person alone for ninety seconds and change what they were about to do.',
      affordances: ['have a word', 'pull them aside', 'talk to them privately', 'get them alone'],
      costs: [{ resourceId: 'stamina', amount: 3 }],
      cooldownMinutes: 45,
      targetRule: 'SINGLE',
      check: { attribute: 'presence', skillId: 'persuasion', baseDc: 13 },
      unlockedByDefault: false,
    },
    {
      id: 'read_the_room',
      name: 'Read the Room',
      tags: ['social'],
      description: 'Stop performing for one breath and work out what everyone actually wants.',
      affordances: ['read the room', 'watch them', 'work out what they want', 'take the temperature'],
      costs: [{ resourceId: 'stamina', amount: 2 }],
      cooldownMinutes: 0,
      targetRule: 'NONE',
      check: { attribute: 'mind', skillId: 'insight', baseDc: 12 },
      unlockedByDefault: true,
    },
    {
      id: 'take_the_note',
      name: 'Take the Note',
      tags: ['social', 'defensive'],
      description: 'Absorb a correction so completely that the person giving it starts rooting for you.',
      affordances: ['take the note', 'accept the criticism', 'agree with them', 'say nothing and do it'],
      costs: [{ resourceId: 'stamina', amount: 3 }],
      cooldownMinutes: 120,
      targetRule: 'SINGLE',
      check: { attribute: 'resolve', skillId: 'composure', baseDc: 13 },
      unlockedByDefault: true,
    },
  ],
  locations: [
    {
      id: 'rehearsal_room',
      takeableItems: [
        { itemId: 'annotated_sides', qty: 1, ownerId: 'talia', aka: ['sides', 'the script', 'her script', 'the annotated pages'] },
      ],
      name: 'Rehearsal Room Two',
      shortName: 'Rehearsal',
      description:
        'Sprung floor, one wall of mirrors, and a piano nobody is allowed to move. Tape on the boards marks a set that does not exist yet.',
      artDirection: 'Morning light through high windows, mirrored wall, coloured tape on a pale wooden floor.',
      stageImage: null,
      discoveredByDefault: true,
      mapPosition: { x: 0.5, y: 0.75 },
      ambientSfx: ['piano', 'footsteps'],
      connections: [
        { to: 'green_room', travelMinutes: 3, label: 'Through to the green room' },
        { to: 'stage', travelMinutes: 5, label: 'Onto the stage' },
      ],
    },
    {
      id: 'green_room',
      takeableItems: [
        { itemId: 'throat_tincture', qty: 1, ownerId: null, aka: ['tincture', 'the bottle'] },
      ],
      name: 'The Green Room',
      shortName: 'Green room',
      description:
        'Two sofas that have outlived four principals, a kettle, and a noticeboard where the cast list goes up. Everyone pretends not to check it.',
      artDirection: 'Cramped warm room, mismatched sofas, a corkboard thick with pinned paper.',
      stageImage: null,
      discoveredByDefault: true,
      mapPosition: { x: 0.24, y: 0.55 },
      ambientSfx: ['kettle', 'murmur'],
      connections: [
        { to: 'rehearsal_room', travelMinutes: 3, label: 'Back to rehearsal' },
        { to: 'wardrobe', travelMinutes: 4, label: 'Down to wardrobe' },
      ],
    },
    {
      id: 'stage',
      name: 'The Main Stage',
      shortName: 'Stage',
      description:
        'Nine hundred empty seats and a ghost light burning at centre. From up here the auditorium is a held breath.',
      artDirection: 'Dark auditorium seen from the stage, single bare bulb on a stand, deep red seating in shadow.',
      stageImage: null,
      discoveredByDefault: true,
      mapPosition: { x: 0.76, y: 0.55 },
      ambientSfx: ['room_tone', 'creak'],
      connections: [
        { to: 'rehearsal_room', travelMinutes: 5, label: 'Back to rehearsal' },
        { to: 'directors_office', travelMinutes: 6, lockedByFlag: 'summoned', label: "The director's office" },
      ],
    },
    {
      id: 'wardrobe',
      name: 'Wardrobe',
      shortName: 'Wardrobe',
      description:
        'Rails to the ceiling and the smell of steam. Marta works here and hears everything, because nobody thinks to stop talking in front of her.',
      artDirection: 'Narrow aisle between costume rails, steamer haze, single warm work lamp.',
      stageImage: null,
      discoveredByDefault: true,
      mapPosition: { x: 0.24, y: 0.28 },
      ambientSfx: ['steam', 'hangers'],
      connections: [{ to: 'green_room', travelMinutes: 4, label: 'Up to the green room' }],
    },
    {
      id: 'directors_office',
      takeableItems: [
        { itemId: 'company_book', qty: 1, ownerId: 'oswin', aka: ['book', 'the ledger', 'the company book'] },
      ],
      name: "The Director's Office",
      shortName: 'Office',
      description:
        'One chair for him and one for whoever is in trouble. The Company Book sits closed on the desk, which is worse than open.',
      artDirection: 'Small office, one desk lamp, a closed ledger, framed posters going back thirty years.',
      stageImage: null,
      discoveredByDefault: false,
      mapPosition: { x: 0.76, y: 0.28 },
      ambientSfx: ['clock'],
      connections: [{ to: 'stage', travelMinutes: 6, label: 'Back to the stage' }],
    },
  ],
  characters: [
    {
      id: 'talia',
      name: 'Talia Renn',
      role: 'First cast, Ysra',
      cardBlurb:
        "The lead you are understudying. She is not your enemy, and she is not going to hand you the part.",
      pronouns: 'she/her',
      publicTraits: ['Gracious', 'Immaculate', 'Never late'],
      hiddenDrives: [
        'She knows you are better in act two and has known since the read-through.',
        'She is being kept by a patron whose name is in the Company Book.',
      ],
      values: ['Craft', 'Not being pitied'],
      fears: ['Being found out as adequate', 'Owing anyone visibly'],
      socialStyle: 'Generous in public, exact in private. Compliments you accurately, which is worse.',
      boundaries: ['Will not sabotage anyone', 'Will not admit fear out loud'],
      goals: ['Open the show', 'Clear her name from the book'],
      secrets: [
        {
          id: 'talia_patron',
          fact: "Talia's place in the company was paid for by a patron, and the debt is recorded.",
          visibility: 'NPC_PRIVATE',
          revealHint: 'Requires the Company Book, or trust above 45.',
        },
      ],
      speechStyle: 'Precise, unhurried, never raises her voice. Asks questions instead of arguing.',
      topics: ['act two', 'the cast list', 'what she owes', 'opening night'],
      voiceSamples: [
        'You were better than me in the second act. I would rather say it than have you think I did not notice.',
        'I am not going to fight you for this. I am simply not going to lose it.',
        'Take the note. He is right, and it costs you nothing to agree.',
      ],
      appearance: 'Tall, dark hair pinned severely, rehearsal blacks that fit properly.',
      visualHook:
        'Half her face in full stage makeup and half of it bare, caught between the dressing room and the floor, the line down the centre perfectly clean.',
      silhouette:
        'Tall and vertical, dark hair pinned severely, rehearsal blacks that fit exactly, hands folded and still.',
      artSeed: 'talia-renn-v1',
      portrait: null,
      expressions: ['neutral', 'gracious', 'guarded', 'stung', 'resolved'],
      voiceId: 'voice_talia',
      homeLocationId: 'rehearsal_room',
      knowledgeScope: ['faction_company'],
      schedule: [
        { startMinute: 540, endMinute: 780, locationId: 'rehearsal_room', activity: 'Principal call' },
        { startMinute: 780, endMinute: 840, locationId: 'green_room', activity: 'Not eating lunch' },
        { startMinute: 840, endMinute: 1080, locationId: 'stage', activity: 'Blocking' },
        { startMinute: 1080, endMinute: 1260, locationId: 'wardrobe', activity: 'Fittings' },
      ],
      startingRelationship: { trust: 0, affection: 5, respect: 20, fear: 0, rivalry: 30 },
      attributes: { might: 9, agility: 13, mind: 13, presence: 16, resolve: 14, arcana: 8 },
      gates: [
        {
          id: 'talia_alliance',
          kind: 'ALLIANCE',
          label: 'Talia will work the problem with you',
          requires: { respect: 45, trust: 30, hasItems: ['company_book'] },
        },
        {
          id: 'talia_romance',
          kind: 'ROMANCE',
          label: 'Talia lets the guard down',
          requires: { affection: 55, trust: 40, flagsSet: ['talia_ghost_light'] },
        },
      ],
      combatant: null,
    },
    {
      id: 'oswin',
      name: 'Oswin Deare',
      role: 'Director',
      cardBlurb:
        "The director. He decides whether you go on, and he has never recast anyone after week three.",
      pronouns: 'he/him',
      publicTraits: ['Blunt', 'Fair in his own terms', 'Bored of talent'],
      hiddenDrives: [
        'He recast this role once, twenty years ago, and it destroyed a career.',
        'He is looking for a reason not to do it again.',
      ],
      values: ['The work', 'Keeping his word'],
      fears: ['Repeating himself', 'A show that is merely competent'],
      socialStyle: 'Says the difficult thing first and waits to see what you do with it.',
      boundaries: ['Never recasts after week three', 'Never explains a note twice'],
      goals: ['Open a show worth remembering'],
      secrets: [
        {
          id: 'oswin_recast',
          fact: 'Oswin recast a lead in his first season and the actor never worked again.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Respect 50+, or ask him directly in his office.',
        },
      ],
      speechStyle: 'Short imperatives. No praise unless it is load-bearing. Calls everyone by surname.',
      topics: ['the note he gave you', 'the cast list', 'what he wants from act two'],
      voiceSamples: [
        'Again. And this time mean the second half of the line.',
        'I do not need you to be better than her. I need you to be necessary.',
        'You are asking me to be fair. I am asking you to be interesting.',
      ],
      appearance: 'Sixties, corduroy, reading glasses pushed up, a pencil behind one ear permanently.',
      visualHook:
        'A carpenter\'s pencil behind one ear and reading glasses shoved up into grey hair, with a conductor\'s baton worn smooth and pale where his thumb sits.',
      silhouette:
        'Broad and settled, corduroy, arms crossed, the only person in the building who is never in a hurry.',
      artSeed: 'oswin-deare-v1',
      portrait: null,
      expressions: ['neutral', 'sharp', 'considering', 'impatient', 'pleased'],
      voiceId: 'voice_oswin',
      homeLocationId: 'rehearsal_room',
      knowledgeScope: ['faction_company'],
      schedule: [
        { startMinute: 540, endMinute: 780, locationId: 'rehearsal_room', activity: 'Running act one' },
        { startMinute: 780, endMinute: 900, locationId: 'directors_office', activity: 'Paperwork' },
        { startMinute: 900, endMinute: 1140, locationId: 'stage', activity: 'Technical' },
      ],
      startingRelationship: { trust: 5, affection: 0, respect: 10, fear: 10, rivalry: 0 },
      attributes: { might: 10, agility: 9, mind: 15, presence: 15, resolve: 16, arcana: 8 },
      gates: [
        {
          id: 'oswin_considers',
          kind: 'OTHER',
          label: 'Oswin will genuinely consider you',
          requires: { respect: 50, flagsSet: ['proved_act_two'] },
        },
      ],
      combatant: null,
    },
    {
      id: 'marta',
      name: 'Marta Voss',
      role: 'Wardrobe mistress',
      cardBlurb:
        "Wardrobe. She hears every conversation in this building, including the ones about you, and repeats almost none of them.",
      pronouns: 'she/her',
      publicTraits: ['Unimpressed', 'Kind in a hurry', 'Hears everything'],
      hiddenDrives: [
        'She has watched thirty years of understudies and has a private ranking.',
        'She keeps a copy of the Company Book. She should not.',
      ],
      values: ['People who say thank you', 'Not being lied to'],
      fears: ['Being asked to choose a side'],
      socialStyle: 'Talks while working and stops working when it matters.',
      boundaries: ['Will not gossip about anyone in the room', 'Will not lie to the director'],
      goals: ['Get the show dressed', 'Keep her copy of the book quiet'],
      secrets: [
        {
          id: 'marta_copy',
          fact: 'Marta keeps her own copy of the Company Book in the wardrobe.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Trust 40+, and only after she has decided you are not a climber.',
        },
      ],
      speechStyle: 'Dry, fast, full of asides. Uses "love" as punctuation and means it about half the time.',
      topics: ['who owes what', 'the last understudy', 'act two', 'what she has heard'],
      voiceSamples: [
        'Arms up, love. You are not the first one to stand there looking like that.',
        'I hear everything in this room and I repeat almost none of it. Almost.',
        'The last one who asked me that got the part and was insufferable about it.',
      ],
      appearance: 'Fifties, pins in her cuff, glasses on a chain, hands that never stop.',
      visualHook:
        'A row of dressmaker\'s pins driven through the cuff of her sleeve like a bandolier, and a measuring tape worn around the neck like a scarf.',
      silhouette:
        'Compact and mid-motion, glasses on a chain, hands that have never once been empty.',
      artSeed: 'marta-voss-v1',
      portrait: null,
      expressions: ['neutral', 'dry', 'warm', 'wary'],
      voiceId: 'voice_marta',
      homeLocationId: 'wardrobe',
      knowledgeScope: ['faction_company'],
      schedule: [
        { startMinute: 480, endMinute: 1140, locationId: 'wardrobe', activity: 'Fittings and repairs' },
        { startMinute: 1140, endMinute: 1260, locationId: 'green_room', activity: 'Tea, finally' },
      ],
      startingRelationship: { trust: 10, affection: 10, respect: 5, fear: 0, rivalry: 0 },
      attributes: { might: 10, agility: 11, mind: 14, presence: 12, resolve: 14, arcana: 8 },
      gates: [
        {
          id: 'marta_shows_book',
          kind: 'TRUST',
          label: 'Marta will show you her copy',
          requires: { trust: 40, affection: 25 },
        },
      ],
      combatant: null,
    },
  ],
  factions: [
    {
      id: 'faction_company',
      name: 'The Verrine Company',
      description: 'Eleven students, one book, and a very long memory.',
      startingReputation: 5,
      ranks: [
        { atReputation: -30, label: 'Talked about' },
        { atReputation: 0, label: 'In the room' },
        { atReputation: 35, label: 'Relied on' },
        { atReputation: 70, label: 'Indispensable' },
      ],
      allies: [],
      enemies: [],
    },
  ],
  quests: [
    {
      id: 'q_six_weeks',
      title: 'Six Weeks',
      summary: 'Make yourself necessary before opening night.',
      kind: 'MAIN',
      startsActive: true,
      involvedCharacterIds: ['oswin', 'talia'],
      involvedLocationIds: ['rehearsal_room', 'stage'],
      knownRewardCopy: 'Oswin stops looking through you.',
      steps: [
        {
          id: 'step_first_note',
          playerCopy: 'Get through the first note without flinching.',
          directorNotes: 'Oswin gives a hard note in front of everyone. Composure or honesty both work; excuses do not.',
          succeedWhen: {
            flagsSet: ['spoke:oswin'],
            atLocation: 'rehearsal_room',
          },
          rewards: { xp: 40, items: [], flags: ['took_first_note'] },
        },
        {
          id: 'step_act_two',
          playerCopy: 'Prove you own act two.',
          directorNotes:
            'The promise the whole world is built on, and there is more than one way to be undeniable. ' +
            'A performer does it in front of people. A technician makes the scene work and lets the room ' +
            'notice who fixed it. A diplomat gets the person who matters to say it for them. Anyone can ' +
            'simply out-prepare the building, and it costs more. Whichever it is, it happens with witnesses.',
          enterWhen: { flagsSet: ['took_first_note'] },
          succeedWhenAny: [
            {
              routeId: 'act_two_by_playing_it',
              label: 'You did it, in front of everyone',
              predicate: {
                flagsSet: ['used:take_the_stage', 'spoke:oswin'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'stage',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['proved_act_two', 'route_performed_it', 'company_saw_you'],
              closesFlags: ['oswin_thinks_you_are_a_technician'],
            },
            {
              routeId: 'act_two_by_running_it',
              label: 'You rebuilt the scene until it worked',
              predicate: {
                flagsSet: ['used:run_it_again', 'spoke:oswin'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'rehearsal_room',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['proved_act_two', 'route_fixed_it', 'oswin_thinks_you_are_a_technician'],
              closesFlags: ['talia_owes_you'],
            },
            {
              routeId: 'act_two_by_talia',
              label: 'Talia said it should be you',
              predicate: {
                flagsSet: ['used:have_a_word', 'spoke:talia'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'talia', dimension: 'trust', value: 30 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['proved_act_two', 'route_talia_said_so', 'talia_owes_you'],
              closesFlags: [],
            },
            {
              routeId: 'act_two_by_grind',
              label: 'You had simply done the work',
              predicate: {
                flagsSet: ['spoke:oswin'],
                flagsUnset: [],
                hasItems: ['annotated_sides'],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'oswin', dimension: 'respect', value: 45 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['proved_act_two', 'route_out_prepared_them'],
              closesFlags: [],
            },
          ],
          rewards: { xp: 90, items: [], flags: [] },
        },
      ],
    },
    {
      id: 'q_the_book',
      title: 'The Company Book',
      summary: 'Find out who is written in it, and for how much.',
      kind: 'MAIN',
      startsActive: false,
      involvedCharacterIds: ['marta', 'talia'],
      involvedLocationIds: ['wardrobe', 'directors_office'],
      knownRewardCopy: 'The truth about how anyone gets cast here.',
      discoverWhen: { flagsSet: ['spoke:marta'] },
      steps: [
        {
          id: 'step_find_copy',
          playerCopy: 'Get someone to show you the book.',
          directorNotes:
            'Marta has a copy and will not hand it over to a climber. She will hand it to someone she ' +
            'trusts, Oswin keeps his in the office, and it can simply be taken — which is a different ' +
            'thing to have done, and the building finds out.',
          succeedWhenAny: [
            {
              routeId: 'book_from_marta',
              label: 'Marta gave you hers',
              predicate: {
                flagsSet: ['spoke:marta'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'marta', dimension: 'trust', value: 30 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['read_the_book', 'marta_trusted_you'],
              closesFlags: ['took_the_book'],
            },
            {
              routeId: 'book_from_the_office',
              label: 'You were in the office for a reason',
              predicate: {
                flagsSet: ['used:run_it_again', 'visited:directors_office'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'directors_office',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['read_the_book', 'oswin_let_you_in'],
              closesFlags: [],
            },
            {
              routeId: 'book_by_taking_it',
              label: 'You took it',
              predicate: {
                flagsSet: [],
                flagsUnset: [],
                hasItems: ['company_book'],
                atLocation: null,
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['read_the_book', 'took_the_book'],
              closesFlags: ['marta_trusted_you'],
            },
          ],
          rewards: { xp: 80, items: [], flags: [] },
        },
      ],
    },
    {
      id: 'lead_ghost_light',
      title: 'The Ghost Light',
      summary: 'Someone is on the stage after hours, and it is not the crew.',
      kind: 'LEAD',
      startsActive: false,
      involvedCharacterIds: ['talia'],
      involvedLocationIds: ['stage'],
      knownRewardCopy: 'Talia, without the performance.',
      discoverWhen: { flagsSet: ['visited:stage'] },
      steps: [
        {
          id: 'step_ghost_light',
          playerCopy: 'Be on the stage late, and wait.',
          directorNotes:
            'The §16.4 relationship payoff. Talia rehearses alone at night because she is not sure either. ' +
            'Being found there is different from being invited, and being asked outright is different again. ' +
            'She is not a prize; she decides.',
          succeedWhenAny: [
            {
              routeId: 'ghost_by_waiting',
              label: 'You were there when she came',
              predicate: {
                flagsSet: ['visited:stage', 'spoke:talia'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'stage',
                completedEvents: [],
                minRelationship: [{ characterId: 'talia', dimension: 'trust', value: 25 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['talia_ghost_light', 'talia_found_you_there'],
              closesFlags: [],
            },
            {
              routeId: 'ghost_by_working',
              label: 'You were working, and she stayed',
              predicate: {
                flagsSet: ['used:run_it_again', 'spoke:talia'],
                flagsUnset: [],
                hasItems: [],
                atLocation: 'stage',
                completedEvents: [],
                minRelationship: [],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['talia_ghost_light', 'talia_stayed_to_watch'],
              closesFlags: [],
            },
            {
              routeId: 'ghost_by_asking',
              label: 'You asked her straight out',
              predicate: {
                flagsSet: ['used:have_a_word', 'spoke:talia'],
                flagsUnset: [],
                hasItems: [],
                atLocation: null,
                completedEvents: [],
                minRelationship: [{ characterId: 'talia', dimension: 'trust', value: 15 }],
                minFactionReputation: [],
                beforeWorldMinute: null,
                afterWorldMinute: null,
              },
              setsFlags: ['talia_ghost_light', 'talia_was_asked'],
              closesFlags: [],
            },
          ],
          rewards: { xp: 90, items: [], flags: [] },
        },
      ],
    },
  ],
  promises: [
    {
      id: 'promise_act_two',
      kind: 'THEME',
      label: 'You are better in act two and everyone knows it',
      seedHint: 'The first run-through stops early, on your scene.',
      payoffHint: 'Oswin asks you to run it with the full company watching.',
      weight: 1,
    },
    {
      id: 'promise_talia',
      kind: 'RIVAL',
      label: 'Talia, who is not your enemy and will not be your friend',
      seedHint: 'She compliments you accurately, in front of people.',
      payoffHint: 'She rehearses alone at night because she is not sure either.',
      weight: 0.9,
    },
    {
      id: 'promise_book',
      kind: 'MYSTERY',
      label: 'The book, and whose name is in it twice',
      seedHint: 'The book is closed on the desk, which is worse than open.',
      payoffHint: 'Talia is in it. So, on page four, are you.',
      weight: 0.85,
    },
  ],
  archetypes: [
    {
      id: 'arch_technician',
      name: 'The Technician',
      role: 'Backstage craft',
      summary:
        'You know how the show is actually built. Best under pressure and best with anything technical; worst at being looked at.',
      playstyle: ['Practical', 'Steady nerve', 'Not a performer'],
      blurb: 'You are not the most watchable person here. You are the most reliable.',
      attributeBonus: { mind: 2, resolve: 1 },
      skillProficiencies: { stagecraft: 3, composure: 2, insight: 1 },
      startingItems: [{ itemId: 'annotated_sides', qty: 1 }],
      startingAbilities: ['run_it_again'],
    },
    {
      id: 'arch_natural',
      name: 'The Natural',
      role: 'Stage presence',
      summary:
        'You are who the room looks at. Highest presence in the company, and nothing whatsoever to fall back on when charm is not the answer.',
      playstyle: ['Commands a room', 'Physical performer', 'One trick'],
      blurb: 'It has always come easily, which is its own kind of problem.',
      attributeBonus: { presence: 3 },
      skillProficiencies: { performance: 3, movement: 2 },
      startingItems: [{ itemId: 'throat_tincture', qty: 1 }],
      startingAbilities: ['take_the_stage'],
    },
    {
      id: 'arch_diplomat',
      name: 'The Diplomat',
      role: 'Social',
      summary:
        'You read a room and quietly fix it. Best with people, which in this building is most of what goes wrong.',
      playstyle: ['Persuasion', 'Reads people', 'Well-rounded'],
      blurb: 'You have never been the best in the room. You have often been the reason it worked.',
      attributeBonus: { presence: 2, mind: 1 },
      skillProficiencies: { persuasion: 3, insight: 2, deception: 1 },
      startingItems: [{ itemId: 'throat_tincture', qty: 1 }],
      startingAbilities: ['have_a_word'],
    },
  ],
  setupFields: [
    { id: 'displayName', label: 'What is on the cast list?', kind: 'TEXT', required: true, maxLength: 40, placeholder: 'e.g. Ines Halloway' },
    { id: 'pronouns', label: 'Pronouns', kind: 'TEXT', required: false, maxLength: 24, placeholder: 'e.g. she/her' },
    {
      id: 'archetype',
      label: 'What kind of theatre person are you?',
      helpText:
        'What you were already good at when the company took you on. It sets your attributes and training, so it decides which scenes you sail through and which ones you have to survive. Fixed for this run.',
      kind: 'ARCHETYPE',
      required: false,
    },
    {
      id: 'worldKnowsAboutYou',
      label: 'What does the company already say about you?',
      kind: 'TEXT',
      required: false,
      maxLength: 300,
      placeholder: 'e.g. Learned the whole part in a week and will not shut up about it.',
    },
  ],
  opening:
    'The director stops the run-through eleven minutes in. Yesterday he made it to twenty.\n\n' +
    '"From the top of the scene." He does not look up from his notes. "Renn, sit down. Understudy, stand in."\n\n' +
    'That is you. Nine people turn to watch you walk to your mark, which is the first time this month anyone in this room has looked directly at you.\n\n' +
    'Talia sits without a word and folds her hands in her lap. You cannot tell from her face whether she is being generous or whether this is the opening move of something.\n\n' +
    'You know the line. You have known it since February.',
  openingSuggestions: [
    'I take my mark and play it exactly the way I have been playing it alone at two in the morning. No adjustments, no apologies.',
    'I stop before the first line and look straight at the director. “Tell me what you actually want from this moment. I will give you that instead.”',
    'I find Talia’s eyes in the dark past the lights and hold them for a second longer than is comfortable. Then I begin.',
  ],
  publishedAt: '2026-08-20T09:00:00.000Z',
};

export const UNDERSTUDY = StoryVersion.parse(raw);
