// Generated by apps/ios/scripts/export-events.mjs — do not edit.
//
// The source of truth is packages/analytics/src/index.ts (spec §37). Add an
// event there and regenerate; adding a case here by hand gives the client a
// name the server's contract has never heard of, which is the exact drift this
// file exists to prevent.

/// Every event Plotbreak emits, on either client.
///
/// The app can only send names in this enum, so a typo is a compile error
/// rather than a chart that is quietly missing a week.
enum PlotbreakEvent: String, CaseIterable, Sendable {
    case appOpened = "app_opened"
    case ageGateCompleted = "age_gate_completed"
    case tasteCalibrationCompleted = "taste_calibration_completed"
    case discoverViewed = "discover_viewed"
    case storyCardViewed = "story_card_viewed"
    case storyDetailViewed = "story_detail_viewed"
    case characterSetupStarted = "character_setup_started"
    case sessionStarted = "session_started"
    case firstTurnSubmitted = "first_turn_submitted"
    case prologueShown = "prologue_shown"
    case prologuePanelViewed = "prologue_panel_viewed"
    case prologueFinished = "prologue_finished"
    case turnSubmitted = "turn_submitted"
    case turnCompleted = "turn_completed"
    case turnFailed = "turn_failed"
    case turn10Reached = "turn_10_reached"
    case questCompleted = "quest_completed"
    case signInStarted = "sign_in_started"
    case signInCompleted = "sign_in_completed"
    case guestAccountMigrated = "guest_account_migrated"
    case walletOpened = "wallet_opened"
    case insufficientCreditsShown = "insufficient_credits_shown"
    case paywallShown = "paywall_shown"
    case offerSelected = "offer_selected"
    case paywallDismissed = "paywall_dismissed"
    case purchaseStarted = "purchase_started"
    case purchaseCompleted = "purchase_completed"
    case purchaseFailed = "purchase_failed"
    case dailyGrantClaimed = "daily_grant_claimed"
    case qualityTierChanged = "quality_tier_changed"
    case timelineForked = "timeline_forked"
    case portraitGenerated = "portrait_generated"
    case consistencyViolation = "consistency_violation"
    case turnRepaired = "turn_repaired"
    case canonCorrectionSubmitted = "canon_correction_submitted"
    case canonCorrectionRefused = "canon_correction_refused"
    case reportSubmitted = "report_submitted"
    case storyHidden = "story_hidden"
    case worldSheetOpened = "world_sheet_opened"
    case suggestionTapped = "suggestion_tapped"
    case sessionResumed = "session_resumed"
    case sessionAbandoned = "session_abandoned"
    case storySaved = "story_saved"
    case shareCreated = "share_created"
    case communityInviteShown = "community_invite_shown"
    case communityInviteTapped = "community_invite_tapped"
    case discordLinked = "discord_linked"
    case badgeClaimed = "badge_claimed"
    case createDraftStarted = "create_draft_started"
    case createCompiled = "create_compiled"
    case createArtDrawn = "create_art_drawn"
    case createPublished = "create_published"
}

/// The API contract this build was generated against, so an event can say which
/// wire format produced it. Same constant the server stamps on
/// `x-contract-version`.
enum PlotbreakAnalyticsContract {
    static let version = "1.0.0"
}
