/**
 * The French half of the launch comment sections.
 *
 * Same rules as the English pools in `seed-social.ts`, and `assertPools` there
 * checks them the same way: every world line names something true of that
 * world (using the names the French fixture gives it), no line is on two
 * worlds, no dashes. Register is a French phone keyboard: lowercase, slang,
 * accents dropped when the thumb could not be bothered.
 *
 * A line about how a world ends says "fin", which is what marks it a spoiler.
 */

/** French handles, kept apart from `NAMES` so a French line never sits under "greg". */
export const FR_NAMES: readonly string[] = [
  'lea.dsn', 'mathis_rsl', 'kenzo_77', 'ines.mp4', 'baguette_quantique', 'yanis_off',
  'camille_nuit', 'nolan.bzh', 'sarah_lpt', 'croissant_fantome', 'jade_sans_s', 'theo.exe',
  'manon_zzz', 'rayan_93', 'chloe.lune', 'hugo_pas_hugo', 'emma_crevee', 'lucas_rlx',
  'nour_s', 'axel.jpeg', 'lina_bsx', 'mael_dort_pas', 'zoe_miel', 'enzo_fps',
  'clara_pls', 'ilyes.wav', 'pain_au_choc_', 'maxime_ptdr',
  'louane_off', 'samy.sd', 'anais_dort', 'bastien_42', 'margaux.lpv', 'kylian_tkt',
  'eva_rien_a_dire', 'adam_sans_wifi', 'lou.pastel', 'wassim_7', 'juliette_zz', 'tom_le_vrai',
  'salome.jsp', 'noah_bzh', 'oceane_lol', 'mehdi_rs', 'agathe_nuit_blanche', 'quentin.exe',
  'yasmine_ptn', 'arthur_pas_roi', 'lola_bof', 'gabin_fr', 'elise.mp3', 'sofiane_off',
];

/** Short and shared, like `NOISE`: repeating these across worlds is what a real section does. */
export const FR_NOISE: readonly string[] = [
  'premier',
  'masterclass',
  'c trop bien ptn',
  'y a des francais ici ?',
  'jsuis censé dormir la',
  'jpp de ce jeu',
  'je commente pour le retrouver plus tard',
  'trop addictif sah',
  'jsuis en cours la mdr',
  'quelqu un a un discord fr ?',
  'j ai fait que des mauvais choix encore une fois',
  'wsh comment ils ecrivent aussi vite',
  'j ai tapé nimporte quoi et ca a marché',
  'la version fr est propre en vrai',
  'jvais y passer la nuit',
  'venu de tiktok',
  'deuxieme',
  'c incroyable jsuis choqué',
  'sous la couette avec le tel a 4%',
  'jai zappé mon episode pour ça',
  'qui me prete des crédits',
  'mes crédits ont fondu en une soirée',
  'jai mis mon tel en mode avion pour pas etre derangé mdr',
  'je like tous les coms par solidarité',
  'jai tapé une blague et ça a suivi mdr',
  'jai tenté de soudoyer un perso et ça a marché ptdr',
  'trop de choix jsuis perdu',
  'qui d\'autre relit ses choix pour voir ou ça a derapé',
  'mon perso a plus de vie sociale que moi mdr',
  'cours a 8h et jsuis encore la dessus',
  'je lis ça dans le bus et jai raté mon arret',
  'mieux que ma serie du moment',
  'jai envoyé ça a ma pote elle est deja plus loin que moi',
  'c quoi vos choix a vous ?',
  'addict grave',
  'jvais me faire virer a force',
  'frr qui a fait cette appli',
  '10/10 sah',
  'ma mere croit que jrevise',
  'jsuis au lit depuis 2h et jai toujours pas dormi',
  'askip on peut tout taper, jai testé, c vrai',
  'jsuis refait',
  'mdr jai tout cassé',
  'ça me donne envie d\'ecrire',
  'grave sous coté',
  'jcomprends pas comment ça marche mais jkiffe',
];

/** Each world's own French lines. Keys must match `CATALOGUE` in `seed-social.ts`. */
export const FR_WORLDS: Record<string, readonly string[]> = {
  story_itachi: [
    'le tas de shurikens dont sasuke est le plus fier en compte onze. ONZE. jsuis pas bien',
    'mikoto qui prepare une boite a 5h30 pour qqn qui a meme pas dit qu\'il partait... elle sait. elle sait toujours tout cette femme',
    'izumi qui achete des dango pour deux avec l\'assurance de qqn qui s\'entraine depuis la veille mdrrr je la protege',
    'le masque de belette au fond du cartable sous une veste pliée, a quatre pieces de la ou dort sasuke. ce genre de detail wsh',
    'c bien ecrit mais hiruzen bouge pas sans preuve a poser sur son bureau et moi j\'avais que des soupcons. 2 runs de perdus',
    'les scenes dans la chambre sous le village jles ai trouvées longues, j\'avais juste envie de rentrer a la maison au coin',
    'danzo pose jamais une seule question de tout le jeu. j\'ai verifié. zero. il parle qu\'en consequences ce mec',
    'le mot du corbeau ou y a juste marqué tot et ca veut jamais dire tot. shisui et itachi ptn je vais pleurer',
    'kakashi qui lit le meme bouquin dans la salle d\'attente sans jamais tourner la page mdrrr',
    'conseil: allez aux postes avec sasuke le premier soir. une heure a corriger sa prise et toutes ses scenes changent apres',
    'mikoto qui essuie le meme bol pendant toute la discussion et qui le pose des que tu dis un truc vrai. frissons',
    'le trajet de sasuke pour aller a l\'ecole il est dans le journal de surveillance. deux fois. wsh',
    'izumi qui fait le tour du quartier pour compter les maisons qui etendent plus leur linge. onze. elle est trop forte',
    'fugaku qui te sort que c la deuxieme fois qu\'il ment a un gamin de sept ans pour toi. jsuis mort',
    'hiruzen avec son chapeau posé a coté de lui toute la journee et jamais sur la tete. c voulu et c parfait',
    'sasuke il t\'a suivi jusqu aux marches du sanctuaire trois fois et il a fait demi tour a chaque fois. il sait frr',
    'fugaku supporte pas qu\'on le contredise devant le clan. j\'ai perdu deux soirs a argumenter sous le septieme tatami pour rien',
    'shisui qui refuse direct que tu decides a sa place. j\'ai voulu le proteger et il m\'a grillé en deux secondes. frustrant mais bon c lui',
    'la salle sous le septieme tatami elle est faite pour 30 et ils sont 40, on sent le bordel. j\'ai rien suivi a la premiere reunion',
    'j\'ai eu la fin ou les deux freres partent par la porte sud. jsuis pas sur que ce soit la bonne mais jregrette rien',
  ],
  story_second_skin: [
    'tessa sera sur les rails a 4h du mat que tu viennes ou pas. meilleure pote de l appli sah',
    'la crypte avec sept siecles de cristaux qui gardent les formes que les gens ont PAS choisies. jsuis resté bloqué sur cette phrase',
    'le cordon du choix tressé par ta famille dans les couleurs qu\'ils pensaient que t\'allais prendre et toi tu prends autre chose. aie aie aie',
    'chez toi y a une porte elargie il y a onze ans pour un de tes parents. rien que ca et j\'y crois a ce monde',
    'gardiens de la couronne, concorde des parentés fixes, les doubles, larkspire... jme suis perdu dans les factions la premiere heure',
    'la grande route ct onze jours de trajet et j\'ai eu l\'impression de les faire en vrai',
    'edran avec ses bois et les embouts dorés qu\'il porte tous les jours, meme pas que pour les ceremonies. il en impose grave',
    'kaia elle faisait du sauvetage en montagne au col de veyr et ca se sent, elle te donne l\'ordre d\'abord et la raison apres',
    'j\'ai pris faucon et je lis un visage a 400 pas mdr, les rails deviennent carrement un deuxieme quartier',
    'sai avec ses mains toujours froides et toujours stables, il regarde tes mains et pas ton visage. serpent et medecin, logique',
    'en panthere des neiges tu te retrouves en haut des trucs avant d\'avoir decidé de grimper. j\'ai passé la moitié du jeu sur les toits',
    'ilyra qui a demandé l\'annexe medicale quatre fois et qui arrete pas de redemander. je l\'aime cette femme',
    'ren qui te sort le truc le plus gentil du monde sans aucune intro, c exactement la qu\'il faut ecouter',
    'le quartier du canal avec ses onze auberges ou personne te pose de questions. ma planque quand ca chauffe avec les gardes',
    'tessa: elle a pas regardé les portes, elle a regardé le sol. ptn cette ligne',
    'j\'ai eu la fin ou tu rentres a larkspire et t\'es juste un ado de 16 ans. calme, un peu triste, j\'ai kiffé',
    'le cerf c stylé deux minutes et apres tes bois se prennent dans chaque porte. je regrette grave',
    'le breuvage apaisant j\'en ai bu a chaque fois et j\'ai rien senti de special, jsp a quoi il sert',
    'j\'ai relaché quatre secondes en plein marché et apres tout le monde me regardait bizarre pendant des heures. un peu abusé',
    'la porte de la capitale c trop administratif, des gardes polis qui notent ton nom et c tout',
  ],
  story_pink_tide: [
    'askip le plancton brille que quelques semaines par an et moi j\'ai eu le rivage pink tide rose magenta a chaque coup de pagaie. plus belle scene de l\'appli',
    'la tour ocean 808 trop propre, le chargeur encore branché derriere la table de nuit... j\'ai eu froid dans le dos en plein soleil',
    'le recoin du personnel avec les 3 marches la poubelle et le cendrier c la que tout se dit, j\'y ai passé la moitie de ma semaine mdr',
    'marcus dans la villa neuf qui t\'offre un verre en t\'expliquant calmement tes options. le calme de ce mec ptn',
    'june bosse que de minuit a 4h donc si tu te couches tot dans le jeu tu la rates. jai raté la moitie des infos a cause de ca',
    'celeste te file pas ses photos parce que c une campagne pour une marque qui l\'a meme pas payée. je comprends mais deux jours de galere, relou',
    'sora qui te pique tes lunettes de soleil dans les dix premieres minutes. elle a decidé que t etais a elle pour la semaine jpp',
    'le carnet marée & sel avec le paddle dessiné sur la couverture... si elle te le montre c qu elle a decidé un truc sur toi. j ai pas survécu',
    'j ai dit a sora que j etais pas interessé et elle a arreté de flirter direct, sans bouder, toujours aussi chaleureuse. respect grave',
    'june avec son crayon planté dans le chignon qui te sort que 2h du mat c l heure ou les gens disent la verité. elle parle peu mais chaque phrase tape',
    'reika qui te recite 180 chambres, 40 villas, 411 employés et 11 semaines de saison comme d autres parlent de leurs sentiments mdr',
    'nami perd ses lunettes h24 jpp',
    'j ai perdu trois matchs de volley apres 17h contre des clients a moitie bourrés et franchement c etait le meilleur moment de ma semaine',
    'le tableau des activités qu ils reecrivent devant tout le monde, plus de catamaran plus de plongée, alors que la mer est encore plate. la pression monte tranquille',
    'pendant la tempete le generateur clignote deux fois et tient. j avais le coeur a 200 genre',
    'le hall avec les orchidées changées tous les deux jours et trois personnes a l accueil qui disent jamais non. tout est trop parfait et c ca qui fout la frousse',
    'la note au checkout c abusé, j ai tout mis sur la chambre et payé des tournées au toit, ca pardonne pas',
    'celeste negocie TOUT, meme le petit dej. perso cool mais au bout d un moment j en pouvais plus',
    'des que la detective debarque tout prend trois plombes, les demandes, les images, l attente. realiste ok mais relou',
    'luka veut pas parler de sora des qu il capte qu elle te plait. logique mais du coup j ai rien su de leur histoire, frustrant',
  ],
  story_good_morning_husband: [
    'la tasse ebrechee que tu evites sans y penser parce que ton corps s\'en souvient et pas toi. j\'ai fermé l\'appli 5 min',
    'le lit parapluie encore dans son emballage dans la chambre d\'amis. j\'ai rien dit. j\'ai juste regardé l\'ecran',
    'la liste de courses sur le frigo en deux ecritures et la mienne c la plus illisible mdr meme dans une autre vie jecris comme un pied',
    'le QG avec le tableau des plats du jour pas mis a jour depuis le printemps et le couple qui a un avis sur vous deux. je veux vivre la',
    'chez les mori c trop pour moi, la cuisine a fond, sa mere qui te sert en 90 secondes, les chaussures partout... jsuis ressorti sans rien retenir',
    'c lent. genre trente tours de petit dej et d\'etagere avant qu\'il se passe quoi que ce soit. c voulu jsp mais bon',
    'kenji avec son crayon de charpentier derriere l\'oreille meme a table, meme a un mariage. ce mec est un meme',
    'astuce: pose a hana une vraie question sur SA semaine a elle, pas sur le mariage. apres ca le balcon le soir change tout',
    'onze metres carres de chambre d\'amis et on s\'est engueulés trois soirs dessus. on l\'a vidée et laissée vide, jsp si c une victoire',
    'emi qui rentre avec sa clé, met la bouilloire avant d\'enlever son manteau et te pose LA question en 90 secondes. je la deteste je l\'adore',
    'lucia qui decroche au neuvieme appel par principe jpp',
    'nao ibarra avec son carnet fermé par un elastique, toujours dans la meme poche. je veux savoir ce qu\'il y a dedans',
    'la gare centrale entre 1h et 2h du mat, y a quasi personne et les agents d\'entretien se parlent d\'un bout a l\'autre. ambiance de ouf',
    'jeudi c la date limite et moi j\'ai trouvé la lettre au studio mercredi soir. ptn le stress',
    'le parc au bord de l\'eau, le banc avec la plaque, demande lui c quoi la blague. c tout ce que je dis',
    'hana est trop parfaite les deux premiers jours, je voyais pas pk j\'aurais envie de partir, du coup le choix fait un peu fake',
    'le mystere du quai 11 est cool mais tellement facultatif que j\'ai fait 2 runs sans le croiser. dommage, askip c le meilleur passage',
    'j\'ai eu deux villes comme fin et les appels a des heures pourries m\'ont achevé. meilleure fin du jeu sah',
    'l\'etagere a moitie montee depuis cinq semaines, j\'ai raté mon jet pour la finir quatre fois. nul en bricolage meme en jeu',
  ],
  story_hush_house: [
    'l\'enregistreur orange dans le tiroir de la cuisine du 312 avec deja 4h dessus. j\'ai ecouté. fallait pas',
    'ayame achete deux cafés en canette tous les soirs et elle a jamais dit pk elle en prend deux. jsuis pas pret',
    'la chaise de la 309 tournée vers la porte. non',
    'mika qui se trompe de temps en temps sur un petit detail de sa propre vie. j\'ai relu la ligne trois fois frr',
    'tomas voit un truc deux fois dans l\'escalier et apres il t\'explique que c rien et repart bosser. ca casse l\'ambiance a chaque fois',
    'le mur de feuilles d\'ayame avec le plan, le rapport d\'incendie et l\'horaire de tram entouré, j\'ai rien capté et le jeu t\'aide pas',
    'mme vale et ses onze porte-cles dans la poche du gilet, tu l\'entends arriver avant de la voir. frisson',
    'le toit a 4h du mat avec la vue sur le port, la porte qui ferme jamais a clé, tout l\'immeuble y est deja monté au moins une fois. mon endroit prefere du jeu',
    'l\'etage 0 avec des lampes a gaz et une fenetre au bout alors que l\'immeuble a aucun couloir avec une fenetre. mon cerveau a buggé',
    'tomas il bosse la nuit et dort toute la journee derriere son scotch noir, je l\'ai croisé genre deux fois de toute ma run',
    'nia qui tient son tel a hauteur de poitrine meme quand elle te parle, avec la coque toute eclatée. c moi en vrai',
    'astuce: prends travail de nuit au debut, 2h du mat c une heure normale pour toi et du coup le toc a 2h13 fait encore plus peur',
    'la 312 est trop belle pour le prix, parquet, grande baie vitree, radiateur... evidemment que c un piege mdr',
    'j\'ai vendu l\'histoire a un journal et tout morrowgate a decidé que j\'etais instable. la maison etait plus sympa avec moi que la ville wsh',
    'le premier soir ayame te demande de pas faire la tete que les gens font. je l\'ai faite direct mdr',
    'mika qui dit qu\'elle voulait juste voir qui habite la 312 maintenant. tu lui ouvres pas. tu lui ouvres PAS',
    'j\'ai eu aube sur bellweather comme fin, rien de resolu mais j\'etais encore moi et le radiateur marchait. ca m\'a suffi',
    'les allers retours dans le reste de morrowgate c interminable, un quart d\'heure pour y aller et la journee entiere pour revenir',
    'je voulais une romance avec ayame et des que ca devenait mignon qqch toquait a la porte. relou. bon c un jeu d\'horreur jsp ce que j\'attendais',
    'le rythme est chelou, un truc horrible dans le couloir et deux min apres la bouilloire siffle et on parle loyer. jamais su si je devais avoir peur',
  ],
  story_zero_throne: [
    'le low ring avec 40 ans d\'ecussons des deux camps et la regle: personne demande a personne ce qu\'il a fait pendant la guerre. meilleur bar de toute l\'appli',
    'la grue du hangar quatre qui grince au troisieme passage jsp pk ce detail m a autant marqué',
    'eli vale a onze lettres que personne a lues et j\'ai passé ma run entiere a essayer de les lire',
    'morrow s\'est construite sur les habitudes d\'un mort et elle me contredit tout le temps. je l\'adore',
    'la place se vide en 90 secondes, dinguerie, et apres t\'enchaines les bureaux de l\'autorite pendant des heures. le rythme s\'effondre',
    'rhea met genre trois jours a decider ce que t es et pendant ce temps elle te regarde de travers. j ai failli lacher',
    'morrow qui sort "ce plan nous fait tuer" et qui y va quand meme derriere. jpp de cette ia',
    'mina qui jure uniquement contre le matos, jamais contre les gens. c moi au taf',
    'rhea et sa cicatrice sous la machoire qu elle cache jamais et qu elle explique jamais. j ai demandé trois fois, rien',
    'talon qui te paie un verre, super sympa pendant deux heures, et qui passe tout ce temps a comprendre ce que tu veux. je me suis fait avoir grave',
    'venn qui te dit cash qu elle te recrute et qu elle prefere que tu voies le mecanisme plutot que de croire que c de l amitié. flippante mais honnete',
    'eli qui se trimballe une mallette de papiers partout parce qu il fait confiance a rien de connecté. il a raison sah',
    'au bar du hall tu poses deux doigts sur le comptoir sans rien dire et on te sert un truc qui est pas du café mdrr',
    'le controle du trafic qui voit onze echos dans la ceinture qui tiennent leur position. des debris ca fait pas ca. frissons',
    'orin qui porte son alliance au bout d une chaine et qui la tripote quand il reflechit. j ai rien demandé, j ai juste regardé',
    'j ai refusé le cockpit et j ai fait passeur aux docks toute la quinzaine. morrow m a quand meme fait la morale mdr',
    'les jauges sont cachées, jsavais jamais combien de nerf il me restait avant de craquer en plein combat',
    'l usure du mecha redescend tellement lentement qu apres un gros combat t as peur de ressortir pendant des jours',
    'kestrel me deteste et jsais meme pas pourquoi, les reputations bougent sans prevenir',
    'la place du memorial fait 140 metres et le mecha la traverse en deux lignes. j voulais que ce moment dure plus',
  ],
  story_nine_weeks: [
    'la pointe avec son arbre mort de l\'autre coté du lac, tout le monde y va une fois avec qqn. moi j\'y suis allé avec la mauvaise personne mdrr',
    'la salle de bain des cabanons avec UNE bonne douche. j\'ai fait deux saisons en vrai et c exactement ca',
    'la route du village a 2h du mat sans aucun lampadaire, les conversations qui commencent la vont toujours au bout. trop vrai',
    'cass sait pourquoi juno a disparu l\'an dernier et le garde pour iel depuis un an. le perso le mieux ecrit du jeu',
    'les services en cuisine c deux cents couverts a chaque fois, au bout dun moment jles skippais tous',
    'juno qui esquive avec une blague deux fois avant de repondre pour de vrai, mignon au debut, a la 15e fois j\'avais envie de secouer ce perso',
    'la photo de l an dernier, neuf personnes sur le ponton et juno qui rit a un truc hors cadre. le jeu sait tres bien ce qu il fait',
    'teo avec les avant bras cramés par le passe des le deuxieme jour. premiere saison energy mdr',
    'cass qui tient jamais debout tout seul, toujours contre le bar, une barque ou un encadrement de porte mdr',
    'nadia et son gilet par dessus l uniforme meme en plein cagnard, et le bloc note sur lequel elle ecrit JAMAIS',
    'astuce: juno est au ponton pour les bateaux en journée, si tu veux lui parler loin du bar c la',
    'ramener la bonne bouteille sur les marches ca veut dire un truc, en ramener deux ca veut dire autre chose. appris a mes depens',
    'les ragots redescendent tout seuls si tu te tiens tranquille quelques jours, trop realiste',
    'le bar du longhouse avec le lac sur tout un coté... j ai passé la moitie de mes pauses a regarder l eau',
    'juno dans la meme veste en jean que l an dernier avec le poignet tout usé. j ai du poser mon tel deux secondes',
    'nadia: tu es au ponton a six heures, je t ai donné le bon service parce que je t aime bien, en fais pas une erreur. glaciale et je l adore',
    'l energie est sur 20 et couvrir un service t en bouffe 8. apres t as plus rien pour la soirée',
    'le chemin pour sortir avec nadia est bloqué derriere tellement de conditions que j ai laché l affaire',
    'les scenes au bar c toujours cass qui drague et nadia qui surveille, au bout de trois semaines ca tourne en rond',
    'c juno qui decide ce qu iel fait avec teo, pas toi, et sur le moment j ai trouvé ca super frustrant',
  ],
  story_red_moon: [
    'la fusée de detresse: rouge pour contact, vert pour clair, et pas de couleur pour ce qui est arrivé a ton equipe. jsuis mort',
    'la crypte sous la salle des specimens, onze cellules et qqn les nettoie. QUELQU\'UN LES NETTOIE',
    'le kit d\'ancrage avec trois ampoules que l\'infirmerie refuse de nommer, jl\'ai jamais ouvert par peur mdr',
    'elian voss il est pas sinistre il est juste content de t\'examiner et c\'est tellement pire',
    'les cendres c vingt km de sable pale et c exactement aussi chiant a traverser que ca en a l\'air',
    'six styles d\'armes d\'un coup, briseur coutelas fusil lance... jsavais pas quoi prendre et j\'ai changé trois fois',
    'ren qui te dit "dis le truc. peu importe ce que c\'est." et moi qui continue a mentir... jme sentais trop mal',
    'le vaultback c\'est 12 metres de dos blindé avec une gueule en dessous et il est deja mort quand tu commences. imagine vivant',
    'le nettlejaw tes cheveux se dressent a une dizaine de metres avant meme que tu le voies, gros frissons',
    'venn et sa brulure dans le cou qu\'elle a jamais expliquée, j\'ai BESOIN de savoir',
    'j\'ai pris "ca paye, sinon c\'etait les tanneries" comme raison et tout le monde me le ressort mdr',
    'ossa qui fait clic clic avec son compteur en laiton et qui a remarqué que t\'as pas pris de bouclier depuis 3 semaines. grillé',
    'l\'ancrage ca prend un quart d\'heure a chaque fois, sangle, truc a mordre, ampoule... au bout de la 5e fois jen pouvais plus',
    'le briseur c\'est un seul coup depuis les talons, trop lent pour moi. mais quand ca touche wsh',
  ],
  story_blackwake: [
    'le cimeterre de l\'atelier que ferro utilisait pour ouvrir des caisses mdrr ton heritage c un ouvre caisse',
    'le silence, une cloche fêlée sans battant qui coupe tout le son onze secondes. je l\'ai sonnée au pire moment et c\'etait parfait',
    'rook qui se balade avec une lame de marine du meme modele que celle qui a tué ferro. j\'ai dormi avec un oeil ouvert toute la traversée',
    'stormlee, la tempete qui s arrete jamais et le village du coté abrité ou personne part. frissons',
    'payer harrow bell pour les deux tiers ouest de ma propre carte ca m\'a saoulé, j\'avais pas l\'argent et jsuis resté bloqué a la derive',
    'nessa vale, veyra sol, ferro vane... jai confondu nessa et veyra pendant une heure, trop de noms qui se ressemblent',
    'tolla qui te sort "tu peux l\'avoir vite ou tu peux l\'avoir qui flotte" jsuis mort',
    'mako qui plonge a presque 30 metres a 16 ans et qui te le dit comme si c\'etait rien',
    'rook "demande moi demain. jsuis serieux." tous les jours. TOUS LES JOURS frr',
    'harrow bell avec une bague a chaque doigt sauf l\'index gauche, j\'ai fixé ce doigt pendant tout le marchandage',
    'la moelle en vf ptdr le bateau s\'appelle la moelle. bon en vrai ca passe',
    'veyra qui se pointe a stormlee canons rentrés juste pour parler... jsavais pas si je devais flipper ou pas',
    'nessa qui se barre parce que j\'ai signé avec une maison marchande. ok elle m\'avait prevenu mais c\'etait pour payer la quille',
    'la traversée de la ceinture de tempetes jusqu\'a stormlee c long, j\'ai passé mon temps a pomper la cale',
  ],
  story_primal_crown: [
    'le cordage du compte avec un noeud pour chaque dette, j\'ai appris a le lire mieux que mon compte en banque mdr',
    'le perchoir a 60 metres avec un escalier de corde et aucune rambarde. vertige irl',
    'suri te nourrit avant de te poser une seule question. voila. c la meilleure',
    'la crete de verre noir chaude sous les pieds depuis le printemps, l\'odeur d\'oeuf, plus rien qui broute. ambiance de fou',
    'griffe de flamme, croc de givre, dos de pierre, feu du ciel... en vf jles melange tous, j\'ai du faire une liste',
    'trop de negociations au cercle de pierres pour moi, je voulais juste monter mon raptor et partir',
    'ilya qui garde ses lunettes en corne sur le front meme pour dormir. c\'est mon perso prefere et il le sait',
    'mako avec ses mains vert-brun jusqu\'aux poignets qui te demande ce que t\'as fait et pas ce que tu voulais faire. jsuis mort',
    'le jeune predateur en panique dans les allées du marché, jme suis mis entre lui et les gosses et kaia m\'a lancé la corde. debut de fou',
    'le quai stoneback c\'est le coin le plus riche du marché et le moins marrant, tout est pesé et noté sur des cordes. vibe comptable',
    'les grottes aux os ou les animaux liés entrent tranquilles et ressortent jamais seuls. j\'ai laissé ma monture dehors, pas folle',
    'suri et son tigre a dents de sabre qui dort la tete sur ses bottes et elle le calcule meme pas. icone',
    'ilya fait payer chaque phrase en sel, j\'etais a sec avant midi le premier jour. economie trop dure frr',
    'on parle de la mâchoire blanche tout le temps et je l\'ai croisée qu\'une fois en trois parties. askip faut la pister jusqu\'aux grottes ?',
  ],
  story_seven_days: [
    'le carnet que tu rachetes chaque lundi chez le marchand de journaux alors qu\'il est vierge a chaque fois. je l\'ai racheté a chaque boucle, par principe',
    'le registre de la marina avec la page de la semaine ou la tour s\'est arretée decoupée au couteau. j\'ai crié tout seul',
    'theo a la table du milieu de la biblio qui remarque que tu sais deja ou sont les trucs. il m a grillé direct ptn',
    'l\'horloge arretée a 23h59 depuis avant la naissance de tout le monde. brrr',
    'sera wynn debarque que le mercredi donc lundi mardi tu te fais chier a chaque boucle',
    'deballer les deux sacs ca prend 40 minutes chaque lundi. a la cinquieme boucle j\'ai arreté, trop repetitif',
    'mina et sa montre a gousset qui marche pas, accrochée par dessus son manteau. j\'ai mis 4 boucles a capter le detail',
    'la salle du conseil est genre beaucoup trop grande pour une ville aussi petite et le jeu le fait remarquer. jadore ce genre de trucs',
    'astuce : pose une deuxieme question a elias. tout le monde decroche a la troisieme phrase, fais pas pareil',
    'la bonne bouteille de l\'esplanade que tout le monde trouve trop chere et que tout le monde achete. j\'en prends une a chaque boucle pour mina',
    'ivy qui te sort "t\'es nouveau, ca va passer" alors que t\'as deja vecu la semaine six fois. jpp',
    'le carnet rouge a spirale de theo qu\'il montre a personne... jveux savoir ce qu\'il y a dedans svp',
    'j\'ai pris le bavard mais tout le monde t\'oublie chaque lundi donc la confiance faut la refaire a chaque boucle, c relou',
    'la clé de la tour en fer beaucoup trop lourde pour sa porte, j\'ai jamais compris a quoi elle servait. ca a mené a rien dans ma partie',
  ],
  story_window_seven: [
    'le piano a queue dans le penthouse que personne joue, je l\'ai fixé au teleobjectif une nuit entiere en attendant que qqn s\'assoie',
    'les trois telephones jetables sous blister dans le tiroir du 7C achetés dans trois quartiers differents. ce detail m a mis en mode parano',
    'le troisieme bollard en partant de l est. jdis rien',
    'halden qui prend des nouvelles de ta santé et le pense vraiment tout en archivant tout ce que tu dis. le perso le plus flippant du jeu',
    'mara gere l\'appart, le planning et toi, les trois premieres nuits j\'avais l\'impression de jamais rien decider',
    'juno a l\'accueil vend tout a un prix qu\'il trouve tres raisonnable. moi pas du tout, j\'ai jamais eu de quoi payer son journal d\'acces',
    'le teleobjectif que mara a reglé et qu\'il faut surtout pas bouger. je l\'ai bougé de 2 cm, elle m\'a regardé comme si j\'avais tué qqn',
    'TU TE TROMPES D\'APPARTEMENT a 01:17 la premiere nuit. j\'ai relu le message genre dix fois',
    'tobin ash qui te dit que tu peux refuser de lui parler et qu\'il notera juste que t\'as refusé. le mec le plus poli et le plus flippant du jeu',
    'selene en chemise blanche a toute heure, meme sur le balcon a 1h du mat. elle a une aura de boss',
    'mara : "j\'en ai fait quatre, deux etaient chiantes, tu veux que celle ci soit chiante". bah c raté ma grande',
    'l\'avenue kellis a 3h du mat avec le tram au milieu, la rue la plus vide de veyra et la plus facile pour se faire prendre en photo. ambiance de ouf',
    'j\'ai pris muté, l\'ancien militaire qui deteste rester immobile... dans un jeu ou tu restes assis sept nuits. grosse erreur mdr',
    'le bureau de halden a la direction neuf sans fenetre, j\'y suis allé une fois et j\'ai rien compris a ce qu\'il voulait vraiment. trop de sous entendus',
  ],
  story_red_floor: [
    'maki a filé onze clés du mikado en vingt ans et il peut citer les onze. jveux etre la douzieme frr',
    'la cassette de daigo avec la note il fait ça quand il s\'ennuie. jai regardé les deux rounds entourés genre 4 fois',
    'onigiri et boisson de sport a 4h du mat a la superette apres s\'etre pris des coups dans la tete et tout le monde fait comme si c normal. jadore ces gens',
    'riku qui t\'observe depuis huit semaines et te sort tout ce que tu fais mal en une phrase. insupportable jlaime',
    'jai pris jamais suivi d\'entrainement et descendre au sous-sol du mikado sans savoir boxer ct violent, les premiers dimanches jme suis fait demonter',
    'technique de ring ou calme jai toujours pas capté la diff',
    'mei qui a une petite gene au genou gauche que dans les escaliers alors que c\'est la plus solide de toute la salle. ce detail ptn',
    'koji avec l\'encre sous les ongles a cause de l\'imprimerie de son oncle, la radio bloquée sur la meme station depuis 2009. jveux un spin off namba impression',
    'junpei qui te demande ce que t\'as pesé ce matin et pas hier soir parce qu\'il sait deja. le grand frere de toute la salle',
    'la ceinture au fond de l\'armoire au onzieme etage, dans un appart ou y a presque rien d\'autre. j\'ai du poser mon tel deux minutes',
    'aya qui s\'enroule les bandes en te parlant et qui recule jamais en ligne droite. meilleure meuf du jeu',
    'maki et ses lunettes sur un cordon autour du cou alors qu\'il lit jamais rien. ce vieux jlaime trop',
    'la clinique de mei est mieux equipée que le mikado et j\'y ai passé beaucoup trop de temps. moi je voulais me battre, pas regarder des scanners',
    'personne rentre au camp de daigo sans etre amené et j\'ai jamais trouvé qui pouvait m\'y amener. frustrant',
  ],
  story_last_five: [
    'le numero 24 parce que personne en voulait. deja attaché a ce maillot sah',
    'bo fait 2m06 et te demande sans aucune honte c quoi un ecran jpp',
    'jun qui tire 400 fois par jour depuis mars et toi tu debarques en octobre pour lui piquer sa place. le malaise dans le vestiaire est reel',
    'tsubame qui demande comment va dai avant meme de savoir qui t\'es. ptn mon coeur',
    'onze casiers dont six utilisés au vestiaire de kosei, jcapte le symbole mais avec si peu de joueurs les matchs se ressemblent vite',
    'gora fait 2m16, c le mec le plus gentil du monde et jai pas mis un seul panier contre lui. match relancé trois fois, jai rage',
    'mikael qui te parle pendant 32 minutes non stop avec sa dent en or, le mec est insupportable jladore',
    'astuce: montez sur le toit apres l\'entrainement, kai se planque la pour eviter le bus et il parle beaucoup plus',
    'nori avec son ordi dont la charniere tient au scotch qui te sort ce que tu fais avant que toi tu le saches. meilleur perso',
    'le truc bleu du distributeur qui a le gout d\'une couleur mdr jen bois un avant chaque match maintenant',
    'le tirage regional ou les cinq ecoles tombent toutes dans la moitié de kosei. quelqu\'un rigole et s\'arrete net. frissons',
    'kurogane a gagné onze fois d\'affilée a domicile et yuki monte jamais le ton. flippant',
    'perdu trois fois contre seiran, rei marque ce qu\'il veut et y a aucune solution tactique, faut juste le defendre et jy arrive pas',
    'dai qui se tord la cheville et aucune bonne option. jlai fait jouer et il etait moins bon tout le reste de la saison, jsp si c voulu',
  ],
  story_tidewall: [
    'la poignée de l\'epee de wren faite pour une main plus petite que la tienne. un detail et jsuis detruit',
    'le dernier arrivé au ptit dej ratisse la cour de rassemblement. jai ratissé toute ma partie mdr',
    'verne a entrainé ta soeur et elle en parle jamais. jamais',
    'le sel de garde qui continue de bruler une heure apres. j\'hesitais a chaque blessure',
    'dix-neuvieme au classement au debut et ça remonte tellement lentement que jai failli lacher',
    'jai pris guerisseur et je me suis retrouvé sous les tentes de la main calme pendant que les autres montaient sur le mur. jaurais du prendre archer',
    'astuce: parlez a bec tard aux tentes ou aux lignes des betes, jamais dans la cour. il dit rien si un officier peut passer',
    'les grands arcs de la longue-vigie sur leurs plateformes qui tournent, quatre personnes par arc qui se gueulent dessus avant le ptit dej mdr',
    'jai grandi au nord du mur dans ma partie et jai rien dit a personne de toute la run. ambiance',
    '160 km de mur et les fermes toutes petites et oranges vues d\'en haut. ça vaut le coup de tenir',
    'le jeton de recrue avec ta place poinçonnée sur le bord, jai regardé le mien changer genre dix fois',
    'la main calme c la seule faction autorisée partout sur le mur et personne discute avec elle. guerisseur rien que pour ça',
    'le fleau guerit pas tout seul et j\'avais plus de sel de garde en pleine marée. galere grave',
    'la marche de fer on te promet un truc enorme a monter "un jour", en attendant t\'as des corvées et du sable gelé',
  ],
  story_seven_names: [
    'marcel qui tousse a travers ton mur depuis onze mois, t\'as jamais vu sa tete et d\'un coup il sort d\'un trou. jpp',
    'une clé limée a partir d\'une cuillere et d\'une charniere. le vieux est un genie',
    'renaud qui a relu le dossier onze fois et trouvé quatre trucs qui collent pas. mon perso prefere et de loin',
    'du pain une saucisse et une bouteille sur un quai a 6h du mat apres onze mois sans sel. cette scene m\'a plus touché que tout le complot',
    'le francais d\'epoque avec les francs et la carte du PLM c stylé mais des fois jcomprenais rien',
    'six heures pour prouver que t\'es innocent ou quitter l\'ile, jai paniqué et perdu la moitié du temps dans le tunnel. trop de pression pour moi',
    'renaud qui numerote tout premierement deuxiemement troisiemement sans s\'en rendre compte, jle fais irl maintenant jpp',
    'la chambre au dessus de la buanderie a 1 franc 50 la nuit, pas de registre, la vapeur qui monte du plancher. mon QG',
    'celeste qui garde ses gants noirs a l\'interieur et les enleve que pour toucher du papier. elle est trop classe',
    'solene artois avec de l\'encre sur la main alors qu\'elle a pas composé une page depuis vingt ans. j\'adore ces details',
    'astuce pour le cabinet bellier: demandez lui ce qui s\'est passé et taisez vous. jai voulu la menacer au premier run, je regrette grave',
    'l\'express de paris 14h de trajet, genre neuf personnes interessantes a bord et au moins une qui te cherche. stress de ouf',
    'la chaleur monte trop vite des que tu fais un truc un peu voyant, j\'ai passé la moitié de ma partie planqué',
    'le registre eparpillé entre une banque un couvent et un notaire, jme suis perdu dans paris askip c normal',
  ],
  story_unbound: [
    'le feuillet de probation ou la liste de ce que t\'as pas le droit de faire est plus longue que l\'autre. direct t\'as compris ta place',
    'jporte le bracelet gris d\'oyan partout, c pas illegal mais tout le monde le remarque et j\'assume',
    'renna qui te dit en face qu\'elle voulait pas de toi. au moins c honnete',
    'une forme laisse une trace lisible pendant un jour et la lorgnette te montre laquelle. l\'enquete est trop bien pensée wsh',
    'jai pris indécis comme souffle et jsais toujours pas si c\'etait une erreur, ça m\'a paru mou longtemps',
    'l\'escalier du fleuve ou les cinq ecoles se croisent deux fois par jour, jaurais voulu qu\'il s\'y passe plus de trucs',
    'renna qui t\'appelle probationnaire jusqu\'au jour ou elle dit ton prenom sans rien expliquer. jai crié',
    'tam et sa coupe de cheveux hors de prix qui repousse n\'importe comment depuis trois mois mdr le detail',
    'astuce: le marché de nuit t\'apprend a lire les traces mais mal et contre de l\'argent. renna le fait mieux si elle t\'aime bien',
    'jai pris pierre et l\'enracinement c trop satisfaisant, les eleves du kiln rebondissent sur toi',
    'la maison de confinement avec du thé pour deux sur la table et une porte sans poignée a l\'interieur. frissons',
    'sera qui porte plus la bande et a une marque plus pale sur le poignet a la place. elle dit rien et moi non plus',
    'la tension monte trop vite quand tu enchaines les formes et y a jamais assez de sel du fleuve',
    'deux cents eleves au kiln et tu parles a genre trois personnes, la cour manque de vie',
  ],
  story_salt_road: [
    'la carte de ferrow avec neuf traversées en neuf encres et un point d\'interrogation sur le troisieme puits. rien que la carte m\'a stressé',
    'le panneau a la porte d\'ossun avec les noms de ceux qui sont pas arrivés. premiere scene et j\'avais deja froid dans le dos',
    'la mallette plus lourde qu\'elle devrait avec la marque d\'une maison fermée y a quarante ans. jai 12 theories',
    'quatre chariots encore chargés et personne a rien pris. ptn',
    'le voile de sel qui te retrecit la vue jsais que c le principe mais jai detesté',
    'jai passé toute ma partie a faire des calculs de gourde avec sabe qui boit la meme eau que moi, ct plus des maths qu\'une histoire',
    'ferrow qui te dit je vais pas te dire que ça va aller, je vais te dire quand boire. jsuis amoureuse',
    'jai pris messager pour les deux gourdes en plus et jai quand meme failli crever au jour 8 mdr',
    'on a emmené toute la caravane au nord vers les epaves et ferrow a accepté, jsuis trop fier de ma persuasion',
    'astuce: parlez a ferrow tot et souvent, sinon au troisieme puits elle vous lache rien',
    'sabe qui parle non stop et qui devient super calme quand ça compte. jlaisserai jamais sabe derriere',
    'le sel conserve tout la bas, meme ce que les gens ont laissé. cette phrase m a hanté toute la partie',
    'eclaireur c nul, tu tiens la ligne contre personne la moitié du temps',
    'le deuxieme puits est blindé de monde et jaurais voulu parler aux autres voyageurs, on peut presque rien faire avec eux',
  ],
  story_fourth_beast: [
    'morel te trouve dans une base de données, t\'envoie quatre phrases et paf t\'as un animal dans ton sac qui meurt sans toi',
    'la boulangere qui demande plus ce qu\'il y a dans ton sac et qui en met un en plus. jsuis mort',
    'nox qui fixe les inconnus au lieu de se cacher avec son air de desapprobation. jai choisi le bon',
    'lina et sa bouilloire allumée depuis mars au quatrieme sans ascenseur avec toutes ses epingles sur la carte. elle merite tout',
    'on revient trop souvent au labo sous l\'institut, jaurais voulu voir plus montmartre et le canal saint martin',
    'les carrieres ça fait 180 km de galeries et jme suis senti perdu tout le long, un peu relou',
    'marea c une mini orque avec des pattes qui te pique tes trucs, j ai rien a ajouter',
    'aurèle qui suit une seule odeur sur quatre arrondissements alors que mon chien trouve pas sa gamelle',
    'ravel qui repete ta phrase avec un seul mot changé pour te montrer ce qui va pas. je la respecte trop',
    'jai dit non aux trois bestioles pour voir et ça continue quand meme, t es juste un humain dans paris avec un tueur. stress de ouf',
    'camille qui repond a chaque question par un plan, jl adore mais elle me laisse jamais finir mes phrases',
    'le canal saint martin avec les gens posés sur le quai alors que deux disparitions ont eu lieu a 400 m, ambiance chelou mais trop bien ecrit',
    'jsuis parisienne et on traverse la ville en 10 min de metro partout, dans la vraie vie c 45 min mdr',
    'ma bestiole a changé de forme en pleine course poursuite et jai rien compris a ce qui se passait',
  ],
  story_ninth_archive: [
    'les portraits dans le bureau de la gardienne, ils sourient tous et plusieurs sont pas dans le registre. frissons',
    'huit portes avec huit chiffres en laiton et toi tu cherches la neuvieme. ce setup est trop fort',
    'bram te trouve tout ce que tu veux et annonce le prix plus tard. jai peur de ce que je lui dois mdr',
    'le manteau plié derriere la cheminée sur le toit. jai passé une soirée entiere a chercher qui montait la haut',
    'le feu de garde qui fait jamais de bruit c flippant les deux premieres fois et apres jmen foutais un peu',
    'kael enquete sur moi tout le trimestre et jaurais aimé plus de scenes ou il est pas en mode prefet',
    'ysolde qui te dit assieds toi, tu as eu une matinée... jsais pas pourquoi mais j ai eu envie de fuir',
    'kael qui te previent qu il va le noter pour que tu puisses pas dire qu il l a pas dit. le mec est carré a un point',
    'bram il lui manque deux doigts et personne en parle jamais. c quoi l histoire ??',
    'mira avec l encre jusqu a la deuxieme phalange qui me couvre au portail sans que je demande rien. je la protegerai',
    'esprit calme pour que les protections te trouvent chiant, c moi en cours tous les jours',
    'astuce: si tu te tiens tranquille la suspicion redescend toute seule, pas besoin de paniquer',
    'jai pris langue d argent et des que la parlote marche pas t as plus rien, kael m a coincé deux fois',
    'lecture de sigil jai rien capté, j ai cramé toute ma concentration le premier jour et apres tout etait flou',
  ],
  story_understudy: [
    'teinture pour la gorge gout anis et desespoir mdr jai ri tout seul',
    'le bureau de deare avec une chaise pour lui et une pour celui qui a un probleme, et le carnet fermé sur la table. jsuis ressorti en sueur',
    'la lumiere fantome au milieu de la scene devant neuf cents sieges vides. ptn cette image',
    'dans le salon vert tout le monde fait semblant de pas regarder la liste des roles. c exactement comme au theatre en vrai',
    'talia est jamais vraiment mechante et jattendais un clash qui arrive pas, un peu frustrant',
    'ysra c un role pas une personne et jai mis trop longtemps a capter qu\'on parlait de la piece, le debut est confus',
    'marta avec ses epingles plantées dans la manche comme une cartouchiere, jveux etre elle plus tard',
    'jai refusé toute aide pour pas avoir de dette et du coup personne me devait rien non plus, jsuis devenu un meuble mdr',
    'la repet qui s arrete au bout de 11 min alors que la veille ils etaient allés jusqu a 20. l intro de ouf',
    'le technicien est nul quand on le regarde mais il sait ce qui casse et quand, jlai pris deux fois grave satisfaisant',
    'la compagnie verrine c onze eleves et un carnet, et le carnet a plus de pouvoir que les onze reunis',
    'tu connais le texte depuis fevrier et deare te dit juste doublure, en place. frissons',
    'le bureau du metteur en scene jy suis allé une fois et plus jamais trop de stress, mais jcrois que j ai raté un truc a cause de ça',
    'l endurance qui descend apres deux conversations c abusé, j etais crevé des la premiere semaine',
  ],
  story_blank_prophecy: [
    'ton tel a 11% et pas de reseau dans un tiers des endroits ou t\'en as besoin. athenes la nuit c ça. detail le plus realiste du jeu mdr',
    'la tasse ebréchée de la maison, tant que tu la tiens t\'es un invité. jlai plus jamais lachée',
    'eirene a lu quatre mille personnes sans jamais tomber sur un blanc et puis toi. jsuis obsédé par cette meuf',
    'la station service sur la route de delphes ou le café est vraiment excellent. pourquoi ce detail me rend aussi heureux',
    'kyros et sa lettre de quatre paragraphes hyper raisonnable, jsavais pas si je devais le detester et ça m\'a perdu',
    'la salle sous la roche avec onze sieges dont six occupés, trop de politique de dieux pour moi jsuis la pour chasser des monstres avec thalia',
    'hermes qui te dit que t\'es le truc le plus interessant pour son boulot depuis l\'imprimerie. un compliment et une estimation en meme temps jpp',
    'les tortues dans l\'herbe a l\'ancien cimetière ptn jy retourne juste pour elles',
    'despina qui recite les regles de la maison avec la meme voix que le plat du jour. donne moi le sac. jla veux comme grand mere',
    'l\'arc sans corde de thalia, elle l\'a depuis 4 ans et elle verifie encore son sac. c trop elle',
    'eirene qui ecrit dans son carnet sans jamais te lacher des yeux, flippant mais jladore',
    'le mur avec neuf cents noms dans l\'entrepot du pirée... le plus jeune avait six ans. jsuis resté bloqué',
    'hécate repond QUE a la question exacte que t\'as posée. jai gaspillé ma piece sur une question nulle, relou',
    'le délire monte et on voit jamais la jauge, jai capté que ça allait mal quand une porte a changé de coté du couloir. jsp si jaime',
  ],
  story_last_service: [
    'le carnet de keiko avec dix-neuf ans de couverts au crayon, une ligne par soir, la meteo et parfois un nom. jai pleuré pour un carnet',
    'la cuillere un peu tordue dans ton rouleau de couteaux que t\'as jamais remplacée. mon perso c moi',
    'la critique de reina que personne a publiée, neuf cents mots sur l\'akari. quand jai compris jai crié',
    'le repas du perso mangé debout a six en onze minutes. jai bossé en resto c EXACTEMENT ça',
    'l\'invitation dit onze services mais pas lesquels sont des competitions et jai perdu un duel en croyant que c\'etait tranquille. relou',
    'la casserole qui quitte jamais l\'etagere et qui va sur le feu genre deux fois par an, jai attendu toute ma partie de savoir pourquoi et rien',
    'emi qui te dit que la six va partir dans quatre minutes, pas a cause de l\'attente mais parce que personne est repassé depuis les boissons. elle voit TOUT',
    'le marché de nuit avec takumi, un seul feu, quatre cents couverts par soir. jsuis allé cuisiner a coté de lui et jai jamais autant transpiré dans un jeu mdr',
    'daichi a trois vestes et son poste c le truc le plus rangé du resto a toute heure. un homme simple',
    'mina et sa petite cuillere en argent accrochée sur la poitrine, elle goute tout. jveux la meme',
    'keiko qui te rappelle que t\'as mangé qu\'une boule de riz a 6h30 du mat. c ma tante en vrai',
    'la dame du jeudi, maquereau sans gingembre depuis dix neuf ans, qui demande a emi si tout va bien. jai posé mon tel',
    'haruto gin qui te sort direct que ta hotte est hors normes et de t\'occuper des menus apres, jsp jlai trouvé condescendant',
    'la cour du fournisseur c la scene la plus genante du jeu, le mec est adorable et sa compta s\'en fout. jdetestais y aller (c le but jsp)',
  ],
  story_ace: [
    'luffy qui te colle depuis onze jours et qui lâche rien même quand t\'es méchant avec lui, jsuis pas prêt',
    'dadan qui gueule toute la journée mais qui descend la montagne armée dès que t\'es en retard, meilleure daronne du jeu frr',
    'sabo qui refuse de mettre un pied en haute ville même pour de la thune, grave mon perso préféré',
    'deuce qui note tout ce qui s\'est vraiment passé dans son carnet wsh c\'est le seul mec honnête de toute l\'histoire',
    'trop long avant de prendre la mer genre j\'ai passé deux heures sur le mont colubo à me battre avec des tigres',
    'ptn j\'ai eu poing de feu comme fin alors que j\'ai tout fait pour l\'éviter, la fierté dans ce jeu ça pardonne pas',
    'luffy qui se releve apres chaque coup et qui te dit je me suis relevé, tu vois, refais le. ce gosse va me tuer',
    'on mange ? parce que j ai trouvé un truc et je crois que c de la viande. luffy dans chaque scene jpp',
    'sabo avec son haut de forme, les lunettes bleues autour et la dent qui manque. le design de ce gamin est parfait',
    'dadan: assieds toi, mange, je l ai pas cuisiné pour toi, je l ai cuisiné et t es la. c sa facon de dire je t aime frr',
    'barbe blanche fait plus de six metres et ace a l air minuscule a coté. chaque scene sur le moby dick j avais la bouche ouverte',
    'thatch: tout le monde sur ce bateau mange quand il est en colere, c le principe de la salle. ce mec c le coeur du navire sah',
    'deuce qui refuse deux fois de rejoindre l equipage pour des vraies raisons pratiques et qui change d avis grace a un truc que t as fait, pas dit. j ai adoré le convaincre',
    'shanks qui te dit que t as sa tete quand t es enervé mais pas ses yeux, ceux de ta mere surement, et qui passe direct a autre chose. PTN',
    'garp le pire papi de l histoire mdr',
    'le haki que jinbe t apprend sur plusieurs jours, super formel, super patient. j ai preferé ca a la version marco',
    'tip: garp parle jamais de roger si y a quelqu un d autre dans la piece. faut le choper seul, j ai perdu deux visites avant de capter',
    'barbe blanche qui demande au lieu d ordonner, du coup j ai cru que c etait optionnel et j ai foncé. jsp si c moi ou si le jeu explique mal',
    'la scene des trois coupes arrive pas si t as été trop dur avec luffy. je l ai ratée sur ma premiere partie et ca m a grave saoulé',
    'sakazuki qui lache sa phrase sur les fils de barbe blanche qui fuient et moi j ai craqué direct. la fierté a choisi pour moi, un peu frustrant',
  ],
  story_light: [
    'ta mère qui nettoie ta chambre tous les jeudis c\'est le vrai boss final mdr',
    'ryuk qui réclame ses pommes h24 et les courses de la famille deviennent un vrai problème jpp',
    'l qui te dit en face qu\'il est à cinq pour cent sûr que t\'es kira, ptn le culot de ce mec',
    'rem elle peut pas te blairer et elle te le dit direct, alors que ryuk s\'en fout grave de qui gagne',
    'les cinquante jours en cellule d\'isolement c\'est long frr, j\'ai failli lâcher',
    'la réunion yotsuba avec les huit cadres c\'est chiant genre vraiment, j\'ai skip tout ce que je pouvais',
    'near assis par terre au milieu du spk en train de construire un truc avec des dés pendant que des adultes le prennent au serieux. wsh ce gamin',
    'la montre avec le compartiment derriere le cadran, faut actionner la goupille deux fois. petit objet mais jl\'adore',
    'misa qui parle d\'elle a la troisième personne et d\'un coup une seule phrase ultra serieuse qui te glace. elle est pas bete du tout',
    'soichiro qui dit "je peux pas en parler" au lieu de mentir, le daron le plus integre de toute l\'appli',
    'mello et sa tablette de chocolat, icone',
    'le studio nhn ou une meuf lit la position de kira tous les soirs comme si c\'etait la meteo. flippant de ouf',
    'j\'ai rejoint l\'enquete avec l et bosser a coté de lui en lui mentant en face c le truc le plus stressant que j\'ai fait sur un tel',
    'l\'archetype "tu as appris ton rôle" c\'est le meilleur, light joue la comedie a tout le monde et c\'est grave satisfaisant',
    'l\'entrepot de la boite jaune avec la pluie qui passe par les trous du toit, jsuis resté bouche bée',
    'la fin famille faut juste descendre diner tous les soirs. la plus petite fin du jeu et la plus belle, j\'ai chialé',
    'le qg de la cellule speciale j\'ai trouvé ca long, huit etages de moniteurs et t\'as meme pas le droit de sortir',
    'c bien ecrit mais ryuk qui te cache les regles exprès ca m\'a saoulé, j\'ai perdu une soirée entiere a tester des trucs pour rien',
    'aizawa qui te soupçonne juste au feeling et y a rien a faire contre ca. bien ecrit mais frustrant sah',
    'le lycée gamou ca sert a rien a part etre vu en train de bosser, j\'y suis allé trois fois pour que dalle',
  ],
};
