/**
 * Every world that has French text.
 *
 * Registering is a side effect of importing, so this barrel is what makes the
 * overlays exist at runtime. Regenerated by `npm run fr:adapt`.
 */
import './blackwake.fr.js';
import './blank-prophecy.fr.js';
import './fourth-beast.fr.js';
import './good-morning-husband.fr.js';
import './hush-house.fr.js';
import './ace.fr.js';
import './itachi.fr.js';
import './light.fr.js';
import './last-five.fr.js';
import './last-service.fr.js';
import './nine-weeks.fr.js';
import './ninth-archive.fr.js';
import './pink-tide.fr.js';
import './primal-crown.fr.js';
import './red-floor.fr.js';
import './red-moon.fr.js';
import './salt-road.fr.js';
import './second-skin.fr.js';
import './seven-days.fr.js';
import './seven-names.fr.js';
import './tidewall.fr.js';
import './unbound.fr.js';
import './understudy.fr.js';
import './window-seven.fr.js';
import './zero-throne.fr.js';
